### PR TITLE
Fix logarithmic behavior when dragging knobs and sliders

### LINKED ISSUE #3871: Mouse contronl on logarithmic models changes the value in linear scale
Not all but some effects have much more value on one side then other making it hard to control.
Ill show example with : GLAME Butterworth Lowpass
Here is maximum : 
image
Here is 50% : 
image
And here is about 10% : 
image
The difference from 100% to 50% is about 16733.
But from 50% to 10% its about 3000.
Tested this on version RC4.

### PR DESCRIPTION
**Pull request by regulus79**
## The Problem

Currently, logarithmic knobs and sliders act very weirdly when dragging them. Instead of visually moving at the same rate as the mouse while internally moving logarithmically, the internal value changes *linearly* with the mouse movement, while only the visual was displayed logarithmically. 

This makes log knobs \*literally\* pointless, as they don't change the sensitivity for values of different magnitudes. They just display their current value logarithmically. In addition, this also causes the knobs to jump at the start and become sluggish relative to the mouse movement, which feels weird.

Might fix #3871

## The Solution

This PR addresses this issue by correctly scaling the mouse movement for all knobs.

### Changes
- Knobs tend to draw their visuals using the inverse scaled value of the model. This means that we need to calculate what internal (scaled) value is needed to move the knob by the same number of "pixels" as the mouse moved. Let's talk through the maths:
  - Imagine a simple inverse scaling curve. LMMS's is super complex, but think of something like a sqrt() curve.
  - The x axis is the internal model value. The y axis is pixels. (well, it's not *really* pixels, but it's close enough)
  - We need to find how much we need to adjust the internal value to change the output by some number of pixels.
  - Imagine that the current internal value of the model is some number, say 0.5. Say that we need to move 5 pixels. How far left/right does the x value need to move so that the y value goes up by 5 pixels?
  - We can use the inverse of the inverse scaling function! I.e., the normal scaling function.
  - The change in internal value given a desired change in pixels is the difference between the current pixel value and the scaledValue(current pixel value + 5 pixels). Since the current pixel value is just inverseScaledValue(model value), it comes out to be:
  - `model()->scaledValue(model()->inverseScaledValue(m_lastModelValue) - valueOffset)`
  And adding that on to the current model value, we get `m_lastModelValue - model()->scaledValue(model()->inverseScaledValue(m_lastModelValue) - valueOffset);`
  - (note: for some reason the offsets are subtracted, not added. Don't ask me why.)

Also, these changes make the knobs more generalizable, since it does not depend on how the knob scaling is implemented, and it does not require any derivatives. If we wanted to add more interesting knob scalings in the future, this would make it easier.

### CODE REVIEW

File: src/gui/widgets/FloatModelEditorBase.cpp [hunk 1]
```diff
@@ -346,41 +346,20 @@ void FloatModelEditorBase::wheelEvent(QWheelEvent * we)
 
 void FloatModelEditorBase::setPosition(const QPoint & p)
 {
-	const float value = getValue(p) + m_leftOver;
+	const float valueOffset = getValue(p) + m_leftOver;
+	const float currentValue = model()->value();
+	const float scaledValueOffset = currentValue - model()->scaledValue(model()->inverseScaledValue(currentValue) - valueOffset);
 	const auto step = model()->step<float>();
-	const float oldValue = model()->value();
+	const float roundedValue = qRound((currentValue - scaledValueOffset) / step) * step;
```
Comment (szeli1) [inline src/gui/widgets/FloatModelEditorBase.cpp:353]: Could `std::round` be used instead? I would prefer that over qt code, but If you do not agree, then you could keep it.

Comment (regulus79) [reply src/gui/widgets/FloatModelEditorBase.cpp]: I left it as `qRound` because that was what the previous code used. However, from searching online, it appears that `q*` functions such as this may have been added before equivalent `std::*` functions were implemented in C++ for all platforms? If that is the case, I think it should be fine to switch to `std::round` to match the majority of the codebase.

**Comment by tresf** [comment]
I tested this on macOS and I can confirm that a logarithmic knobs behavior at low values is fixed.   I believe a code review should be done prior to merging.

**Comment by bratpeki** [comment]
Can you give me examples of knobs that exhibit this behaviour?

**Comment by regulus79** [comment]
> Can you give me examples of knobs/faders that exhibit this behaviour?

Any knob which is set to logarithmic will exhibit this behavior.

For example, the decay time slider on Calf Reverb LADSPA is by default logarithmic, and has this problem. Or if you take a linear knob, say in the Amplifier plugin, and rightclick and make it logarithmic, it will have this issue too.

Look at this. I am moving my mouse at a constant speed (or nearly constant), but the visual slider/knob is moving crazy fast at low values, and very slow at high values.


https://github.com/user-attachments/assets/20455b5a-86a8-4a04-823b-52b6edfd4217



Also, the tooltips which show the current value (not recorded by OBS, but you can see them yourself) show the value of the knob increasing at a linear rate, not a logarithmic rate (!?)

**Comment by tresf** [comment]
> [...] for example, the decay time slider on Calf Reverb LADSPA is by default logarithmic, and has this problem.

Thanks!  I was trying to understand which "sliders" were impacted, the LADSPA "knobs" makes perfect sense.   Yeah that's horribly broken!

**Comment by tresf** [comment]
> The frequency filter knobs in lmms instruments are affected too, as an aside.

Affected as an improvement or as a regression?

**Comment by tyzoid** [comment]
> > The frequency filter knobs in lmms instruments are affected too, as an aside.
> 
> Affected as an improvement or as a regression?

(using commit ff738ef )
Click+drag works as expected with this PR, but scroll wheel still seems to adjust it linearly. That particular knob is the first I tried, as it's always been the one that stands out to me, and I tend to adjust those knobs with the scroll wheel, which is why I didn't notice the fix at first.

Testing other controls, it seems like both sliders and knobs are still updating linearly if using scroll wheel.

https://github.com/user-attachments/assets/f631aefd-2b55-49d9-b081-20922b69f0cf

**Comment by bratpeki** [comment]
Checking now.

I checked for audible differences in a sine wave with Calf Reverb, although there shouldn't be any difference there. Just to be safe.

As expected, all is well, saving a project returns the proper values, and the knobs not speeding to 0% and taking forever to reach 100% is a nice feature!

**Review by bratpeki — APPROVED** [review]

**Comment by tresf** [comment]
@bratpeki thanks for approving, but I believe the mousewheel behavior needs to be fixed prior to merge thanks to the findings of @tyzoid https://github.com/LMMS/lmms/pull/7647#issuecomment-2667670947.

**Comment by bratpeki** [comment]
Just spotted the issue, @tresf, thanks to @tyzoid for catching it!

**Comment by regulus79** [comment]
> @bratpeki thanks for approving, but I believe the mousewheel behavior needs to be fixed prior to merge thanks to the findings of @tyzoid [#7647 (comment)](https://github.com/LMMS/lmms/pull/7647#issuecomment-2667670947).

Scrolling behavior of log knobs should be fixed now.

**Comment by bratpeki** [comment]
Works great!

**Review by bratpeki — APPROVED** [review]

**Comment by sakertooth** [comment]
When I move a knob down to its lowest value and continue moving the mouse down, I have to reach a certain point when moving the mouse back up to reflect any change in the knob's value. I just need clarification on this because it's different from master.

> Instead of visually moving at the same rate as the mouse while internally moving logarithmically, the internal value changes linearly with the mouse movement, while only the visual was displayed logarithmically.

Sorry but I'm a bit lost here with the concepts of both an internal value and a visual value. If visually the knob or slider moves logarithmically, then I would imagine that the internal value is also moving logarithmically. Can you elaborate?

**Comment by regulus79** [comment]
> When I move a knob down to its lowest value and continue moving the mouse down, I have to reach a certain point when moving the mouse back up to reflect any change in the knob's value. I just need clarification on this because it's different from master.

Yeah I think I noticed that when testing also. I thought I had fixed that, but maybe I should take a closer look at the maths. Log scaling is a mess, and log scaling around 0 is even more of a mess, so I might have to add some kind of min movement amount. Actually wait no that's not a good way to solve it. Hmm. This may be difficult to solve.

> Sorry but I'm a bit lost here with the concepts of both an internal value and a visual value. If visually the knob or slider moves logarithmically, then I would imagine that the internal value is also moving logarithmically. Can you elaborate?

So like you know if you have a log frequency slider set to, say, 10 Hz, out of 100 Hz. Visually, it will be halfway (well sort of, it depends on the log base and the bounds but whatever)
If you drag it to the right so that it's about 3/4 of the way across, the internal value will be more like 31 Hz (10^1.5). That's all fine and good.
The problem in master is that sliding the slider with the same amount of mouse movement moves it a different amount depending on the current position (low values move fast, high values move slow). So say you drag your mouse 40 pixels to the right, but the slider only moves a little bit. And you drag your mouse 40 pixel to the left, and the slider moves a whole lot. This was because the dragged amount was sort of being added directly to the value of the model, with no respect for the log scaling.

This PR fixes that by properly scaling the movement of the slider/knob.

**Comment by sakertooth** [comment]
> The problem in master is that sliding the slider with the same amount of mouse movement moves it a different amount depending on the current position (low values move fast, high values move slow). So say you drag your mouse 40 pixels to the right, but the slider only moves a little bit. And you drag your mouse 40 pixel to the left, and the slider moves a whole lot. This was because the dragged amount was sort of being added directly to the value of the model, with no respect for the log scaling.

So we want the mouse to follow the curve like we are moving a ball along it basically, where before it was moving along the x-axis (linearly) and then mapped to the curve? Thanks for the clarification :+1:

**Review by sakertooth — COMMENTED** [review]
Besides that one issue I mentioned, I didn't see any other issue (though my testing was quite brief).

File: src/gui/widgets/FloatModelEditorBase.cpp [hunk 2]
```diff
@@ -346,41 +349,20 @@ void FloatModelEditorBase::wheelEvent(QWheelEvent * we)
...
-	const float value = getValue(p) + m_leftOver;
+	const float valueOffset = getValue(p) + m_leftOver;
+	const float currentValue = model()->value();
+	const float scaledValueOffset = currentValue - model()->scaledValue(model()->inverseScaledValue(currentValue) - valueOffset);
 	const auto step = model()->step<float>();
-	const float oldValue = model()->value();
+	const float roundedValue = std::round((currentValue - scaledValueOffset) / step) * step;
 
-	if (model()->isScaleLogarithmic()) // logarithmic code
+	if (roundedValue != currentValue)
```
Comment (sakertooth) [inline src/gui/widgets/FloatModelEditorBase.cpp:358]: Nevermind I do have something. Are we sure we do not want to use something like `approximatelyEqual` here? I'm not necessarily saying use it, just making sure your logic here is sound.

Comment (regulus79) [reply src/gui/widgets/FloatModelEditorBase.cpp]: I don't think it should matter if the model has stepped values(?) But I'm not an expert on floats, so it's probably a good idea to add it in anyway.

**Comment by regulus79** [comment]
> When I move a knob down to its lowest value and continue moving the mouse down, I have to reach a certain point when moving the mouse back up to reflect any change in the knob's value. I just need clarification on this because it's different from master.

Nevermind, this was being caused by `m_leftOver` not being reset when you drag the mouse left when the model is at its min. Fixed now.

**Comment by tresf** [comment]
> When I move a knob down to its lowest value and continue moving the mouse down, I have to reach a certain point when moving the mouse back up to reflect any change in the knob's value. I just need clarification on this because it's different from master.
> 
> > Instead of visually moving at the same rate as the mouse while internally moving logarithmically, the internal value changes linearly with the mouse movement, while only the visual was displayed logarithmically.
> 
> Sorry but I'm a bit lost here with the concepts of both an internal value and a visual value. If visually the knob or slider moves logarithmically, then I would imagine that the internal value is also moving logarithmically. Can you elaborate?

I tested this on Garage Band and interestingly the behavior of the main knobs matches this behavior (at time of writing this, the OLD behavior).  Oddly, the native plugins in Garage Band use the new behavior.

I think the new behavior is ultimately best because it offers more range for instances when hitting the edge of the screen.  I'm re-marking this as approved from a testing perspective (macOS).

**Review by tresf — APPROVED** [review]

**Review by sakertooth — APPROVED** [review]
Tested it again and the problem I mentioned previously has been resolved, and I couldn't find any other issue.
