### PR TITLE
Fix Shift+Space corrupting playback state when used on stopped editors

### LINKED ISSUE #8036: Spacebar stops working after shift-space pausing two editors in a row
### System Information

Arch Linux

### LMMS Version(s)

master(?)

### Most Recent Working Version

_No response_

### Bug Summary

You can press the spacebar to play/stop the current editor/last played editor. But you can also do shift+space to play/pause.

If you do shift+space on one editor which is stopped, nothing happens. Then if you switch focus to another editor which is also stopped, and do shift+space there, also nothing happens. But now all of a sudden using the spacebar to play any editor doesn't work.

But you can reset the state by pressing the play button manually.

### Expected Behaviour

Performing shift+space to play/pause in a certain order should not break the spacebar functionality.

### Steps To Reproduce

1. Open a project
2. Focus the Song Editor
3. Press shift+space
4. Focus the Pattern Editor
5. Press shift+space
6. Try to press space to play anything

### Logs

I added some debug statements, and I believe it is due to Song's `m_playing = true`, while `m_playMode = PlayMode::None`. That combination probably shouldn't be possible.

### Screenshots / Minimum Reproducible Project

_No response_

### Please search the issue tracker for existing bug reports before submitting your own.

- [x] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by jefrecantuledesma**
Shift+Space (togglePause) was allowing state corruption by modifying m_playing and m_paused without checking m_playMode. This created an impossible state where m_playing=true while m_playMode=None, causing the regular Space key to stop working.

Added a guard to ensure togglePause() only operates when something is actually playing (m_playMode != PlayMode::None). This prevents the corrupted state and maintains proper play/pause/stop behavior.

To put it simply: Space starts and stops playback, and Shift+Space pauses and resumes playback, but **does not** start playback.

Fixes #8036

### CODE REVIEW

File: src/core/Song.cpp [hunk 1]
```diff
@@ -625,6 +625,12 @@ void Song::setPlayPos( tick_t ticks, PlayMode playMode )
 
 void Song::togglePause()
 {
+	// Pause/unpause only works when something is actually playing
+	if( m_playMode == PlayMode::None )
```
Comment (regulus79) [inline src/core/Song.cpp]: Code style/formatting
```suggestion
	if (m_playMode == PlayMode::None)
```
