### PR TITLE
Extend the creation of default lmms folder, and default template.

### LINKED ISSUE #1695: Cannot save templates
Just tried to save a template several times, it saved as mmpz.

Steps to reproduce
- Do something with a project
- Go to save as
- "Save as template" in the dropdown menu
- Watch that the pop up box in the bottom left tells you that .mmpz has been saved, confirm it by browsing to the file.

### LINKED ISSUE #1702: user defined default-project
From forum:
http://lmms.io/forum/viewtopic.php?f=4&t=1621
so the user would like to set his own *default-project* -eg the *empty-project*
Looks like many users has access to same account (?) and that this is the reason for this request.

### PR DESCRIPTION
**Pull request by curlymorphic**
Added the following folders to the users lmms folder

- templates
- themes
- plugin
- plugin/vst
- plugin/ladspa
- plugin/gig

If no default project template is found, one is saved upon creation. This allows users to delete there default template to return to factory settings

fixes #1702

### CODE REVIEW

**Comment by tresf** [comment]
plugin needs a conversation..   


 1.  Where does SF2 fall into this structure?
 2.  Does the SF2, GIG, VST browser now open to this new location?
 3. What about VST effects vs VST instruments?

-Tres

**Comment by tresf** [comment]
Meh... This says it better:

https://github.com/LMMS/lmms/issues/1541#issuecomment-68555684

**Comment by Spekular** [comment]
This looks pretty great :) Not sure about the plugins either though, to be honest.

**Comment by curlymorphic** [comment]
Ok, probably best if i break this down, will change this to just create the the user template directory, and default project template, as per issue #1702 will handle the rest as a separate entity

**Comment by Umcaruje** [comment]
>Where does SF2 fall into this structure?

Since SF2's can be dragged from the sample browser, I don't think there is a need for this folder (I'd never use it, idk about others)

>Does the SF2, GIG, VST file open browser now open to its respective new location?

Hmm yeah this would be the only benefit for a SF2 folder perhaps.

>What about VST effects vs VST instruments?

I think LMMS should make this seperation, not the user.

Well those are my thoughts. 

P.S. if this comment should be in the other thread, please say, I'll move it there.

**Comment by curlymorphic** [comment]
@Umcaruje 


> if this comment should be in the other thread, please say, I'll move it there.

yes please. :)

**Comment by curlymorphic** [comment]
Changed this to deal with just #1702, creates a user project template folder while creating user directory. On new project creation, if we have no default user template project, we create one.

File: src/core/ConfigManager.cpp [hunk 1]
```diff
@@ -423,6 +423,7 @@ void ConfigManager::loadConfigFile()
 	if( QDir( m_workingDir ).exists() )
 	{
 		QDir().mkpath( userProjectsDir() );
+		QDir().mkpath( userProjectsDir() + TEMPLATE_PATH );
```
Comment (badosu) [inline src/core/ConfigManager.cpp]: Why is templates under the projects folder?

**Comment by badosu** [comment]
:+1: Although I don't like templates being under the projects folder.

**Comment by tresf** [comment]
> :+1: Although I don't like templates being under the projects folder, this is what's already expected.

If enough people agree... let's move it. :+1:

**Comment by curlymorphic** [comment]
> If enough people agree... let's move it.

let me know when we reach that moment :)

**Comment by Umcaruje** [comment]
I vote for templates folder being moved out of the projects folder, it is confusing to me too.

**Comment by Spekular** [comment]
I vote templates outside of projects as well. It makes sense but with the
amount of projects I have it would get super messy.

**Comment by tresf** [comment]
That's pretty unanimous... 

If Stian agrees, we'll move it. :+1: @Sti2nd?

**Comment by Sti2nd** [comment]
I agree, it is confusing!

**Comment by tresf** [comment]
There you go @curlymorphic, its a done deal! ;)

**Comment by curlymorphic** [comment]
> There you go @curlymorphic, its a done deal! ;)

Well that didnt take long :)

**Comment by curlymorphic** [comment]
Updated this pull request to use the location of lmms/templates/default.mpt instead of lmms/projects/templates/default.mpt. This new location is used for loading and saving the default project.

**Comment by curlymorphic** [comment]
That merge conflict is now sorted.

**Comment by tresf** [comment]
@curlymorphic do you mind adjusting the PR body since it no longer reflects the change?

**Comment by curlymorphic** [comment]
> do you mind adjusting the PR body since it no longer reflects the change?

if you mean, the top post in this issue, sure, done :)

**Comment by tresf** [comment]
:+1:

**Comment by tresf** [comment]
P.S. Added to our release notes draft.
