### PR TITLE
Fix Sf2 player freezing on project unloading with shared SoundFonts

### LINKED ISSUE #6437: LMMS Freezes when creating a new project
### 
  LMMS Freezes when creating a new file

#### 
  1. Have loaded a Soundfont default file in permissions (might not be required)
      2. Load any midi, preferably above 40kb
      3. Change instruments on channels
      4. Create new project
    5. Repeat

####
  New Project is created

#### 
  Program freezes instantly, killing the application fixes the issue.

#### 
  Screenshot_2022-06-15_20-41-16

#### 
  Version 1.2.2 (Linux/x86_64, Qt 5.15.4, GCC 12.1.0)
  Installation origin - Arch Official Repository

#### 
  No log file was produced, It would freeze before it could be produced

### PR DESCRIPTION
**Pull request by PhysSong**
Fixes #6437.

`fluid_sfont_t` instances were shared between different SF2 player instances which shares a same SoundFont file. However, the upstream documentation says `fluid_synth_add_sfont` transfers the ownership of the SoundFont instance to the synth, making the manual sharing illegal.

Fortunately, FluidSynth internally shares sample data between different instances starting from 1.1.7. Therefore, the manual sharing mechanism is removed while bumping up the minimum version of FluidSynth.

### CODE REVIEW

File: plugins/Sf2Player/Sf2Player.cpp [hunk 1]
```diff
@@ -375,31 +369,12 @@ void Sf2Instrument::freeFont()
...
-		// Just remove our reference
-		else
-		{
-			qDebug() << "un-referencing " << m_filename;
-
-			fluid_synth_remove_sfont( m_synth, m_font->fluidFont );
-		}
-		s_fontsMutex.unlock();
-
+		fluid_synth_sfunload( m_synth, m_fontId, true );
```
Comment (sakertooth) [inline plugins/Sf2Player/Sf2Player.cpp:374]:
```suggestion
		fluid_synth_sfunload(m_synth, m_fontId, true);
```

File: plugins/Sf2Player/Sf2Player.cpp [hunk 2]
```diff
@@ -413,49 +388,29 @@ void Sf2Instrument::openFile( const QString & _sf2File, bool updateTrackName )
...
+			loaded = true;
 		}
+	}
 
-		if(!loaded)
-		{
-			collectErrorForUI( Sf2Instrument::tr( "A soundfont %1 could not be loaded." ).
-				arg( QFileInfo( _sf2File ).baseName() ) );
-		}
+	if(!loaded)
```
Comment (sakertooth) [inline plugins/Sf2Player/Sf2Player.cpp:409]:
```suggestion
	if (!loaded)
```

File: plugins/Sf2Player/Sf2Player.cpp [hunk 3]
```diff
@@ -627,12 +582,12 @@ void Sf2Instrument::reloadSynth()
 	{
 		// Now, delete the old one and replace
 		m_synthMutex.lock();
-		fluid_synth_remove_sfont( m_synth, m_font->fluidFont );
+		fluid_synth_remove_sfont( m_synth, m_font );
```
Comment (sakertooth) [inline plugins/Sf2Player/Sf2Player.cpp:585]:
```suggestion
		fluid_synth_remove_sfont(m_synth, m_font);
```

File: plugins/Sf2Player/Sf2Player.cpp [hunk 4]
```diff
@@ -627,12 +582,12 @@ void Sf2Instrument::reloadSynth()
...
 		delete_fluid_synth( m_synth );
 
 		// New synth
 		m_synth = new_fluid_synth( m_settings );
-		m_fontId = fluid_synth_add_sfont( m_synth, m_font->fluidFont );
+		m_fontId = fluid_synth_add_sfont( m_synth, m_font );
```
Comment (sakertooth) [inline plugins/Sf2Player/Sf2Player.cpp:590]:
```suggestion
		m_fontId = fluid_synth_add_sfont(m_synth, m_font);
```

**Review by sakertooth — COMMENTED** [review]
Just formatting suggestions from me for now. Will test soon.

File: plugins/Sf2Player/Sf2Player.cpp (hunk 3 above)
Comment (PhysSong) [reply plugins/Sf2Player/Sf2Player.cpp:585]: I'll leave this one as-is for consistency.

File: plugins/Sf2Player/Sf2Player.cpp (hunk 4 above)
Comment (PhysSong) [reply plugins/Sf2Player/Sf2Player.cpp:590]: I'll leave this one as-is for consistency.

**Review by sakertooth — APPROVED** [review]
Couldn't reproduce the issue, but the code LGTM.

**Review by zonkmachine — APPROVED** [review]
Tested. Issue reproduced and fix confirmed.
