### PR TITLE
Fix crash when switching opened projects

### LINKED ISSUE #7793: File > Open crashes
### System Information

Arch Linux, 5800X3D, 7800XT, 32GB Ram, Hyprland.

### LMMS Version(s)

3c3441bb0ca11b00af2d06e011c229caea3077c4

### Most Recent Working Version

3417dfe86da0f6e9a41b3e71e30485a84213ffbf

### Bug Summary

Commit 3c3441bb0ca11b00af2d06e011c229caea3077c4 seems to introduce a bug where attempting to open a project via `File > Open` results in a crash for certain projects. Note that opening projects via `lmms /path/to/my.mmpz` doesn't crash. Reverting this commit fixes the crash, but perhaps there's a better solution.

### Expected Behaviour

`File > Open` Should open the selected project instead of crash.

### Steps To Reproduce

1. Launch LMMS against a project file so it starts with a project open.
2. File
3. Open
4. Double click test.mmpz
5. Observe crash

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Screenshots / Minimum Reproducible Project

[test.zip](https://github.com/user-attachments/files/19324611/test.zip)

### Please search the issue tracker for existing bug reports before submitting your own.

- [x] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by cyberrumor**
When the DAW is already running and you attempt to open another project
via File > Open (or probably when you switch projects via any other
method as well), a segfault previously occurred.

The crash seems to have been caused by `model()->value()`, which was
called in `Fader::getModelValueAsDbString()`. The `model()` function
looked like it should return a pointer to an AutomatableModel.

I suspect that when a model was dropped in favor of loading models for
a new project, the AutomatableModel pointer became a null pointer.

Add a check to the pointer returned by `model()` to confirm it's
true-ish (E.g. not a null pointer) before calling any member
functions we expect to exist. This fixes the crash.

Fixes #7793

### CODE REVIEW

**Review by Rossmaxx — APPROVED** [review]
Haven't tested, but the changes look good. Approving.

File: src/gui/widgets/Fader.cpp [hunk 1]
```diff
@@ -512,9 +512,16 @@ void Fader::modelValueChanged()
 
 QString Fader::getModelValueAsDbString() const
 {
-	const auto value = model()->value();
-
 	QString label(tr("Volume: %1 dB"));
+	// Check that the pointer isn't dangling, which can happen if the
+	// model was dropped in order to load a new project from an existing one.
+	auto* m = model();
```
Comment (Rossmaxx) [inline src/gui/widgets/Fader.cpp:518]:
```suggestion
	auto* newModel = model();
```

**Review by Rossmaxx — COMMENTED** [review]
Though I did approve last time, I got an idea for a minor improvement. Make the temporary variable's name more descriptive, and also use that variable instead of calling the model() function twice.

File: src/gui/widgets/Fader.cpp [hunk 2]
```diff
@@ -369,7 +369,7 @@ int Fader::calculateKnobPosYFromModel() const
 	else
 	{
 		// The model is in dB so we just show that in a linear fashion
-
```
Comment (Rossmaxx) [inline src/gui/widgets/Fader.cpp:372]: This ain't really a thing, but we usually tend to avoid unnecessary whiteline changes to keep git blame clean. You can add that tab back in and it will negate.

**Comment by Rossmaxx** [comment]
Also, no need to force push. We do squash on merge, which is better for such minor changes. There's a huge discussion going on over here but better not bother about it and keep things simple.

File: src/gui/widgets/Fader.cpp (hunk 2 above)
Comment (cyberrumor) [reply src/gui/widgets/Fader.cpp]: Done. Hope we can just use the commit message from the original patch when it squashes and ignore the one from the whitespace change.

Comment (Rossmaxx) [reply src/gui/widgets/Fader.cpp]: Yeah, that's how it works.

**Comment by Rossmaxx** [comment]
I'll wait for a 2nd approval, preferably with testing before merge.

**Review by messmerd — APPROVED** [review]

**Comment by messmerd** [comment]
Thanks!
