### PR TITLE
PathUtil: Serialization and Formatting

### LINKED ISSUE #8107: VstEffect saves and uses native path in <key <attribute type="file" value="[path]" /> /> instead of agnostic path.
### System Information

Windows as cause, all other platforms affected

### LMMS Version(s)

Since commit e30e558 / first implementation

### Most Recent Working Version

_No response_

### Bug Summary

When adding a VstEffect, a native path is used to store the information in
<key>
  <attribute type="file" value="[path]" />
</key>

All currently supported platforms except Windows use / as the path separator.
Windows uses \.

Windows does support / in most operations, however.
Linux platforms do not support \.

When you load a _project that was created on Windows that contains a VstEffect_ on Linux, the VstEffect will not be found due to wrong paths.
This is not the case when loading Linux projects on Windows.

NOTE: The <vsteffectcontrols plugin="[path]" /> section is managed differently and thus is saved correctly when modified internally. It is, as far as I can see, only used for the name displayed in the window, not for the actual file being loaded.

### Expected Behaviour

Should be saved with forward slashes for cross-platform compatibility.

### Steps To Reproduce

1. Create project on Windows.
2. Add VstEffect on Windows.
3. Try to load said project on Linux.

### Screenshots / Minimum Reproducible Project

Image
See wrong paths from a Windows project.

### Please search the issue tracker for existing bug reports before submitting your own.

- [x] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by Jan125**
-Serialize all operations to use / instead of platform specific paths. (Also fixes #8082)
-Formatting changes for consistency.

**Edit**: by @tresf:

This new function is necessary because `QDir::fromNativeSeparators` has a `#if defined(Q_OS_WIN)` guard preventing it from being used on other OSs.

Closes #8107

### CODE REVIEW

**Comment by Jan125** [comment]
> @Jan125 thank you for this patch! I think you can minimize the lines you touch by leaving most function signatures alone, only touching what's absolutely needed.
>
I would rather we unify the input headers in one go for this one.

> I think the description of the serialize function should come before it (no need to number it, just say what it does). I also feel that serialize can be simplified (e.g. `return QString(input).replace(R"(\)", R"(/)");`). I'm even inclined to say to drop the string literal syntax since I personally find it harder to read, but I'd like a second opinion on that.
>
Will be done.
I did not know that you could have floating(?) variables like that.

> My biggest concern with this patch in regards to regression is any relative path logic breaking as a result... this may force us to sanitize relativeBases too so we're always comparing 🍎 : 🍎.
>
I assumed that they were always at the beginning of that and marked with a basename:path colon.

**Comment by tresf** [comment]
> I would rather we unify the input headers in one go for this one.

I don't particularly find `input` to be better than `path`, so we'll have to agree to disagree here.   The description should be short and concise unless it's not obvious.. this is.  We're just enforcing `/` everywhere, no need to explain why unless there's an anti-pattern to warn people of.  I don't see this occurring.

File: src/core/PathUtil.cpp [hunk 1]
```diff
@@ -97,76 +97,91 @@ namespace lmms::PathUtil
...
 			QString prefix = basePrefix(base);
-			if ( path.startsWith(prefix) ) { return base; }
+			if (input.startsWith(prefix)) { return base; }
 		}
 		return Base::Absolute;
 	}
 
 
+	//VstEffect saved as a platform native path in previous versions of LMMS. (PR#8082)
+	//Enforce forward slashes for compatibility.
```
Comment (tresf) [inline src/core/PathUtil.cpp]:
```suggestion
	// Enforce forward slashes for cross-platform compatibility, see also <insert issue # here after you've filed the bug report related to this issue>
```

File: src/core/PathUtil.cpp [hunk 2]
```diff
@@ -97,76 +97,91 @@ namespace lmms::PathUtil
...
+
 		return stripPrefix(QFileInfo(path).completeBaseName());
 	}
 
 
 
-
 	QString oldRelativeUpgrade(const QString & input)
 	{
-		if (input.isEmpty()) { return input; }
```
Comment (tresf) [inline src/core/PathUtil.cpp:128]: This guard should come first.  There's no instance where an empty string is no longer empty as a result of serialization, so this is a wasted compute cycle.

File: src/core/PathUtil.cpp [hunk 3]
```diff
@@ -97,76 +97,91 @@ namespace lmms::PathUtil
...
-		QString upgraded = input.contains(":") ? input : oldRelativeUpgrade(input);
+		QString upgraded = path.contains(":") ? path : oldRelativeUpgrade(path);
 
 		Base base = baseLookup(upgraded);
 		return baseLocation(base, error) + upgraded.remove(0, basePrefix(base).length());
 	}
 
 	QString relativeOrAbsolute(const QString & input, const Base base)
 	{
-		if (input.isEmpty()) { return input; }
```
Comment (tresf) [inline src/core/PathUtil.cpp:168]: Same here.  Your serialization doesn't break the `isEmpty()` check, keep it first to avoid unnecessary compute.

File: src/core/PathUtil.cpp (hunk 1 above)
Comment (tresf) [reply src/core/PathUtil.cpp]: @Jan125 please file a bug report describing the issue so that we can link it in the serialization comment.  Inferring a bug based on a PR is harder for a developer and tester to understand.  Having a dedicated bug report also offers steps for a tester to provide a pass/fail, which will help get a PR merged faster.

If you don't want to open a new issue, at least update the description here with it.

File: src/core/PathUtil.cpp (hunk 2 above)
Comment (Jan125) [reply src/core/PathUtil.cpp:128]: Should that guard be on every function then?

Comment (tresf) [reply src/core/PathUtil.cpp:128]: I would recommend changing as few logic paths as possible unless you fully understand the use-case.  This particular function is "old" and to the best of my knowledge unused and a candidate for removal.  It should probably be marked with deprecated notation to help others remove it in the future.

Comment (Jan125) [reply src/core/PathUtil.cpp:128]: This function is used for upgrading from Stable.

Comment (Jan125) [reply src/core/PathUtil.cpp:128]: Nevermind, seems they use the toShortestRelative for upgrading from stable.

Comment (Jan125) [reply src/core/PathUtil.cpp:128]: Nevermind, toShortestRelative is invoking toAbsolute in cases where the path is absolute, which invokes oldRelativeUpgrade.
I will run tests.

Comment (tresf) [reply src/core/PathUtil.cpp:128]: Whoops.  Yeah, good catch, sorry for the bad advice.  Looks like it's for projects that predate the introduction of the `:`.  This still seems a bit bugged because I feel like `C:\foo` would pass this test.  Perhaps we guard that with something like... 

```cpp
input.contains(":") && !input.contains(":\\") ... 
```

Comment (Jan125) [reply src/core/PathUtil.cpp:128]: A left-check to check for [a-z]&[A-Z]:\ should be more intended. .contains() checks the entire string and could lead to unintended behaviour.

Comment (Jan125) [reply src/core/PathUtil.cpp:128]: Check unnecessary because it would be filtered out by the absolute path check above.

Comment (tresf) [reply src/core/PathUtil.cpp:128]: > Check unnecessary because it would be filtered out by the absolute path check above.

Good catch, but this is completely unobvious... Please quote the documentation so others don't get tripped up on this.

```cpp
// Note: Paths starting with a colon (:) are always considered absolute, as they denote a QResource
```

**Comment by Jan125** [comment]
As mentioned on the Discord and with a thumbsup reacted by:
oldRelativeUpgrade now assumes an absolute path instead of usersample: for things it does not find.

File: src/core/PathUtil.cpp [hunk 4]
```diff
@@ -15,7 +15,7 @@ namespace lmms::PathUtil
 
 	QString baseLocation(const Base base, bool* error /* = nullptr*/)
 	{
-		// error is false unless something goes wrong
+		// error is false unless something goes wrong.
```
Comment (tresf) [inline src/core/PathUtil.cpp]:
```suggestion
		// error is false unless something goes wrong
```

lol don't do this

File: src/core/PathUtil.cpp [hunk 5]
```diff
@@ -97,67 +97,94 @@ namespace lmms::PathUtil
...
 			QString prefix = basePrefix(base);
-			if ( path.startsWith(prefix) ) { return base; }
+			if (input.startsWith(prefix)) { return base; }
 		}
 		return Base::Absolute;
 	}
 
 
+	// Enforce forward slashes for cross-platform compatibility.
+	// See issue #8107.
```
Comment (tresf) [inline src/core/PathUtil.cpp]:
```suggestion
	// Enforce forward slashes for cross-platform compatibility, see also #8107.
```

File: src/core/PathUtil.cpp [hunk 6]
```diff
@@ -97,67 +97,94 @@ namespace lmms::PathUtil
...
+
+		return path.mid(basePrefix(baseLookup(path)).length());
 	}
 
-	QString cleanName(const QString& path)
+	QString cleanName(const QString & input)
 	{
+		if (input.isEmpty()) { return input; }
+
+		QString path = serializePath(input);
```
Comment (tresf) [inline src/core/PathUtil.cpp:135]: ~~These are now both redundant, they're handled 100% of the time in the call to `stripPrefix`.~~

Comment (tresf) [reply src/core/PathUtil.cpp:135]: Nevermind, I'm overthinking it.

Comment (Jan125) [reply src/core/PathUtil.cpp:135]: This is here in case external functions use it.
I know stripPrefix() is used in the code, and I am pretty certain that cleanName() is also called from somewhere.

File: src/core/PathUtil.cpp [hunk 7]
```diff
@@ -97,67 +97,94 @@ namespace lmms::PathUtil
...
+
 		return stripPrefix(QFileInfo(path).completeBaseName());
 	}
 
 
 
-
```
Comment (tresf) [inline src/core/PathUtil.cpp:125]: You can add this whitespace back.  4 newlines is the old convention, which I'm pretty sure we removed but there's no reason to touch lines you don't have to. https://github.com/LMMS/lmms/wiki/Coding-Conventions

File: src/core/PathUtil.cpp [hunk 8]
```diff
@@ -97,67 +97,94 @@ namespace lmms::PathUtil
...
 	QString oldRelativeUpgrade(const QString & input)
 	{
-		if (input.isEmpty()) { return input; }
+		if (input.isEmpty()) { return basePrefix(Base::Absolute); }
```
Comment (tresf) [inline src/core/PathUtil.cpp]: Can you please explain this thought process in a code comment?  I don't think it's obvious here.

Comment (tresf) [reply src/core/PathUtil.cpp]: Oh, I see, it's lower.  Ok, for readability, let's declare `Base assumedBase = Base::Absolute;` above and return `assumedBase` so that it can be read properly.  The compiler will likely optimize out the wasted assignment.

File: src/core/PathUtil.cpp [hunk 9]
```diff
@@ -166,28 +193,35 @@ namespace lmms::PathUtil
 	QString relativeOrAbsolute(const QString & input, const Base base)
 	{
 		if (input.isEmpty()) { return input; }
-		QString absolutePath = toAbsolute(input);
+
+		QString path = serializePath(input);
+
+		QString absolutePath = toAbsolute(path);
```
Comment (tresf) [inline src/core/PathUtil.cpp]:
```suggestion
		QString absolutePath = toAbsolute(serializePath(input));
```

I don't see a need for an additional variable here.

Comment (Jan125) [reply src/core/PathUtil.cpp]: The initial idea was to have all of the functions structured the same way for easier understanding.

Comment (tresf) [reply src/core/PathUtil.cpp]: > The initial idea was to have all of the functions structured the same way for easier understanding.

In several cases, you use the intermediate variable.  Here you don't, so this changes one single line of code and illustrates to the code reviewer that you're only sanitizing the input variable.  It's less lines changed and easier for a reviewer to read.  1 line touched versus 4.

File: src/core/PathUtil.cpp (hunk 4 above)
Comment (tresf) [reply src/core/PathUtil.cpp]: There's still some unnecessary formatting changes that I would like reverted before this is approved.

Comment (Jan125) [reply src/core/PathUtil.cpp]: This entire experience has been taxing on me.

**Comment by tresf** [comment]
> This entire experience has been taxing on me.

@Jan125 thank you for the code cleanup, it's much easier to read and review now and only touches lines that are justified, which is greatly appreciated.

I haven't tested this, but from what I understand, you have.  I'm approving this, but would like a second set of eyes from another code reviewer before merging.

**Review by tresf — APPROVED** [review]

File: src/core/PathUtil.cpp [hunk 10]
```diff
@@ -125,39 +141,50 @@ namespace lmms::PathUtil
...
 		{
 			if (error) { *error = false; }
-			return input;
+			return path;
 		}
 		//Next, handle old relative paths with no prefix
-		QString upgraded = input.contains(":") ? input : oldRelativeUpgrade(input);
+		QString upgraded = path.contains(":") ? path : oldRelativeUpgrade(path);
 
 		Base base = baseLookup(upgraded);
```
Comment (tresf) [inline src/core/PathUtil.cpp]: Since ...

> Paths starting with a colon (:) are always considered absolute, as they denote a QResource.

... this check is now redundant.  I've proposed a simplified version as a code suggestion.


```suggestion
		Base base = baseLookup(oldRelativeUpgrade(path));
```

**Comment by Jan125** [comment]
Latest commit not working.

File: src/core/PathUtil.cpp (hunk 10 above)
Comment (Jan125) [reply src/core/PathUtil.cpp]: Removing upgraded breaks it because it's called later.
Updating the upgraded things makes it way more unreadable IMHO.

File: src/core/PathUtil.cpp [hunk 11]
```diff
@@ -125,48 +141,58 @@ namespace lmms::PathUtil
...
 		{
 			if (error) { *error = false; }
-			return input;
+			return path;
 		}
 		//Next, handle old relative paths with no prefix
-		QString upgraded = input.contains(":") ? input : oldRelativeUpgrade(input);
-
-		Base base = baseLookup(upgraded);
+		Base base = baseLookup(oldRelativeUpgrade(path));
```
Comment (tresf) [inline src/core/PathUtil.cpp]:
```suggestion
		QString upgraded = oldRelativeUpgrade(input);

		Base base = baseLookup(upgraded);
```

File: src/core/PathUtil.cpp (hunk 10 above)
Comment (tresf) [reply src/core/PathUtil.cpp]: Yeah, oversimplified.  Proposed a new patch, resolving this outdated convo.

**Comment by Jan125** [comment]
Commit fixed.

File: src/core/PathUtil.cpp [hunk 12]
```diff
@@ -97,26 +97,42 @@ namespace lmms::PathUtil
...
+			if (input.startsWith(prefix)) { return base; }
 		}
 		return Base::Absolute;
 	}
 
 
+	// Enforce forward slashes for cross-platform compatibility, see #8107.
+	QString serializePath(const QString & input)
+	{
+		if (input.isEmpty()) { return input; }
```
Comment (rubiefawn) [inline src/core/PathUtil.cpp]:
```suggestion
```

File: src/core/PathUtil.cpp [hunk 13]
```diff
@@ -125,48 +141,59 @@ namespace lmms::PathUtil
...
 	}
 
 
 
 
 	QString toAbsolute(const QString & input, bool* error /* = nullptr*/)
 	{
+		if (input.isEmpty()) { return input; }
+
+		QString path = serializePath(input);
```
Comment (rubiefawn) [inline src/core/PathUtil.cpp]:
```suggestion
		if (input.isEmpty()) { return input; }
		QString path = serializePath(input);
```

**Review by rubiefawn — APPROVED** [review]
I have some non-blocking feedback. Good work!

As per our established [coding conventions](https://github.com/LMMS/lmms/wiki/Coding-Conventions#pointers),

> The `*` symbol in pointer declarations MUST be adjacent to the type, not the variable name. This rule also applies to `**`, `&`.

There are many instances of `const QString & path` that should be changed to `const QString& path`, and the same should be done for anything else you touched where the above coding convention applies.

There's also a lot of blank lines between lines of code. Blank lines can be used to increase readability by visually separating different parts of code in the same scope, but this is happening in between every line of tiny three-line functions, where it doesn't really help readability at all. These are best removed.

**Comment by Jan125** [comment]
I had misunderstood the &'s mechanics.
The previous language I used declares them as *Pointer.
Moving the pointer declarations and fixing one indent.

Reducing blank lines a bit.
I would prefer to keep every return X; statement in a separate block.

File: include/PathUtil.h [hunk 14]
```diff
@@ -48,12 +48,14 @@ namespace lmms::PathUtil
 	QString LMMS_EXPORT basePrefix(const Base base);
 	//! Check the prefix of a path and return the base it corresponds to
 	//! Defaults to Base::Absolute
-	Base LMMS_EXPORT baseLookup(const QString & path);
+	Base LMMS_EXPORT baseLookup(const QString & input);
 
+	//! Enforce forward slash (/) for folder paths for uniform handling.
+	QString LMMS_EXPORT serializePath(const QString & input);
```
Comment (messmerd) [inline include/PathUtil.h]: Looks like the new function is not used outside of `PathUtil`? If it's an implementation detail that isn't intended to be used by other programmers, it should be in `PathUtil.cpp` only, inside an anonymous namespace.

File: include/PathUtil.h [hunk 15]
```diff
@@ -48,12 +48,14 @@ namespace lmms::PathUtil
 	QString LMMS_EXPORT basePrefix(const Base base);
 	//! Check the prefix of a path and return the base it corresponds to
 	//! Defaults to Base::Absolute
-	Base LMMS_EXPORT baseLookup(const QString & path);
+	Base LMMS_EXPORT baseLookup(const QString & input);
```
Comment (messmerd) [inline include/PathUtil.h]:
```suggestion
	Base LMMS_EXPORT baseLookup(const QString& input);
```
You missed the coding convention changes in this header file

File: include/PathUtil.h [hunk 16]
```diff
@@ -48,12 +48,14 @@ namespace lmms::PathUtil
...
 
+	//! Enforce forward slash (/) for folder paths for uniform handling.
+	QString LMMS_EXPORT serializePath(const QString & input);
 	//! Remove the prefix from a path, iff there is one
-	QString LMMS_EXPORT stripPrefix(const QString & path);
+	QString LMMS_EXPORT stripPrefix(const QString & input);
```
Comment (messmerd) [inline include/PathUtil.h]:
```suggestion
	QString LMMS_EXPORT stripPrefix(const QString& input);
```

File: include/PathUtil.h [hunk 17]
```diff
@@ -48,12 +48,14 @@ namespace lmms::PathUtil
...
 	//! Get the filename for a path, handling prefixed paths correctly
-	QString LMMS_EXPORT cleanName(const QString & path);
+	QString LMMS_EXPORT cleanName(const QString & input);
```
Comment (messmerd) [inline include/PathUtil.h]:
```suggestion
	QString LMMS_EXPORT cleanName(const QString& input);
```

File: src/core/PathUtil.cpp [hunk 18]
```diff
@@ -22,7 +22,7 @@ namespace lmms::PathUtil
 		switch (base)
 		{
 			case Base::ProjectDir       : loc = ConfigManager::inst()->userProjectsDir(); break;
-			case Base::FactoryProjects :
+			case Base::FactoryProjects  :
```
Comment (rubiefawn) [inline src/core/PathUtil.cpp]: This seems like an accidental change. Please undo it.

```suggestion
			case Base::FactoryProjects :
```

File: src/core/PathUtil.cpp [hunk 19]
```diff
@@ -60,7 +60,7 @@ namespace lmms::PathUtil
 				if (error) { *error = (!s || projectPath.isEmpty()); }
 				break;
 			}
-			default                   : return QString("");
+			default                     : return QString("");
```
Comment (rubiefawn) [inline src/core/PathUtil.cpp]: This also looks like an accidental change, please undo this as well.

```suggestion
			default                   : return QString("");
```

**Review by rubiefawn — CHANGES_REQUESTED** [review]

File: src/core/PathUtil.cpp (hunk 18 above)
Comment (Jan125) [reply src/core/PathUtil.cpp]: Not an accidental change but I will undo it.

**Comment by Jan125** [comment]
I wish to be frank and would like a consensus here:
Either I do formatting changes as requested, or I don't do formatting changes as requested.
I will not do any further formatting changes in any way, shape, or form.

**Comment by tresf** [comment]
> I wish to be frank and would like a consensus here: Either I do formatting changes as requested, or I don't do formatting changes as requested. I will not do any further formatting changes in any way, shape, or form.

I understand this is frustrating, however the first review was warning about this, quoting:

>  I think you can minimize the lines you touch by leaving most function signatures alone, only touching what's absolutely needed

Once you touch the lines, they should match our new formatting standards.  Sorry if this wasn't clear and thanks for the understanding.

File: include/PathUtil.h (hunk 14 above)
Comment (tresf) [reply include/PathUtil.h]: This was completed as part of 252e1a2.

**Comment by tresf** [comment]
Sorry I found this so late... It looks like Qt has a built-in for this called [`QDir::fromNativeSeparators`](https://doc.qt.io/qt-6/qdir.html#fromNativeSeparators).  This means we can simplify this even more by removing the `serializePath ` function declaration.

**Comment by tresf** [comment]
> Sorry I found this so late... It looks like Qt has a built-in for this called [`QDir::fromNativeSeparators`](https://doc.qt.io/qt-6/qdir.html#fromNativeSeparators). This means we can simplify this even more by removing the `serializePath ` function declaration.

As @Jan125 has pointed out on Discord, Qt has a [guard that prevents this from working on non-Windows platforms](https://github.com/qt/qtbase/blob/0982fc73c49cc21bb9e6925312116060b1bd0b39/src/corelib/io/qdir.cpp#L1074), so this function is useless to us.  Thanks!

**Comment by tresf** [comment]
Note, that as we discussed on Discord, this PR essentially abolishes the use of the `\` character in any Unix filename or path.  I believe this is a compromise that we must make, since it's an invalid character on Windows and would otherwise break cross-platform project support.

As @Jan125 explained, we don't currently have a way to distinguish what platform a project was saved on, so conditional logic is gone.  I think we're OK with this.  If macOS or Linux projects that leverage `\` in filenames start to break as a result of this, this PR is to blame. 😈

**Comment by Jan125** [comment]
In the long term, a platform identifier should be added to the save files and a "reselect plugin" option on platform specific invalid file paths should be made available to the user.

The current market dominance of Windows means that we will not encounter a lot of UNIX specific paths that would be illegal under Windows. People are arguably used to not using * \ < > ? : " and | in their filenames.

**Comment by tresf** [comment]
> In the long term, a platform identifier should be added 

Agreed.

> "reselect plugin" option on platform specific invalid file paths 

Well, re-selecting the plugin is what's needed under many other similar circumstances (unrelated to path separators, I mean), so this is an existing issue that's solvable under some circumstances by user intervention, not solvable under others.
