### PR TITLE
Remove note from m_playingNotes before deleting m_pluginData

### LINKED ISSUE #2401: Random crash in sf2_player
Branch: lmms-master, up to date
(Linux x86_64, Qt 4.8.6, GCC 4.8.4)
Ubuntu 14.04 x64 Core i5 8Gb ram

I already reported this problem in issue #2192 but it was occurring on my old box (a P4 with Ubuntu 12.04) and I thought it was because of a lack of hardware resources.
I am pretty well equipped now and the problem is still happening at a point that I cannot play a piece completely most of the time.
Note: this never occurs in stable-1.1 (1.1.3)

Steps to reproduce:
1- Start a new project
2- Import a Midi file with more than 10 tracks
3- Play

Lmms crashes randomly in sf2Instrument::noteOff() or sf2Instrument::noteOn() where the contents of the SF2PluginData* is totally corrupted:
noteoff-crash

Notes:
* The Midi file is not corrupted
* The crash does not occurs every time at the same place in the piece. Sometime at the very beginning, sometime later while playing.

A Midi file to reproduce can be found there:
http://jazzycat.tripod.com/tpspecl.mid

The backtrace I put in the other issue is still valid.

### PR DESCRIPTION
**Pull request by midi-pascal**
fixes #2401: Random crash in sf2_player

### CODE REVIEW

**Comment by tresf** [comment]
Much cleaner, thanks!

FYI - If you modify the PR description to contain "fixes #2401" or "closes #2401", the associated bug report will be closed as soon as this PR is merged.

Also, as I'm sure you can observe, the PR title is getting cut off because if it is too long, this is something to consider for future commits or PRs to avoid the `...` ellipses being added to the end. :+1:

**Comment by midi-pascal** [comment]
Done!

**Comment by tresf** [comment]
:+1: 

FYI - "fixes" will need to go in the description, not the title for auto-close to work.

**Comment by midi-pascal** [comment]
Done (Take 2)

**Comment by tresf** [comment]
@michaelgregorius @Wallacoloo any thoughts on merging? :eyeglasses:

File: plugins/sf2_player/sf2_player.cpp [hunk 1]
```diff
@@ -780,6 +784,13 @@ void sf2Instrument::deleteNotePluginData( NotePlayHandle * _n )
 									// do it here
 	{
 		noteOff( pluginData );
+		if( m_playingNotes.indexOf( _n ) >= 0 )
+		{
+			m_playingNotesMutex.lock();
+			m_playingNotes.remove( m_playingNotes.indexOf( _n ) );
```
Comment (Wallacoloo) [inline plugins/sf2_player/sf2_player.cpp]: There's the possibility that `m_playingNotes.indexOf( _n ) >= 0` evaluates to true, then another thread removes `_n`, and then we obtain a lock and attempt to call `m_playingNotes.remove( m_playingNotes.indexOf( _n ) )`, which would be an error.

The simple solution is to move the locking and unlocking to just outside of the if statement.

Comment (Wallacoloo) [inline plugins/sf2_player/sf2_player.cpp]: Although, maybe that's not a race condition that you're trying to protect against (as the other note removals don't have these checks). Though you still should lock `m_playingNotes` before calling `indexOf` in case another thread causes the vector to be resized before `indexOf` returns. So in either case, the locking should be moved to outside the conditional.

**Comment by Wallacoloo** [comment]
@tresf I left my feedback. The code inside these lock statements doesn't have the opportunity to hang or call another function that will attempt to obtain other locks, so it looks to be safe and deadlock-free.

**Comment by michaelgregorius** [comment]
@tresf If I understand correctly this patch is rather a band-aid than fixing the "real" cause of the problem but I think it is still better than having nothing. I investigated the problem together with @midi-pascal in #2401 but unfortunately it is hard to find the root cause (as is most of the times with threading related problems). So with regards to the goal of having a version 1.2 I'd say we should merge this as it provides a solution to the problem. There is always room for improvement later.

@midi-pascal Thanks for your endurance in investigating this problem! :smiley:

**Comment by midi-pascal** [comment]
@Wallacoloo  I did what you suggested.
@tresf Not sure if I squashed the 2 commits correctly. Can you verify, please?

**Comment by midi-pascal** [comment]
@michaelgregorius Thanks! This one was tough!

**Comment by tresf** [comment]
@midi-pascal, try rebase again with HEAD~2.

If you click on the `commits` tab above, you'll see how many commits you have.

**Comment by midi-pascal** [comment]
@tresf I already tried this but I get:

# This is a combination of 2 commits.
# The first commit's message is:

Move m_playingNotesMutex.lock() and m_playingNotesMutex.unlock() outside of if( m_playingNotes.indexOf( _n ) >= 0 )

Conflicts:
        plugins/sf2_player/sf2_player.cpp
......
So git sees a conflict so I cannot commit later.

**Comment by midi-pascal** [comment]
@tresf I think I got it.

**Comment by tresf** [comment]
Great.  Consensus says :+1:, merging.

**Comment by midi-pascal** [comment]
:smile:
