### PR TITLE
Don't restore audio device during exporting

### LINKED ISSUE #4032: SDL - Deadlock with gui option: File->Export Tracks
LMMS consistently crashes after rendering 10 tracks with the "Export Tracks" file menu option. OS Windows 10, Version 1.2.0-rc4. Project file is 126 bars long, contains 5 empty beat/bassline tracks, 7 automation tracks, and 34 instrument tracks (11 ZASFX, 16 AFP, 9 3xOsc (2 of which are omitted from rendering)). Will grab and send additional system/project file/otherwise details if deemed necessary.

### PR DESCRIPTION
**Pull request by PhysSong**
This PR fixes deadlock on multi-track export with SDL.
Fixes #4032.

### CODE REVIEW

File: src/core/Mixer.cpp [hunk 1]
```diff
@@ -630,6 +627,17 @@ void Mixer::setAudioDevice( AudioDevice * _dev,
 
 
 
+void Mixer::storeAudioDevice()
+{
+	if( !m_oldAudioDev )
```
Comment (PhysSong) [inline src/core/Mixer.cpp]: I've included this check, but looks redundant. Maybe removing is better?

File: src/core/ProjectRenderer.cpp [hunk 2]
```diff
@@ -103,8 +102,6 @@ ProjectRenderer::ProjectRenderer( const Mixer::qualitySettings & qualitySettings
 
 ProjectRenderer::~ProjectRenderer()
 {
-	Engine::mixer()->restoreAudioDevice();  // also deletes audio-dev
-	Engine::mixer()->changeQuality( m_oldQualitySettings );
```
Comment (zonkmachine) [inline src/core/ProjectRenderer.cpp]: Make sure #3680 still works. If [these test projects](https://github.com/LMMS/lmms/pull/3680#issuecomment-312736420) renders, as instructed, it's a 'go' from me.

Comment (PhysSong) [reply src/core/ProjectRenderer.cpp]: @zonkmachine I'm pretty sure #3680 will still work because `RenderManager` destructor is called after `ProjectRenderer` destructor. However, testing is always good. I'll double-check it!

Comment (PhysSong) [reply src/core/ProjectRenderer.cpp]: @zonkmachine Tested. It still works!

Comment (zonkmachine) [reply src/core/ProjectRenderer.cpp]: OK. I think you should merge.

**Comment by zonkmachine** [comment]
Merge?

**Comment by zonkmachine** [comment]
I've managed to get it hung on the last step but can't replicate it. I don't know if I had https://github.com/LMMS/lmms/pull/4189 cherry-picked on top when this happened or not. I think so but it seem to work fine generally, with or without it.

```
[Thread 0x7fffb1b10700 (LWP 15233) exited]
[New Thread 0x7fffb1b10700 (LWP 15309)]
[Thread 0x7fffb1b10700 (LWP 15309) exited]
^C
Program received signal SIGINT, Interrupt.
__lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
135	../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S: No such file or directory.
(gdb) bt
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff7bc6664 in _L_lock_952 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007ffff7bc64c6 in __GI___pthread_mutex_lock (mutex=0xd80320) at ../nptl/pthread_mutex_lock.c:114
#3  0x00007ffff62ab5fe in SDL_mutexP (mutex=<optimized out>) at ./src/thread/pthread/SDL_sysmutex.c:108
#4  0x000000000058265c in AudioSdl::stopProcessing (this=0xe7a5e0) at /home/zonkmachine/builds/lmms/lmms/src/core/audio/AudioSdl.cpp:110
#5  0x0000000000533fe3 in Mixer::stopProcessing (this=0xc45210) at /home/zonkmachine/builds/lmms/lmms/src/core/Mixer.cpp:251
#6  0x0000000000534f0a in Mixer::changeQuality (this=0xc45210, _qs=...) at /home/zonkmachine/builds/lmms/lmms/src/core/Mixer.cpp:564
#7  0x0000000000552036 in RenderManager::~RenderManager (this=0x189c050, __in_chrg=<optimized out>)
    at /home/zonkmachine/builds/lmms/lmms/src/core/RenderManager.cpp:54
#8  0x00000000005520a6 in RenderManager::~RenderManager (this=0x189c050, __in_chrg=<optimized out>)
    at /home/zonkmachine/builds/lmms/lmms/src/core/RenderManager.cpp:55
#9  0x000000000059b4a9 in ExportProjectDialog::accept (this=0x7fffffffcc30) at /home/zonkmachine/builds/lmms/lmms/src/gui/ExportProjectDialog.cpp:114
#10 0x00000000006438c2 in ExportProjectDialog::qt_static_metacall (_o=0x7fffffffcc30, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7fffffffc400)
    at /home/zonkmachine/builds/lmms/lmms/build/src/moc_ExportProjectDialog.cpp:56
#11 0x00007ffff697087a in QMetaObject::activate (sender=0x189c050, m=<optimized out>, local_signal_index=<optimized out>, argv=0x0)
    at kernel/qobject.cpp:3539
#12 0x000000000064ba9b in RenderManager::finished (this=0x189c050) at /home/zonkmachine/builds/lmms/lmms/build/src/moc_RenderManager.cpp:113
#13 0x00000000005521a1 in RenderManager::renderNextTrack (this=0x189c050) at /home/zonkmachine/builds/lmms/lmms/src/core/RenderManager.cpp:77
#14 0x000000000064b91e in RenderManager::qt_static_metacall (_o=0x189c050, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7fff9c0013c0)
    at /home/zonkmachine/builds/lmms/lmms/build/src/moc_RenderManager.cpp:57
```

**Comment by PhysSong** [comment]
@zonkmachine What is the backtrace? When did you get that?

**Comment by PhysSong** [comment]
The backtrace seems to be from this PR. However, the problem looks like a separate issue and an edge case. I think I can fix that, but probably in another PR.

**Comment by zonkmachine** [comment]
> I think I can fix that, but probably in another PR.

OK. Merge?

**Comment by PhysSong** [comment]
> OK. Merge?

I'll do that soon once Travis-CI build finishes.
