### PR TITLE
Fix Lv2 help window related issues (#6753)

### LINKED ISSUE #6753: LV2 help window - Issue on closing with the 'x' button
### Bug Summary

LV2 plugins with help button/window is disrupted when the help window is closed with the builtin `[x]` button.

#### Steps to reproduce

* Open LV2 plugin. Either an instrument or an effect. Press `[Help]` (Open right corner, if the plugin has one which is not always the case). Help window opens.
* Close the help window by once more pressing the `[Help]` button. Help window closes. This works.
* Now open the help window once more and close it by pressing the top right `[x]` on the help window. Help window closes.
* Repeat opening the help window and this time it's:
    A - Broken, no text in there.
    B - You need to press one extra time to get the focus on the help button.
The window stays broken for this instance of the effect until lmms is restarted.

#### Affected LMMS versions
On master build since LV2 was introduced. At least since LV2-Options.

#### Screenshots

Help window opened.
help2

Help window opened a second time after closing it with the `[x]` instead of the `[Help]` button.
help3

### PR DESCRIPTION
**Pull request by JohannesLorenz**
This fixes at least 3 issues:

* Help window is not synched with window manager's `X`-button
* Help window is not being closed on track destruction or on closing the plugin window
* Trims help window strings and force-adds a newline, because `QLabel::sizeHint` sometimes computes too small values. Now, together with #6956, all help windows fit their strings. Some help windows are too large by one line, but I think this is better than forcing the user to resize them if they are too small by one line.

Fixes #6753

### CODE REVIEW

File: src/gui/Lv2ViewBase.cpp [hunk 1]
```diff
@@ -248,6 +251,32 @@ AutoLilvNode Lv2ViewBase::uri(const char *uriStr)
...
+
+
+
+HelpWindowEventFilter::HelpWindowEventFilter(Lv2ViewBase* viewBase) :
+	m_viewBase(viewBase) {}
+
+
+
+
+bool HelpWindowEventFilter::eventFilter(QObject* , QEvent* event)
```
Comment (JohannesLorenz) [inline src/gui/Lv2ViewBase.cpp:270]: I was not sure whether I should install the `eventFilter` on a separate object (as here, on `HelpWindowEventFilter`), or directly in `Lv2ViewBase`.

**Comment by zonkmachine** [comment]
I get a crash when removing tracks with an LV2 synth that does implement getDescription().

* Open amsynth or any calf synth
* remove the track while the window is still open

```cpp
Thread 1 "lmms" received signal SIGSEGV, Segmentation fault.
0x00007ffff7a84f54 in QWidget::close() () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
(gdb) bt full
#0  0x00007ffff7a84f54 in QWidget::close() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x00005555557f7e4f in lmms::gui::Lv2ViewBase::~Lv2ViewBase() ()
#2  0x00007fff7833ed8f in lmms::gui::Lv2InsView::~Lv2InsView() () at /home/zonkmachine/builds/lmms/build/plugins/liblv2instrument.so
#3  0x000055555588a7b8 in lmms::gui::InstrumentTrackWindow::~InstrumentTrackWindow() ()
#4  0x000055555588a81d in lmms::gui::InstrumentTrackWindow::~InstrumentTrackWindow() ()
#5  0x00005555558b794f in lmms::gui::InstrumentTrackView::~InstrumentTrackView() ()
#6  0x00005555558b7c7d in lmms::gui::InstrumentTrackView::~InstrumentTrackView() ()
#7  0x000055555587a07d in lmms::gui::TrackContainerView::deleteTrackView(lmms::gui::TrackView*) ()
#8  0x00007ffff66f741e in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff7a46713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff66c9e3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff66ccf27 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff6723a67 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff50bbd3b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff5111258 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff50b93e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff67230b8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff66c875b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff66d0cf4 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00005555556a8aa5 in main ()
(gdb) 
```

**Comment by JohannesLorenz** [comment]
> I get a crash when removing tracks with an LV2 synth that does implement getDescription().

Great finding! You mean "that doesn't", right? Fixed it.

**Comment by zonkmachine** [comment]
You mean "that doesn't", right?

That I did. Fix tested. :+1:

**Review by zonkmachine — APPROVED** [review]
Tested, works well.

**Comment by zonkmachine** [comment]
I wonder if the help window should also close when it's parent window is closed. Is there a case for when you want it to stay open after the instrument plugin has been closed?
(this behavior isn't new by the way)

**Comment by JohannesLorenz** [comment]
> I wonder if the help window should also close when it's parent window is closed. Is there a case for when you want it to stay open after the instrument plugin has been closed?

Good point. I cannot see of any use case to leave it open - I pushed a fix.

Also, note that the whole thing should work not only for instruments, but also for effects.

**Comment by zonkmachine** [comment]
> I cannot see of any use case to leave it open - I pushed a fix.

Yes, this is better. It's what you expect really.

> Also, note that the whole thing should work not only for instruments, but also for effects.

I'm testing this together with https://github.com/LMMS/lmms/pull/6956 and haven't faced any issues apart from what has been fixed already.

**Comment by zonkmachine** [comment]
I tested it some more with FPE turned on and we're good. I think this can be merged.

**Comment by JohannesLorenz** [comment]
Small impact, minor changes. Will merge on Sunday if no one will complain.
