### PR TITLE
Don't play anything when no sample is loaded (AFP)

### LINKED ISSUE #7265: Crash in afp with loop and no file loaded
### LMMS Version(s)

master after a81ad74e3ae6c4ac053ef26670f96aba640d96c4

### Bug Summary

lmms crashes when you play a note on the Audio File Processor with loop set but no file loaded.
Issue was introduced in https://github.com/LMMS/lmms/pull/7100
Partially fixed in https://github.com/LMMS/lmms/pull/7113

I tried moving the test from Loop::Off to the top of the for loop and that fixed the crash. I don't know what other possible issues arise from this however. 

```patch
diff --git a/src/core/Sample.cpp b/src/core/Sample.cpp
index cd238b2ca..cef0f4ab1 100644
--- a/src/core/Sample.cpp
+++ b/src/core/Sample.cpp
@@ -175,10 +175,10 @@ void Sample::playRaw(sampleFrame* dst, size_t numFrames, const PlaybackState* st
 
        for (size_t i = 0; i < numFrames; ++i)
        {
+               if (index < 0 || index >= m_endFrame) { return; }
                switch (loopMode)
                {
                case Loop::Off:
-                       if (index < 0 || index >= m_endFrame) { return; }
                        break;
                case Loop::On:
                        if (index < m_loopStartFrame && backwards) { index = m_loopEndFrame - 1; }

```

@sakertooth @khoidauminh 

### Steps To Reproduce

* Add an Audio File Processor to a project
* Set loop play
* Press a key

### Logs

**bt full**
<details>
<summary>Click to expand</summary>
<pre>
Thread 37 "AudioEngine::fi" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff997fc640 (LWP 126074)]
0x00005555558d51af in lmms::Sample::playRaw (this=0x7fffdc003ec0, dst=0x7fff40005830, numFrames=207, state=0x7fff40004610, loopMode=lmms::Sample::Loop::On) at /home/zonkmachine/builds/lmms/src/core/Sample.cpp:204
204			dst[i] = m_buffer->data()[m_reversed ? m_buffer->size() - index - 1 : index];
(gdb) bt full
#0  0x00005555558d51af in lmms::Sample::playRaw(std::array<float, 2ul>*, unsigned long, lmms::Sample::PlaybackState const*, lmms::Sample::Loop) const
    (this=0x7fffdc003ec0, dst=0x7fff40005830, numFrames=207, state=0x7fff40004610, loopMode=lmms::Sample::Loop::On) at /home/zonkmachine/builds/lmms/src/core/Sample.cpp:204
        i = 0
        index = 0
        backwards = false
#1  0x00005555558d4bc7 in lmms::Sample::play(std::array<float, 2ul>*, lmms::Sample::PlaybackState*, unsigned long, float, lmms::Sample::Loop) const
    (this=0x7fffdc003ec0, dst=0x555558ee4c10, state=0x7fff40004610, numFrames=256, desiredFrequency=349.228241, loopMode=lmms::Sample::Loop::On) at /home/zonkmachine/builds/lmms/src/core/Sample.cpp:136
        __PRETTY_FUNCTION__ = "bool lmms::Sample::play(lmms::sampleFrame*, lmms::Sample::PlaybackState*, size_t, float, lmms::Sample::Loop) const"
        pastBounds = true
        outputSampleRate = 55562.5156
        inputSampleRate = 44100
        resampleRatio = 1.25992095
        marginSize = 4

                      playBuffer = std::vector of length 207, capacity 207 = {{_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}, {_M_elems = {0, 0}}...}
        resampleResult = {error = 0, inputFramesUsed = 0, outputFramesGenerated = 0}
        outputFrames = 0
#2  0x00007fffc41177f3 in lmms::AudioFileProcessor::playNote(lmms::NotePlayHandle*, std::array<float, 2ul>*) (this=0x7fffdc003e50, _n=0x5555563def48, _working_buffer=0x555558ee4c10)
    at /home/zonkmachine/builds/lmms/plugins/AudioFileProcessor/AudioFileProcessor.cpp:158
        frames = 256
        offset = 0
#3  0x0000555555a9895c in lmms::InstrumentTrack::playNote(lmms::NotePlayHandle*, std::array<float, 2ul>*) (this=0x555558c9eba0, n=0x5555563def48, workingBuffer=0x555558ee4c10)
    at /home/zonkmachine/builds/lmms/src/tracks/InstrumentTrack.cpp:584
#4  0x00005555558aefc0 in lmms::NotePlayHandle::play(std::array<float, 2ul>*) (this=0x5555563def48, _working_buffer=0x555558ee4c10) at /home/zonkmachine/builds/lmms/src/core/NotePlayHandle.cpp:263
        framesThisPeriod = 256

</pre>
</details>

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by khoidauminh**
(I realized the PR tittle should've been the commit message and the other way around)

Fixes #7265

### CODE REVIEW

**Review by zonkmachine — APPROVED** [review]

File: src/core/Sample.cpp [hunk 1]
```diff
@@ -170,6 +170,8 @@ void Sample::setAllPointFrames(int startFrame, int endFrame, int loopStartFrame,
 
 void Sample::playRaw(sampleFrame* dst, size_t numFrames, const PlaybackState* state, Loop loopMode) const
 {
+	if (m_buffer->size() < 1) { return; }
```
Comment (sakertooth) [inline src/core/Sample.cpp:173]: I think this expresses the intent more clearly, but it's not that much of a big deal.
```suggestion
	if (m_buffer->size() == 0) { return; }
```

**Review by sakertooth — APPROVED** [review]
We might want to switch to using `nullptr` to represent having no buffer, but callers would have to handle that case properly and not just use the `nullptr` buffer like it was a normal one, which was why I went with just having empty buffers. I might still consider switching to check against `nullptr` in the future if it makes more sense though.

**Review by messmerd — APPROVED** [review]
