### PR TITLE
Fix segfault when moving channels

### LINKED ISSUE #1584: Crash when moving mixer channels to left/right
Sometimes you are able to cause a Segmentation Fault when using the "Move Right"/"Move Left" functionality on mixer channels.

I was not able to identify how to reproduce this error deterministically, but you should be able to trigger this just moving nearby channels at the rightmost part of the mixer.

The backtrace shows that this is the offending line: https://github.com/LMMS/lmms/blob/40438689922e843fcf07d22dd52378cb7e5237d5/src/gui/widgets/FxLine.cpp#L208

Full backtrace here: https://gist.github.com/badosu/54bf4c6cd2d504daaab0

### PR DESCRIPTION
**Pull request by badosu**
This commit addresses a lot of issues, namely:

1. When the "Move left/right" action was selected on a mixer channel
menu sometimes it would segfault due to the fxline object being
deleted before it returned to a method inside itself

2. The Fader was declaring a new variable for the model rather
than using the inherited model from FloatModelView < AutomatableModelView

3. Some methods were doing more things than they should and
performing unnecessary actions. A little cleanup/refactor was made

Please notice that a bug of the same class as the one referred at point 1
still exists: clicking on "Remove channel". This commit does not
address it.

Fixes #1584

### CODE REVIEW

File: src/core/FxMixer.cpp [hunk 1]
```diff
@@ -327,6 +327,19 @@ void FxMixer::deleteChannel( int index )
 	for( int i = index; i < m_fxChannels.size(); ++i )
 	{
 		validateChannelName( i, i + 1 );
+
+		// set correct channel index
+		m_fxChannels[i]->m_channelIndex = i;
```
Comment (badosu) [inline src/core/FxMixer.cpp]: This looks stupid, and indeed it is.

I did not add any behaviour here, though. This is just inlining what was the previous `validateChannelName` function.

I did not analyze whether this could be removed or not, mantained consistency with the previous code.

**Comment by badosu** [comment]
Eagerly hoping for @diizy 's:

Seal of Approval

File: src/gui/FxMixerView.cpp [hunk 2]
```diff
@@ -432,53 +444,39 @@ void FxMixerView::deleteUnusedChannels()
...
+	// Swap positions in array
+	qSwap(m->m_fxChannels[index], m->m_fxChannels[index - 1]);
 
-		// add it again
-		m_fxChannelViews[i] = new FxChannelView( m_channelAreaWidget, this, i );
-		chLayout->insertWidget( replaceIndex, m_fxChannelViews[i]->m_fxLine );
-		m_racksLayout->insertWidget( replaceIndex, m_fxChannelViews[i]->m_rackView );
-	}
+	// Focus on new position
+	setCurrentFxLine( focusIndex );
```
Comment (diizy) [inline src/gui/FxMixerView.cpp]: What is the point of this? If I move a channel, that doesn't imply I want the moved channel necessarily selected...

File: src/core/FxMixer.cpp (hunk 1 above)
Comment (diizy) [inline src/core/FxMixer.cpp]: Why did you move it here? What is the purpose of this move?

File: include/Fader.h [hunk 3]
```diff
@@ -100,14 +100,12 @@ class EXPORT Fader : public QWidget, public FloatModelView
...
 	{
-		float fRange = m_model->maxValue() - m_model->minValue();
-		float realVal = m_model->value() - m_model->minValue();
+		float fRange = model()->maxValue() - model()->minValue();
+		float realVal = model()->value() - model()->minValue();
 
 		return height() - ( ( height() - m_knob->height() ) * ( realVal / fRange ) );
 	}
 
-	FloatModel * m_model;
```
Comment (diizy) [inline include/Fader.h]: Why are you removing the model variable from a widget???

File: src/gui/FxMixerView.cpp (hunk 2 above)
Comment (tresf) [inline src/gui/FxMixerView.cpp]: Agreed.  Furthermore, if we use a function `moveChannelLeft(...)` to actually move a channel right, we may consider renaming the function to better describe its purpose. :)

Comment (badosu) [inline src/gui/FxMixerView.cpp]: Well, this is previous behaviour. My intention is to *fix* the segfault, not introducing changes.

Do you want me to remove this?

File: src/core/FxMixer.cpp (hunk 1 above)
Comment (badosu) [inline src/core/FxMixer.cpp]: To not do **this** on a function called `validateChannelName`? Do you have a better idea?

File: include/Fader.h (hunk 3 above)
Comment (badosu) [inline include/Fader.h]: As described on the PR. This was creating ambiguity since this widget is **already** an `Float ModelView`, so instead of accessing the inner variable `m_model` that is inherited from that you would have a bug where a different, out of the blue, model is accessed.

This was the cause of hours and hours of debugging to try to understand why when I moved the fader model, it was **still** being modeled by the other FX Variable.

This is fixed by using `model()`.

Comment (diizy) [inline include/Fader.h]: On 01/23/2015 05:30 PM, Amadeus Folego wrote:
>
> In include/Fader.h
> <https://github.com/LMMS/lmms/pull/1678#discussion_r23456242>:
>
> >  
> >  		return height() - ( ( height() - m_knob->height() ) * ( realVal / fRange ) );
> >  	}
> >  
> > -	FloatModel * m_model;
>
> As described on the PR. This was creating ambiguity since this widget
> is *already* an |Float ModelView|, so instead of accessing the inner
> variable |m_model| that is inherited from that you would have a bug
> where a different, out of the blue, model is accessed.
>
> This was the cause of hours and hours of debugging to try to
> understand why when I moved the fader model, it was *still* being
> modeled by the other FX Variable.
>
> This is fixed by using |model()|.
>

Cool, that seems sensible.

**Comment by badosu** [comment]
@tresf @diizy Let's keep this PR hanging for a few days, I want to be sure that I am not introducing any bug.

**Comment by tresf** [comment]
@badosu it has been a while since this PR was submitted.  We should probably decide how to proceed  with this so we can start the 1.2 freeze.

**Comment by badosu** [comment]
@tresf I am awaiting for this for a long time, this is ready for testing since then.

It may have some issues but I never got any feedback.

**Comment by tresf** [comment]
> It may have some issues but I never got any feedback.

We're merging then.  We'll get test results with the imminent 1.2-RC releases.  Thanks!
