### PR TITLE
Recording logarithmic automation hotfix

### LINKED ISSUE #6954: Logarithmic vs linear, and automation, uncanny behavior
Hi, I search the tracker but found nothing. I’m not even sure if it’s a bug or a feature… You tell me.

When a knob is set to logarithmic scale and you record a movement in an automation track, that’s the logarithmic values which are recorded, and that’s fine. But, then you play back the automation, you have to put back the knob to linear mode, or else, you get logarithm of logarithmic values!

To reproduce, get any knob which can be switched to linear or logarithmic, put it in logarithmic mode. Create an automation track in the song editor, record some moves of the knob, then play it back.

Expected behavior is to get the same value you recorded when you play it back without minding if the knob is linear or logarithmic. 

Actual behavior is that’s the values which are rendered are log(log(x)), unless you put back the knob to linear mode before playing back the automation. 

LMMS 1.3.0-alpha.1.445+gcd018c04f
(Linux x86_64, Qt 5.15.8, GCC 12.2.0)

I said I wasn’t sure it wasn’t a feature, because with the actual behavior you may move a knob which set logarithmic values and then get the log(log(c)) using the automation. But I’m not sure this could be useful, but sure is disconcerting at first (and not a problem once you know it).

### PR DESCRIPTION
**Pull request by regulus79**
When you record an automation clip with a logarithmic knob (for example, a freq knob in the equalizer) the recorded values in the automation editor are correct.....

....*But*, for whatever reason, lmms tries to scale the recorded values back to linear when playing the automation, which causes the recorded frequency to be much lower.

This pr does not fix the underlying issue, but instead just scales the recorded values so that everything works.

Imo, the whole automation system needs some reorganizing, but that will have to wait. Just one example of the choas caused by swithcing between scaled/unscaled values: The automation editor conflicts with itself when showing scaled parameters. The tooltip shows the scaled value, while the actual stored value which you can edit when double-clicking on a node is unscaled. But again, that's for another day.

Fixes #6954 and #6209 and maybe #6490

### CODE REVIEW

File: src/core/Song.cpp [hunk 1]
```diff
@@ -396,7 +396,7 @@ void Song::processAutomations(const TrackList &tracklist, TimePos timeStart, fpp
 		if (p->isRecording() && relTime >= 0 && relTime < p->length())
 		{
 			const AutomatableModel* recordedModel = p->firstObject();
-			p->recordValue(relTime, recordedModel->value<float>());
+			p->recordValue(relTime, recordedModel->inverseScaledValue(recordedModel->value<float>()));
```
Comment (sakertooth) [inline src/core/Song.cpp:399]: Maybe add a TODO comment explaining we should come back and do a real fix?

**Comment by regulus79** [comment]
This is ready to merge btw

**Comment by allejok96** [comment]
The better solution would to give the automation editor a logarithmic Y axis when working with logarithmic models (possibly even an letting the user choose linear/log when drawing) and updating the draw code in AutomationClipView the same way. And then we'd need to do a update routine for older files...

But until then let's merge this.

**Comment by regulus79** [comment]
> Why isn't this merged yet?

I can't merge it until someone with write access approves.

**Comment by sakertooth** [comment]
Pretty sure you have write access @allejok96? I haven't been able to test this, but if it fixed the issue it should be fine for now.

**Comment by sakertooth** [comment]
Oh wait you aren't a member? Hm..

**Comment by sakertooth** [comment]
@bratpeki can you help quickly test this for me? The PR code wise is fine, it isn't too invasive, but testing it never hurts. I think the TODO comment also explains the situation quite well.

**Review by sakertooth — APPROVED** [review]
Eh.. I would also be fine if @regulus79 is sure about the fix. Sorry for all the @'s lol.
