### PR TITLE
Fix DynamicsProcessor bugs

### LINKED ISSUE #1581: Dynamics processor causes waveshaping, even with the highest possible attack and decay values
I could be wrong about how the dynamics processor is supposed to work, but as I understand, it should work like a compressor with a custom curve. If you have experience with compressors, you probably know that a compressor will start doing strange things if the attack (or decay) is set to a value that is too short. If you have an attack that is too short, the compressor will change the shape of the wave because it is changing the volume so fast. Here's an example of a sine wave (roughly 50 hz) that has been run through C\* Compress with the attack and decay set to 1.2 ms:

image

And here it is without:

image

Even with the low attack, there is still interpolation of some sort to keep the edges smooth.

The dynamics processor is doing something with roughly the same effect. Here are the settings I'm using to test this:

image

And here is the waveform it generates, along with the harmonics (each line represents a sine wave at that frequency - the original input was a single sine wave):

image

image

Am I wrong about how it's supposed to work, or is this a flaw in the algorithm?

### PR DESCRIPTION
**Pull request by LostRobotMusic**
Dynamics Processor has... a lot of issues.  This fixes them.

1. Only one of the coefficient calculations has a negative sign.  The reason for this is unknown.  I'm thinking the creator was thrown off by the attack and release coefficient calculations being identical and tossed in a negative due to attack and release being thought of as opposites.
2. The coefficient calculations use `10^x` instead of `e^x`.  This is incorrect.
3. `DNF_LOG` is a seemingly totally arbitrary value of `5`.  I've only ever seen values of `1` and `2.2` used there (the latter of which I'm pretty sure is a bug in online code that thousands wound up copying, given `2.3` is the actual correct value to get the desired 10:1 ratio).  The value of this variable is _not_ something that should be adjusted for personal preference, it is what determines the ratio between the new and old volumes after the exact duration of the attack or release time passes.
4. The coefficients are ultimately used incorrectly, rather than for 1-pole IIR filters as they should be used for.

**THIS BREAKS BACKWARDS COMPATIBILITY,** but there seems to be unanimous agreement that in this case it is entirely acceptable.

This closes #1581 and replaces #7013 (apologies).

Audio examples can be found here:
[avocado.zip](https://github.com/LMMS/lmms/files/14761767/avocado.zip)

### CODE REVIEW

File: plugins/DynamicsProcessor/DynamicsProcessor.cpp [hunk 1]
```diff
@@ -155,15 +155,15 @@ bool DynProcEffect::processAudioBuffer( sampleFrame * _buf,
...
 			}
 			else
 			if( t < m_currentPeak[i] )
 			{
-				m_currentPeak[i] = qMax( m_currentPeak[i] * m_relCoeff, t );
+				m_currentPeak[i] = m_currentPeak[i] * m_relCoeff + (1 - m_relCoeff) * t;
 			}
 
-			m_currentPeak[i] = qBound( DYN_NOISE_FLOOR, m_currentPeak[i], 10.0f );
+			m_currentPeak[i] = qMax(DYN_NOISE_FLOOR, m_currentPeak[i]);
```
Comment (Veratil) [inline plugins/DynamicsProcessor/DynamicsProcessor.cpp:166]:
```suggestion
			m_currentPeak[i] = std::max(DYN_NOISE_FLOOR, m_currentPeak[i]);
```

File: plugins/DynamicsProcessor/DynamicsProcessor.cpp [hunk 2]
```diff
@@ -56,7 +56,7 @@ Plugin::Descriptor PLUGIN_EXPORT dynamicsprocessor_plugin_descriptor =
 }
 
 const float DYN_NOISE_FLOOR = 0.00001f; // -100dBFS noise floor
-const double DNF_LOG = 5.0;
+const double DNF_LOG = -1.0;
```
Comment (messmerd) [inline plugins/DynamicsProcessor/DynamicsProcessor.cpp:59]: Just double-checking you meant this to be -1 not +1

Comment (LostRobotMusic) [reply plugins/DynamicsProcessor/DynamicsProcessor.cpp:59]: Yes, the negative sign was removed from the coefficient calculation function.

**Review by messmerd — APPROVED** [review]

**Review by sakertooth — APPROVED** [review]
