### PR TITLE
Only set sample clips for valid files

### LINKED ISSUE #6287: SampleClip: valid file disappears when replaced with invalid one
### Bug Summary
When a sample clip contains a valid audio file and the user replaces it with an invalid one, the previous (valid) sample disappears. #6286 is related and should be merged before a fix is proposed.

#### Steps to reproduce
1. Create an empty file with the ".wav" extension.
2. Start LMMS.
3. Add a sample track.
4. Add a clip to the sample track and load a valid audio file into it.
5. Replace the valid file loaded on step 4 with the empty file created on step 1.

#### Expected behavior
The previous (valid) audio file should be kept intact in the sample clip (and an error message should be shown, which #6286 addresses).

#### Actual behavior
The sample clip becomes empty.

#### Affected LMMS versions
1.3.0-alpha.1.163+g0d1b455be (Linux/x86_64, Qt 5.15.2, GCC 10.2.1 20201203).

### PR DESCRIPTION
**Pull request by michaelgregorius**
Check if a non-empty buffer was loaded and only set the sample clip if that's the case.

Fix code formatting.

Fixes #6287.

### CODE REVIEW

File: src/gui/clips/SampleClipView.cpp [hunk 1]
```diff
@@ -183,16 +182,22 @@ void SampleClipView::mouseDoubleClickEvent( QMouseEvent * )
...
-	{	//Instead of reloading the existing file, just reset the size
-		int length = static_cast<int>(m_clip->m_sample.sampleSize() / Engine::framesPerTick());
-		m_clip->changeLength(length);
+	// Don't do anything if no file is loaded
+	if (af.isEmpty()) { return; }
+	
+	if (af == m_clip->m_sample.sampleFile())
+	{
+		// Don't reload the same file again. Just reset the size.
+		m_clip->changeLengthToSampleLength();
```
Comment (sakertooth) [inline src/gui/clips/SampleClipView.cpp:191]: Was this refactoring necessary?

File: src/gui/clips/SampleClipView.cpp [hunk 2]
```diff
@@ -183,16 +182,22 @@ void SampleClipView::mouseDoubleClickEvent( QMouseEvent * )
...
 	}
 	else
```
Comment (sakertooth) [inline src/gui/clips/SampleClipView.cpp:193]: You could combine this like so:
```suggestion
	else if (auto sampleBuffer = SampleLoader::createBufferFromFile(af); sampleBuffer != SampleBuffer::emptyBuffer()) 
```

File: src/core/SampleClip.cpp [hunk 3]
```diff
@@ -129,6 +134,8 @@ void SampleClip::setSampleBuffer(std::shared_ptr<const SampleBuffer> sb)
 	updateLength();
 
 	emit sampleChanged();
+
+	Engine::getSong()->setModified();
```
Comment (sakertooth) [inline src/core/SampleClip.cpp:138]: Is this in scope?

File: src/core/SampleClip.cpp [hunk 4]
```diff
@@ -210,6 +217,8 @@ void SampleClip::setIsPlaying(bool isPlaying)
 void SampleClip::updateLength()
 {
 	emit sampleChanged();
+
+	Engine::getSong()->setModified();
```
Comment (sakertooth) [inline src/core/SampleClip.cpp:221]: Same here?

**Review by sakertooth — COMMENTED** [review]
The comments are a bit much. I feel like the code is simple enough that it can be understood very well without them.

File: src/gui/clips/SampleClipView.cpp (hunk 1 above)
Comment (michaelgregorius) [reply src/gui/clips/SampleClipView.cpp:191]: It's more or less an application of the [boyscout rule](https://deviq.com/principles/boy-scout-rule). The view contained logic/actions that's part of the core/"business" and therefore I moved it to where it belongs.

File: src/gui/clips/SampleClipView.cpp (hunk 2 above)
Comment (michaelgregorius) [reply src/gui/clips/SampleClipView.cpp:193]: Thanks for the suggestion but I find it more readable and quicker to comprehend as is.

File: src/core/SampleClip.cpp (hunk 3 above)
Comment (michaelgregorius) [reply src/core/SampleClip.cpp:138]: Same as above with regards to the boyscout rule. Setting the song to modified because something has changed in the core/"business" is not in the responsibility of the presentation/GUI layer. With the changes it will work even if the GUI was switched completely of if there was no GUI and some other entity would listen to song changes.

File: src/core/SampleClip.cpp (hunk 4 above)
Comment (michaelgregorius) [reply src/core/SampleClip.cpp:221]: Same answer as above. :wink:

File: src/core/SampleClip.cpp [hunk 5]
```diff
@@ -112,6 +112,11 @@ void SampleClip::changeLength( const TimePos & _length )
 	Clip::changeLength(std::max(static_cast<int>(_length), 1));
 }
 
+void SampleClip::changeLengthToSampleLength()
+{
+	int length = static_cast<int>(m_sample.sampleSize() / Engine::framesPerTick());
```
Comment (Veratil) [inline src/core/SampleClip.cpp:117]: Do we need the static_cast if we're already assigning to int? Or is this to suppress a warning?

Comment (michaelgregorius) [reply src/core/SampleClip.cpp]: You're right. We don't need it. It was "inherited" from the existing code and I moved it without putting too much thought into it. Removed with commit ef681e1b79a.

File: src/gui/clips/SampleClipView.cpp (hunk 1 above)
Comment (sakertooth) [reply src/gui/clips/SampleClipView.cpp:191]: Since its low hanging fruit, it's not a big deal at all, but I would add some details about it in the commit description (something along the lines of also move around `setModified` logic to the correct spot) since this PR is doing more than what it said it would on the tin.

Comment (michaelgregorius) [reply src/gui/clips/SampleClipView.cpp:191]: It's already mentioned in the commit message of commit 14ce3cc0.

**Comment by sakertooth** [comment]
Do we really need all of these comments? The code is very simple to understand without them.

**Comment by michaelgregorius** [comment]
> Do we really need all of these comments? The code is very simple to understand without them.

Most of the comments have been kept and slightly adjusted from the previous code. With commit 4d5bf7c6078 I have removed them. I have also introduced `SampleClip::hasSampleFileLoaded` to make the check more readable so that the comment can also be removed there. Before it was not directly obvious that the string comparison checks if the filename corresponds to the file that's loaded in the clip.

**Review by sakertooth — APPROVED** [review]
