### PR TITLE
Fixed bug where cross hairs were incorrectly draw in Automation Editor

### LINKED ISSUE #1052: Automation editor cursor redraw
This is not the known 'theme problem' 
It occurs if the mouse is moved *together* with a smaller window *over* the automation-editor ate, and is immediately gone, when the ate get focus.
Looks like it caused by lmms trying to draw the red cross-positioned bars, in are, but the screen are at the same time working on foreground updating.
It is more than likely that this glitch will be different on different hw! 
IMO -Insignificant, but now its at least known

*Edited @tref 2014-12-04, added screenshots, fixed typos :)*
image

image

### PR DESCRIPTION
**Pull request by curlymorphic**
The cross hairs in the automation editor were incorrectly drawn
when moving another window infront.
This change only draws the cross hairs when the window has focus.

fixes #1052

### CODE REVIEW

File: src/gui/editors/AutomationEditor.cpp [hunk 1]
```diff
@@ -1314,8 +1314,9 @@ void AutomationEditor::paintEvent(QPaintEvent * pe )
 		m_leftRightScroll->setPageStep( l );
 	}
 
-	if( validPattern() )
+	if( validPattern() && GuiApplication::instance()->automationEditor()->hasFocus() )
```
Comment (badosu) [inline src/gui/editors/AutomationEditor.cpp]: Aren't you already inside the `AutomationEditor` instance?

In this case wouldn`t simply `hasFocus()` work?

Comment (curlymorphic) [inline src/gui/editors/AutomationEditor.cpp]: The name is confusing. ````!GuiApplication::instance()->automationEditor()```` returns an ````AutomationEditorWindow````.

It's this ````AutomationEditorWindow````.that we need to check not ````AutomationEditor````. It took me a while to figure this out.

Comment (badosu) [inline src/gui/editors/AutomationEditor.cpp]: Oh, ok :-)

**Comment by tresf** [comment]
Travis is lying.  This build passes.   Thanks Dave.  Merging.

**Comment by curlymorphic** [comment]
:)
