### PR TITLE
Fixes #6786: Lv2: Fix losing automation on export

### LINKED ISSUE #6786: Lv2 instruments looses automation on export
### Bug Summary 
Lv2 instruments looses control from Automation Track on export.

#### Steps to reproduce
Connect an LV2 plugin control to an Automation Track and make a distinct pattern.
Make sure it works under lmms live with a distinct change in sound.
Export it. The exported project sees no variation in the controller.
 
Here is a demo project using DISTRHO/DPF-Plugins Kars, automating the Release.
[lv2automationexport.mmp.zip](https://github.com/LMMS/lmms/files/12206180/lv2automationexport.mmp.zip)

Issue introduced in f48dd0fb1f424e06cd7bff1cb3d4c37f5d9a11a7
`Fixes #6401: Reload Lv2 plugin on SR change`
@JohannesLorenz

### PR DESCRIPTION
**Pull request by JohannesLorenz**
This is the bugfix for #6786

### CODE REVIEW

**Comment by zonkmachine** [comment]
Testing ongoing. I haven't been able to reproduce the issue or seen any other glitches in a couple of hours. Looks like it's fixed.

**Review by zonkmachine — APPROVED** [review]
Tested, works fine. The parts of the code I understand looks fine and I'm not going to touch style...

File: src/core/lv2/Lv2Features.cpp [hunk 1]
```diff
@@ -109,7 +109,12 @@ void *&Lv2Features::operator[](const char *featName)
 
 void Lv2Features::clear()
 {
-	m_featureByUri.clear();
+	m_features.clear();
+	for(auto& [uri, feature] : m_featureByUri)
```
Comment (messmerd) [inline src/core/lv2/Lv2Features.cpp:113]:
```suggestion
	for (auto& [uri, feature] : m_featureByUri)
```
style

File: src/core/lv2/Lv2Proc.cpp [hunk 2]
```diff
@@ -168,13 +168,35 @@ Plugin::Type Lv2Proc::check(const LilvPlugin *plugin,
...
+public:
+	Lv2ProcSuspender(Lv2Proc* proc)
+		: m_proc(proc)
+		, m_wasActive(proc->m_instance)
+	{
+		if(m_wasActive) { m_proc->shutdownPlugin(); }
+	}
+	~Lv2ProcSuspender()
+	{
+		if(m_wasActive) { m_proc->initPlugin(); }
```
Comment (messmerd) [inline src/core/lv2/Lv2Proc.cpp:182]:
```suggestion
		if (m_wasActive) { m_proc->shutdownPlugin(); }
	}
	~Lv2ProcSuspender()
	{
		if (m_wasActive) { m_proc->initPlugin(); }
```
style

**Review by messmerd — APPROVED** [review]
Haven't tested it, but it looks pretty good.

A few weeks ago I noticed this same issue in the CLAP host I've been working on and I [fixed it in a similar way](https://github.com/messmerd/lmms/commit/058efde5a7595f9f4df84099938b9b062ea92287#diff-9126fa55a4c861ba7eefc5fac37657caab3bd1cd9e0b3790cfffe23fe169c62fR310-R316) - just without the RAII.

**Comment by JohannesLorenz** [comment]
> Haven't tested it, but it looks pretty good.

Thanks for the review.

> A few weeks ago I noticed this same issue in the CLAP host I've been working on and I [fixed it in a similar way](https://github.com/messmerd/lmms/commit/058efde5a7595f9f4df84099938b9b062ea92287#diff-9126fa55a4c861ba7eefc5fac37657caab3bd1cd9e0b3790cfffe23fe169c62fR310-R316) - just without the RAII.

Funny, that indeed looks like the issue which I fixed here :grin:

**Comment by JohannesLorenz** [comment]
Will merge next weekend if no one complains.

File: src/core/lv2/Lv2Proc.cpp [hunk 3]
```diff
@@ -168,13 +168,35 @@ Plugin::Type Lv2Proc::check(const LilvPlugin *plugin,
...
+class Lv2ProcSuspender
+{
+public:
+	Lv2ProcSuspender(Lv2Proc* proc)
+		: m_proc(proc)
+		, m_wasActive(proc->m_instance)
+	{
+		if (m_wasActive) { m_proc->shutdownPlugin(); }
+	}
+	~Lv2ProcSuspender()
```
Comment (messmerd) [inline src/core/lv2/Lv2Proc.cpp:180]: This should be marked `noexcept(false)` if `initPlugin()` can throw exceptions, because this destructor is implicitly `noexcept`.

**Comment by messmerd** [comment]
@JohannesLorenz You should add "Fixes #6786" in the PR's body so that GitHub links this PR with that issue.

File: src/core/lv2/Lv2Proc.cpp (hunk 3 above)
Comment (sakertooth) [reply src/core/lv2/Lv2Proc.cpp:180]: [Destructors should never fail](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c36-a-destructor-must-not-fail), so I think a termination on exceptions is practically required and `noexcept`  [should be added](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c37-make-destructors-noexcept).

Comment (messmerd) [reply src/core/lv2/Lv2Proc.cpp:180]: Generally speaking that is true. But for `Lv2ProcSuspender`, given its purpose as a scope guard, and looking at how its data members are plain old data, no issues would be caused by an exception thrown in its destructor. Sort of like the [`std::experimental::scope_success`](https://en.cppreference.com/w/cpp/experimental/scope_success/%7Escope_success) scope guard's destructor which uses a conditional `noexcept`.

But after looking at the implementation of `shutdownPlugin()`, it shouldn't be throwing any exceptions, so `Lv2ProcSuspender` is fine as it is.

File: src/core/lv2/Lv2Proc.cpp [hunk 4]
```diff
@@ -168,13 +168,35 @@ Plugin::Type Lv2Proc::check(const LilvPlugin *plugin,
...
+	{
+		if (m_wasActive) { m_proc->initPlugin(); }
+	}
+private:
+	Lv2Proc* const m_proc;
+	const bool m_wasActive;
```
Comment (sakertooth) [inline src/core/lv2/Lv2Proc.cpp:186]: Must these variables be `const`?

Comment (JohannesLorenz) [reply src/core/lv2/Lv2Proc.cpp:186]: I understand the Guidelines as [`const` should always be preferred](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rconst-immutable)?

Comment (Veratil) [reply src/core/lv2/Lv2Proc.cpp:186]: If the intent is to initialize the class with the value and it will never change within the class for any reason, then `const` is fine.

Comment (sakertooth) [reply src/core/lv2/Lv2Proc.cpp:186]: I generally do not make member variables `const` because it breaks the general semantics of the class, such as moving it.

Comment (JohannesLorenz) [reply src/core/lv2/Lv2Proc.cpp:186]: I still prefer having `const`-safety over not break copyability which I actually even want to break.

Actually, I even added this on purpose. I copied my code from

https://github.com/LMMS/lmms/blob/6d4343ca948d81d30698cf9442c84fc595bd2bed/plugins/VstBase/RemoteVstPlugin.cpp#L401-L417

and I was first confused about this code. I was somehow thinking `m_resumed` was something like a state which changes when the plugin gets resumed - `const` makes this clear.

Comment (sakertooth) [reply src/core/lv2/Lv2Proc.cpp:186]: > I still prefer having const-safety over not break copyability which I actually even want to break.

If you do not intend this class to be copied, movied, or assigned, I would disable the operations explicitly with `= delete`, because now its not as clear that this class is not meant to be copied, moved or assigned in any way. I understand this class to be a scope guard, and scope guards (atleast in the TS) do not have such capabilities for the most part.

**Comment by JohannesLorenz** [comment]
I finally added the `NoCopyNoMove` class. Will merge on Sunday if no one has more comments.

File: include/NoCopyNoMove.h [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+ *
+ * You should have received a copy of the GNU General Public
+ * License along with this program (see COPYING); if not, write to the
+ * Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
+ * Boston, MA 02110-1301 USA.
+ *
+ */
+
+#ifndef NOCOPYNOMOVE_H
+#define NOCOPYNOMOVE_H
```
Comment (sakertooth) [inline include/NoCopyNoMove.h:26]:
```suggestion
#ifndef LMMS_NOCOPYNOMOVE_H
#define LMMS_NOCOPYNOMOVE_H
```

File: include/NoCopyNoMove.h [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+	NoCopyNoMove() = default;
+	NoCopyNoMove(const NoCopyNoMove& other) = delete;
+	NoCopyNoMove& operator=(const NoCopyNoMove& other) = delete;
+	NoCopyNoMove(NoCopyNoMove&& other) = delete;
+	NoCopyNoMove& operator=(NoCopyNoMove&& other) = delete;
+};
+
+} // namespace lmms
+
+#endif // NOCOPYNOMOVE_H
```
Comment (sakertooth) [inline include/NoCopyNoMove.h:46]:
```suggestion
#endif // LMMS_NOCOPYNOMOVE_H
```

**Review by sakertooth — APPROVED** [review]
Could you explain why the inheritance for `NoCopyNoMove` should be `private`? Other examples I've seen online do this as well, but wasn't too sure why.

**Comment by JohannesLorenz** [comment]
> Could you explain why the inheritance for `NoCopyNoMove` should be `private`? Other examples I've seen online do this as well, but wasn't too sure why.

My idea was that this class does not contain anything that any user of `Lv2Suspender` could need. So it could be both `public` or `private`, but I prefer the stronger restriction, and tbh, having one word less.
