### PR TITLE
Some fixes to recent files

### LINKED ISSUE #528: New Project opens with old paramters
valid for loop-indicator-state & windows-states
Significance :Low

loop-indicators
In Song-editor & piano-roll:
A 'New Project' will have the loop-indicators in the same posistions, and state as the last saved project. It is more intuitive if 'New Project'loop-indicators are in the first beat, and off.

Windows-states
'New Project' open with the same windows-states as the last saved project. For instance -if all windows was closed, the 'New Project' has an empty GUI.

(cheked Main tempo, time-sign, master-vol & master-pitch -all are correctly set to default values)

### PR DESCRIPTION
**Pull request by zonkmachine**
The recent file system feels a bit glitchy. If you work with a saved file and then start a new project, or a new project from template that you decide to scratch, the next time you launch LMMS you will get back the previous saved work again. I find this a bit unintuitive as you've done other work in between.

---

### Fixes

 - If the last project was a template we create a new project.
 - If there is a recovery file present and you discard it we create a new project. The project launched could be defective or, if .lmmsrc.xml wasn't written, an earlier project.
 - Add a factory default data/projects/templates/default.mpt. Fixes #528

### CODE REVIEW

**Comment by zonkmachine** [comment]
> - if the last project was a template we create a new project. ( This PR )

Works fine. Clears the action up good. Some more testing and I'll merge this later.

**Comment by zonkmachine** [comment]
> - if the last project was a template we create a new project. ( This PR )

Seem to be fixed for when you create project from a template but not when the project is the `default.mpt` .

**Comment by zonkmachine** [comment]
> > - if the last project was a template we create a new project. ( This PR )
> 
> Seem to be fixed for when you create project from a template but not when the project is the default.mpt .

No. It works if you save a project as default project. `Song::createNewProject()` first tries to find `default.mpt` in your templates directory. Next it looks in [`factoryProjectsDir()`](https://github.com/LMMS/lmms/blob/stable-1.2/src/core/Song.cpp#L916:L917) and this it cant find because there seem to be no `default.mpt` among the [factory templates](https://github.com/LMMS/lmms/tree/stable-1.2/data/projects/templates), so it proceeds to generate a hard coded project and this isn't really a file so it doesn't get registered in the recent files list.

@tresf Should there be a default.mpt in the factory templates?

**Comment by tresf** [comment]
> @tresf Should there be a default.mpt in the factory templates?

It certainly sounds more logical than a hard-coded project.

**Comment by zonkmachine** [comment]
Works like a charm!

**Comment by zonkmachine** [comment]
> - Add a factory default data/projects/templates/default.mpt

I believe this also takes care of issue https://github.com/LMMS/lmms/issues/528

File: src/core/ConfigManager.cpp [hunk 1]
```diff
@@ -282,7 +282,8 @@ void ConfigManager::addRecentlyOpenedProject( const QString & file )
 {
 	QFileInfo recentFile( file );
 	if( recentFile.suffix().toLower() == "mmp" ||
-			recentFile.suffix().toLower() == "mmpz" )
+			recentFile.suffix().toLower() == "mmpz" ||
+				recentFile.suffix().toLower() == "mpt" )
```
Comment (Umcaruje) [inline src/core/ConfigManager.cpp]: You could remove the one tab of indentation here so these two lines are at the same level

File: src/core/main.cpp [hunk 2]
```diff
@@ -846,13 +846,15 @@ int main( int argc, char * * argv )
 		else if( ConfigManager::inst()->
 				value( "app", "openlastproject" ).toInt() &&
 			!ConfigManager::inst()->
-				recentlyOpenedProjects().isEmpty() )
+				recentlyOpenedProjects().isEmpty() &&
+			!recoveryFilePresent )
```
Comment (Umcaruje) [inline src/core/main.cpp]: And here you could add another tab

File: data/projects/templates/default.mpt [hunk 3]
```diff
@@ -0,0 +1,89 @@
+<?xml version="1.0"?>
+<!DOCTYPE lmms-project>
+<lmms-project version="1.0" creator="LMMS" creatorversion="1.2.0-rc3.15" type="song">
```
Comment (Umcaruje) [inline data/projects/templates/default.mpt]: I wonder what we should do with the creator version, this way we'd need to update it for every version, otherwise the users would keep getting the 'Project version mismatch' tool tip on each new project, right?

File: src/core/ConfigManager.cpp (hunk 1 above)
Comment (zonkmachine) [inline src/core/ConfigManager.cpp]: Fixed

File: src/core/main.cpp (hunk 2 above)
Comment (zonkmachine) [inline src/core/main.cpp]: I added even more for a casual look. Bohemic chic.

**Comment by tresf** [comment]
Interesting point about creator version.  A `default.mpt.in` could address this problem, or we could suppress project version warnings for template files.

File: src/core/main.cpp (hunk 2 above)
Comment (Umcaruje) [inline src/core/main.cpp]: Haha, it'll maybe look weird in some editors that don't have the same spaces for tabs like github does, don't you think?

**Comment by zonkmachine** [comment]
I thought about suppressing warnings too but we should really keep our own made stuff up to date, making such a sing a bit superfluous. Update the projects for a new release makes most sense to me.
We should have a release protocol to follow with things like this defined.

**Comment by tresf** [comment]
Cherry-picked and ready for master via 9edaa59.
