### PR TITLE
Initialize LOMM arrays

### LINKED ISSUE #7353: LOMM is distorted and delayed.
### System Information

Debian Sid Cinnamon

### LMMS Version(s)

Nightly Version

### Most Recent Working Version

Versión 1.3.0-alpha.1.642+g6634cec12 (Linux/x86_64, Qt 5.12.8, GCC 9.4.0).

### Bug Summary

LOMM is an excellent plugin and I use it a lot, but it has a serious distortion and lag problem. When I open a project for the first time or when I select a preset with LOMM integrated, this plugin occasionally lags or distorts.

In this video I show you LOMM distorting a bus of bass tracks and another of well-mixed leads, but it sounds distorted more on the left side than on the right and you don't see the indicators move either.

https://github.com/LMMS/lmms/assets/26127693/0293c6d8-8a4e-4350-b615-f57ee0402b25

In this other video I show you LOMM as a multiband compressor (My favorite) on the Master Track, but this time it is distorting the entire track and it is heard more on the left side.

https://github.com/LMMS/lmms/assets/26127693/7a7f1e11-6f9e-43d4-8262-cebf0ce90c9a

In this case I have some presets exported with LOMM integrated, when I click with the mouse (because the presets are not previewed with the keys) on some occasions the presets sound distorted or the effect is delayed in the preview.

https://github.com/LMMS/lmms/assets/26127693/d413e5ac-54f6-445e-995e-de2759986a4d

Also when I export a song I hear a clip at the beginning or a delay on the track where LOMM is integrated, or distortion on the track, bus or master. In this case I don't have proof video, but do it yourself.

### Expected Behaviour

May LOMM not be delayed or distorted.

### Steps To Reproduce

1- Open an LMMS project with LOMM integrated into a track, bus or the master.
2- Create a preset with an instrument with integrated LOMM and do the test.
3- Before playing the entire song, move the cursor to the part of the track that contains integrated LOMM.
4- Close LMMS and open it again.
5- Go to the presets section and look for the ones you created previously.
6- You will notice the distortion or delay of LOMM.

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Screenshots / Minimum Reproducible Project

_No response_

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by LostRobotMusic**
This one's rather embarrassing.  Way back when I made this plugin I was still quite new to C++ and didn't know anything about data manipulation in general.  At that time I believed arrays are initialized to 0 by default, which obviously isn't true.

Fixes #7353.

### CODE REVIEW

File: plugins/LOMM/LOMM.cpp [hunk 1]
```diff
@@ -97,6 +93,11 @@ void LOMMEffect::changeSampleRate()
 			m_scLookBuf[j][i].resize(m_lookBufLength, LOMM_MIN_FLOOR);
 		}
 	}
+
+	m_yL[0][0] = m_yL[0][1] = m_yL[1][0] = m_yL[1][1] = m_yL[2][0] = m_yL[2][1] = LOMM_MIN_FLOOR;
```
Comment (Rossmaxx) [inline plugins/LOMM/LOMM.cpp:97]: I believe you can use `std::fill` or fill_n here

File: plugins/LOMM/LOMM.cpp [hunk 2]
```diff
@@ -97,6 +93,11 @@ void LOMMEffect::changeSampleRate()
 			m_scLookBuf[j][i].resize(m_lookBufLength, LOMM_MIN_FLOOR);
```
Comment (JohannesLorenz) [inline plugins/LOMM/LOMM.cpp:93]: Is it wanted that `m_inLookBuf` is being initialized to `0.f`, while the other arrays are initialized to `LOMM_MIN_FLOOR`?

Comment (LostRobotMusic) [reply plugins/LOMM/LOMM.cpp:93]: Yes.  The lookahead buffer stores past audio.  Many of these other variables are used as denominators and shouldn't ever be zero.

**Review by messmerd — APPROVED** [review]

**Review by JohannesLorenz — APPROVED** [review]
Code looks OK, Testing OK, valgrind OK.

**Comment by super-manis** [comment]
Is that the case with the compressor as well?
