### PR TITLE
Fix NaNs in basic filters and Equalizer

### LINKED ISSUE #7131: Equalizer muting output??
### Bug Summary
When using the equalizer after a recent push, it sometimes mutes the output.
#### Steps to reproduce
Not 100%, but so far I've had it happen seemingly connected to bands 7 &/or 8 (high-end) when messing with the equalizer
#### Expected behavior
Sound continues
#### Actual behavior
Equalizer sometimes decides to permanently mute output
#### Screenshot
image

#### Affected LMMS versions
1.3.0-alpha.1.532+gc991a85ee

### PR DESCRIPTION
**Pull request by michaelgregorius**
Fix several NaNs in the context of the basic filters and the Equalizer.

The coefficients of the `BiQuad` were not initialized which seems to have led to NaNs down the line.

Fix a division by zero in `EqEffect::peakBand` and `EqSpectrumView::paintEvent` if the energy is zero.

The condition `m_peakSum <= 0` was removed from `EqSpectrumView::paintEvent` because the value is initialized to 0 down the line and later only potentially positive values are added.

Seems to fix #7131.

### CODE REVIEW

File: plugins/Eq/EqSpectrumView.cpp [hunk 1]
```diff
@@ -238,7 +238,7 @@ void EqSpectrumView::paintEvent(QPaintEvent *event)
 	const float fallOff = 1.07;
 	for( int x = 0; x < MAX_BANDS; ++x, ++bands )
 	{
-		peak = ( fh * 2.0 / 3.0 * ( 20 * ( log10( *bands / energy ) ) - LOWER_Y ) / ( - LOWER_Y ) );
+		peak = *bands != 0 ? ( fh * 2.0 / 3.0 * ( 20 * ( log10( *bands / energy ) ) - LOWER_Y ) / ( - LOWER_Y ) ) : 0.;
```
Comment (Veratil) [inline plugins/Eq/EqSpectrumView.cpp:241]: `0.` ? Maybe `20.` too?

File: plugins/Eq/EqEffect.cpp [hunk 2]
```diff
@@ -289,14 +289,20 @@ bool EqEffect::processAudioBuffer( sampleFrame *buf, const fpp_t frames )
...
+
 	float peak = -60;
 	float *b = fft->m_bands;
 	float h = 0;
 	for( int x = 0; x < MAX_BANDS; x++, b++ )
 	{
 		if( bandToFreq( x ,sr) >= minF && bandToFreq( x,sr ) <= maxF )
 		{
-			h = 20 * ( log10( *b / fft->getEnergy() ) );
+			h = 20 * ( log10( *b / fftEnergy ) );
```
Comment (Veratil) [inline plugins/Eq/EqEffect.cpp:305]: `20.` ?

File: plugins/Eq/EqSpectrumView.cpp [hunk 3]
```diff
@@ -208,10 +208,10 @@ EqSpectrumView::EqSpectrumView(EqAnalyser *b, QWidget *_parent) :
 
 void EqSpectrumView::paintEvent(QPaintEvent *event)
 {
-	const float energy =  m_analyser->getEnergy();
-	if( energy <= 0 && m_peakSum <= 0 )
+	const float energy = m_analyser->getEnergy();
+	if (energy <= 0)
```
[the remark this answers is not in the document]
Comment (michaelgregorius) [reply plugins/Eq/EqSpectrumView.cpp]: Thanks for checking! Fixed with commit 12a5981d2b2.

File: plugins/Eq/EqSpectrumView.cpp (hunk 1 above)
Comment (michaelgregorius) [reply plugins/Eq/EqSpectrumView.cpp]: Fixed with commit 12a5981d2b2.

File: plugins/Eq/EqEffect.cpp (hunk 2 above)
Comment (michaelgregorius) [reply plugins/Eq/EqEffect.cpp]: Fixed with commit 12a5981d2b2.

File: plugins/Eq/EqSpectrumView.cpp [hunk 4]
```diff
@@ -238,7 +238,7 @@ void EqSpectrumView::paintEvent(QPaintEvent *event)
 	const float fallOff = 1.07;
 	for( int x = 0; x < MAX_BANDS; ++x, ++bands )
 	{
-		peak = ( fh * 2.0 / 3.0 * ( 20 * ( log10( *bands / energy ) ) - LOWER_Y ) / ( - LOWER_Y ) );
+		peak = *bands != 0. ? ( fh * 2.0 / 3.0 * ( 20. * ( log10( *bands / energy ) ) - LOWER_Y ) / ( - LOWER_Y ) ) : 0.;
```
Comment (Veratil) [inline plugins/Eq/EqSpectrumView.cpp:241]: Optional style fix
```suggestion
		peak = *bands != 0. ? (fh * 2.0 / 3.0 * (20. * (log10(*bands / energy)) - LOWER_Y) / (-LOWER_Y)) : 0.;
```

File: plugins/Eq/EqEffect.cpp [hunk 5]
```diff
@@ -289,14 +289,20 @@ bool EqEffect::processAudioBuffer( sampleFrame *buf, const fpp_t frames )
...
+
 	float peak = -60;
 	float *b = fft->m_bands;
 	float h = 0;
 	for( int x = 0; x < MAX_BANDS; x++, b++ )
 	{
 		if( bandToFreq( x ,sr) >= minF && bandToFreq( x,sr ) <= maxF )
 		{
-			h = 20 * ( log10( *b / fft->getEnergy() ) );
+			h = 20. * ( log10( *b / fftEnergy ) );
```
Comment (Veratil) [inline plugins/Eq/EqEffect.cpp:305]: Optional style fix
```suggestion
			h = 20. * (log10(*b / fftEnergy));
```

File: plugins/Eq/EqEffect.cpp [hunk 6]
```diff
@@ -289,14 +289,20 @@ bool EqEffect::processAudioBuffer( sampleFrame *buf, const fpp_t frames )
 
 float EqEffect::peakBand( float minF, float maxF, EqAnalyser *fft, int sr )
 {
+	auto const fftEnergy = fft->getEnergy();
+	if (fftEnergy == 0.)
+	{
+		return 0.;
+	}
```
Comment (Veratil) [inline plugins/Eq/EqEffect.cpp:296]: Optional style
```suggestion
	if (fftEnergy == 0.) { return 0.; }
```

**Review by Veratil — APPROVED** [review]

**Review by sakertooth — APPROVED** [review]

**Comment by sakertooth** [comment]
I want to test before merge real quick, give me a second.

**Comment by sakertooth** [comment]
Just tested it, it seems to have fixed the issue :+1:

File: plugins/Eq/EqSpectrumView.cpp (hunk 4 above)
Comment (michaelgregorius) [reply plugins/Eq/EqSpectrumView.cpp]: Done with commit 2991fa0024b.

File: plugins/Eq/EqEffect.cpp (hunk 5 above)
Comment (michaelgregorius) [reply plugins/Eq/EqEffect.cpp]: Done with commit 2991fa0024b.

File: plugins/Eq/EqEffect.cpp (hunk 6 above)
Comment (michaelgregorius) [reply plugins/Eq/EqEffect.cpp]: Done with commit 2991fa0024b.
