### PR TITLE
Fix bad Granular Pitch Shifter init values

### LINKED ISSUE #7349: Granular Pitch Shifter is delayed.
### System Information

Debian Sid Cinnamon

### LMMS Version(s)

Nightly Version

### Most Recent Working Version

Versión 1.3.0-alpha.1.642+g6634cec12 (Linux/x86_64, Qt 5.12.8, GCC 9.4.0).

### Bug Summary

When I open a project for the first time in LMMS with a track that has the Granular Pitch Shifter plugin, the effect delays (I don't know if it doesn't load at the beginning), but when I put the cursor over that same track again, the effect if it syncs. Even when I export the song, the plugin delay is noticeable in the track. In this video I show you a song where I have the plugin in a Bass track bus.

https://github.com/LMMS/lmms/assets/26127693/a2420109-afaf-4b15-99ca-bb7e39450b94

### Expected Behaviour

That the effect of the plugin is synchronized from when the project is opened.

### Steps To Reproduce

1- Open a project that has tracks or buses with the Granular Pitch Shifter plugin.
2- Move the cursor to the part where the plugin effect begins to play before playing the entire song.
3- Export the song in mp3 format (Optional).

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Screenshots / Minimum Reproducible Project

_No response_

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by LostRobotMusic**
Fixes #7349, the plugin is initialized thinking it just barely spawned a grain so it needs to wait for half of a grain length before spawning the first one.

Also fixes a bug where the pitch is initialized to 0 instead of the current pitch values, which is audible with large glide values.

<sub><sup>(and threw in a small CPU optimization I missed)</sub></sup>

### CODE REVIEW

**Comment by Gabrielxd195** [comment]
> Fixes #7349, the plugin is initialized thinking it just barely spawned a grain so it needs to wait for half of a grain length before spawning the first one.
> 
> Also fixes a bug where the pitch is initialized to 0 instead of the current pitch values, which is audible with large glide values.
> 
> (and threw in a small CPU optimization I missed)

Thank you for listening to my request, Granular Pitch Shifter is an excellent plugin, I was waiting for it for a long time, and now I have it in my serious projects. Greetings

File: plugins/GranularPitchShifter/GranularPitchShifterEffect.cpp [hunk 1]
```diff
@@ -275,12 +275,12 @@ void GranularPitchShifterEffect::changeSampleRate()
 	
 	m_dcCoeff = std::exp(-2.0 * F_PI * DcRemovalHz / m_sampleRate);
 
-	const float pitch = m_granularpitchshifterControls.m_pitchModel.value();
-	const float pitchSpread = m_granularpitchshifterControls.m_pitchSpreadModel.value() * 0.5f;
+	const float pitch = m_granularpitchshifterControls.m_pitchModel.value() * (1. / 12.);
```
Comment (Rossmaxx) [inline plugins/GranularPitchShifter/GranularPitchShifterEffect.cpp:278]:
```suggestion
    const float pitch = m_granularpitchshifterControls.m_pitchModel.value() * (1.f / 12.f);
```

Comment (Rossmaxx) [reply plugins/GranularPitchShifter/GranularPitchShifterEffect.cpp:278]: ignore the spacing, i typed in 4 spaces because i couldn't type tab in the web editor

File: plugins/GranularPitchShifter/GranularPitchShifterEffect.cpp [hunk 2]
```diff
@@ -275,12 +275,12 @@ void GranularPitchShifterEffect::changeSampleRate()
...
+	const float pitchSpread = m_granularpitchshifterControls.m_pitchSpreadModel.value() * (1. / 24.);
```
Comment (Rossmaxx) [inline plugins/GranularPitchShifter/GranularPitchShifterEffect.cpp:279]: same here, use `f`

File: plugins/GranularPitchShifter/GranularPitchShifterEffect.cpp [hunk 3]
```diff
@@ -96,8 +96,8 @@ bool GranularPitchShifterEffect::processAudioBuffer(sampleFrame* buf, const fpp_
 
 	for (fpp_t f = 0; f < frames; ++f)
 	{
-		const double pitch = pitchBuf ? pitchBuf->value(f) : m_granularpitchshifterControls.m_pitchModel.value();
-		const double pitchSpread = (pitchSpreadBuf ? pitchSpreadBuf->value(f) : m_granularpitchshifterControls.m_pitchSpreadModel.value()) * 0.5f;
+		const double pitch = (pitchBuf ? pitchBuf->value(f) : m_granularpitchshifterControls.m_pitchModel.value()) * (1. / 12.);
```
Comment (Rossmaxx) [inline plugins/GranularPitchShifter/GranularPitchShifterEffect.cpp:99]: Here too, but since this is double, should you?

**Review by Rossmaxx — COMMENTED** [review]
minor nitpicks

File: plugins/GranularPitchShifter/GranularPitchShifterEffect.cpp (hunk 3 above)
Comment (LostRobotMusic) [reply plugins/GranularPitchShifter/GranularPitchShifterEffect.cpp:99]: I forgot it's working with doubles instead of floats.

File: plugins/GranularPitchShifter/GranularPitchShifterEffect.h [hunk 4]
```diff
@@ -168,7 +168,7 @@ class GranularPitchShifterEffect : public Effect
 	int m_ringBufLength = 0;
 	int m_writePoint = 0;
 	int m_grainCount = 0;
-	int m_timeSinceLastGrain = 0;
```
Comment (Rossmaxx) [inline plugins/GranularPitchShifter/GranularPitchShifterEffect.h:171]: why this arbitrary high value?

Comment (LostRobotMusic) [reply plugins/GranularPitchShifter/GranularPitchShifterEffect.h:171]: The plugin spawns a new grain when the time since the last grain surpasses a certain value.  Initializing this to 0 means when the plugin is first run in the project, it has to wait on that timer before it spawns that first grain.  Initializing it to an arbitrary high value guarantees the first grain will spawn right away instead.

Comment (Rossmaxx) [reply plugins/GranularPitchShifter/GranularPitchShifterEffect.h:171]: Ohh, can't you make it in such a way that it spaws a grain at initialization?

Comment (LostRobotMusic) [reply plugins/GranularPitchShifter/GranularPitchShifterEffect.h:171]: This behavior is identical.  The timer value already surpasses the value required so it properly spawns a grain the moment the first sample is processed as it should.  Spawning one manually in the constructor would require a ridiculous amount of duplicate code and/or complex performance-harming functions and/or code readability deficits in general, with no upside.

Comment (Rossmaxx) [reply plugins/GranularPitchShifter/GranularPitchShifterEffect.h:171]: Ok then.

**Review by Rossmaxx — APPROVED** [review]
looks good

**Comment by Gabrielxd195** [comment]
Friends, the error persists, the plugin delays when I start the project for the first time, I don't know if it is because the plugin does not load when starting the project and perhaps suddenly entering it causes a delay (I guess). I have the Granular Pitch Shifter on a Bass bus and a Chord bus. Here I show you another demonstration of this error:

https://github.com/LMMS/lmms/assets/26127693/3d0d6769-87f4-477f-8180-c55a4c2a7d61

**Comment by Rossmaxx** [comment]
Have you checked any other plug-ins. Ladspa effects (to be more specific, calf) has some weird phasing issues at times. Maybe that might be the actual cause of your issues.

**Comment by Gabrielxd195** [comment]
> Have you checked any other plug-ins. Ladspa effects (to be more specific, calf) has some weird phasing issues at times. Maybe that might be the actual cause of your issues.

Yes, a long time ago I tried Calf Filter Ladspa, and it did the same thing, but also when I exported the song, at the beginning it made a clip. I had to replace it with the equalizer. I don't have videos of that, I can't show you.

**Comment by LostRobotMusic** [comment]
> Here I show you another demonstration of this error:

@Gabrielxd195 Your video once again does not have audio.  Please provide one with audio.

**Comment by LostRobotMusic** [comment]
> It's on your end, I can hear the audio.

Thanks, sorry about that, for some reason half of the videos have audio on Firefox and half don't (showing the disabled no-audio symbol in the bottom right).  Switching to another browser fixed it.

**Comment by LostRobotMusic** [comment]
> Friends, the error persists, the plugin delays when I start the project for the first time, I don't know if it is because the plugin does not load when starting the project and perhaps suddenly entering it causes a delay (I guess). I have the Granular Pitch Shifter on a Bass bus and a Chord bus. Here I show you another demonstration of this error:
> Granulat.Pitch.Shifter.se.retraza.2.mp4

This is happening due to your settings this time, this is not the same error persisting.  Trying to judge by the visuals, you have the grain size turned all the way down to 4 Hz (up to 0.25 seconds), and you have the crossfades disabled entirely.  Because you have the crossfades disabled, the first grain's volume snaps in at the halfway point of the grain, at 0.125 seconds.  Without disabling the crossfades, the fade would audibly start immediately upon playback, which means the bug is fixed.

However, as you have shown, this isn't the desired behavior, despite everything working as originally intended.  I can attempt to counter this by spawning a grain that's already at 50% phase upon plugin initialization.

**Comment by Gabrielxd195** [comment]
@LostRobotMusic Brother, first of all the videos that I have uploaded obviously have audio, but for some reason Github disables the audio for the videos, as @softrabbit told you. I also have no problems with the effects chain, because I have been creating this project since mid-2023, long before you released the LOMM and Granular Pitch Shifter plugins.

The problems I have had in my LOMM #7355 and Granular Pitch Shifter #7349 project are only from these two plugins. I also did a lot of testing: deactivating, activating, removing and adding each plugin you see in my effects chain. In other words, I did enough testing to conclude that these two plugins have delay and distortion problems. But I want to let you know so that when you can, you can correct those errors in time. I am always up to date with LMMS news and I report what I find, precisely so that your work is not undervalued due to a simple mistake.

But I also want to clarify that this delay error not only happens with the LOMM and Granular Pitch Shifter plugins @LostRobotMusic,
but also with the Calf Filter Ladspa (I don't have videos of this, but it happened to me and that's why I use the equalizer as a bass filter), which I clipped when I played the project for the first time and when I exported the song.

Correct me if I'm wrong, but plugins in general do not initialize when you open a project, but when they receive audio for the first time they initialize abruptly and that causes clips or delays; However, when you move the cursor to the point where the audio of the track with those plugins to be played begins, it no longer clips or delays, and it sounds fine, because the plugin is already initialized. That's my opinion, but you are the ones who know about programming.

(Google Translate)

**Comment by Gabrielxd195** [comment]
> @Gabrielxd195 Can you verify that this behavior is no longer present in https://lmms.io/download/pull-request/7356?

Error corrected!!!. Granular Pitch Shifter now does not lag when starting the project for the first time. I did another test by opening the project for the first time and moving the cursor to the drop part of my instrumental and the plugin didn't lag. As I show you in this video:

https://github.com/LMMS/lmms/assets/26127693/cd468bde-7f48-4272-9c13-28e7f0f5984c

What did happen at one point was that LMMS closed unexpectedly on some occasions and on another occasion LOMM was distorted while Granular Pitch Shifter worked correctly, after several tests everything worked normally. This clarifies my doubt regarding all plugins, which should be initialized as soon as the project is opened so that they are not delayed or distorted. 

I wish they couldn't merge this as soon as possible, to fix this bug.
