### PR TITLE
Remove the FIFO thread

### LINKED ISSUE #7320: Constant freezing during export
### System Information

Windows 10

### LMMS Version(s)

gbeedc18a

### Most Recent Working Version

_No response_

### Bug Summary

pretty much most of the time I go to export a project, the program stops responding, and never unfreezes. the only way to fix is to force close the program and hope it doesn't happen next time.

### Expected Behaviour

I can export songs

### Steps To Reproduce

Export a song.
I don't know if there's any specifics, I just know half the time I go to export it stops responding and never comes back.

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Screenshots / Minimum Reproducible Project

image

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by sakertooth**
Removes the FIFO thread, which was a thread used in the audio engine that wrote chunks of rendered audio buffers to a circular buffer, while the audio callback thread would read from that. Instead, the audio callback is the one rendering the buffers directly and doing any chunking as necessary.

The functionality this thread brought allowed for buffers to be "written ahead" of the audio callback, meaning that the FIFO thread would be rendering buffers as fast it can, stopping when it can't write any more buffers, while the audio callback would be reading them at a fixed interval. However:
1. Since the priority of this thread was the same as every other thread running on the system (i.e., not high priority), while the audio callback is commonly thought to run on high priority, it is more likely that the FIFO thread wouldn't have gotten much time to do its task of rendering (i.e., a high priority task). Moving that work into the audio callback is better in this case.
2. Even if the FIFO thread had high priority, it would have to compete with the audio callback's high priority as well. If we assume that the FIFO thread had high priority, but just a little bit less than the audio callback, then for buffers like 64, 32, etc, the audio callback thread will be running so frequently that we run the risk of not being able to render any buffers at all since the FIFO thread may not have a large enough time slice.
3. The latency wasn't completely determined by the buffer size, but also by how long it took to get this thread running since it was the one rendering the buffers.
4. Very strange deadlocks happened because of this thread. For example, simplifying the thread communication in this case fixes #7320.

This PR also greatly simplifies the transmission of buffers between the engine and the audio devices. `AudioEngine::renderNextBuffer` has been changed to correctly process the chunks of audio returned by `AudioEngine::renderNextPeriod` (a new function), and also manages both interleaved and planar outputs. This removes a lot of repetitive code in each audio device that originally was handling their configuration on their own.

This PR also makes the `AudioAlsa` device use floating-point audio instead of int16.

### CODE REVIEW

**Comment by sakertooth** [comment]
Changed the PR to still remove the FIFO thread but keep the chunking of the buffer size (to avoid problems with non sample accurate automation but to also fix the problems this thread has caused).

**Comment by Rossmaxx** [comment]
This shoulda had higher priority. @LMMS/testers

File: src/core/AudioEngine.cpp [hunk 1]
```diff
@@ -205,18 +166,8 @@ void AudioEngine::initDevices()
 
 
 
-void AudioEngine::startProcessing(bool needsFifo)
+void AudioEngine::startProcessing()
```
Comment (Rossmaxx) [inline src/core/AudioEngine.cpp:169]: Would it make sense to inline it to the header?  Now that 90% of the functionality is gone.

File: src/core/AudioEngine.cpp [hunk 2]
```diff
@@ -225,18 +176,7 @@ void AudioEngine::startProcessing(bool needsFifo)
```
Comment (Rossmaxx) [inline src/core/AudioEngine.cpp:176]: Same here.

File: src/core/audio/AudioDevice.cpp [hunk 3]
```diff
@@ -46,49 +45,17 @@ AudioDevice::AudioDevice( const ch_cnt_t _channels, AudioEngine*  _audioEngine )
...
-	delete[] m_buffer;
 	m_devMutex.tryLock();
 	unlock();
 }
 
 
-
-
-void AudioDevice::processNextBuffer()
+void AudioDevice::startProcessing()
```
Comment (Rossmaxx) [inline src/core/audio/AudioDevice.cpp:53]: Is this now an empty function?

**Review by Rossmaxx — COMMENTED** [review]
The fatloss on this is insane. I am not approving for now because I am doubtful if something might have gotten lost somewhere. I will approve after i get around to testing.

Also, don't understand what is now happening with the chunking mechanism. Is the audio thread processing in chunks of 256 and then outputting to the playback/export at the user defined buffer size? Or is there something I missed.

File: src/core/AudioEngine.cpp (hunk 2 above)
Comment (Rossmaxx) [reply src/core/AudioEngine.cpp:176]: I mean the stop process function

**Comment by bratpeki** [comment]
> @LMMS/testers
Reporting!

I'm busy with managing #7477, #7444 and #7366.

Is this making the code more readable without reducing performance? Or is it a performance boosting PR? In any case, great stuff, I'll look at it when I'm done with these three PRs!

**Comment by Rossmaxx** [comment]
This is supposed to solve the performance degradation on master compared to 1.2 and the rare case with deadlocks making a mess, along with the buffer size and automation performance, among other stuff. @sakertooth correct me if I'm wrong. If what i guess is right, this PR has the potential to straighten up a lot of the performance bugs.

**Comment by bratpeki** [comment]
> Wait the tester role is only for peki? 

For the time being, yeah. I think I get rights to review PRs and whatnot, so it's probably not wise to give it away to anyone wanting to test, but I'm not entirely sure about if that's how it behaves, just speculation.

File: src/core/AudioEngine.cpp (hunk 1 above)
Comment (sakertooth) [reply src/core/AudioEngine.cpp:169]: Yeah, probably.

**Comment by sakertooth** [comment]
> This is supposed to solve the performance degradation on master compared to 1.2 and the rare case with deadlocks making a mess, along with the buffer size and automation performance, among other stuff. @sakertooth correct me if I'm wrong. If what i guess is right, this PR has the potential to straighten up a lot of the performance bugs.

It's mostly to fix deadlock bugs involving this thread waiting forever to close. It's less of a performance benefit (though that could be possible) but more so to simplify the thread communication within the audio pipeline.

File: src/core/audio/AudioDevice.cpp (hunk 3 above)
Comment (sakertooth) [reply src/core/audio/AudioDevice.cpp:53]: It seems like I removed it entirely.

**Comment by CorruptVoidSoul** [comment]
So I tested this PR.
Exporting works fine, no hearable differences.
Playback is still pretty much the same as on master, I made it play the performance intensive part of a song, my phone is still in pain, no noticeable gain or loss there.
I had two random crashes but I expect this to be a me problem because well, it's a phone and this mmpz is uhh... a bit tough sometimes.
Still on the "me problem" side, usually Equalizer takes a minute to load for the first time, in this PR it takes 30 seconds so it's better, not gonna complain.
Now back on playback, the playhead will desync itself from the actual sound after a huge lag spike, but that's a general performance problem, it doesn't have much to do with this PR I think.

Final feedback is this seems good, did Peki test that too ? There could be differences with a computer that can handle heavy workload.

**Comment by sakertooth** [comment]
> Final feedback is this seems good, did Peki test that too ? There could be differences with a computer that can handle heavy workload.

I don't think Peki has tested this yet, but they're probably busy with other PRs so it's fine. Thank you for testing this for me :+1:

**Comment by sakertooth** [comment]
> Also, don't understand what is now happening with the chunking mechanism. Is the audio thread processing in chunks of 256 and then outputting to the playback/export at the user defined buffer size? Or is there something I missed.

Sorry, just realized that I didn't answer this question @Rossmaxx. What happens is that the user selects their desired buffer size and audio device to use, and then when LMMS starts, the audio device thread starts, which periodically calls `renderNextBuffer`, which either returns the latest rendered chunk (256 sample frames per chunk), or calls the overloaded variant for `renderNextBuffer` to render any buffer size wanted (e.g. 1024 frames). All of the audio devices call the overloaded variant for `renderNextBuffer` to be able to render any desired buffer size for real-time playback.

There is one thread requesting data periodically. That's it. There are other worker threads that do the actual processing, but this is the only thread requesting data (if not that thread then the export thread). To compare this to before, there was an additional thread, but this was removed, as it was mostly unnecessarily and causing issues.

**Comment by bratpeki** [comment]
I could test this, if it's ready to be tested, or needs WIP testing. @sakertooth ?

**Comment by sakertooth** [comment]
> I could test this, if it's ready to be tested, or needs WIP testing. @sakertooth ?
There were merge conflicts, so I'm still working on this.

**Comment by sakertooth** [comment]
Should be ready @bratpeki.

**Comment by bratpeki** [comment]
Please request a review so I see it on the GitHub UI :)

**Comment by bratpeki** [comment]
Okay, so, how do I test this?

**Comment by bratpeki** [comment]
Alright, I'll use it for some time as if it were the real deal, make a few songs, and report anything I see!

**Comment by sakertooth** [comment]
PR is currently broken, will be fixed when I make this PR ready for review again.

**Comment by sakertooth** [comment]
Applied the fixes, this PR should be good now.

**Comment by bratpeki** [comment]
Tested with commit [29a6829](https://github.com/LMMS/lmms/commit/29a6829c2e1cb98206b6843bbdfe07f86ac31e33), seems to be just fine. I even noticed a performance boost! I believe Rossmaxx mentioned something about fewer deadlocks.

Testing the latest commit.

**Review by bratpeki — APPROVED** [review]

**Comment by qnebra** [comment]
One of latest commits completly messed up playback on SDL backend on Windows. Only left channel can be heard and right channel is completly silent.

**Comment by sakertooth** [comment]
> One of latest commits completly messed up playback on SDL backend on Windows. Only left channel can be heard and right channel is completly silent.

Thanks for the heads up. It should be fixed now.

**Comment by bratpeki** [comment]
I got a "Bus error (Core dumped)" and can't reliably recreate it. This only happened the first time I tried exporting a project made at a "later" LMMS (MIDI slicing, etc). So it could be tied to that. I'd rebase this to upstream or, because this is a HUGE improvement, just merge and we can make a follow-up PR.

**Review by bratpeki — APPROVED** [review]

**Comment by bratpeki** [comment]
@regulus79 @Rossmaxx please have a look and if all is well, merge

**Comment by sakertooth** [comment]
> @regulus79 @Rossmaxx please have a look and if all is well, merge

I'm not sure I'm done with this yet.

**Comment by bratpeki** [comment]
Follow-up PR if needed, then!

**Comment by Rossmaxx** [comment]
I have been thinking of getting back to this, but I'm in the middle of exams. Will take some time.

**Review by bratpeki — APPROVED** [review]

**Comment by bratpeki** [comment]
No objections, and it drives great. Please do final checks and merge! :grin:

EDIT: Spoke too soon, there seems to be an issue with the `msvc-x64` check.

**Comment by sakertooth** [comment]
> EDIT: Spoke too soon, there seems to be an issue with the `msvc-x64` check.

Probably not related to this PR because the build still passed, but I can rerun the check.

File: src/core/audio/AudioAlsa.cpp [hunk 4]
```diff
@@ -42,8 +42,7 @@ AudioAlsa::AudioAlsa( bool & _success_ful, AudioEngine*  _audioEngine ) :
 		DEFAULT_CHANNELS), _audioEngine),
 	m_handle( nullptr ),
 	m_hwParams( nullptr ),
-	m_swParams( nullptr ),
-	m_convertEndian( false )
+	m_swParams( nullptr )
```
Comment (szeli1) [inline src/core/audio/AudioAlsa.cpp]:
```suggestion
	m_swParams(nullptr)
```

**Comment by bratpeki** [comment]
We can merge now? I feel like this has been opened for too long.

File: include/AudioDevice.h [hunk 5]
```diff
@@ -75,66 +75,52 @@ class AudioDevice
...
+	virtual void stopProcessing() { m_running.clear(std::memory_order_release); }
 
 protected:
-	// subclasses can re-implement this for being used in conjunction with
-	// processNextBuffer()
-	virtual void writeBuffer(const SampleFrame* /* _buf*/, const fpp_t /*_frames*/) {}
+	//! Render the next audio playback buffer into @p dst.
+	//! @p dst is expected to represent interleaved floating-point audio.
+	//! @return `true` if playback was rendered into @p dst.
+	bool nextBuffer(float* dst, std::size_t frames, int channels);
```
Comment (messmerd) [inline include/AudioDevice.h]: Can use this now:
```cpp
bool nextBuffer(InterleavedBufferView<float> dst);
```

File: include/AudioDevice.h [hunk 6]
```diff
@@ -75,66 +75,52 @@ class AudioDevice
...
 
-	// called by according driver for fetching new sound-data
-	fpp_t getNextBuffer(SampleFrame* _ab);
+	//! Render the next audio playback buffer into @p dst.
+	//! @p dst is expected to represent planar floating-point audio.
+	//! @return `true` if playback was rendered into @p dst.
+	bool nextBuffer(float** dst, std::size_t frames, int channels);
```
Comment (messmerd) [inline include/AudioDevice.h]: Can use this now:
```cpp
bool nextBuffer(PlanarBufferView<float> dst);
```

File: include/AudioDummy.h [hunk 7]
```diff
@@ -80,29 +80,23 @@ class AudioDummy : public QThread, public AudioDevice
...
 		stopProcessingThread( this );
 	}
 
 	void run() override
 	{
 		MicroTimer timer;
-		while( true )
+		while (true)
 		{
+			audioEngine()->renderNextBuffer();
```
Comment (messmerd) [inline include/AudioDummy.h]: Should this go after the `timer.reset()` line?

File: src/core/audio/AudioOss.cpp [hunk 8]
```diff
@@ -250,31 +252,26 @@ void AudioOss::startProcessing()
...
 
-	while( true )
+	while (nextBuffer(buf.data(), framesPerPeriod(), channels()))
 	{
-		const fpp_t frames = getNextBuffer( temp );
-		if( !frames )
+		for (auto i = std::size_t{0}; i < buf.size(); ++i)
 		{
-			break;
+			pcmBuf[i] = static_cast<int16_t>(buf[i] * OUTPUT_SAMPLE_MULTIPLIER);
```
Comment (messmerd) [inline src/core/audio/AudioOss.cpp:234]: This doesn't handle endianness, and it looks like `m_convertEndian` can be true sometimes.

Side note: The code that selects the endian of the samples (starting at line 126) should probably make the selection based on the result of `isLittleEndian()` rather than always using little endian `AFMT_S16_LE` first if OSS supports it. That would be more optimal.

File: src/core/audio/AudioPulseAudio.cpp [hunk 9]
```diff
@@ -243,35 +250,23 @@ void AudioPulseAudio::run()
...
 
-void AudioPulseAudio::streamWriteCallback( pa_stream *s, size_t length )
-{
-	const fpp_t fpp = audioEngine()->framesPerPeriod();
-	auto temp = new SampleFrame[fpp];
-	auto pcmbuf = (int_sample_t*)pa_xmalloc(fpp * channels() * sizeof(int_sample_t));
-
-	size_t fd = 0;
-	while( fd < length/4 && m_quit == false )
+	if (!nextBuffer(reinterpret_cast<float*>(buf), numFrames, channels()))
```
Comment (messmerd) [inline src/core/audio/AudioPulseAudio.cpp]:
```suggestion
	if (!nextBuffer(static_cast<float*>(buf), numFrames, channels()))
```

File: src/core/audio/AudioPulseAudio.cpp [hunk 10]
```diff
@@ -243,35 +250,23 @@ void AudioPulseAudio::run()
 	pa_mainloop_free( mainLoop );
 }
 
+void AudioPulseAudio::streamWriteCallback(pa_stream*, size_t)
+{
+	auto buf = static_cast<void*>(nullptr);
+	auto maxBufSizeInBytes = framesPerPeriod() * channels() * sizeof(float);
 
+	pa_stream_begin_write(m_s, &buf, &maxBufSizeInBytes);
```
Comment (messmerd) [inline src/core/audio/AudioPulseAudio.cpp]: According to [the documentation](https://www.freedesktop.org/software/pulseaudio/doxygen/stream_8h.html#a6cf50cfc4ea8897391941184d74d7dfa):
> *nbytes can be smaller or have the same value as you passed in. You need to be able to handle both cases.

File: include/AudioDevice.h [hunk 11]
```diff
@@ -75,66 +75,52 @@ class AudioDevice
...
+	fpp_t framesPerPeriod() const { return m_framesPerPeriod; }
 
-	virtual void startProcessing()
-	{
-		m_inProcess = true;
-	}
-
-	virtual void stopProcessing();
+	virtual void startProcessing() { m_running.test_and_set(std::memory_order_acquire); }
+	virtual void stopProcessing() { m_running.clear(std::memory_order_release); }
```
Comment (messmerd) [inline include/AudioDevice.h]: Instead of needing to remember to call `AudioDevice::startProcessing` and `AudioDevice::stopProcessing` from the overridden methods in the child classes, why not let these be non-virtual wrappers that call some new pure virtual methods that the child classes would implement?

For example:
```cpp
public:
	void startProcessing()
	{
		m_running.test_and_set(std::memory_order_acquire);
		startProcessingImpl();
	}

protected:
	virtual void startProcessingImpl() = 0;
```

**Comment by sakertooth** [comment]
Thanks for the review @messmerd, will try to go over it soon, just a bit busy.

File: include/AudioDummy.h (hunk 7 above)
Comment (sakertooth) [reply include/AudioDummy.h]: Probably. It was after before I made the changes too.

File: src/core/audio/AudioOss.cpp (hunk 8 above)
Comment (sakertooth) [reply src/core/audio/AudioOss.cpp:234]: Ideally, the endianness should match that of the current system. We should never really have to worry about such things.

File: src/core/audio/AudioPulseAudio.cpp (hunk 10 above)
Comment (sakertooth) [reply src/core/audio/AudioPulseAudio.cpp]: Yes. `maxBufSizeInBytes` is modified and returns the number of bytes, which is then later used to calculate the number of samples and audio frames. The code initially calculates the max size in bytes, but never assumes that `maxBufSizeInBytes == framesPerPeriod() * channels() * sizeof(float);`

File: include/AudioDevice.h (hunk 11 above)
Comment (sakertooth) [reply include/AudioDevice.h]: I like this idea.

File: src/core/audio/AudioPulseAudio.cpp (hunk 10 above)
Comment (sakertooth) [reply src/core/audio/AudioPulseAudio.cpp]: And if `maxBufSizeInBytes` isn't modified? The code still works anyways.

File: include/AudioDevice.h (hunk 11 above)
Comment (sakertooth) [reply include/AudioDevice.h]: Though, I think `startProcessingImpl` can actually be made `private` here.

File: src/core/audio/AudioOss.cpp (hunk 8 above)
Comment (sakertooth) [reply src/core/audio/AudioOss.cpp:234]: Yess, we have `AFMT_S16_NE` for OSS, so yeah it shouldn't be an issue.

File: include/AudioDevice.h [hunk 12]
```diff
@@ -75,66 +76,62 @@ class AudioDevice
...
 
 	virtual void startProcessing()
 	{
-		m_inProcess = true;
+		m_running.test_and_set(std::memory_order_acquire);
+		startProcessingImpl();
 	}
 
-	virtual void stopProcessing();
+	virtual void stopProcessing()
```
Comment (messmerd) [inline include/AudioDevice.h]: This and `startProcessing` should no longer be virtual

File: src/core/audio/AudioPulseAudio.cpp [hunk 13]
```diff
@@ -229,11 +224,14 @@ void AudioPulseAudio::run()
 	}
 	else
 	{
-		const fpp_t fpp = audioEngine()->framesPerPeriod();
+		const fpp_t fpp = framesPerPeriod();
```
Comment (messmerd) [inline src/core/audio/AudioPulseAudio.cpp]: Looks like `temp` doesn't have a purpose anymore?

File: src/core/audio/AudioDevice.cpp [hunk 14]
```diff
@@ -45,53 +49,69 @@ AudioDevice::AudioDevice( const ch_cnt_t _channels, AudioEngine*  _audioEngine )
...
-
-
-
-void AudioDevice::processNextBuffer()
+bool AudioDevice::nextBuffer(InterleavedBufferView<float> dst)
 {
-	const fpp_t frames = getNextBuffer( m_buffer );
-	if (frames) { writeBuffer(m_buffer, frames); }
-	else
+	if (!m_running.test_and_set(std::memory_order_acquire))
```
Comment (messmerd) [inline src/core/audio/AudioDevice.cpp]: Are you using `m_running` like a mutex? Why wasn't something like this needed in `AudioDevice` prior to this PR?

Comment (sakertooth) [reply src/core/audio/AudioDevice.cpp]: `m_running` is a flag that tells the device if it is supposed to be running or not. If it is running, it keeps fetching buffers from calls to `nextBuffer`. If not, it stops. This is needed because most devices can only fully stop processing when their callbacks/threads have closed or finished. Without this flag, the callbacks would never finish and a call to `stopProcessing` would block forever.

Before this PR, each device had there own flag to handle this, but since this was a common pattern, I made it so that they all store a `m_running` flag instead.

**Comment by bratpeki** [comment]
Tested again, @rdrpenguin04. Everything works well!

File: src/core/audio/AudioDevice.cpp [hunk 15]
```diff
@@ -45,54 +49,66 @@ AudioDevice::AudioDevice( const ch_cnt_t _channels, AudioEngine*  _audioEngine )
...
 {
-	fpp_t frames = audioEngine()->framesPerPeriod();
-	const SampleFrame* b = audioEngine()->nextBuffer();
+	for (auto frame = std::size_t{0}; frame < dst.frames(); ++frame)
+	{
+		if (m_audioEngineBufferIndex == 0) { m_audioEngineBuffer = m_audioEngine->renderNextBuffer(); }
+		const auto audioEngineFrame = m_audioEngineBuffer[m_audioEngineBufferIndex];
 
-	if (!b) { return 0; }
+		for (auto channel = 0; channel < dst.channels(); ++channel)
```
Comment (messmerd) [inline src/core/audio/AudioDevice.cpp]: Here's another way of implementing the loop which I think is easier to understand and probably more efficient

```cpp
switch (dst.channels())
{
	case 0:
		assert(false);
		break;
	case 1:
		dst[frame][0] = audioEngineFrame.average();
		break;
	case 2:
		dst[frame][0] = audioEngineFrame[0];
		dst[frame][1] = audioEngineFrame[1];
		break;
	default:
	{
		dst[frame][0] = audioEngineFrame[0];
		dst[frame][1] = audioEngineFrame[1];
		for (auto channel = 2; channel < dst.channels(); ++channel)
		{
			dst[frame][channel] = 0.f;
		}
		break;
	}
}
```

File: src/core/audio/AudioDevice.cpp [hunk 16]
```diff
@@ -45,54 +49,66 @@ AudioDevice::AudioDevice( const ch_cnt_t _channels, AudioEngine*  _audioEngine )
...
+void AudioDevice::nextBuffer(PlanarBufferView<float> dst)
 {
-	if( audioEngine()->hasFifoWriter() )
+	for (auto frame = std::size_t{0}; frame < dst.frames(); ++frame)
 	{
-		while( m_inProcess )
+		if (m_audioEngineBufferIndex == 0) { m_audioEngineBuffer = m_audioEngine->renderNextBuffer(); }
+		const auto audioEngineFrame = m_audioEngineBuffer[m_audioEngineBufferIndex];
+
+		for (auto channel = 0; channel < dst.channels(); ++channel)
```
Comment (messmerd) [inline src/core/audio/AudioDevice.cpp]:
```cpp
switch (dst.channels())
{
	case 0:
		assert(false);
		break;
	case 1:
		dst[0][frame] = audioEngineFrame.average();
		break;
	case 2:
		dst[0][frame] = audioEngineFrame[0];
		dst[1][frame] = audioEngineFrame[1];
		break;
	default:
	{
		dst[0][frame] = audioEngineFrame[0];
		dst[1][frame] = audioEngineFrame[1];
		for (auto channel = 2; channel < dst.channels(); ++channel)
		{
			dst[channel][frame] = 0.f;
		}
		break;
	}
}
```

File: src/core/audio/AudioPulseAudio.cpp [hunk 17]
```diff
@@ -229,12 +221,10 @@ void AudioPulseAudio::run()
 	}
 	else
 	{
-		const fpp_t fpp = audioEngine()->framesPerPeriod();
-		auto temp = new SampleFrame[fpp];
-		while( getNextBuffer( temp ) )
+		while (true)
```
Comment (messmerd) [inline src/core/audio/AudioPulseAudio.cpp]: Is this supposed to be an infinite loop?

File: src/core/audio/AudioPulseAudio.cpp [hunk 18]
```diff
@@ -42,21 +42,16 @@ static void stream_write_callback(pa_stream *s, size_t length, void *userdata)
...
-		DEFAULT_CHANNELS), _audioEngine),
-	m_s( nullptr ),
-	m_quit( false ),
-	m_convertEndian( false )
+AudioPulseAudio::AudioPulseAudio(bool& _success_ful, AudioEngine* _audioEngine)
+	: AudioDevice(std::clamp<ch_cnt_t>(
+					  ConfigManager::inst()->value("audiopa", "channels").toInt(), DEFAULT_CHANNELS, DEFAULT_CHANNELS),
+		  _audioEngine)
+	, m_s(nullptr)
+	, m_quit(false)
```
Comment (messmerd) [inline src/core/audio/AudioPulseAudio.cpp]: Can `m_quit` be replaced with `!isRunning()` now?

File: src/core/audio/AudioOss.cpp [hunk 19]
```diff
@@ -237,44 +208,36 @@ QString AudioOss::probeDevice()
...
 
 
-void AudioOss::startProcessing()
+void AudioOss::startProcessingImpl()
 {
-	if( !isRunning() )
-	{
-		start( QThread::HighPriority );
-	}
+	start(QThread::HighPriority);
```
Comment (messmerd) [inline src/core/audio/AudioOss.cpp:211]: Should `startProcessingImpl` only be called when not running?

If there's any possibility `startProcessing` could be called twice in a row, it could be rewritten like this:
```cpp
if (!m_running.test_and_set(std::memory_order_acquire))
{
	startProcessingImpl();
}
```

Or if that should never happen, you could still add an assertion just to be sure:
```cpp
[[maybe_unused]] const bool alreadyRunning = m_running.test_and_set(std::memory_order_acquire);
assert(!alreadyRunning);
startProcessingImpl();
```

File: src/core/audio/AudioDevice.cpp [hunk 20]
```diff
@@ -45,54 +49,66 @@ AudioDevice::AudioDevice( const ch_cnt_t _channels, AudioEngine*  _audioEngine )
...
+void AudioDevice::startProcessing()
+{
+	m_running.test_and_set(std::memory_order_acquire);
+	startProcessingImpl();
+}
 
-
-
-void AudioDevice::processNextBuffer()
+void AudioDevice::stopProcessing()
```
Comment (messmerd) [inline src/core/audio/AudioDevice.cpp:54]: In `AudioDevice` implementations, `stopProcessing();` is called from the destructor, and since `stopProcessing` calls virtual methods, that could be problematic (see the [C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c82-dont-call-virtual-functions-in-constructors-and-destructors)). I believe it works correctly now, but if a class were to be derived from one of the `AudioDevice` implementations, it would cause issues that might be difficult to track down.

So maybe the virtual function calls could be removed from the destructors, and `audioDevice->stopProcessing();` could instead be called just before objects are deleted (like in `AudioEngine`)?

And `AudioDevice::~AudioDevice()` could assert `isRunning() == false` just to be sure calling code is destroying it correctly.

Comment (sakertooth) [reply src/core/audio/AudioDevice.cpp:54]: > In AudioDevice implementations, stopProcessing(); is called from the destructor, and since stopProcessing calls virtual methods, that could be problematic (see the [C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c82-dont-call-virtual-functions-in-constructors-and-destructors)). I believe it works correctly now, but if a class were to be derived from one of the AudioDevice implementations, it would cause issues that might be difficult to track down.

Besides the obvious calling of virtual methods in the destructor problem, something is telling me calling `stopProcessing` here is not right in general. It would probably be more reasonable to have implementations of `AudioDevice` forcefully close or abort the device when it is being destroyed. This will also allow for destruction of `AudioDevice` objects without the need to remember to stop it before they are deleted.

File: src/core/audio/AudioOss.cpp (hunk 19 above)
Comment (sakertooth) [reply src/core/audio/AudioOss.cpp:211]: > Should startProcessingImpl only be called when not running?

> If there's any possibility startProcessing could be called twice in a row, it could be rewritten like this:

I don't think theres any good reason why we would need to call `startProcessing` twice in a row. If somehow it is called twice in a row, it's probably a bug, so the `assert` approach makes more sense here IMO.

File: src/core/audio/AudioDevice.cpp (hunk 15 above)
Comment (messmerd) [reply src/core/audio/AudioDevice.cpp]: I think you could also remove the switch statement from the loop so there aren't unnecessary branches each frame:

```cpp
using Func = void(*)(float* dstFrame, const SampleFrame& audioEngineFrame, proc_ch_t channels);
Func func;

switch (dst.channels())
{
	case 0:
		assert(false);
		break;
	case 1:
		func = +[](float* dstFrame, const SampleFrame& audioEngineFrame, proc_ch_t) {
			dstFrame[0] = audioEngineFrame.average();
		};
		break;
	case 2:
		func = +[](float* dstFrame, const SampleFrame& audioEngineFrame, proc_ch_t) {
			dstFrame[0] = audioEngineFrame[0];
			dstFrame[1] = audioEngineFrame[1];
		};
		break;
	default:
		func = +[](float* dstFrame, const SampleFrame& audioEngineFrame, proc_ch_t channels) {
			dstFrame[0] = audioEngineFrame[0];
			dstFrame[1] = audioEngineFrame[1];
			for (auto channel = 2; channel < channels; ++channel)
			{
				dstFrame[channel] = 0.f;
			}
		};
		break;
}

// for loop here

```

Comment (sakertooth) [reply src/core/audio/AudioDevice.cpp]: I think it might be overly complex to do that. In this case, switching on `dst.channels()` should be a very predictable branch since the value is not changing, so the performance impact should be negligible.

File: src/core/audio/AudioPulseAudio.cpp (hunk 17 above)
Comment (sakertooth) [reply src/core/audio/AudioPulseAudio.cpp]: Good catch, should be using `AudioDevice::isRunning` I believe.

File: src/core/audio/AudioDevice.cpp [hunk 21]
```diff
@@ -69,25 +69,35 @@ template void AudioDevice::nextBuffer<InterleavedBufferView<float>>(InterleavedB
 template void AudioDevice::nextBuffer<PlanarBufferView<float>>(PlanarBufferView<float> dst);
 void AudioDevice::nextBuffer(AudioBufferView<float> auto dst)
 {
-	for (auto frame = std::size_t{0}; frame < dst.frames(); ++frame)
+	auto dstAt = [&dst](ch_cnt_t channel, f_cnt_t frame) -> float& {
+		return decltype(dst)::Interleaved ? dst[frame][channel] : dst[channel][frame];
+	};
```
Comment (messmerd) [inline src/core/audio/AudioDevice.cpp]: This would be best as a method (or methods?) in the buffer views

```cpp
constexpr auto sampleRef(proc_ch_t channel, f_cnt_t frame) noexcept -> T&;
constexpr auto sample(proc_ch_t channel, f_cnt_t frame) const noexcept -> T;
```

File: src/core/audio/AudioDevice.cpp [hunk 22]
```diff
@@ -44,54 +49,61 @@ AudioDevice::AudioDevice( const ch_cnt_t _channels, AudioEngine*  _audioEngine )
...
+		case 2:
+			dstAt(0, frame) = audioEngineFrame[0];
+			dstAt(1, frame) = audioEngineFrame[1];
+			break;
+		default:
+			dstAt(0, frame) = audioEngineFrame[0];
+			dstAt(1, frame) = audioEngineFrame[1];
+			for (auto channel = 2; channel < dst.channels(); ++channel)
+			{
+				dst[frame][channel] = 0.f;
```
Comment (messmerd) [inline src/core/audio/AudioDevice.cpp]: This could cause failed asserts in `PlanarBufferView`

File: src/core/audio/AudioDevice.cpp (hunk 21 above)
Comment (sakertooth) [reply src/core/audio/AudioDevice.cpp]: Yeah, it just wasn't available. I can add it in another PR

Comment (messmerd) [reply src/core/audio/AudioDevice.cpp]: Why not this one? It's not a major addition

File: src/core/audio/AudioDevice.cpp (hunk 22 above)
Comment (sakertooth) [reply src/core/audio/AudioDevice.cpp]: Good catch :+1:

File: src/core/audio/AudioOss.cpp (hunk 19 above)
Comment (sakertooth) [reply src/core/audio/AudioOss.cpp:211]: I'm inclined to keep it the way it is honestly, I dont want to do something extra when I can't prove its needed. I also believe most of our audio devices are idempotent already, so starting/stopping them more than once in a row should be a noop.

Maybe we could use RAII to enforce this better, but that seems overkill.

File: src/core/AudioEngine.cpp [hunk 23]
```diff
@@ -66,27 +66,29 @@ using LocklessListElement = LocklessList<PlayHandle*>::Element;
...
-	m_audioDev( nullptr ),
-	m_oldAudioDev( nullptr ),
-	m_audioDevStartFailed( false ),
-	m_profiler(),
-	m_clearSignal(false)
+AudioEngine::AudioEngine(bool renderOnly)
+	: m_renderOnly(renderOnly)
+	, m_framesPerAudioBuffer(std::clamp(ConfigManager::inst()->value("audioengine", "framesperaudiobuffer").toULong(),
+		  MINIMUM_BUFFER_SIZE, MAXIMUM_BUFFER_SIZE))
+	, m_framesPerPeriod(std::min(m_framesPerAudioBuffer, DEFAULT_BUFFER_SIZE))
```
Comment (messmerd) [inline src/core/AudioEngine.cpp]: So with commit https://github.com/LMMS/lmms/pull/7568/commits/e00f57f42adf1eebeff5feca8973ea29d81bfae6, a change to the frames per buffer in the settings would take effect immediately without restarting LMMS? This is new behavior and could break a lot of stuff that assumes the frames per buffer stays constant without trying to update it when it changes.

Comment (sakertooth) [reply src/core/AudioEngine.cpp]: > So with commit https://github.com/LMMS/lmms/commit/e00f57f42adf1eebeff5feca8973ea29d81bfae6, a change to the frames per buffer in the settings would take effect immediately without restarting LMMS?

How did you arrive at this conclusion? If I understand correctly, we are merely pulling the value from the config and then using that during the initialization of the `Engine`.

Comment (messmerd) [reply src/core/AudioEngine.cpp]: I must have been thinking that this code would run more than once, but `AudioEngine` is a singleton created at startup. Nevermind!

**Comment by bratpeki** [comment]
Is this merge-ready?

**Comment by messmerd** [comment]
What are you doing in https://github.com/LMMS/lmms/pull/7568/commits/927141bcba6fd045ae1dc6a3ecbd963b38d3e9b0? It seems you're changing the behavior by forcing the frames per period to always be `DEFAULT_BUFFER_SIZE` even when the user selects a smaller buffer size?

File: src/core/AudioEngine.cpp [hunk 24]
```diff
@@ -1045,49 +994,7 @@ MidiClient * AudioEngine::tryMidiClients()
...
-		memcpy(buffer, b, frames * sizeof(SampleFrame));
-		m_fifo->write(buffer);
-	}
-
-	// Let audio backend stop processing
-	m_fifo->write(nullptr);
-	m_fifo->waitUntilRead();
-}
+template void AudioEngine::renderNextBuffer(InterleavedBufferView<float> dst);
+template void AudioEngine::renderNextBuffer(PlanarBufferView<float> dst);
```
Comment (messmerd) [inline src/core/AudioEngine.cpp]: I'd rather you have two separate overloads: one for `InterleavedBufferView` and one for `PlanarBufferView`. Or just define the function template in the header.

Doing the explicit template instantiation in the source file like this is pretty unusual and doesn't offer much of a benefit. I'd be worried about potential linker errors if it's used incorrectly. Also, in the future once we've switched completely over to planar buffers, wouldn't this also be planar-only?

Comment (sakertooth) [reply src/core/AudioEngine.cpp]: > I'd rather you have two separate overloads: one for `InterleavedBufferView` and one for `PlanarBufferView`. 

This is what I did in the beginning but the duplication was bugging me. If we do not care about the duplication issue then yeah I can do two overloads.

> Doing the explicit template instantiation in the source file like this is pretty unusual and doesn't offer much of a benefit.

Keeps the header file clean, and allows me to put this in the `.cpp` file. It seems to have a benefit. What's wrong with it?

> I'd be worried about potential linker errors if it's used incorrectly.
I wouldn't worry about things that haven't transpired yet. It hasn't caused me much issue so far.

> Also, in the future once we've switched completely over to planar buffers, wouldn't this also be planar-only?

It depends if the switch to planar only includes switching the audio backends to use planar as well (which I guess it makes sense to do so). And once we switch we can easily remove these explicit template instantiations if we want to.

Comment (messmerd) [reply src/core/AudioEngine.cpp]: I think I'd prefer duplicate code over a function template implementation in the .cpp file, but if you prefer to keep it this way, then that's fine

**Comment by sakertooth** [comment]
> What are you doing in https://github.com/LMMS/lmms/commit/927141bcba6fd045ae1dc6a3ecbd963b38d3e9b0? It seems you're changing the behavior by forcing the frames per period to always be DEFAULT_BUFFER_SIZE even when the user selects a smaller buffer size?

Notice there are now 2, frames per period, and frames per audio buffer. A "period" is one cycle of rendering. It's a fixed size of 256 frames (what we've always been using for our fixed chunk size), needed for SIMD and per-buffer updates.

The "audio buffer" represents the actual buffer sent to the hardware and subsequently the user's chosen latency.

`renderNextBuffer` accepts a buffer of any size. It basically treats the audio period buffer as a circular buffer, reading as many frames as needed and rendering new periods when it wraps around.

So when the user selects a buffer size less than `DEFAULT_BUFFER_SIZE`, `renderNextBuffer` will read the first, say, 32 frames of the audio period. That would then be delivered to the hardware, and it does it again, and when it wraps around, a new audio period is rendered.

If you check the `renderNextPeriod` and `renderNextBuffer` functions, I added documentation that explains this as well.

A possible concern is correctness (e.g. cant call `renderNextPeriod` while also calling `renderNextBuffer`, not meant to be called by multiple threads, etc), but I think these are mostly non-issues.

Edit: Ah I see the problem now. Yeah I did change the original logic a bit. If the user buffer size is less than 256, the period size should be up to that amount. I thought the period size was always 256. Will fix that.

File: src/core/AudioEngine.cpp (hunk 24 above)
Comment (sakertooth) [reply src/core/AudioEngine.cpp]: > I think I'd prefer duplicate code over a function template implementation in the .cpp file

Do you think explicit template instantiations are bad? I don't see why and I'm kinda curious now. I know you gave reasons previously but I'm not seeing it.

And I'll add two overloads then. :+1:

**Comment by sakertooth** [comment]
@messmerd, seeing that I originally requested for something like `AudioBufferView` but won't be using it here, should it be removed? Do we really need it?

File: src/core/AudioEngine.cpp (hunk 24 above)
Comment (sakertooth) [reply src/core/AudioEngine.cpp]: > And I'll add two overloads then. 👍

Done in 3bb7b29c419e78fb6405e511292192c9327540e3.

**Comment by messmerd** [comment]
> seeing that I originally requested for something like `AudioBufferView` but won't be using it here, should it be removed? Do we really need it?

I don't think it'll hurt to leave it in. It's just a few lines of code and could still be useful in the future.

File: src/core/AudioEngine.cpp [hunk 25]
```diff
@@ -68,26 +67,28 @@ using LocklessListElement = LocklessList<PlayHandle*>::Element;
...
-	m_workers(),
-	m_numWorkers( QThread::idealThreadCount()-1 ),
-	m_newPlayHandles( PlayHandle::MaxNumber ),
-	m_masterGain( 1.0f ),
-	m_audioDev( nullptr ),
-	m_oldAudioDev( nullptr ),
-	m_audioDevStartFailed( false ),
-	m_profiler(),
-	m_clearSignal(false)
+AudioEngine::AudioEngine(bool renderOnly)
```
Comment (messmerd) [inline src/core/AudioEngine.cpp:69]: Could you add this back into the constructor?

```cpp
if (m_framesPerAudioBuffer % m_framesPerPeriod != 0)
{
	throw std::invalid_argument{"Frames per period is not a multiple of buffer size"};
}
```

Comment (sakertooth) [reply src/core/AudioEngine.cpp:69]: Given that there is no real danger if they are not a multiple anymore, throwing for these cases I find is excessive. If they are not a multiple, when then `renderNextBuffer` completes, a fraction of a period will be waiting to be read at a later time, which is accounted for in the design.

**Comment by sakertooth** [comment]
> I don't think it'll hurt to leave it in. It's just a few lines of code and could still be useful in the future.

I've been thinking about this recently, and I've realized I am wary of having code/complexity when we aren't using it. It could be useful in the future, but we have no guarantee of that. Even in places where `AudioBufferView` could be used, we resort to using separate function overloads, which weakens the argument of keeping it IMO. It wouldn't hurt to leave it in definitely, but at the end of the day, it is added complexity we aren't using, and we resort to not using it when we could've (raises the question of if we actually want it in the first place).

Edit: Eh, I might just use it and put it in the header this time.
Edit 2: I made the switch in b09cc43.

**Review by bratpeki — APPROVED** [review]
Approved for code and testing! 🎉

File: src/core/audio/AudioPulseAudio.cpp [hunk 26]
```diff
@@ -243,35 +214,27 @@ void AudioPulseAudio::run()
 	pa_mainloop_free( mainLoop );
 }
 
+void AudioPulseAudio::streamWriteCallback(pa_stream*, size_t)
+{
+	auto buf = static_cast<void*>(nullptr);
+	auto maxBufSizeInBytes = audioEngine()->framesPerAudioBuffer() * channels() * sizeof(float);
 
+	pa_stream_begin_write(m_s, &buf, &maxBufSizeInBytes);
+	if (!buf) { return; }
```
Comment (messmerd) [inline src/core/audio/AudioPulseAudio.cpp]:
```suggestion
	if (pa_stream_begin_write(m_s, &buf, &maxBufSizeInBytes) != 0 || !buf) { return; }
```
According to the [documentation](https://www.freedesktop.org/software/pulseaudio/doxygen/stream_8h.html#a6cf50cfc4ea8897391941184d74d7dfa), a non-zero return value or null buffer indicates an error.

File: src/core/audio/AudioPulseAudio.cpp [hunk 27]
```diff
@@ -243,35 +214,27 @@ void AudioPulseAudio::run()
...
-		{
-			pa_stream_write( m_s, pcmbuf, bytes, nullptr, 0,
-							PA_SEEK_RELATIVE );
-		}
-		fd += frames;
+		std::fill_n(static_cast<float*>(buf), numSamples, 0.f);
+	}
+	else
+	{
+		audioEngine()->renderNextBuffer({reinterpret_cast<float*>(buf), channels(), numFrames});
```
Comment (messmerd) [inline src/core/audio/AudioPulseAudio.cpp]:
```suggestion
		audioEngine()->renderNextBuffer({static_cast<float*>(buf), channels(), numFrames});
```

File: src/core/audio/AudioSoundIo.cpp [hunk 28]
```diff
@@ -269,55 +252,42 @@ void AudioSoundIo::underflowCallback()
...
+			errorCallback(error);
 			return;
 		}
 
-		if (!frameCount)
-			break;
+		if (!frameCount) { break; }
+
+		auto buffers = std::array<float*, SOUNDIO_MAX_CHANNELS>{};
+		buffers.fill(nullptr);
```
Comment (messmerd) [inline src/core/audio/AudioSoundIo.cpp]:
```suggestion
		auto buffers = std::array<float*, SOUNDIO_MAX_CHANNELS>{};
```
The `{}` initialization should already fill the array with nullptr.

File: src/core/audio/AudioJack.cpp [hunk 29]
```diff
@@ -306,7 +296,7 @@ void AudioJack::startProcessing()
 	m_active = true;
 
 	// try to sync JACK's and LMMS's buffer-size
-	//	jack_set_buffer_size( m_client, audioEngine()->framesPerPeriod() );
+	jack_set_buffer_size(m_client, audioEngine()->framesPerAudioBuffer());
```
Comment (messmerd) [inline src/core/audio/AudioJack.cpp]: Did you mean to uncomment this?

File: include/AudioEngine.h [hunk 30]
```diff
@@ -171,13 +171,11 @@ class LMMS_EXPORT AudioEngine : public QObject
...
+	f_cnt_t framesPerPeriod() const { return m_framesPerPeriod; }
 
-	// methods providing information for other classes
-	inline f_cnt_t framesPerPeriod() const
-	{
-		return m_framesPerPeriod;
-	}
-
+	//! @returns the number of audio frames per audio buffer
+	f_cnt_t framesPerAudioBuffer() const { return m_framesPerAudioBuffer; }
```
Comment (messmerd) [inline include/AudioEngine.h]: Can you improve the comment here by explaining what this is? What's the difference between `framesPerPeriod` and `framesPerAudioBuffer`? What's the range of values these methods could return?

File: include/AudioEngine.h [hunk 31]
```diff
@@ -253,10 +246,34 @@ class LMMS_EXPORT AudioEngine : public QObject
...
+
+	/**
+	 * @brief Renders an audio buffer into @a dst.
+	 *
+	 * This function renders audio into @a dst in discrete chunks of audio periods. As @a dst can have any number of
+	 * frames, it can contain a whole number of periods or some fraction of a period.
+	 *
+	 * If @a dst has 1 channel, the audio periods are averaged to mono.
+	 * If @a dst has 2 channels, the audio periods are directly copied.
+	 * If @a dst has more than 2 channels, the stero channels are copied and the rest are zero-filled.
```
Comment (messmerd) [inline include/AudioEngine.h]:
```suggestion
	 * If @a dst has more than 2 channels, the stereo channels are copied and the rest are zero-filled.
```

File: src/core/audio/AudioJack.cpp (hunk 29 above)
Comment (sakertooth) [reply src/core/audio/AudioJack.cpp]: I'm not sure why this was uncommented? I'll have to investigate with a `git blame`. I'm guessing `jack_set_buffer_size` doesn't actually set the buffer size or something?

File: src/core/audio/AudioPulseAudio.cpp (hunk 26 above)
Comment (sakertooth) [reply src/core/audio/AudioPulseAudio.cpp]: Seems like the previous code was also returning early on error. What do you wish we do instead/what's the problem?

Comment (sakertooth) [reply src/core/audio/AudioPulseAudio.cpp]: Oh wait, I read this wrong. I thought your suggestion was my code, lol.

File: include/AudioEngine.h (hunk 30 above)
Comment (sakertooth) [reply include/AudioEngine.h]: > Can you improve the comment here by explaining what this is? What's the difference between `framesPerPeriod` and `framesPerAudioBuffer`? What's the range of values these methods could return?

My plan is to just remove the `AudioEngine::framesPerAudioBuffer` member function, since only the devices need it. `framesPerAudioBuffer` is just the number of frames processed per audio callback, i.e., the actual buffer size specified by the user, while `framesPerPeriod` is a "chunk of work" that the `AudioEngine` does. The audio buffer requested by the hardware may consist of multiple chunks or periods (it can also contain a fraction of a period) after rendering. I wasn't sure how to describe this succinctly in the documentation here. I think my explanation in `renderNextBuffer` and `renderNextPeriod` were adequate?

I hope that the names are clear enough to distinguish it in the code. If there is a better name for `framesPerPeriod`/`framesPerAudioBuffer`, I'm open to suggestions.

Comment (sakertooth) [reply include/AudioEngine.h]: Changed my plans. Opted to just update the documentation as requested in 8cf7c4e.

File: src/core/audio/AudioJack.cpp (hunk 29 above)
Comment (sakertooth) [reply src/core/audio/AudioJack.cpp]: Did some reading up on JACK, and I learned JACK is a server, and that the buffer size doesn't just assign that size to the application, but to the whole server and everything running through it. That's the reason I'm guessing this was disabled (too invasive and can ruin the user's buffer size setting).

Recommented the line in 3b10d33.

File: include/AudioEngine.h [hunk 32]
```diff
@@ -253,10 +240,55 @@ class LMMS_EXPORT AudioEngine : public QObject
...
+	 * @returns A non-owning buffer to the next audio period.
+	 */
+	const SampleFrame* renderNextPeriod();
+
+	/**
+	 * @brief Renders an audio buffer into @a dst.
+	 *
+	 * Renders @ref renderNextAudioPeriod() "audio periods" into @a dst. If @a dst is not a multiple of the period
+	 * size, the remaining frames are partially rendered (an extra period may be rendered in such cases, which can
+	 * degradge performance).
```
Comment (messmerd) [inline include/AudioEngine.h]:
```suggestion
	 * degrade performance).
```

File: include/AudioEngine.h [hunk 33]
```diff
@@ -253,10 +240,55 @@ class LMMS_EXPORT AudioEngine : public QObject
...
 	}
 
-	inline const SampleFrame* nextBuffer()
-	{
-		return hasFifoWriter() ? m_fifo->read() : renderNextBuffer();
-	}
+	/**
+	 * @returns The internal buffer size used by audio plugins and other processing done within the audio engine.
+	 * It's maximum value is @ref DEFAULT_BUFFER_SIZE, or equal to @ref framesPerAudioBuffer() if it is less than @ref
+	 * DEFAULT_BUFFER_SIZE.
```
Comment (messmerd) [inline include/AudioEngine.h]:
```suggestion
	 * Its value is @ref DEFAULT_BUFFER_SIZE or @ref framesPerAudioBuffer() - whichever is lower.
```

**Review by messmerd — APPROVED** [review]
I haven't tested it, but the code seems fine.

File: include/AudioEngine.h (hunk 33 above)
Comment (sakertooth) [reply include/AudioEngine.h]: Would prefer a comma but this works.

**Comment by messmerd** [comment]
Time to merge?

**Comment by sakertooth** [comment]
> Time to merge?

That should be ok.

File: include/AudioPortAudio.h
Comment (messmerd) [inline include/AudioPortAudio.h:1]: There's a compiler warning on macOS:
```
In file included from /Users/runner/work/lmms/lmms/src/core/audio/AudioPortAudio.cpp:33:
/Users/runner/work/lmms/lmms/include/AudioPortAudio.h:92:14: warning: private field 'm_outBufPos' is not used [-Wunused-private-field]
   92 |         std::size_t m_outBufPos = 0;
      |                     ^
```

`m_outBufPos` can be removed now.

File: src/core/audio/AudioJack.cpp
Comment (messmerd) [inline src/core/audio/AudioJack.cpp:1]: This doesn't appear related to this PR, but there's another easy-to-fix compiler warning in this file:
```
/Users/runner/work/lmms/lmms/src/core/audio/AudioJack.cpp:482:26: warning: lambda capture 'this' is not used [-Wunused-lambda-capture]
  482 |         auto buildToolButton = [this](QWidget* parent, const QString& currentSelection, const std::vector<std::string>& names, const QString& filteredLMMSClientName)
      |                                 ^~~~
```
