### PR TITLE
Beat note bug at the end of bars

### LINKED ISSUE #1105: B+B plays extra bar with note near the end
I have a beat with a drum note very close to the end of the bar (although it doesn't touch).
B+B
As you can see, the arrow showing what is playing is in the next bar.
What I found more interesting is that If I add normal note to any point in the bar, it loops normally.
B+B
Thanks

### PR DESCRIPTION
**Pull request by zonkmachine**
Fixes #1105 

I had a go at fixing the problem with beat notes on position near the end of the beat forcing the insert of an extra bar. ~~I also tweaked the Piano Roll notes to not do the same depending on where they end but on the start position. To me that's more logical behaviour.~~

_Edit2: This is now a pure fix for #1105 and the rest is edited out and will be a separate PR._

### CODE REVIEW

**Comment by zonkmachine** [comment]
> I also tweaked the Piano Roll notes to not do the same depending on where they end but on the start position. To me that's more logical behaviour.

I mean more logical for notes in a BBTrack. Just an experiment...

**Comment by zonkmachine** [comment]
It's really a bit tricky this one with BBTrack vs. InstrumentTracks. Maybe, instead of checking the pattern type , it would be better to let the deciding factor of how the pattern is played back be the track type. If it's played from within a BBTrack it loops like this PR and if it's played from an instrument track the beat notes loops like the first commit while ordinary notes creates a wider space if they go over the the beat?

**Comment by Umcaruje** [comment]
:+1: I really like this solution. Feels really natural and also fixes the original problem. I was fearing a note extending to the next bar that gets cut off at the end of a loop wouldn't ever get a noteoff, but this is not the case, the note plays out for its length and works perfectly, tested with zyn and VST's too.

**Comment by zonkmachine** [comment]
> I was fearing a note extending to the next bar that gets cut off at the end of a loop wouldn't ever get a noteoff,

And I was fearing it would just add to the volume and get noisy... and weeellll it can do. I've mostly sorted the backward compatibility but will split this into two parts. The bug fix separate and then the change in behaviour which needs a discussion.

**Comment by zonkmachine** [comment]
Here is the fix for  #1105 
The backward compattbility part in `Pattern::loadSettings()` is longer than usually but pretty straight forward. We just check for version and then, if it's a beat pattern, load it in the old way. The final check is for patterns that have been manually adjusted. Works but needs more testing.

**Comment by Umcaruje** [comment]
I think the backwards support should be handled in Datafile::Upgrade, if possible

**Comment by zonkmachine** [comment]
I'll look into Datafile::Upgrade, and also I think I've found a way to make it not so ridiculously long...

**Comment by jasp00** [comment]
I will have a look at #2969, it should be fixed first for the upgrade.

**Comment by zonkmachine** [comment]
I suggest to postpone this PR to 1.3 .

**Comment by jasp00** [comment]
>I suggest to postpone this PR to 1.3 .

Why? The bug is important. The only problem with this request is the need for an upgrade function. Let us merge #3011 (which fixes #2969) and finish this one.

**Comment by zonkmachine** [comment]
OK. I'll look into it again.

**Comment by zonkmachine** [comment]
> The only problem with this request is the need for an upgrade function.

Looking at it now. It seems like there is more than an upgrade function needed here. :beetle:

**Comment by zonkmachine** [comment]
Right. In https://github.com/LMMS/lmms/pull/3037 setting "len" was dropped and this holds the length of the beat so I have to read in "len" and convert it to "steps" directly.

**Comment by zonkmachine** [comment]
https://github.com/LMMS/lmms/issues/2030 / https://github.com/LMMS/lmms/issues/3105 needs to be fixed before an upgrade path can be fully tested for this. Not a big problem, just a note.

**Comment by zonkmachine** [comment]
@jasp00 ^Since we don't know for sure what the time signature will be, as this could either be changed manually or automated, I don't think I can do the upgrade in DataFile.cpp as I'm working on now.
I think it should be done in [`Pattern::changeTimeSignature()`](https://github.com/LMMS/lmms/blob/1eded63a197a330e1fd786c8460bdc8bac8bd592/src/tracks/Pattern.cpp#L581) and a call to `Pattern::changeTimeSignature()` should perhaps be added to `Pattern::loadSettings()` to take care of the initial state. Does this sound about right to you?

**Comment by jasp00** [comment]
There is a design problem: it does not make sense to update patterns with time signatures on playback. If you change the signature, you break the pattern; each pattern should have its own signature. `changeTimeSignature()` is being used as a hack right now. So it does not really matter what you do now, you may proceed as you see fit.

File: src/tracks/Pattern.cpp [hunk 1]
```diff
@@ -453,6 +461,48 @@ void Pattern::loadSettings( const QDomElement & _this )
...
 
+	// Backward compatibility for < 1.2.0
+	if( ! _this.hasAttribute( "version" ) )
+	{
+		if( m_patternType == BeatPattern )
+		{
+			MidiTime oldLength = MidiTime( _this.attribute( "len" ).toInt() );
+
+			tick_t max_length = MidiTime::ticksPerTact();
+			int oldSteps = m_steps;
```
Comment (zapashcanon) [inline src/tracks/Pattern.cpp]:
```c++
const int oldSteps = m_steps;
```

Comment (zonkmachine) [inline src/tracks/Pattern.cpp]: Thanks, but if you follow the thread you will see that this is old code that's going to change completely. Also, I use the tag `In progress` for stuff that isn't really ready for review.

**Comment by zonkmachine** [comment]
@jasp00 I haven't given up on the DataFile.cpp upgrade path for this one. I'm just reverting to the original commit for now.

**Comment by zonkmachine** [comment]
Oh brother!
The algorithm is: `"steps" = "len" / 12`
It's that simple... :tractor:

File: src/core/DataFile.cpp [hunk 2]
```diff
@@ -898,6 +899,25 @@ void DataFile::upgrade_1_1_91()
 			el.setAttribute( "arpdir", "3" );
 		}
 	}
+
```
Comment (zonkmachine) [inline src/core/DataFile.cpp]: This should be in it's own upgrade function, right?
 void DataFile::upgrade_1_1_91()
What's the new upgrade function called `_1_1_92()` ? `_1_2_0_rc2` ?

Comment (tresf) [inline src/core/DataFile.cpp]: > `_1_2_0_rc3`

Yes, `1.2.0-rc3` will be the next release assuming the fix is that specific.  If it's only a regression since `1.1.x`, it's preferred to keep it in the existing `1.1.91` section.

**Comment by zonkmachine** [comment]
@tresf I think I'm done here. The bug in question, actually I think it's a feature that just didn't cut it, goes way back. Before 1.0 .

**Comment by zonkmachine** [comment]
Merge?

File: src/core/DataFile.cpp [hunk 3]
```diff
@@ -901,6 +901,29 @@ void DataFile::upgrade_1_1_91()
...
+	for( int i = 0; !list.item( i ).isNull(); ++i )
+	{
+		list = elementsByTagName( "pattern" );
+		for( int i = 0; !list.item( i ).isNull(); ++i )
+		{
+			int patternLength, steps;
+			QDomElement el = list.item( i ).toElement();
+			for( int i = 0; !list.item( i ).isNull(); ++i )
+			{
+				patternLength = el.attribute( "len" ).toInt();
```
Comment (tresf) [inline src/core/DataFile.cpp]: Do all `"pattern"` attributes contain an integer value (never blank?).  We just need to make sure we [sanitize our input](https://github.com/zonkmachine/lmms/blob/f2b611b0e8f6848e64d233fbd9c81b509a305268/src/core/DataFile.cpp#L413).  I think this change is fine, but any time we assume a String is an integer we need to make sure we don't segfault on something simple.

Comment (zonkmachine) [inline src/core/DataFile.cpp]: Nice catch. I'll test it some more with:

```c++
if( el.attribute( "len" ) != "" )
{
    patternLength = el.attribute( "len" ).toInt();
    steps = patternLength / 12;
    el.setAttribute( "steps", steps );
}
```

Comment (zonkmachine) [inline src/core/DataFile.cpp]: Pushed a fix. With or without this the projects open up just like before. If I create some len="" in a .mmp the results are a bit buggy so I think that indicates there probably are no blank "len".
But that doesn't compare to testing real project files and they come out just fine. I don't know how to devise a good test case for this.

Comment (tresf) [inline src/core/DataFile.cpp]: > If I create some len="" in a .mmp the results are a bit buggy so I think that indicates there probably are no blank "len".

That was my suspicion as well but I wanted to mention it as I'm not sure how they're stored for all use-cases.

Comment (zonkmachine) [inline src/core/DataFile.cpp]: OK. I have no more tests do do here but as it changes the behaviour of a central tool maybe leave it up for a while before merge. Is it too optimistic to think that someone is going to bother to take it for a spin? We have quite a list of pull requests to go through. :)

**Comment by zonkmachine** [comment]
I'm going to wait with merging this for the outcome of the discussion on upgrade methods [here](https://github.com/LMMS/lmms/pull/3281#issuecomment-277476750).

File: src/core/DataFile.cpp [hunk 4]
```diff
@@ -901,6 +901,32 @@ void DataFile::upgrade_1_1_91()
 }
 
 
+void DataFile::upgrade_1_2_0_rc3()
+{
+	// Upgrad from earlier bbtrack beat note behaviour of adding
```
Comment (tresf) [inline src/core/DataFile.cpp]: typo, `Upgrade`

**Comment by zonkmachine** [comment]
OK. Merge...
