### PR TITLE
Emit the `playbackPositionJumped` signal only when the active timeline jumps

### LINKED ISSUE #8251: Crackling when recording a MIDI clip while playing over a sample clip
### System Information

Arch Linux

### LMMS Version(s)

1.3.0-alpha.1.937+13ea2ee

### Most Recent Working Version

_No response_

### Bug Summary

Recording into a MIDI clip in the Piano Roll while playing over a sample clip causes immediate crackling of the sound. 

### Expected Behaviour

You should be able to record into the MIDI clip without crackling.

### Steps To Reproduce

1. Create a new instrument track (can be any instrument)
2. Add a empty MIDI clip to the new track
3. Add a sample track with a sample clip directly over the MIDI clip
4. Load a file into the sample clip
5. In the Piano Roll for the empty MIDI clip, press "Record notes from MIDI-device/channel-piano while playing song or pattern track"

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Screenshots / Minimum Reproducible Project

_No response_

### Please search the issue tracker for existing bug reports before submitting your own.

- [x] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by sakertooth**
#7454 introduced a change where it aggregated all the timelines and emitted the `playbackPositionChanged` signal whenever any of the timelines move and the song is playing. This PR brings fourth a stronger guarantee: only emit the `playbackPositionChanged` signal when the song is playing *and* the timeline that jumped is responsible for the current play mode.

Fixes #8251

### CODE REVIEW

File: src/core/Song.cpp [hunk 1]
```diff
@@ -118,14 +118,18 @@ Song::Song() :
...
-			if (m_playing) { emit playbackPositionJumped(); }
-		}, Qt::DirectConnection);
+		connect(
+			&timeline, &Timeline::positionJumped, this,
+			[this, &timeline] {
+				// Only emit the signal when the song is actually playing and the active timeline jumps
+				// This prevents LFOs from changing phase when the user drags the timeline while paused
+				if (m_playing && isTimelineActive(timeline)) { emit playbackPositionJumped(); }
+			},
+			Qt::DirectConnection);
```
Comment (messmerd) [inline src/core/Song.cpp]: Here's another way that would not require adding the `isTimelineActive` method:
```cpp
for (std::size_t playMode = 0; playMode < m_timelines.size(); ++playMode)
{
	connect(&m_timelines[playMode], &Timeline::positionJumped, this, [=, this] {
		// Only emit the signal when the song is actually playing and the active timeline jumps
		// This prevents LFOs from changing phase when the user drags the timeline while paused
		if (m_playing && m_playMode == static_cast<PlayMode>(playMode))
		{
			emit playbackPositionJumped();
		}
	}, Qt::DirectConnection);
}
```
EDIT: It looks like this is more or less how you did it in your first commit.

File: include/Song.h [hunk 2]
```diff
@@ -222,6 +222,12 @@ class LMMS_EXPORT Song : public TrackContainer
 		setPlayPos(ticks, m_playMode);
 	}
 
+	//! @returns true if @a timeline is the timeline responsible for the current playback position
+	bool isTimelineActive(Timeline& timeline)
+	{
+		return static_cast<PlayMode>(std::distance(m_timelines.begin(), &timeline)) == m_playMode;
+	}
```
Comment (messmerd) [inline include/Song.h]:
```suggestion
	bool isTimelineActive(const Timeline& timeline) const
	{
		return static_cast<PlayMode>(std::distance(m_timelines.data(), &timeline)) == m_playMode;
	}
```
If you want to go the route of using this method, here's how you could fix the MSVC build + apply const correctness.  (NOTE: I haven't tested this, but it should work.)

Unfortunately, if `timeline` doesn't exist within `m_timeline`, this method would exhibit UB when it calls `std::distance`, and considering how there's no use case for this method outside of this class, I think this method should not be provided.

Better to go `play mode` --> `timeline` via the `getPlayPos` methods than try to go the opposite direction.

File: src/core/Song.cpp (hunk 1 above)
Comment (sakertooth) [reply src/core/Song.cpp]: I wanted to bring the notion of an "active timeline" to simplify the comment in that first commit, but I can do this if we all definitely know what an active timeline is.

File: include/Song.h (hunk 2 above)
Comment (sakertooth) [reply include/Song.h]: I'm so confused why `timeline` wouldn't exist in `m_timelines`. 🤔
