### PR TITLE
Fix cloned track position

### LINKED ISSUE #170: Insert cloned tracks after the original track (not at the end)
This shouldn't be a difficult thing to implement. It's hard to move tracks up, especially with the bug that causes weird behaviour in song/bb-editors when you move tracks when the editor is scrolled down (anywhere but the very top). I guess fixing that bug would be nice too, but it'd still be better and more expected behaviour if cloned tracks appeared next to the originals.

Also, an option to clear all patterns/sequences from a track. Would be convenient when you clone a track but don't want the sam note data on it.

### PR DESCRIPTION
**Pull request by badosu**
I provided a solution for the original ask-for-review of this PR, I bypass the signal creating a view myself before or retrieving it.

This is ready for review.

See original thread below:

> I am opening this as a call for help, I really don't know how to work around an architectural problem to be able to fix #170.
> 
> The problem is that when we clone a track we just create another one with the same settings from the original. This would not be a problem if there wasn't the fact that we add a TrackView asynchronously waiting for track creation signals, see: https://github.com/LMMS/lmms/blob/7b5084c53bd4b036ae6a4790c027ecfab625b8a1/src/gui/TrackContainerView.cpp#L87-89 .
> 
> This PR would work if not for this fact, and I am just pushing this so that you can see what I was trying to do. My PR assumes that after `Track::clone()` returns, a TrackView was already created, so I get the last one and put it under the original one, which of course does not happens because the TrackView will only be created later on the event loop.
> 
> This is a very core part of LMMS and I don't know how to solve this, since this would probably require a change on how we create views from tracks or a crazy workaround.
> 
> The only possibility I see right now is to remove the trackAdded signal listening and explicitly adding a TrackView every time a new track gets created, this would increase the amount of boilerplate but would make things explicit. However I am not sure whether this would affect DSP capabilities or not.
> 
> Any ideas @Lukas-W @diizy @curlymorphic ?

### CODE REVIEW

File: src/gui/TrackContainerView.cpp [hunk 1]
```diff
@@ -156,44 +156,45 @@ void TrackContainerView::removeTrackView( TrackView * _tv )
...
 
 
 
-void TrackContainerView::moveTrackViewDown( TrackView * _tv )
+void TrackContainerView::moveTrackViewDown( TrackView * trackView )
 {
-	for( int i = 0; i < m_trackViews.size()-1; ++i )
+	int index = m_trackViews.indexOf( trackView );
+
+	if ( index < m_trackViews.size() - 1 )
```
Comment (tresf) [inline src/gui/TrackContainerView.cpp]: Not related to your question, but can't the bounds checking on up/down move to the `moveTrackView` function?

**Comment by tresf** [comment]
Is there a constructor candidate that could receive track position as a parameter that would help?  We could always default to zero and pop it on the top of the stack (shooting blindly here as I'm not familiar with the code).

That or our slot has the ability to call yet another slot in a call-back fashion (sorry if I'm way off here).

**Comment by badosu** [comment]
@tresf I thought of that, but there are some problems:

1. We will be adding a view parameter to the creation of something that should not receive view parameters.
2. Even if we tried to implement it, we would still have the asychronocity problem.

File: src/gui/TrackContainerView.cpp (hunk 1 above)
Comment (badosu) [inline src/gui/TrackContainerView.cpp]: Yeah, we can, but this code will probably not even be used until we figure this out.

**Comment by badosu** [comment]
@tresf I updated the PR.

File: src/gui/TrackContainerView.cpp [hunk 2]
```diff
@@ -156,45 +156,48 @@ void TrackContainerView::removeTrackView( TrackView * _tv )
...
+			m_trackViews[indexTo]->getTrack() );
+
+	m_scrollLayout->removeWidget( trackView );
+	m_scrollLayout->insertWidget( indexTo, trackView );
+
+	Track * track = m_tc->m_tracks[indexFrom];
+
+	m_tc->m_tracks.remove( indexFrom );
+	m_tc->m_tracks.insert( indexTo, track );
+	m_trackViews.move( indexFrom, indexTo );
```
Comment (badosu) [inline src/gui/TrackContainerView.cpp]: This is really weird, the list of tracks is actually a `QVector` and the list of track views is a `QList`, is there any reason for this difference? Using both as `QList` would help a lot.

**Comment by tresf** [comment]
Very nice approach.  I will need help from Lukas and Vesa to merge as this is a bit out of my comfort zone.  Nice work.

File: src/gui/TrackContainerView.cpp (hunk 2 above)
Comment (tresf) [inline src/gui/TrackContainerView.cpp]: Vesa can confirm, but a QVector may be better long-term when we do collapsible tracks.

**Comment by badosu** [comment]
@tresf To be frank, I don't like the solution I had to use. What we really needed to do was to refactor the `Track`/`TrackView` creation and assignment logic from implicit to explicit. This would require a lot of knowledge on edge cases and on why it was done this way, which is not something we have today.

**Comment by diizy** [comment]
Ugh, I remember trying to solve this exact same problem quite some time ago, getting frustrated with the mess of the Track/Trackview code...

I'd really have to take a look at this PR when I have more time to see if it's safe to merge.

**Comment by badosu** [comment]
Thanks @diizy, I don't feel very confident wth the quality of this PR so your feedback is invaluable.

File: src/gui/TrackContainerView.cpp [hunk 3]
```diff
@@ -156,45 +156,48 @@ void TrackContainerView::removeTrackView( TrackView * _tv )
...
-		}
-	}
+	// Can't move out of bounds
+	if ( indexTo >= m_trackViews.size() || indexTo < 0 ) { return; }
+
+	// Does not need to move to itself
+	int indexFrom = m_trackViews.indexOf( trackView );
+	if ( indexFrom == indexTo ) { return; }
+
+	BBTrack::swapBBTracks( trackView->getTrack(),
```
Comment (badosu) [inline src/gui/TrackContainerView.cpp]: @diizy In particular this is the part that worries me the most: I changed the logic of all other tracks from swapping to a move action, this can however change the location of the BB track on the selector in an inconsistent way.

I did not experience problems with this on my local tests, but should be something to worry about.

**Comment by tresf** [comment]
@badosu we should probably close out this PR and reference it in a bug if we're not going to address this prior to 1.2.  Or we could merge it... :)

**Comment by badosu** [comment]
@tresf Here is the bug: #170 

This is ready for testing for a long time, I was/am awaiting for feedback.

@tresf 
> Or we could merge it... :)

I can't merge it by myself

**Comment by tresf** [comment]
My impression from comments above is your primary concern was in regards to implementation technique.  We can test this for the 1.2 release, but I need someone to help make the decision to merge or shelve and that's what I'm asking you for. :)

**Comment by curlymorphic** [comment]
I have just tested this, It works fine in both the song and BB editors, The cloned track is now in the correct position. I have also spent some time changing positions of track in both editors, both in a normal fashion, and by dragging quickly, off the top and bottom while playing various songs from the Demo folder,and all seems to be working fine. Loading as saving of the new positions also works.

This moving of tracks, is only moving the gui representation, no dsp code is touched.

My opinion is we should merge this.

**Comment by tresf** [comment]
Merging due to positive testing and feedback.  Thanks Dave.

**Comment by badosu** [comment]
Thanks for testing @curlymorphic and for merging @tresf

**Comment by tresf** [comment]
... and for coding @badosu. :)
