### PR TITLE
Fixes #6626: Throw if Lv2 object CTORs fail

### LINKED ISSUE #6626: `Lv2Proc::run` crashes after `Lv2Proc::m_valid` has been unset
### Bug Summary

On plugin instantiation failure, `Lv2Proc::m_valid` is being set to false. However, `Lv2Proc::run` does not evaluate `m_valid` and still calls `lilv_instance_run`, which causes undefined behavior, including crashes.

#### Steps to reproduce

* Startup LMMS with a new project
* Add the blop Sawtooth wave
* Export the song to WAV

#### Expected behavior

Export aborts, but LMMS does not crash, or at least it crashes with a descriptive error.

#### Actual behavior

LMMS can crash with an unclear "Segmentation fault".

#### Affected LMMS versions

All.

### Fix suggestions

Either evaluate `m_valid` in `Lv2Proc::run` or do not even create such plugins at all.

### PR DESCRIPTION
**Pull request by JohannesLorenz**
I still have open questions here, as written on discord:

1. Which types of exceptions do we really want to catch? E.g. should an `std::logic_error` be ignored and cause LMMS to terminate? Should we create a new `lmms::plugin_error` class to decide what exactly we want to catch? Or should we just catch everything? I would rather say the last, because users will want to avoid LMMS crashes, no matter what kind of plugin error?
2. Many people argue to not use std::string when throwing. Should we follow this? If yes, should a throw be accompanied by a `qCritical()` (or similar) if a verbose message is needed? (it is needed in a lot of cases). Or should we create a class which contains multiple arguments (`void*` or template parameters), that we concatenate when catching that class?

In this PR I solved it like this:

1. Simply catch all kinds of exception. No exception from any plugin code is worth crashing LMMS.
2. I avoided creating `std::string`, but this leads to redundant `qCritical()` calls. It might be a cleaner approach to throw an exception which keeps its arguments in an `std::tuple`, which we pass to `qCritical()` at `catch` time.

Feel free to suggest changes.

Fixes #6626

### CODE REVIEW

**Comment by messmerd** [comment]
Since the `lmms_plugin_main` function is marked `extern "C"` and is called across a DLL boundary, it might not be a good idea for it to throw exceptions. It may be undefined behavior, though I'm not certain about this.

Returning an error from `lmms_plugin_main` may require modifying its function signature - maybe something like this:

```c++
PLUGIN_EXPORT Plugin* lmms_plugin_main(Model* parent, void* data, PluginIssue* error);
```

This would also give the `PluginIssue` class a purpose outside of just its internal LV2 host usage. If plugin instantiation failed, the plugin error could then be passed to `DummyPlugin` which could tell users what exactly caused it to fail.

Though if we decide we don't need to get that information to users and simply failing to instantiate the plugin is sufficient, couldn't you just return `nullptr` from `lmms_plugin_main`? You could even have a try/catch in `lmms_plugin_main` if you wanted the LV2 plugin's constructor to throw an exception upon failure, and just return `nullptr` in the catch statement.

**Comment by JohannesLorenz** [comment]
Good point with the "C"...

> You could even have a try/catch in `lmms_plugin_main` if you wanted the LV2 plugin's constructor to throw an exception upon failure, and just return `nullptr` in the catch statement.

I like this most. Another possibility would be that we offer an `lmms_plugin_main_cpp`, which guarantees staying in C++.
After all, I wonder why our plugin hooks are not C++ - some libraries may use a lot of C code, but in any case, we use C++ for the entry stuff. Even the descriptor:

```c++
extern "C"
{

Plugin::Descriptor PLUGIN_EXPORT bitcrush_plugin_descriptor =
{
	LMMS_STRINGIFY( PLUGIN_NAME ),
	"Bitcrush",
	QT_TRANSLATE_NOOP( "PluginBrowser", "An oversampling bitcrusher" ),
	"Vesa Kivimäki <contact/dot/diizy/at/nbl/dot/fi>",
	0x0100,
	Plugin::Type::Effect,
	new PluginPixmapLoader( "logo" ),
	nullptr,
	nullptr,
};

}
```

`Plugin` itself is a C++ class, `Descriptor` uses `bool`, and `::` is not available in standard C. So why not remove the "C" stuff completely from the hook, and plugins that insist on using C must manage it themselves?

**Comment by JohannesLorenz** [comment]
> So why not remove the "C" stuff completely from the hook, and plugins that insist on using C must manage it themselves?

Hmm, I just read the `QLibrary` docs: `The symbol must be exported as a C function from the library. This means that the function must be wrapped in an extern "C" if the library is compiled with a C++ compiler. ` . So, bad idea.

**Comment by JohannesLorenz** [comment]
I posted [on SO](https://stackoverflow.com/questions/77382678/is-extern-c-code-allowed-to-throw-exceptions), let's see...

**Comment by JohannesLorenz** [comment]
From the duplicate answer, it seems like there is nothing preventing it, though some suggest to not use it and specify `noexcept`.

How about if we use the principle "If it passes CI, we allow it"?

File: src/core/Plugin.cpp
Comment (messmerd) [inline src/core/Plugin.cpp:1]: I would revert all the changes you made to this file and move the `try`/`catch` to your `lmms_plugin_main` functions instead.

**Comment by DomClark** [comment]
> Which types of exceptions do we really want to catch? E.g. should an `std::logic_error` be ignored and cause LMMS to terminate? Should we create a new `lmms::plugin_error` class to decide what exactly we want to catch? Or should we just catch everything? I would rather say the last, because users will want to avoid LMMS crashes, no matter what kind of plugin error?

I would argue against throwing `std::logic_error` in the first place, and suggest using assertions instead. How should the program be expected to handle a bug in itself? I would use exceptions in cases where they indicate some runtime problem (e.g. failure to acquire some resource), rather than a problem intrinsic to the software itself. If there's an exception you never want to catch, it probably shouldn't be an exception. However, the standard library unfortunately throws subclasses of `std::logic_error` in a few places. I'm torn between catching everything, or just `std::runtime_error`, but I don't think we need to catch only an LMMS-specific error type.

> Many people argue to not use `std::string` when throwing. Should we follow this? If yes, should a throw be accompanied by a `qCritical()` (or similar) if a verbose message is needed? (it is needed in a lot of cases). Or should we create a class which contains multiple arguments (`void*` or template parameters), that we concatenate when catching that class?

I don't think we should follow this, unless I'm misunderstanding the arguments. The main objection I can see is that operations on a `std::string` can themselves throw exceptions, in particular when trying to allocate memory, and these end up thrown instead of the exception you were trying to throw. The usual advice when dealing with memory allocation errors, however, is "don't bother" - it's a rare occurence, and handling it effectively is difficult. Additionally, on many platforms, throwing an exception requires allocating memory internally anyway, so avoid string operations may well not save you. Using `std::runtime_error`, or subclassing it, should be fine.

> So why not remove the [extern] "C" stuff completely from the hook, and plugins that insist on using C must manage it themselves?

The `extern "C"` declaration has nothing to do with the plugin being written in C - it's used to give the names of the symbol inside C linkage, which avoids C++ name mangling. (See [the specification](https://timsong-cpp.github.io/cppwp/n4659/dcl.link).) This means that we can look up the descriptor reliably by name when importing the library.

> Though if we decide we don't need to get that information to users and simply failing to instantiate the plugin is sufficient, couldn't you just return `nullptr` from `lmms_plugin_main`? You could even have a try/catch in `lmms_plugin_main` if you wanted the LV2 plugin's constructor to throw an exception upon failure, and just return `nullptr` in the catch statement.

I support this approach too - it's [what I did for VST3](https://github.com/DomClark/lmms/blob/e048c0f27afc100bedf4e727590f7ff2921cbc0c/plugins/Vst3Instrument/Vst3Instrument.cpp#L144-L156). It helps keeps the plugin API C-compatible, so would make it easier to use LMMS plugins from a host written in a different language in the future (not necessarily a goal, but it's nice to keep language concerns out of the API). As for how to report errors to the user, we need to consider how to do this from the core more generally, and I wouldn't worry about it for now.

**Comment by PhysSong** [comment]
@JohannesLorenz So do you want to keep this approach or switch to @messmerd's proposal?

**Comment by JohannesLorenz** [comment]
I think using `try/catch` in `lmms_plugin_main` and returning `nullptr` has two votes in favor. About `PluginIssue`: That class was marked to note that a plugin could not even be instantiated, so I am not sure if it would be a good use case. We can probably still do something like this later, should we find out that we need to categorize runtime issues.

File: plugins/Lv2Effect/Lv2Effect.cpp [hunk 1]
```diff
@@ -22,6 +22,7 @@
  *
  */
 
+#include <QDebug>
 #include "Lv2Effect.h"
```
Comment (DomClark) [inline plugins/Lv2Effect/Lv2Effect.cpp:26]: First inclusion in source file should be the corresponding header.

File: plugins/Lv2Effect/Lv2Effect.cpp [hunk 2]
```diff
@@ -109,8 +110,13 @@ extern "C"
...
-	auto eff = new Lv2Effect(_parent, static_cast<const KeyType*>(_data));
-	if (!eff->isValid()) { delete eff; eff = nullptr; }
+	Lv2Effect* eff;
+	try {
+		eff = new Lv2Effect(_parent, static_cast<const KeyType*>(_data));
+	} catch (const std::runtime_error& e) {
+		qCritical() << e.what();
+		eff = nullptr;
+	}
 	return eff;
```
Comment (DomClark) [inline plugins/Lv2Effect/Lv2Effect.cpp:120]: I think it would be simpler to return directly in each case, rather than using a local variable (which is forced to be declared without being initialised).
```suggestion
	try {
		return new Lv2Effect(_parent, static_cast<const KeyType*>(_data));
	} catch (const std::runtime_error& e) {
		qCritical() << e.what();
		return nullptr;
	}
```

File: plugins/Lv2Instrument/Lv2Instrument.cpp [hunk 3]
```diff
@@ -321,8 +313,13 @@ extern "C"
...
-	auto ins = new Lv2Instrument(static_cast<InstrumentTrack*>(_parent), static_cast<KeyType*>(_data));
-	if (!ins->isValid()) { delete ins; ins = nullptr; }
+	Lv2Instrument *ins;
+	try {
+		ins = new Lv2Instrument(static_cast<InstrumentTrack*>(_parent), static_cast<KeyType*>(_data));
+	} catch (const std::runtime_error& e) {
+		qCritical() << e.what();
+		ins = nullptr;
+	}
 	return ins;
```
Comment (DomClark) [inline plugins/Lv2Instrument/Lv2Instrument.cpp:323]: Same here.
```suggestion
	try {
		return new Lv2Instrument(static_cast<InstrumentTrack*>(_parent), static_cast<KeyType*>(_data));
	} catch (const std::runtime_error& e) {
		qCritical() << e.what();
		return nullptr;
	}
```

File: src/core/lv2/Lv2Proc.cpp [hunk 4]
```diff
@@ -476,16 +476,12 @@ void Lv2Proc::initPlugin()
...
-		lilv_instance_deactivate(m_instance);
-		lilv_instance_free(m_instance);
-		m_instance = nullptr;
+	lilv_instance_deactivate(m_instance);
+	lilv_instance_free(m_instance);
+	m_instance = nullptr;
 
-		m_features.clear();
+	m_features.clear();
 		m_options.clear();
```
Comment (DomClark) [inline src/core/lv2/Lv2Proc.cpp:484]: Indentation needs adjusting on this line too.

**Review by DomClark — APPROVED** [review]

File: plugins/Lv2Effect/Lv2FxControls.cpp [hunk 5]
```diff
@@ -38,11 +38,8 @@ Lv2FxControls::Lv2FxControls(class Lv2Effect *effect, const QString& uri) :
 	EffectControls(effect),
 	Lv2ControlBase(this, uri)
 {
-	if (isValid())
-	{
-		connect(Engine::audioEngine(), &AudioEngine::sampleRateChanged,
-			this, [this](){onSampleRateChanged();});
-	}
+	connect(Engine::audioEngine(), &AudioEngine::sampleRateChanged,
+		this, [this](){onSampleRateChanged();});
```
Comment (messmerd) [inline plugins/Lv2Effect/Lv2FxControls.cpp:42]:
```suggestion
	connect(Engine::audioEngine(), &AudioEngine::sampleRateChanged, this, &Lv2FxControls::onSampleRateChanged);
```
I think you can avoid using a lambda here

**Review by messmerd — APPROVED** [review]
