### PR TITLE
Fix Compressor zero divisions

### LINKED ISSUE #6886: Compressor - More fpe issues
### Bug Summary
The Native compressor has some default variable values that gives an arithmetic exception on debugging.

#### Steps to reproduce
On Linux
1 - Compile lmms with debug AND fpe flags set:
`cmake -DCMAKE_BUILD_TYPE=Debug -DWANT_DEBUG_FPE=ON`

2 - Start lmms in gdb
` gdb ./lmms`

3 - Add and open a Compressor.

4A - Turn the `Threshold` knob to 0.

```gdb
Thread 1 "lmms" received signal SIGFPE, Arithmetic exception.
0x00007fff64598704 in lmms::gui::CompressorControlDialog::redrawKnee (this=0x55555d1d5800) at /home/zonkmachine/builds/lmms/plugins/Compressor/CompressorControlDialog.cpp:502
502		float kneePoint2Y = (m_controls->m_effect->m_thresholdVal + (-m_controls->m_effect->m_thresholdVal * (actualRatio * (m_controls->m_effect->m_kneeVal / -m_controls->m_effect->m_thresholdVal))));
(gdb) bt full
#0  0x00007fff64598704 in lmms::gui::CompressorControlDialog::redrawKnee() (this=0x55555d1d5800) at /home/zonkmachine/builds/lmms/plugins/Compressor/CompressorControlDialog.cpp:502
        actualRatio = 0.555555582
        kneePoint1 = -6
        kneePoint2X = 6
        kneePoint2Y = 4.59163468e-41
        ratioPoint = -nan(0x7fd590)
```
4B - Turn the `Size` knob to 0.

```gdb
Thread 1 "lmms" received signal SIGFPE, Arithmetic exception.
0x00007fff65512829 in lmms::CompressorEffect::resizeRMS (this=0x7ffff2950080) at /home/zonkmachine/builds/lmms/plugins/Compressor/Compressor.cpp:180
180		m_rmsTimeConst = exp(-1.f / (m_compressorControls.m_rmsModel.value() * 0.001f * m_sampleRate));
```

@LostRobotMusic

### PR DESCRIPTION
**Pull request by LostRobotMusic**
Errors only occur with `-DCMAKE_BUILD_TYPE=Debug -DWANT_DEBUG_FPE=ON`
Fixes #6886

### CODE REVIEW

File: plugins/Compressor/Compressor.cpp [hunk 1]
```diff
@@ -177,7 +177,8 @@ void CompressorEffect::calcRange()
 
 void CompressorEffect::resizeRMS()
 {
-	m_rmsTimeConst = exp(-1.f / (m_compressorControls.m_rmsModel.value() * 0.001f * m_sampleRate));
+	const float rmsValue = m_compressorControls.m_rmsModel.value();
+	m_rmsTimeConst = (rmsValue != 0) ? exp(-1.f / (rmsValue * 0.001f * m_sampleRate)) : 0;
```
Comment (DomClark) [inline plugins/Compressor/Compressor.cpp:181]: It's generally advised to avoid strict equality comparisons with floating point numbers. In this case, negative numbers are undesirable too, so you could replace `!=` with `>`.

File: plugins/Compressor/CompressorControlDialog.cpp [hunk 2]
```diff
@@ -497,10 +497,12 @@ void CompressorControlDialog::redrawKnee()
...
 	// Calculate endpoints for the two straight lines
-	float kneePoint1 = m_controls->m_effect->m_thresholdVal - m_controls->m_effect->m_kneeVal;
-	float kneePoint2X = m_controls->m_effect->m_thresholdVal + m_controls->m_effect->m_kneeVal;
-	float kneePoint2Y = (m_controls->m_effect->m_thresholdVal + (-m_controls->m_effect->m_thresholdVal * (actualRatio * (m_controls->m_effect->m_kneeVal / -m_controls->m_effect->m_thresholdVal))));
-	float ratioPoint = m_controls->m_effect->m_thresholdVal + (-m_controls->m_effect->m_thresholdVal * actualRatio);
+	const float thresholdVal = m_controls->m_effect->m_thresholdVal;
+	const float kneeVal = m_controls->m_effect->m_kneeVal;
+	float kneePoint1 = thresholdVal - kneeVal;
+	float kneePoint2X = thresholdVal + kneeVal;
+	float kneePoint2Y = (thresholdVal != 0.f) ? (thresholdVal + (-thresholdVal * (actualRatio * (kneeVal / -thresholdVal)))) : 0.f;
```
Comment (DomClark) [inline plugins/Compressor/CompressorControlDialog.cpp:504]: Could you cancel `-thresholdVal` from the product in here to get `thresholdVal + actualRatio * kneeValue`? Then you don't need to check the threshold, and the expression will be continuous at zero threshold.

Comment (LostRobotMusic) [reply plugins/Compressor/CompressorControlDialog.cpp]: Good catch.  I thought something seemed odd about that code, but I didn't bother looking into it because I assumed me four years ago knew what he was doing.  But me four years ago never knew what he was doing.

**Review by DomClark — APPROVED** [review]

**Review by messmerd — APPROVED** [review]

**Review by zonkmachine — APPROVED** [review]
