### PR TITLE
SharedMemory: Make key optional, default to shorter UID on macOS

### LINKED ISSUE #7666: ZynAddSubFX won't open GUI on macOS
* ✅ Works: 1.2.2
* 🚫 Broken: nightly

The console shows the following, which suggests this may have been caused by some RemotePlugin refactoring.  Pinging @DomClark for some insight.

```
Failed to allocate shared audio buffer: SharedMemoryImpl: shm_open() failed: File name too long
RemotePlugin::DebugMessage: Failed to attach sync data: SharedMemoryImpl: shm_open() failed: No such file or directory
Remote plugin exit code:  1
```

This bug was discovered while testing #7252.

### PR DESCRIPTION
**Pull request by tresf**
Remote plugins use [QUuid](https://doc.qt.io/qt-5/quuid.html) key for a unique shared memory mapping (e.g. `67C8770B-44F1-410A-AB9A-F9B5446F13EE`) but this value is too long on macOS for `shm_get`: https://stackoverflow.com/a/38075686/3196753 and causes the UI for ZynAddSubFx to never open properly.

This PR proposes a change to create our own 128-bit/32-character unique ID "key" in `SharedMemory` .
* To simplify the implementation of it, starting with this PR, this key is generated directly inside `SharedMemory` (unless one's manually provided).  This simplifies calls to `create(...)`.
*  For macOS and other BSD flavors, I shorten this value to 30-characters to workaround the [`shm_get` limitation](https://stackoverflow.com/a/38075686/3196753).
* Windows had previously used a built-in [`Uuidgen`](https://learn.microsoft.com/en-us/windows/win32/rpc/generating-interface-uuids) -- provided by Qt.  Since this may offer benefits over rolling our own, I wanted to mention is specifically/invite comments about its removal.
* Added `size` and `size_bytes` getters. This required a modification to the MSVC implementation to query the shared memory size using [VirtualQuery](https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualquery).
 
Fixes #7666 

image

### CODE REVIEW

File: include/SharedMemory.h [hunk 1]
```diff
@@ -71,6 +75,26 @@ class SharedMemoryData
...
+		std::string key;
+		std::random_device rd;
+		std::mt19937 gen(rd()); // mersenne twister, seeded
+		std::uniform_int_distribution<> distrib(0, 15); // hex range (0-15)
+
+		for (int i = 0; i < length; i++) {
+			std::stringstream ss;
+			ss << std::hex << distrib(gen);
+			key += ss.str();
+		}
```
Comment (messmerd) [inline include/SharedMemory.h:93]:
```suggestion
		key.reserve(length);	
		for (int i = 0; i < length; i++) {
			key += "0123456789ABCDEF"[distrib(gen)];
		}
```
This is more efficient and will let you remove `<sstream>`.

**Review by messmerd — COMMENTED** [review]
Haven't tested it yet

File: include/SharedMemory.h [hunk 2]
```diff
@@ -71,6 +75,26 @@ class SharedMemoryData
 	void* m_ptr = nullptr;
 };
 
+	static inline std::string createKey() {
```
[the remark this answers is not in the document]
Comment (tresf) [reply include/SharedMemory.h:78]: Should it be? The namespace and inlining were chosen after seeking advice from a chatbot because my comprehension of C++ is poor.  I'll happily do what's recommended, I just need to know what's best in this scenario.

[the remark this answers is not in the document]
Comment (messmerd) [reply include/SharedMemory.h:78]: Yes, after thinking about it some more, it could actually be entirely in the .cpp file as an implementation detail if we added another constructor to `detail::SharedMemoryData` which doesn't take a key.

If you want, I could make the change if that'd be easier

[the remark this answers is not in the document]
Comment (tresf) [reply include/SharedMemory.h:77]: > Yes, after thinking about it some more, it could actually be entirely in the .cpp file as an implementation detail if we added another constructor to `detail::SharedMemoryData` which doesn't take a key.
> 
> If you want, I could make the change if that'd be easier

Good catch.  Yes, I'll take you up on that offer if you don't mind.  I understand exactly what you're saying but I think you will be much quicker.

File: include/SharedMemory.h [hunk 3]
```diff
@@ -71,6 +74,25 @@ class SharedMemoryData
...
+#if defined(LMMS_BUILD_APPLE) || defined(LMMS_BUILD_FREEBSD) || defined(LMMS_BUILD_OPENBSD)
+		constexpr int length = 30; // PSHMNAMLEN=31
```
Comment (tresf) [inline include/SharedMemory.h:79]: It may be desired by the project to just hard-code `30` here and skip the `#ifdef`, as a collision would be nearly impossible, however the comment may help other use of the class down the road.

Comment (messmerd) [reply include/SharedMemory.h:79]: How does this look for all OS's?
```cpp
// Max length (minus prepended '/') on macOS (PSHMNAMLEN=31)
constexpr int length = 30;
```

Comment (tresf) [reply include/SharedMemory.h:79]: Readable enough for me!  I thought that I had read somewhere that all BSD flavors had that limitation but I couldn't confirm this earlier and added them out of paranoia.  I think it's good!

**Comment by tresf** [comment]
> @tresf I'm pretty sure the change I made to the MSVC shared memory implementation should work, but if it doesn't, it will fail with a "SharedMemoryImpl: VirtualQuery() failed" message.

MSVC loaded Zyn for me before the refactor (tested with Prism 😈).  I'll test again tomorrow with the latest changes and report my findings.
