### PR TITLE
arpeggiator sorted mode fixed

### LINKED ISSUE #4491: Arpeggiator in Random and Sort mode does not randomize notes of a played chord
When using LMMS arpeggios in Sort mode, it isn't currently possible for it to randomly select notes in the played chord.  Random mode only randomizes the notes chosen in the selected chord type, not the notes of a chord plotted in Piano Roll.  Hopefully I explained this well enough for you all to understand what I'm talking about.

I am unsure whether this would be considered a bug fix or an enhancement, but I would love to see this in a future LMMS release!  I already talked with @zonkmachine about it, told me to open an issue about it because it may take some work to implement.

### LINKED ISSUE #6499: Arpeggiator - Wrong sequence with multiple notes and sort mode
### Bug Summary
Arpeggio sequence over more than one note and mode sort, comes out wrong.
(Chord: Octave, Direction 'Up', and Range 2 octaves)

Instead of going through the notes of the chord in one octave before advancing to the next octave, it loops over one note in the chord in different octaves before advancing to the next note.

In essence, manually entering a chord in the piano roll, and arpeggiating it over sort mode, should give you the same result as if you entered the same base note and selected the same chord in the arpeggiator chord menu. All other settings being equal.

The responsible line of code is here:
https://github.com/LMMS/lmms/blob/4821606465a5c46109f048466f84e55aeeb31d6e/src/core/InstrumentFunctions.cpp#L400

With this chord:
arpchord

I get this arpeggio:
arpget

But this is what I want and which is the behavior of other arpeggiators. Hardware synths, Logic, LV2 arpeggiators with Ardour:
arpwant

#### Steps to reproduce
Enter a chord in the piano roll. Dial in an arpeggio based around sort mode and chord: octave.
Demo: [arpsequence.mmp.zip](https://github.com/LMMS/lmms/files/9437854/arpsequence.mmp.zip)
Chord that arpeggiates wrong followed by explicit notes showing again how it's acting today and last the wanted result.

#### Version
Any version of lmms

### PR DESCRIPTION
**Pull request by szeli1**
closes #6499
closes #4491

with this change the arpeggiator with sorted mode enabled will cycle through all of the active (currently playing) note's chords in order without skipping notes or randomly playing other ones.

this works by combining all of the chord's keys in an array and then playing it back as one single larger chord (sorted as suggested).

### CODE REVIEW

**Comment by zonkmachine** [comment]
Hi! Testing this now (sorry for the long waiting time). Thank you so much for taking care of this issue! It seem to work really well but the arpeggiator has a lot of functions now so it's starting to get really finicky to test. While testing this PR I discovered a bug that I introduced with the 'Repeats' function. This has been fixed in https://github.com/LMMS/lmms/pull/7007 together with the original bug which that PR takes care of. I think it's better to merge that PR first and then rebase this PR so we can test this one some more with two less bugs to worry about. Are you OK with this?

**Comment by zonkmachine** [comment]
I'm currently running these changes on top from https://github.com/LMMS/lmms/pull/7007

```cpp
diff --git a/src/core/InstrumentFunctions.cpp b/src/core/InstrumentFunctions.cpp
index 0911d28a4..b1fa0902e 100644
--- a/src/core/InstrumentFunctions.cpp
+++ b/src/core/InstrumentFunctions.cpp
@@ -470,42 +470,25 @@ void InstrumentFunctionArpeggio::processNote( NotePlayHandle * _n )
 
                int cur_arp_idx = 0;
                // process according to arpeggio-direction...
-               if( dir == ArpDirection::Up )
+               if (dir == ArpDirection::Up || dir == ArpDirection::Down)
                {
                        cur_arp_idx = (cur_frame / arp_frames) % (range + sortOffset);
                }
-               else if( dir == ArpDirection::Down )
-               {
-                       cur_arp_idx = range + sortOffset - (cur_frame / arp_frames) %
-                                                               (range + sortOffset) - 1;
-               }
-               else if (dir == ArpDirection::UpAndDown && (range + sortOffset) > 1)
+               else if ((dir == ArpDirection::UpAndDown || dir == ArpDirection::DownAndUp) && (range + sortOffset) > 1)
                {
                        // imagine, we had to play the arp once up and then
                        // once down -> makes 2 * range possible notes...
                        // because we don't play the lower and upper notes
                        // twice, we have to subtract 2
-                       cur_arp_idx = (cur_frame / arp_frames) % ((range + sortOffset) * 2 - 2);
+                       cur_arp_idx = (cur_frame / arp_frames) % ((range + sortOffset) * 2 - (2 * static_cast<int>(m_arpRepeatsModel.value())));
                        // if greater than range, we have to play down...
                        // looks like the code for arp_dir==DOWN... :)
                        if (cur_arp_idx >= range + sortOffset)
                        {
                                cur_arp_idx = range + sortOffset - cur_arp_idx % (range + sortOffset - 1) - 1;
+                               cur_arp_idx = range + sortOffset - cur_arp_idx % (range + sortOffset - 1) - static_cast<int>(m_arpRepeatsModel.value());
                        }
                }
-               else if (dir == ArpDirection::DownAndUp && (range + sortOffset) > 1)
-               {
-                       // copied from ArpDirection::UpAndDown above
-                       cur_arp_idx = (cur_frame / arp_frames) % ((range + sortOffset) * 2 - 2);
-                       // if greater than range, we have to play down...
-                       // looks like the code for arp_dir==DOWN... :)
-                       if (cur_arp_idx >= range + sortOffset)
-                       {
-                               cur_arp_idx = range + sortOffset - cur_arp_idx % (range + sortOffset - 1) - 1;
-                       }
-                       // inverts direction
-                       cur_arp_idx = range + sortOffset - cur_arp_idx - 1;
-               }
                else if( dir == ArpDirection::Random )
                {
                        // just pick a random chord-index
@@ -522,6 +505,12 @@ void InstrumentFunctionArpeggio::processNote( NotePlayHandle * _n )
                        cur_arp_idx %= static_cast<int>((range + sortOffset) / m_arpRepeatsModel.value());
                }
 
+               // If ArpDirection::Down or ArpDirection::DownAndUp, invert the final range.
+               if (dir == ArpDirection::Down || dir == ArpDirection::DownAndUp)
+               {
+                       cur_arp_idx = static_cast<int>(range + sortOffset / m_arpRepeatsModel.value()) - cur_arp_idx - 1;
+               }
+
                // now calculate final key for our arp-note
                int sub_note_key = 0;
                if (static_cast<ArpMode>(m_arpModeModel.value()) != ArpMode::Sort)
(END)

```

**Comment by szeli1** [comment]
> Are you OK with this?

What does this mean for me? If it isn't too difficult, then sure! (I do not have this branch locally currently)

**Comment by zonkmachine** [comment]
I suspect it's a simple rebase. I can push the changes to your branch if you like. 
Can you rebase this PR on latest master?

**Comment by szeli1** [comment]
Do what you think is the best solution here. I will try to rebase soon.

**Comment by zonkmachine** [comment]
OK - The plan is:
1. you rebase this PR
2. We merge https://github.com/LMMS/lmms/pull/7007
3. This PR is rebased once more on master

**Comment by szeli1** [comment]
I think i have rebased. You can merge #7007 if I'm correct.

**Comment by zonkmachine** [comment]
> I think i have rebased. You can merge #7007 if I'm correct.

That looks correct. I'll allow some time for feedback on that PR first. A day or two.

**Comment by zonkmachine** [comment]
> This PR is rebased once more on master

I went with merging just my changes from https://github.com/LMMS/lmms/pull/7007. This keeps your original commits so we can more easily test for regressions.

File: src/core/InstrumentFunctions.cpp [hunk 1]
```diff
@@ -474,37 +474,19 @@ void InstrumentFunctionArpeggio::processNote( NotePlayHandle * _n )
...
-				cur_arp_idx = range + sortOffset - cur_arp_idx % (range + sortOffset - 1) - 1;
-			}
-		}
-		else if (dir == ArpDirection::DownAndUp && (range + sortOffset) > 1)
-		{
-			// copied from ArpDirection::UpAndDown above
-			cur_arp_idx = (cur_frame / arp_frames) % ((range + sortOffset) * 2 - 2);
+			cur_arp_idx = (cur_frame / arp_frames) % ((range + sortOffset) * 2 - (2 * static_cast<int>(m_arpRepeatsModel.value())));
 			// if greater than range, we have to play down...
 			// looks like the code for arp_dir==DOWN... :)
```
Comment (zonkmachine) [inline src/core/InstrumentFunctions.cpp:485]: // looks like the code for arp_dir==DOWN... :)

Which was removed so this line should be removed.

Comment (szeli1) [reply src/core/InstrumentFunctions.cpp:485]: I will fix this in a few days. Sorry for the waiting.

**Comment by zonkmachine** [comment]
It looks like this could be a fix also for issue https://github.com/LMMS/lmms/issues/2606. At least the demo project in the original post is fixed.

**Comment by szeli1** [comment]
I have rebased, and changed your changes. This should be tested because unfortunately I do not remember my changes in great detail. There seems to be a display bug when sorted mode is enabled and multiple notes are pressed. This bug makes the pressed notes light up incorrectly (while not being played).

File: src/core/InstrumentFunctions.cpp [hunk 2]
```diff
@@ -435,26 +472,27 @@ void InstrumentFunctionArpeggio::processNote( NotePlayHandle * _n )
 		// process according to arpeggio-direction...
 		if (dir == ArpDirection::Up || dir == ArpDirection::Down)
 		{
-			cur_arp_idx = ( cur_frame / arp_frames ) % range;
+			cur_arp_idx = (cur_frame / arp_frames) % (range + sortOffset);
```
Comment (zonkmachine) [inline src/core/InstrumentFunctions.cpp:475]: `range + sortOffset` is the same as `total_range`. I think you can skip `sortOffset` alltogether.

Comment (szeli1) [reply src/core/InstrumentFunctions.cpp:475]: It is only total_range when sorting.

Comment (zonkmachine) [reply src/core/InstrumentFunctions.cpp:475]: Ah, got it!

**Comment by zonkmachine** [comment]
In this test project from issue https://github.com/LMMS/lmms/issues/2606 you can see the problems with Sync mode over more than one note. It has two identical arpeggios but one inverted so the sound cancels out unless one of the tracks skips a note. The last 6th of the sequence is the one with Sync mode over two notes. Turn up the tempo and enjoy!
[arpnotesilence-01.mmp.zip](https://github.com/LMMS/lmms/files/5682517/arpnotesilence-01.mmp.zip)

**Comment by szeli1** [comment]
What are you trying to say? Would you rather me fix that issue as well? And the display issue I talked about? If not, I think this is ready for merge.

**Comment by zonkmachine** [comment]
> What are you trying to say? Would you rather me fix that issue as well?

No, you're welcome to, but I mentioned above that it looks like at least one of the demo projects was fixed by this commit so there is a connection. I'm a bit tired now so I'm happy to stick with just this issue.

I've tested it with a bunch of arpeggios and they are almost all possible to compute ahead what the result will be. Almost all. This doesn't seem to be true for when you have a note that is looped before it's end so that it will overlap itself. I don't think it's reasonable to cover everything and this is an edge case. Just seeing the same result over and over again is fine.
Example: [arpdowncycle-02.mmp.txt](https://github.com/LMMS/lmms/files/14968717/arpdowncycle-02.mmp.txt)

**Review by zonkmachine — APPROVED** [review]

**Comment by zonkmachine** [comment]
Fixes https://github.com/LMMS/lmms/issues/4491

File: src/core/InstrumentFunctions.cpp [hunk 3]
```diff
@@ -395,15 +399,48 @@ void InstrumentFunctionArpeggio::processNote( NotePlayHandle * _n )
...
+			if (minIndex != _n->index())
+			{
+				break;
+			}
+
+			// sorting:
+			std::sort(noteKeysArray.begin(), noteKeysArray.end(), [](int a, int b)
+			{
+				return a < b;
+			});
```
Comment (Veratil) [inline src/core/InstrumentFunctions.cpp:439]: Is it possible to just use `std::less`?
```suggestion
			std::sort(noteKeysArray.begin(), noteKeysArray.end(), std::less{});
```

Comment (szeli1) [reply src/core/InstrumentFunctions.cpp]: Replaced lambda with std::less.

File: src/core/InstrumentFunctions.cpp [hunk 4]
```diff
@@ -464,18 +499,33 @@ void InstrumentFunctionArpeggio::processNote( NotePlayHandle * _n )
...
+		int sub_note_key = 0;
+		if (static_cast<ArpMode>(m_arpModeModel.value()) != ArpMode::Sort)
+		{
+			sub_note_key = base_note_key + (cur_arp_idx / cur_chord_size) *
 							KeysPerOctave + chord_table.chords()[selected_arp][cur_arp_idx % cur_chord_size];
+		}
+		else
+		{
+			// if we are sorting, we already have the base note key and the chord key
+			sub_note_key = noteKeysArray[cur_arp_idx % total_chord_size] + (cur_arp_idx / total_chord_size) *
```
Comment (Veratil) [inline src/core/InstrumentFunctions.cpp:521]: Compiler is probably smart and will get the quotient and remainder at the same time, but just in case we may want to use `std::div` and for `cur_arp_idx` and `total_chord_size`? Similar for above block with `cur_chord_size` denominator.

File: src/core/InstrumentFunctions.cpp [hunk 5]
```diff
@@ -435,26 +469,27 @@ void InstrumentFunctionArpeggio::processNote( NotePlayHandle * _n )
...
 			{
-				cur_arp_idx = range - cur_arp_idx % (range - 1) - static_cast<int>(m_arpRepeatsModel.value());
+				cur_arp_idx = (range + sortOffset) - cur_arp_idx % (range + sortOffset - 1) - static_cast<int>(m_arpRepeatsModel.value());
 			}
 		}
 		else if( dir == ArpDirection::Random )
 		{
 			// just pick a random chord-index
-			cur_arp_idx = (int)( range * ( (float) rand() / (float) RAND_MAX ) );
+			cur_arp_idx = (int)((range + sortOffset) * ((float) rand() / (float) RAND_MAX));
```
Comment (Veratil) [inline src/core/InstrumentFunctions.cpp:492]: Convert to static_cast
```suggestion
			cur_arp_idx = static_cast<int>((range + sortOffset) * (static_cast<float>(rand()) / static_cast<float>(RAND_MAX)));
```

**Review by Veratil — COMMENTED** [review]
The only other thing is perhaps it would be better to pull out all the `range + sortOffset` into a new variable so it's not repeated over and over and over and over. :)

File: src/core/InstrumentFunctions.cpp (hunk 4 above)
Comment (szeli1) [reply src/core/InstrumentFunctions.cpp:521]: I think I do not fully understand this. Could you please describe it in an other way?

Comment (Veratil) [reply src/core/InstrumentFunctions.cpp:521]: Using `std::div` we pull the `%` and `/` operations out. Can make it easier to read. This isn't always needed since the operations are nearby and the compiler should be able to automatically do this for us, but it doesn't hurt readability and standardization.
```cpp
auto result = std::div(cur_arp_idx, total_chord_size);
sub_note_key = noteKeysArray[result.rem] + result.quot * ...;
```
Alternatively it could be done just by pulling the operations out:
```cpp
auto noteIndex = cur_arp_idx % total_chord_size;
auto offset = cur_arp_idx / total_chord_size;
sub_note_key = noteKeysArray[noteIndex] + offset * ...;
```

Comment (szeli1) [reply src/core/InstrumentFunctions.cpp:521]: Thanks for the explanation. I have implemented this.

**Comment by zonkmachine** [comment]
@szeli1 There are some good points made in the original issue that you may want to read through. https://github.com/LMMS/lmms/issues/6499#issuecomment-2076103825

**Comment by szeli1** [comment]
I will not redo this now, but later. I also would like to add a feature that makes the instrument envelope apply to the arp notes like they were a whole note (using the base note's length).

**Comment by zonkmachine** [comment]
> I will not redo this now, but later.

You mean the different orders of arpeggio mentioned in #6499? Merge now and refactor later?

**Comment by szeli1** [comment]
Yes. I do not want to merge yet. I can do the changes sooner if you would like that.

**Comment by szeli1** [comment]
Implemented changes, the vector can not be moved elsewhere since it can not be a member because of multithreading.
Using mutexes did not solve the issue, they just locked the threads for some reason.
Did not push jet because the above mentioned envelope feature.

**Comment by szeli1** [comment]
> Implemented changes, the vector can not be moved elsewhere since it can not be a member because of multithreading. Using mutexes did not solve the issue, they just locked the threads for some reason. Did not push jet because the above mentioned envelope feature.

**Comment by szeli1** [comment]
> I also would like to add a feature that makes the instrument envelope apply to the arp notes like they were a whole note (using the base note's length).

Can I add this to this pr?

**Comment by zonkmachine** [comment]
> Can I add this to this pr?

If you want to do that change here I think we're fine with it. I usually fail to stick with just one change when I'm fiddling with the arpeggiator myself. ;)

**Comment by szeli1** [comment]
Order of the sorted notes in the arpeggio is now "octave-arp-piano". The implementation can be optimized by using binary search, but in my view that would be too complex without much performance improvements.

Added new check box in the envelope settings that makes the envelope use the parent note instead of the sub note.
This will allow the user to make the envelope apply over multiple arpeggio notes instead of each note separately.

Please check spelling.

**Comment by zonkmachine** [comment]
This now seem to have issues. For instance. If I arpeggiate over multiple notes and one octave with sort, up is now down and the other way around. Please test this some more.

**Comment by szeli1** [comment]
Fixed the sorting algorithm and added more comments.
The arp settings should now behave like with the old sorting order.

**Comment by zonkmachine** [comment]
> Added new check box in the envelope settings that makes the envelope use the parent note instead of the sub note. This will allow the user to make the envelope apply over multiple arpeggio notes instead of each note separately.


Interesting, I see what you're trying to do but I don't think this is ready for merge. Some quick observations.
* It's a bit hard to dial in an envelope that works both for the individual arpeggio notes and for the whole arpeggio, because they use the same envelope (this is my understanding anyway).
* I think I've seen similar implementations in synth plugins but they would let the arpeggio continue over the release.
* Also, in this test project you see that there is a bump in volume on key off where this is not the case with the new option disabled. 
[arpenvelope.mmp.txt](https://github.com/LMMS/lmms/files/15313310/arpenvelope.mmp.txt)

I think the envelope part is probably better to bud off to it's own PR.

**Comment by szeli1** [comment]
> envelope part is probably better to bud off to it's own PR.

I reverted the changes. Looking back on this, I completely agree with you.

**Comment by zonkmachine** [comment]
I've tested it again but it doesn't seem to behave properly. The current implementation seem to be octave-piano-arp, referring to @DomClark from his analysis of the arpeggiator in #6499.

Borrowed from https://github.com/LMMS/lmms/issues/6499#issuecomment-2076103825
image

Here are some different ways the notes (C-F-A) could be arpeggiated on.
1. The way LMMS does it today (piano-octave-arp)
2. How it currently works on this PR (octave-piano-arp)
3. The behavior I believe we agreed on (octave-arp-piano)
4. The original implementation in this PR (octave-sort(arp-piano))

Project used in testing: [arpsorttest.mmp.txt](https://github.com/user-attachments/files/15570100/arpsorttest.mmp.txt)

**Comment by szeli1** [comment]
Fixed, I really hope the arp is working as intended now.

File: src/core/InstrumentFunctions.cpp [hunk 6]
```diff
@@ -435,26 +508,27 @@ void InstrumentFunctionArpeggio::processNote( NotePlayHandle * _n )
 		// process according to arpeggio-direction...
 		if (dir == ArpDirection::Up || dir == ArpDirection::Down)
 		{
-			cur_arp_idx = ( cur_frame / arp_frames ) % range;
+			cur_arp_idx = (cur_frame / arp_frames) % offsetRange;
 		}
-		else if ((dir == ArpDirection::UpAndDown || dir == ArpDirection::DownAndUp) && range > 1)
+		else if ((dir == ArpDirection::UpAndDown || dir == ArpDirection::DownAndUp) &&
+			offsetRange > 1)
```
Comment (zonkmachine) [inline src/core/InstrumentFunctions.cpp:514]: I'd keep this on the same line.

**Review by zonkmachine — APPROVED** [review]
Looks great and tests fine. I'm approving this and keep testing it ahead of the final word from @DomClark

**Review by DomClark — COMMENTED** [review]
I think this PR can be simplified a bit. Firstly, I would introduce the variable `const auto arpMode = static_cast<ArpMode>(m_arpModeModel.value());`, to avoid repeating that expression every time you want to check the mode. Then, I would do the following:
* The `notMinIndex` bits can be replaced with an early return. I would check `arpType == ArpMode::Sort && _n != cnphv.first()` just before the declaration of `chord_table`, and return if it's true. I think this is a more obvious (and a bit more efficient) way to ensure only the first note drives the sorted arpeggio processing.
* Rather than introducing `offsetRange`, and replacing `range` with it, I would put the appropriate value into `range` in the first place. I'd rename the original `range` to `singleNoteRange` (or something like that), and then define `const auto range = arpType == ArpMode::Sort ? singleNoteRange * cnphv.size() : singleNoteRange;`. Then `total_range` can be removed too. This will simplify the diff a bit, and is a bit clearer as a variable name (I'm not sure what the "offset" refers to in "offsetRange").
* You can use a modulo operation to find which step of the chord you're at, in the same way you do to find which octave you're in. Then you don't need to build a list of notes in a separate vector, and can just sort `cnphv` in-place. The note computation will end up looking something like this:
  ```cpp
  const auto octaveDiv = std::div(cur_arp_idx, total_chord_size);
  const auto octave = octaveDiv.quot;
  const auto arpDiv = std::div(octaveDiv.rem, cnphv.size());
  const auto arpIndex = arpDiv.quot;
  const auto pianoRollIndex = arpDiv.rem;
  sub_note_key = cnphv[pianoRollIndex]->key()
  	+ chord_table.chords()[selected_arp][arpIndex]
  	+ octave * KeysPerOctave;
  ```
  See how the octave-arp-piano order becomes obvious now. The octave is the first quotient, the arp index the second, and the piano roll index the final remainder.

**Comment by szeli1** [comment]
> * You can use a modulo operation to find which step of the chord you're at

Smart idea, I didn't think about that.
Implemented the changes that you suggested.

**Review by DomClark — APPROVED** [review]
Code looks good to me, although I haven't tested it myself.

**Comment by zonkmachine** [comment]
On the connection with #2606 (Race condition in arpeggio processing). Initially it looked fixed but this was just with the simple test file provided and I couldn't replicate the fix. That issue may have been more intermittent than I remember. I think this PR should be merged and #2606 be kept open.

**Comment by zonkmachine** [comment]
@szeli1 Thank you for coding this, and for your patience in the review. Top notch work!
@DomClark Thanks for bringing clarity to the issue.
 @Veratil Thank you for reviewing.

This is a great step for the arpeggiator and for lmms-1.3
The arpeggiator now can be played via a keyboard live or played back from the piano
roll and it will work like any other 'arp' out there. With some extra cherries on top and
obviously a bug or two but the biggest glitches, in my opinion, have been taken care of.
