### PR TITLE
Fix UI freeze when zooming in on long samples

### LINKED ISSUE #7249: UI freezes when zooming to much in the song editor when there is a long sample track
### System Information

Debian 12 - gcc 12.2.0 - QT5 5.15.8

### LMMS Version(s)

LMMS 1.3.0-alpha.1.591+gb71d4f2aa

### Most Recent Working Version

9ca9143f5b26ae0e0ab54dcecf5c81a3d4549d05

### Bug Summary

Hi,

With a long sample track zooming-in too much freezes the UI.

After the sample is loaded (but before it freezes I have the following message):

    qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 21390, resource id: 10657754, major code: 40 (TranslateCoords), minor code: 0
    
LMMS does not crash and I see two processes running at nearly 100% but the UI doesn’t respond anymore. If it happens during a playback the playback continues.

### Expected Behaviour

UI not to freeze

### Steps To Reproduce

Empty project.
Add sample track in the song editor with a quite long audio. In my case a mono 24bit/96kHz 00:35:03.43 long FLAC file (518Mo)
Zoom-in and zoom-out few times in the song editor (most of the times it happens when zooming-in too much)

### PR DESCRIPTION
**Pull request by khoidauminh**
In the first loop of the function, `resolution` (float) gets added to the loop index. On extremely large indices this operation fails, resulting in an infinite loop.

Solution is to declare an `int` version of `resolution` for loop incrementing.

Fixes #7249

### CODE REVIEW

File: src/gui/SampleWaveform.cpp [hunk 1]
```diff
@@ -53,7 +54,7 @@ void SampleWaveform::visualize(Parameters parameters, QPainter& painter, const Q
 
 	int pixelIndex = 0;
 
-	for (int i = 0; i < maxFrames; i += resolution)
+	for (int i = 0; i < maxFrames; i += resolutionInt)
```
Comment (Rossmaxx) [inline src/gui/SampleWaveform.cpp:57]: Would it make sense to cast it directly inside the loop argument instead of introducing a variable?

Comment (khoidauminh) [reply src/gui/SampleWaveform.cpp:57]: I wasn't sure whether the cast would be done over and over again or optimized into a one-time conversion, so I decided to make it a variable outside.

Comment (Rossmaxx) [reply src/gui/SampleWaveform.cpp:57]: It will be done only once from what I know. Would anyone confirm this?

Comment (khoidauminh) [reply src/gui/SampleWaveform.cpp:57]: Compared the 2 ways and the performance difference is hardly noticeable. I'll go ahead and move the cast into the loop

Comment (zonkmachine) [reply src/gui/SampleWaveform.cpp]: > It will be done only once from what I know. Would anyone confirm this?

Not sure but I think that depends on the level of optimization. I don't think it matters that much since it's not executing unless you poke the gui and resize something that forces a recompute of the wave.

**Review by zonkmachine — APPROVED** [review]
Tested, issue fixed! Looks fine to me.

**Review by Rossmaxx — APPROVED** [review]
LGTM.

**Review by DomClark — APPROVED** [review]
