### PR TITLE
Display flats in Piano Roll's keys dropdown

### LINKED ISSUE #6862: Key Display Doesn't List "Correct" Keys
### Bug Summary

The Key display options are weird and list keys which don't really normally occur in normal music theory. 

image

As visible in the above screenshot, I can select my key display to be "A# minor" which is more accurately reflected as Bb minor because Bb minor doesn't include "B Sharp" (C) as the second degree in it's scale. Technically, it's the same note, but this key is nearly universally expressed as Bb due to this oddity. The same issue occurs with "D#" as D#'s second degree would be "E#", which is F. If you express these as Bb and Eb, then the second degrees are correctly expressed as C and F respectively.

#### Steps to reproduce

Open Key selection dropdown in the Piano Roll 

#### Expected behavior

There are certain keys where sharp is the correct expression, so maybe the best way is to simply list all keys (with all sharps and flats) and let the user pick the one which best fits their mode.

#### Actual behavior

There are unusual/invalid keys displayed.

#### Screenshot

See above

#### Affected LMMS versions

1.3.0-alpha.1.354+ge1d3ecb18
#### Logs
```NA```

### PR DESCRIPTION
**Pull request by mvoorhes**
This was an attempt to fix this issue #6862 where the user noted that there aren't any flats listed in the list of keys in the piano roll. I wasn't really sure how to address their concerns without changing a big chunk of the code, so what I did was add the flats alongside the sharps in the array. Here is what the dropdown menu for the keys looks like now.

Screenshot 2023-09-13 at 3 05 42 PM

~~I also made a very tiny change where I added a space to an if statement to make it more consistent with the rest of the if statements in the file.~~ Reverted this as it wasn't relevant to this issue.

UPDATE: Added space in between sharps and flats to make dropdown menu look a little nicer.

### CODE REVIEW

File: src/gui/editors/PianoRoll.cpp [hunk 1]
```diff
@@ -1687,7 +1687,7 @@ void PianoRoll::mousePressEvent(QMouseEvent * me )
 		m_moveStartY = me->y();
 	}
 
-	if(me->button() == Qt::LeftButton &&
+	if( me->button() == Qt::LeftButton &&
```
Comment (sakertooth) [inline src/gui/editors/PianoRoll.cpp:1690]: We do infact have our own [Coding Conventions](https://github.com/LMMS/lmms/wiki/Coding-Conventions), and so we try to be consistent with that rather than the existing codebase if we were to make changes. We would do something like this instead.
```suggestion
if (me->button() == Qt::LeftButton &&
```

Comment (Veratil) [inline src/gui/editors/PianoRoll.cpp:1690]: Undo this change since it's not related to the PR please :)

**Review by sakertooth — APPROVED** [review]
Tested the characters and they appear fine. I'm not too sure if they wanted it to be an option to display sharps or flats exclusively, but I see no major problem here. Displaying them exclusively would prove to be less simple, and it may not be necessary/wanted.

**Comment by Veratil** [comment]
Please make sure that piano key labels are fine as well.

**Comment by mvoorhes** [comment]
@Veratil  Is this what you're referring too?

Screenshot 2023-09-13 at 6 36 45 PM

**Comment by Veratil** [comment]
> @Veratil Is this what you're referring too?

Yes. Those notes labels are pulled from the same note array.
https://github.com/LMMS/lmms/blob/master/src/gui/editors/PianoRoll.cpp#L1055

Just want to make sure they still look okay through the whole piano.

**Comment by zonkmachine** [comment]
> Just want to make sure they still look okay through the whole piano.

They do. In the case of the black keys the note labels are only shown on longer notes (or larger zoom levels) where there's place for the whole label so there is a difference in this PR between black and white keys. I don't think this is a problem. It looks good and it's a most reasonable fix.

**Review by zonkmachine — APPROVED** [review]

**Review by Veratil — APPROVED** [review]

**Comment by g4vr0che** [comment]
> Tested the characters and they appear fine. I'm not too sure if they wanted it to be an option to display sharps or flats exclusively, but I see no major problem here. Displaying them exclusively would prove to be less simple, and it may not be necessary/wanted.

I think this should do what I was thinking, yeah. From a technical music theory perspective, A# and Bb are different keys (they're "spelled" differently) but as that really only affects sheet notation this should be fine; the actual tones are the same. It mostly affects how one "thinks" about the key, and so if the display lists Bb (even if it's next to A#) then this should accomplish that just fine.

**Comment by zonkmachine** [comment]
@g4vr0che Forgot to tag you for review. Next time...

**Comment by DomClark** [comment]
I like that flats use the appropriate Unicode character U+266D "MUSIC FLAT SIGN", but this is now inconsistent with sharp signs, which still use U+0023 "NUMBER SIGN". It would be great if those could be updated to use U+266F "MUSIC SHARP SIGN".
