### PR TITLE
Lv2Proc: Delay setting worker iface (Fixes #6946)

### LINKED ISSUE #6946: Lv2 worker - Segmentation fault
These plugins were tested and known to work during the work with [Lv2-worker ](https://github.com/LMMS/lmms/pull/6484#issuecomment-1214443782) but prior to merge the commits were cleaned up and this may have been when something broke and they will no longer load.

[amsynth](http://code.google.com/p/amsynth/amsynth)
[Black Pearl Drumkit](http://gareus.org/oss/lv2/avldrums#BlackPearl)
[Red Zeppelin Drumkit](http://gareus.org/oss/lv2/avldrums#RedZeppelin)
[setBfree DSP Tonewheel Organ](https://x42-plugins.com/x42/setBfree)

The backtraces are pretty much identical. Included is the one for amsynth
#### Thread 38 "lmms::Instrumen" received signal SIGSEGV, Segmentation fault.
<details>
  <summary>Click to expand</summary>
<pre>
Thread 38 "lmms::Instrumen" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffea7fc640 (LWP 5692)]
0x00005555558e3beb in lilv_instance_get_extension_data (instance=0x0, uri=0x555555ab2eb0 "http://lv2plug.in/ns/ext/worker#interface") at /usr/include/lilv-0/lilv/lilv.h:1974
1974	  if (instance->lv2_descriptor->extension_data) {
(gdb) bt full
#0  0x00005555558e3beb in lilv_instance_get_extension_data(LilvInstance const*, char const*) (instance=0x0, uri=0x555555ab2eb0 "http://lv2plug.in/ns/ext/worker#interface")
    at /usr/include/lilv-0/lilv/lilv.h:1974
#1  0x00005555558e5ba7 in lmms::Lv2Proc::initPluginSpecificFeatures() (this=0x7fffd4003f80) at /home/zonkmachine/builds/lmms/src/core/lv2/Lv2Proc.cpp:538
        iface = 0x7fffd4039f60
        threaded = false
        mgr = 0x55555687be80
#2  0x00005555558e5672 in lmms::Lv2Proc::initPlugin() (this=0x7fffd4003f80) at /home/zonkmachine/builds/lmms/src/core/lv2/Lv2Proc.cpp:441
        __PRETTY_FUNCTION__ = "void lmms::Lv2Proc::initPlugin()"
#3  0x00005555558e4701 in lmms::Lv2Proc::Lv2Proc(LilvPluginImpl const*, lmms::Model*) (this=0x7fffd4003f80, plugin=0x555556ad0b60, parent=0x7fff78130080)
    at /home/zonkmachine/builds/lmms/src/core/lv2/Lv2Proc.cpp:200
#4  0x00005555558dc205 in std::make_unique<lmms::Lv2Proc, LilvPluginImpl const*&, lmms::Model*&>(LilvPluginImpl const*&, lmms::Model*&) () at /usr/include/c++/11/bits/unique_ptr.h:962
#5  0x00005555558db23f in lmms::Lv2ControlBase::init(lmms::Model*) (this=0x7fff781300e8, meAsModel=0x7fff78130080) at /home/zonkmachine/builds/lmms/src/core/lv2/Lv2ControlBase.cpp:79
        newOne = std::unique_ptr<lmms::Lv2Proc> = {get() = 0x7fffd4003ed0}
        channelsLeft = 2
        __PRETTY_FUNCTION__ = "void lmms::Lv2ControlBase::init(lmms::Model*)"
#6  0x00005555558db0ad in lmms::Lv2ControlBase::Lv2ControlBase(lmms::Model*, QString const&) (this=0x7fff781300e8, that=0x7fff78130080, uri=...)
    at /home/zonkmachine/builds/lmms/src/core/lv2/Lv2ControlBase.cpp:57
#7  0x00007fff79a21cbd in lmms::Lv2Instrument::Lv2Instrument(lmms::InstrumentTrack*, lmms::Plugin::Descriptor::SubPluginFeatures::Key*)
    (this=0x7fff78130080, instrumentTrackArg=0x7ffff27eba80, key=0x7fffea7fbbd0) at /home/zonkmachine/builds/lmms/plugins/Lv2Instrument/Lv2Instrument.cpp:77
#8  0x00007fff79a22b0e in lmms::lmms_plugin_main(lmms::Model*, void*) (_parent=0x7ffff27eba80, _data=0x7fffea7fbbd0) at /home/zonkmachine/builds/lmms/plugins/Lv2Instrument/Lv2Instrument.cpp:315
        ins = 0x22866ad1e3804400
#9  0x0000555555881df1 in lmms::Plugin::instantiate(QString const&, lmms::Model*, void*) (pluginName=..., parent=0x7ffff27eba80, data=0x7fffea7fbbd0) at /home/zonkmachine/builds/lmms/src/core/Plugin.cpp:232
        instantiationHook = 0x7fff79a22ad7 <lmms::lmms_plugin_main(lmms::Model*, void*)>

                  pi = @0x7fffea7fbb50: {file = {d_ptr = {d = 0x55555c00d7a0}}, library = std::shared_ptr<QLibrary> (use count 3, weak count 0) = {get() = 0x55555c0638b0}, descriptor = 0x7fff79a2e700 <lv2instrument_plugin_descriptor>}
        inst = 0x55555582b620 <QMap<QString, QString>::QMap(QMap<QString, QString> const&)+36>
#10 0x0000555555881aa2 in lmms::Plugin::instantiateWithKey(QString const&, lmms::Model*, lmms::Plugin::Descriptor::SubPluginFeatures::Key const*, bool)
    (pluginName=..., parent=0x7ffff27eba80, key=0x0, keyFromDnd=true) at /home/zonkmachine/builds/lmms/src/core/Plugin.cpp:198
        keyCopy = {desc = 0x7fff79a2e700 <lv2instrument_plugin_descriptor>, name = {d = 0x55555c079960}, attributes = {d = 0x7fffd4001330}}
        keyPtr = 0x55555c06ad10

                  pi = @0x7fffea7fbbf0: {file = {d_ptr = {d = 0x55555c00d7a0}}, library = std::shared_ptr<QLibrary> (use count 3, weak count 0) = {get() = 0x55555c0638b0}, descriptor = 0x7fff79a2e700 <lv2instrument_plugin_descriptor>}
#11 0x000055555584b75f in lmms::Instrument::instantiate(QString const&, lmms::InstrumentTrack*, lmms::Plugin::Descriptor::SubPluginFeatures::Key const*, bool)
    (_plugin_name=..., _instrument_track=0x7ffff27eba80, key=0x0, keyFromDnd=true) at /home/zonkmachine/builds/lmms/src/core/Instrument.cpp:74
        p = 0x5555558b4396 <lmms::Track::lock()+34>
#12 0x0000555555a4679a in lmms::InstrumentTrack::loadInstrument(QString const&, lmms::Plugin::Descriptor::SubPluginFeatures::Key const*, bool) (this=0x7ffff27eba80, _plugin_name=..., key=0x0, keyFromDnd=true)
    at /home/zonkmachine/builds/lmms/src/tracks/InstrumentTrack.cpp:1048
#13 0x00005555559d2f30 in lmms::InstrumentLoaderThread::run() (this=0x55555d1177f0) at /home/zonkmachine/builds/lmms/src/gui/editors/TrackContainerView.cpp:66
        i = 0x0
        parent = 0x22866ad1e3804400
#14 0x00007ffff6423ca1 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff5e90ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>

                      unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737488338144, 3268165398512743456, 140737127630400, 11, 140737319077840, 140737488338496, -3268188490322201568, -3268152287426431968}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
#16 0x00007ffff5f22a40 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb)
</pre>
</details>

### PR DESCRIPTION
**Pull request by JohannesLorenz**
This delays passing the `LV2_Worker_Interface` to the `Lv2Worker` class,
because prior to the patch, the instance, which provides the interface,
has not been initialized yet, which resulted in a segfault.

### CODE REVIEW

File: src/core/lv2/Lv2Proc.cpp [hunk 1]
```diff
@@ -442,11 +442,16 @@ void Lv2Proc::initPlugin()
 
 	if (m_instance)
 	{
-		if(m_worker) {
+		const auto iface = static_cast<const LV2_Worker_Interface*>(
+			lilv_instance_get_extension_data(m_instance, LV2_WORKER__interface));
+		if(iface) {
```
Comment (zonkmachine) [inline src/core/lv2/Lv2Proc.cpp:447]:
```cpp
if (
```

**Review by zonkmachine — APPROVED** [review]
Based on testing. Approved. First some of the LV2 plugins wouldn't load and now they do.

File: src/core/lv2/Lv2Worker.cpp [hunk 2]
```diff
@@ -91,6 +88,20 @@ Lv2Worker::Lv2Worker(const LV2_Worker_Interface* iface,
...
 
 
+void Lv2Worker::setHandle(LV2_Handle handle) { m_handle = handle; }
+
+
+
+
+void Lv2Worker::setIface(const LV2_Worker_Interface* iface)
+{
+	assert (iface);
```
Comment (messmerd) [inline src/core/lv2/Lv2Worker.cpp:98]:
```suggestion
	assert(iface);
```
style

File: include/Lv2Worker.h [hunk 3]
```diff
@@ -47,9 +47,10 @@ class Lv2Worker
 {
 public:
 	// CTOR/DTOR/feature access
-	Lv2Worker(const LV2_Worker_Interface* iface, Semaphore* common_work_lock, bool threaded);
+	Lv2Worker(Semaphore* common_work_lock, bool threaded);
 	~Lv2Worker();
-	void setHandle(LV2_Handle handle) { m_handle = handle; }
+	void setHandle(LV2_Handle handle);
+	void setIface(const LV2_Worker_Interface* iface);
```
Comment (messmerd) [inline include/Lv2Worker.h:53]: Maybe `setInterface` would be a better name? That's what the LV2 API calls it and "iface" is not a very common abbreviation from what I've seen.

**Comment by JohannesLorenz** [comment]
Thanks! Two reviews passed, testing successful. Also, this PR is only a small bugfix. Will merge in 3 days if no one screams.

File: include/Lv2Worker.h [hunk 4]
```diff
@@ -47,9 +47,10 @@ class Lv2Worker
 {
 public:
 	// CTOR/DTOR/feature access
-	Lv2Worker(const LV2_Worker_Interface* iface, Semaphore* common_work_lock, bool threaded);
+	Lv2Worker(Semaphore* common_work_lock, bool threaded);
```
Comment (sakertooth) [inline include/Lv2Worker.h:50]: I would prefer ``common_work_lock`` to be ``commonWorkLock``. It fits better with our style.

File: src/core/lv2/Lv2Proc.cpp [hunk 5]
```diff
@@ -442,11 +442,16 @@ void Lv2Proc::initPlugin()
 
 	if (m_instance)
 	{
-		if(m_worker) {
+		const auto iface = static_cast<const LV2_Worker_Interface*>(
```
Comment (sakertooth) [inline src/core/lv2/Lv2Proc.cpp:445]: Since you changed `setIface` to `setInterface`, I would think that `iface` and `m_iface` gets replaced with `interface` and `m_interface` as well.

File: src/core/lv2/Lv2Proc.cpp [hunk 6]
```diff
@@ -528,12 +533,11 @@ void Lv2Proc::initPluginSpecificFeatures()
...
 	if (lilv_plugin_has_extension_data(m_plugin, mgr->uri(LV2_WORKER__interface).get())) {
-		const auto iface = static_cast<const LV2_Worker_Interface*>(
-			lilv_instance_get_extension_data(m_instance, LV2_WORKER__interface));
 		bool threaded = !Engine::audioEngine()->renderOnly();
-		m_worker.emplace(iface, &m_workLock, threaded);
+		m_worker.emplace(&m_workLock, threaded);
 		m_features[LV2_WORKER__schedule] = m_worker->feature();
-		// Note: m_worker::setHandle will still need to be called later
+		// note: the worker interface can not be instantiated yet - it requires m_instance
+		//       see initPlugin()
```
Comment (sakertooth) [inline src/core/lv2/Lv2Proc.cpp:540]: Doesn't really matter much, I just think that a single comment is simpler and more readable.
```suggestion
		// note: the worker interface can not be instantiated yet - it requires m_instance. see initPlugin()
```

File: src/core/lv2/Lv2Worker.cpp [hunk 7]
```diff
@@ -91,6 +88,20 @@ Lv2Worker::Lv2Worker(const LV2_Worker_Interface* iface,
 
 
 
+void Lv2Worker::setHandle(LV2_Handle handle) { m_handle = handle; }
+
+
+
+
+void Lv2Worker::setInterface(const LV2_Worker_Interface* iface)
```
Comment (sakertooth) [inline src/core/lv2/Lv2Worker.cpp:96]: Could change this parameter from `iface` to `interface` too.

**Review by sakertooth — COMMENTED** [review]
Just some style suggestions.

**Comment by sakertooth** [comment]
> Fixup: interface is reserved on MSVC

Truly atrocious. What kind of compiler does that?

File: include/Lv2Worker.h [hunk 8]
```diff
@@ -47,16 +47,17 @@ class Lv2Worker
 {
 public:
 	// CTOR/DTOR/feature access
-	Lv2Worker(const LV2_Worker_Interface* iface, Semaphore* common_work_lock, bool threaded);
+	Lv2Worker(Semaphore* commonWorkLock, bool threaded);
 	~Lv2Worker();
-	void setHandle(LV2_Handle handle) { m_handle = handle; }
+	void setHandle(LV2_Handle handle);
+	void setInterface(const LV2_Worker_Interface* new_interface);
```
Comment (sakertooth) [inline include/Lv2Worker.h:53]:
```suggestion
	void setInterface(const LV2_Worker_Interface* newInterface);
```

File: src/core/lv2/Lv2Worker.cpp [hunk 9]
```diff
@@ -91,6 +87,20 @@ Lv2Worker::Lv2Worker(const LV2_Worker_Interface* iface,
...
+void Lv2Worker::setHandle(LV2_Handle handle) { m_handle = handle; }
+
+
+
+
+void Lv2Worker::setInterface(const LV2_Worker_Interface* new_interface)
+{
+	assert(new_interface);
+	m_interface = new_interface;
+}
```
Comment (sakertooth) [inline src/core/lv2/Lv2Worker.cpp:99]:
```suggestion
void Lv2Worker::setInterface(const LV2_Worker_Interface* newInterface)
{
	assert(newInterface);
	m_interface = newInterface;
}
```

**Review by sakertooth — APPROVED** [review]

File: include/Lv2Worker.h [hunk 10]
```diff
@@ -69,7 +70,7 @@ class Lv2Worker
 	std::size_t bufferSize() const;  //!< size of internal buffers
 
 	// parameters
-	const LV2_Worker_Interface* m_iface;
+	const LV2_Worker_Interface* m_interface;
```
Comment (messmerd) [inline include/Lv2Worker.h:73]:
```suggestion
	const LV2_Worker_Interface* m_interface = nullptr;
```
Now that it's no longer being initialized by the constructor, this should be set to null just to be safe.

Comment (JohannesLorenz) [reply include/Lv2Worker.h:73]: Thanks, though I used this on purpose to tell the reader: We do not make any assumptions about this value before we initialize it. So I would prefer to keep this.

Comment (messmerd) [reply include/Lv2Worker.h:73]: As a reader, that is not what I thought when I saw it. Instead I thought, "oh, he forgot to initialize a member variable". Since it is implicitly and not explicitly uninitialized, it's something very easy to miss and can't really be called a message to the reader.

The second thing I thought was "it will be a problem if that variable is ever read from in that state".
Say in the future someone less familiar with your code (or even yourself) introduces a null pointer check to see if the interface has been set - then you'd have UB. And an unnecessary headache debugging it. So I think it's good practice to simply initialize all member variables during construction unless there's a good reason not to (such as performance), and in this case I don't see a reason not to.

**Review by messmerd — APPROVED** [review]
Tested and works
