### PR TITLE
Fix zooming and sliding of the waveform view in AudioFileProcessor

### LINKED ISSUE #7375: Buggy points in LMMS AudioFileProcessor
### System Information

Windows 10 intel i7 2.6Ghz

### LMMS Version(s)

g1420a1f7e (nightly)

### Most Recent Working Version

1.2.2 

### Bug Summary

Points only work when moving them to the right, not left. (AudioFileProcessor)

all 3 points (Start, loop, and finish) have this bug

### Expected Behaviour

Should move points to the left

### Steps To Reproduce

Load AudioFileProcessor

load sound

adjust using the UI window (not knob)

There you have it. (Video footage cant be shown bcuz of file limit)

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Screenshots / Minimum Reproducible Project

_No response_

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by szeli1**
closes #7375

fixes partially #7074

I have fixed some issues with the graph:

- sliding the start, loop, end indicator
- sliding the waveshape
- zooming in
- possibly segfaults

The sliding and the zooming was separated in mouseMoveEvent, if the user starts sliding or zooming, they will no longer be able to zoom or slide until next mouse press.

### CODE REVIEW

**Comment by Rossmaxx** [comment]
> fixes partially #7074

can you fully fix it? with help from @michaelgregorius

File: plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp [hunk 1]
```diff
@@ -376,14 +382,16 @@ void AudioFileProcessorWaveView::zoom(const bool out)
 void AudioFileProcessorWaveView::slide(int px)
 {
 	const double fact = qAbs(double(px) / width());
-	auto step = range() * fact * (px > 0 ? -1 : 1);
+	double step = range() * fact * (px > 0 ? 1 : -1);
```
Comment (Rossmaxx) [inline plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp:385]: why this inversion?

File: plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp [hunk 2]
```diff
@@ -395,7 +403,7 @@ void AudioFileProcessorWaveView::slideSamplePointByPx(Point point, int px)
 	);
 }
 
-void AudioFileProcessorWaveView::slideSamplePointByFrames(Point point, f_cnt_t frames, bool slide_to)
+void AudioFileProcessorWaveView::slideSamplePointByFrames(Point point, long frames, bool slide_to)
```
Comment (Rossmaxx) [inline plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp:406]: If this is a loop variable, better to use `size_t` and make the change in loops too accordingly

**Review by Rossmaxx — COMMENTED** [review]
some minor thoughts

File: plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp (hunk 2 above)
Comment (szeli1) [reply plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp:406]: The problem was that `frames` could be negative, so I changed it to long. I can change it to `ssize_t` if you want.

File: plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp (hunk 1 above)
Comment (szeli1) [reply plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp:385]: Because I changed how it works. I didn't know how it was supposed to work and it wasn't working, so I redesigned it slightly.

**Comment by szeli1** [comment]
> can you fully fix it? with help from @michaelgregorius

I would appreciate some help, but it isn't strictly needed.

File: plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp (hunk 2 above)
Comment (Rossmaxx) [reply plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp:406]: Nope this is better then

File: plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp (hunk 1 above)
Comment (Rossmaxx) [reply plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp:385]: I would ask opinion from @sakertooth since you mentioned a redesign

Comment (sakertooth) [reply plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp:385]: It's fine to leave `auto` here. `fact` is a double, so `step` will be a `double`. For the actual inversion, if the function changed but still achieves the same goal (i.e., zooms properly), it is fine. I will try to do some testing if time permits.

Comment (sakertooth) [inline plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp:385]: No need to switch these to `double`. This was switched to `auto` to allow the right hand side to completely determine the type of the variable, avoiding implicit conversions.

```suggestion
	auto step = range() * fact * (px > 0 ? 1 : -1);
```

File: plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp [hunk 3]
```diff
@@ -376,14 +382,16 @@ void AudioFileProcessorWaveView::zoom(const bool out)
...
+	double step = range() * fact * (px > 0 ? 1 : -1);
 
-	const auto stepFrom = std::clamp(m_from + step, 0.0, static_cast<double>(m_sample->sampleSize())) - m_from;
-	const auto stepTo = std::clamp(m_to + step, m_from + 1.0, static_cast<double>(m_sample->sampleSize())) - m_to;
+	// get the real start and end frame
+	const double sampleStart = static_cast<double>(m_sample->startFrame());
+	const double sampleEnd = static_cast<double>(m_sample->endFrame());
+
+	const double stepFrom = std::clamp(sampleStart + step, 0.0, static_cast<double>(m_sample->sampleSize())) - sampleStart;
+	const double stepTo = std::clamp(sampleEnd + step, sampleStart + 1.0, static_cast<double>(m_sample->sampleSize())) - sampleEnd;
```
Comment (sakertooth) [inline plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp:392]:
```suggestion
	const auto sampleStart = static_cast<double>(m_sample->startFrame());
	const auto sampleEnd = static_cast<double>(m_sample->endFrame());

	const auto stepFrom = std::clamp(sampleStart + step, 0.0, static_cast<double>(m_sample->sampleSize())) - sampleStart;
	const auto stepTo = std::clamp(sampleEnd + step, sampleStart + 1.0, static_cast<double>(m_sample->sampleSize())) - sampleEnd;
```

File: plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp [hunk 4]
```diff
@@ -499,6 +507,7 @@ void AudioFileProcessorWaveView::knob::slideTo(double v, bool check_bound)
 	{
 		return;
 	}
+
```
Comment (sakertooth) [inline plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp:510]:
```suggestion
```

File: plugins/AudioFileProcessor/AudioFileProcessorWaveView.h [hunk 5]
```diff
@@ -118,14 +118,18 @@ public slots:
...
+		SlideWave,
+		ZoomWave,
 		SampleStart,
 		SampleEnd,
 		SampleLoop
 	} ;
 
 	Sample const* m_sample;
 	QPixmap m_graph;
+	// display from
```
Comment (sakertooth) [inline plugins/AudioFileProcessor/AudioFileProcessorWaveView.h:130]:
```suggestion
```

File: plugins/AudioFileProcessor/AudioFileProcessorWaveView.h [hunk 6]
```diff
@@ -118,14 +118,18 @@ public slots:
...
 	int m_from;
+	// display to
```
Comment (sakertooth) [inline plugins/AudioFileProcessor/AudioFileProcessorWaveView.h:132]:
```suggestion
```

File: plugins/AudioFileProcessor/AudioFileProcessorWaveView.h [hunk 7]
```diff
@@ -158,8 +162,9 @@ public slots:
 	void zoom(const bool out = false);
 	void slide(int px);
 	void slideSamplePointByPx(Point point, int px);
-	void slideSamplePointByFrames(Point point, f_cnt_t frames, bool slide_to = false);
-	void slideSampleByFrames(f_cnt_t frames);
+	// point: wihch knob to slide, frames: how mutch, can be negative, slide_to: should set the value instead of adding it
```
Comment (sakertooth) [inline plugins/AudioFileProcessor/AudioFileProcessorWaveView.h:165]:
```suggestion
```

File: plugins/AudioFileProcessor/AudioFileProcessorWaveView.h [hunk 8]
```diff
@@ -158,8 +162,9 @@ public slots:
...
+	void slideSamplePointByFrames(Point point, long frames, bool slide_to = false);
```
Comment (sakertooth) [inline plugins/AudioFileProcessor/AudioFileProcessorWaveView.h:166]:
```suggestion
	void slideSamplePointByFrames(Point point, long frames, bool slideTo = false);
```

**Review by sakertooth — COMMENTED** [review]
Small code suggestions here. Will try to test later.

File: plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp (hunk 2 above)
Comment (sakertooth) [reply plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp:406]: Good catch @szeli1, it could be negative, so it could be a signed integer variable rather than unsigned. These were recently changed to `size_t`, so I was questioning why these were changed, but I realized that these can infact be negative.

File: plugins/AudioFileProcessor/AudioFileProcessorWaveView.h (hunk 7 above)
Comment (szeli1) [reply plugins/AudioFileProcessor/AudioFileProcessorWaveView.h:165]: Why do you suggest removing this comment?

Comment (sakertooth) [reply plugins/AudioFileProcessor/AudioFileProcessorWaveView.h:165]: The comment feels like added noise. If you insist, I would try to clean up the spelling/punctuation/grammar and use `//!` for documentation comments.

Comment (szeli1) [reply plugins/AudioFileProcessor/AudioFileProcessorWaveView.h:165]: All right, I wanted to make it clear that `frames` can be negative, this comment will be removed.

Comment (sakertooth) [reply plugins/AudioFileProcessor/AudioFileProcessorWaveView.h:165]: > All right, I wanted to make it clear that `frames` can be negative, this comment will be removed.

I would suggest using a better name to make it clear that `frames` is not actually for a count of frames, but rather used to determine how many frames should we slide/zoom.

I can't think of one off the top of my head, so don't bother with it if it's too much trouble. You can still use the comment here, just make it a documentation comment and clean it up a bit.

**Comment by bratpeki** [comment]
I'll test this ASAP.

**Comment by bratpeki** [comment]
When looking at this initially, it seems perfectly fine. I'll install it on my system at test it, you'll have more opinions from me in a few days.

@Rossmaxx says some users mentioned it didn't solve the issue for them. Would you like any info regarding my system and building process?

**Comment by szeli1** [comment]
> @Rossmaxx says some users mentioned it didn't solve the issue for them. Would you like any info regarding my system and building process?

I'm hearing about this for the first time. I've changed how thing work so I'm not sure what is exactly the issue they are experiencing. I would like to hear info about what is the problem firstly. Thank you for reviewing it and communicating the issue. I would like to know how the testing goes.

**Comment by bratpeki** [comment]
@szeli1, what do the second and third point mean? I would like to be sure I've tested them, so if you could elaborate on them more, that would be terrific!

**Comment by szeli1** [comment]
> @szeli1, what do the second and third point mean? I would like to be sure I've tested them, so if you could elaborate on them more, that would be terrific!

In other words:
I need to know what is the issue that they are talking about ("says some users mentioned it didn't solve the issue for them"). Thank you for notifying me that there is an issue and thank you for deciding that you will test this. I meant to say this by the last 3 sentences.

**Comment by bratpeki** [comment]
Oh, no, not that, that's something @Rossmaxx [mentioned on Discord](https://discord.com/channels/203559236729438208/207159523616489473/1274048172381175819). I'm talking about "sliding the waveshape" and "zooming in".

File: plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp [hunk 9]
```diff
@@ -376,14 +382,16 @@ void AudioFileProcessorWaveView::zoom(const bool out)
 void AudioFileProcessorWaveView::slide(int px)
 {
 	const double fact = qAbs(double(px) / width());
-	auto step = range() * fact * (px > 0 ? -1 : 1);
+	double step = range() * fact * (px > 0 ? 1 : -1);
+
+	// get the real start and end frame
+	const auto sampleStart = static_cast<double>(m_sample->startFrame());
+	const auto sampleEnd = static_cast<double>(m_sample->endFrame());
```
Comment (sakertooth) [inline plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp:389]: Wanted to point out that comments should really only be used scarcely IMO. For simple code like that, I can quickly understand what it does. Using good names like `sampleStart` and `sampleEnd` also really help with understanding the code already.

**Review by sakertooth — APPROVED** [review]
Haven't tested it, but the changes look sane.

File: plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp (hunk 1 above)
Comment (sakertooth) [reply plugins/AudioFileProcessor/AudioFileProcessorWaveView.cpp:385]: Could we change this back to using `auto`? The inversion itself is fine if the behavior ultimately changed for the better.

**Comment by sakertooth** [comment]
Just tested it, it works a lot better now :+1:. We should still address the outstanding comments if possible before merge though.

**Comment by szeli1** [comment]
> I'm talking about "sliding the waveshape" and "zooming in".

Dragging the waveshape left and right or up and down.

**Review by bratpeki — APPROVED** [review]

**Comment by bratpeki** [comment]
LGTM, we've discussed the fact that sometimes sliding happens instead of zooming, and vice versa, but I believe this is the minor mouse/trackpad twitches, so it's fine.

If you still want to work on that, I'm more than willing to test it!
