### PR TITLE
Ogg export truncation fix

### LINKED ISSUE #8047: Exporting as OGG cuts the end off the song
### System Information

Windows 10 Home 22H2

### LMMS Version(s)

LMMS 1.3.0-alpha.1.792+d4fe398

### Most Recent Working Version

LMMS 1.3.0-alpha.1.102+g89fc6c960

### Bug Summary

Exporting a project as an OGG file with "Export as loop" and "Export between loop markers" enabled cuts off a little part of the song at the end.

Pictured are the same project exported in versions 1.2.2, 1.3.0-alpha.1 and 1.3.0-alpha.1.792+d4fe398
Image

### Expected Behaviour

The project should be exported without cutting off a little part of the song at the end

### Steps To Reproduce

Have a project with set loop points.
Export it as an OGG file, as a loop between loop markers

Image

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Screenshots / Minimum Reproducible Project

_No response_

### Please search the issue tracker for existing bug reports before submitting your own.

- [x] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by jefrecantuledesma**
Fixes #8047

The OGG export was cutting off audio at the end when the AudioFileOgg destructor cleaned up encoder resources without first flushing the remaining encoded data from libvorbis internal buffers. After signaling end-of-stream with vorbis_analysis_wrote(&m_vds, 0), the destructor now properly drains all buffered encoded data through the standard libvorbis finalization sequence before cleanup. This ensures the complete audio stream is written to the file.

image

One export is .ogg, one export is .wav. Both are of same length and audio content.

### CODE REVIEW

File: src/core/Song.cpp [hunk 1]
```diff
@@ -625,6 +625,12 @@ void Song::setPlayPos( tick_t ticks, PlayMode playMode )
 
 void Song::togglePause()
 {
+	// Pause/unpause only works when something is actually playing
+	if( m_playMode == PlayMode::None )
```
Comment (sakertooth) [inline src/core/Song.cpp]: This change doesn't seem to belong in this PR.

File: src/core/audio/AudioFileOgg.cpp [hunk 2]
```diff
@@ -79,7 +79,30 @@ AudioFileOgg::AudioFileOgg(OutputSettings const& outputSettings, const ch_cnt_t
...
+			ogg_stream_packetin(&m_oss, &m_packet);
+
+			// Use ogg_stream_flush instead of pageout to ensure all pages are written
+			while (ogg_stream_flush(&m_oss, &m_page))
+			{
+				writeData(m_page.header, m_page.header_len);
+				writeData(m_page.body, m_page.body_len);
+			}
+		}
+	}
```
Comment (sakertooth) [inline src/core/audio/AudioFileOgg.cpp]: This code looks very similar to the main writing loop a few lines down (except it calls a different function). I wonder if we could simplify some stuff here.

File: src/core/Song.cpp (hunk 1 above)
Comment (jefrecantuledesma) [reply src/core/Song.cpp]: Oh shoot, yes, my bad. I'm new to creating pull requests—will fix in a few hours. Thank you!

File: src/core/audio/AudioFileOgg.cpp (hunk 2 above)
Comment (jefrecantuledesma) [reply src/core/audio/AudioFileOgg.cpp]: @sakertooth The similarity is intentional--the key difference is that the destructor uses ogg_stream_flush() instead of ogg_stream_pageout(). pageout() only returns pages when they're naturally ready (efficient for streaming), while flush() forces all buffered data out immediately (necessary to prevent truncation at end-of-stream).

Using pageout() in the destructor would leave data in the encoder's buffers, recreating the original bug. Using flush() in writeBuffer() would work but hurt encoding efficiency by forcing premature page breaks during normal operation.

We could abstract this into a helper function with a boolean parameter, but I think that would obscure the intent. The current code makes it obvious why we're using different stream functions in different contexts.

The two functions are both necessary and (I believe) make sense separately.

**Review by sakertooth — DISMISSED** [review]
Are those comments AI? PR looks good just wondering lol

**Comment by jefrecantuledesma** [comment]
> Are those comments AI? PR looks good just wondering lol

Haha yeaaaaaah :( I'm (shamefully and regrettably) a vibe coder, but I really like LMMS and wanted to contribute somehow! I did make sure to reproduce the bug, confirm that the bug was fixed, and (of course) review the code. 

As I mentioned, this is my first time contributing to a project that is not my own--if you don't mind sharing, what are the guidelines on using AI for open-source projects? Is it frowned down upon, or is it more of a "if it fixes the bug, it fixes the bug!"

**Comment by sakertooth** [comment]
> > Are those comments AI? PR looks good just wondering lol
> 
> 
> 
> Haha yeaaaaaah :( I'm (shamefully and regrettably) a vibe coder, but I really like LMMS and wanted to contribute somehow! I did make sure to reproduce the bug, confirm that the bug was fixed, and (of course) review the code. 
> 
> 
> 
> As I mentioned, this is my first time contributing to a project that is not my own--if you don't mind sharing, what are the guidelines on using AI for open-source projects? Is it frowned down upon, or is it more of a "if it fixes the bug, it fixes the bug!" 

Don't worry about it, I don't think we have any policy against that, especially when it comes to documentation and comments. I use it for documentation and then change stuff up a bit so no worries lol. I think a handful of other devs (me included) also use AI for general guidance/domain knowledge, just not copying code from it without scrutiny.

**Comment by sakertooth** [comment]
PR looks good code wise, but could use some more testing if it hasn't been tested already.

File: src/core/audio/AudioFileOgg.cpp (hunk 2 above)
Comment (sakertooth) [reply src/core/audio/AudioFileOgg.cpp]: I think if there is a way so that the concern of doing a write is in one place, that would be better. Just so that we don't have to worry about two separate write loops if we can help it. I took another look at the write loop in `writeBuffer`, and it seems the loop might be prematurely exiting. Will try to find another solution.

**Comment by sakertooth** [comment]
Okay, so I found two bugs (one of them which you somewhat found already)

1. We do in fact need to write data within the destructor to flush it properly. This is what you found, but we still want the `vorbis_analysis_wrote` call to signal to libvorbis that no more data is coming through (edit: thought this was removed but it wasn't).
2. There was a bug I found within the `writeBuffer` function, where `ogg_stream_pageout` was being used as the stop condition when it should've been `ogg_page_eos`.

I discovered these issues with [this example](https://github.com/xiph/vorbis/blob/main/examples/encoder_example.c) (and ChatGPT lol).

```diff
diff --git a/src/core/audio/AudioFileOgg.cpp b/src/core/audio/AudioFileOgg.cpp
index 8da89d634..0414de5ea 100644
--- a/src/core/audio/AudioFileOgg.cpp
+++ b/src/core/audio/AudioFileOgg.cpp
@@ -79,30 +79,9 @@ AudioFileOgg::AudioFileOgg(OutputSettings const& outputSettings, const ch_cnt_t
 
 AudioFileOgg::~AudioFileOgg()
 {
-	// Signal end of stream - no more audio data will be written
 	vorbis_analysis_wrote(&m_vds, 0);
+	writeBuffer(nullptr, 0);
 
-	// Flush all remaining encoded data from the encoder's internal buffers
-	// This is critical to prevent truncation at the end of the file
-	while (vorbis_analysis_blockout(&m_vds, &m_vb) == 1)
-	{
-		vorbis_analysis(&m_vb, nullptr);
-		vorbis_bitrate_addblock(&m_vb);
-
-		while (vorbis_bitrate_flushpacket(&m_vds, &m_packet))
-		{
-			ogg_stream_packetin(&m_oss, &m_packet);
-
-			// Use ogg_stream_flush instead of pageout to ensure all pages are written
-			while (ogg_stream_flush(&m_oss, &m_page))
-			{
-				writeData(m_page.header, m_page.header_len);
-				writeData(m_page.body, m_page.body_len);
-			}
-		}
-	}
-
-	// Clean up encoder resources
 	ogg_stream_clear(&m_oss);
 	vorbis_block_clear(&m_vb);
 	vorbis_dsp_clear(&m_vds);
@@ -137,14 +116,13 @@ void AudioFileOgg::writeBuffer(const SampleFrame* _ab, const fpp_t _frames)
 		{
 			ogg_stream_packetin(&m_oss, &m_packet);
 
-			while (ogg_stream_pageout(&m_oss, &m_page))
+			do
 			{
+				if (ogg_stream_pageout(&m_oss, &m_page) == 0) { break; }
 				writeData(m_page.header, m_page.header_len);
 				writeData(m_page.body, m_page.body_len);
-			}
+			} while (!ogg_page_eos(&m_page));
 		}
-
-		if (ogg_page_eos(&m_page)) { break; }
 	}
 }
```

```
soxi ~/Desktop/lmms_*

Input File     : '/home/saker/Desktop/lmms_122_ogg_export.ogg'
Channels       : 2
Sample Rate    : 44100
Precision      : 16-bit
Duration       : 00:00:18.82 = 829952 samples = 1411.48 CDDA sectors
File Size      : 382k
Bit Rate       : 162k
Sample Encoding: Vorbis
Comment        : 'Cool=This song has been made using LMMS'


Input File     : '/home/saker/Desktop/lmms_pr8156_ogg_export.ogg'
Channels       : 2
Sample Rate    : 44100
Precision      : 16-bit
Duration       : 00:00:18.96 = 836096 samples = 1421.93 CDDA sectors
File Size      : 283k
Bit Rate       : 119k
Sample Encoding: Vorbis
Comment        : 'Cool=This song has been made using LMMS'
```

First snippet I posted is the diff for the changes. You can copy it into a file and apply it with `git apply file.diff`. It looks like we can use the same write loop in the destructor (found this out with the example I shared), I just had accidentally removed the `writeBuffer` call in my previous refactor in #7697.

The second snippet shows the OGG export for the Alf42red demo for the first 9 bars between LMMS 1.2.2 and the patch, which seems to capture more data than 1.2.2 actually. Ignore the bitrate differences by the way, this was also somewhat of a regression in that PR that I made (as well as slower to export OGG?). I plan to look into this.

**Comment by sakertooth** [comment]
Let me know if you've tested the changes on your end and okay with me pushing it to the PR (you can do it too, just need to add me as a coauthor).

File: src/core/audio/AudioFileOgg.cpp (hunk 2 above)
Comment (sakertooth) [reply src/core/audio/AudioFileOgg.cpp]: > The similarity is intentional--the key difference is that the destructor uses ogg_stream_flush() instead of ogg_stream_pageout(). pageout() only returns pages when they're naturally ready (efficient for streaming), while flush() forces all buffered data out immediately (necessary to prevent truncation at end-of-stream).
>...

Gah! I just realized that explanation was AI too lol.

Just my two cents: use LLMs as a guide, I use it for that purpose quite a bit (like I just did recently with the new patch), but don't let it do the work/critical thinking for you. I have gotten into so many fits because ChatGPT (the same probably applies to Claude or whatever else) did not have any of the critical thinking necessary for various discussions, and it was always doubling down/messing stuff up. If I ask ChatGPT to play a game of Wordle with me (which I have done in the past) and it keeps changing up the actual word in between responses/spitting 10 different and inconsistent states each time, then its probably in my best interest not to use it heavily for something technical and a bit more serious.

You will not only learn a lot more, but also maybe even be proud of yourself diving deep into a problem and figuring it out yourself/putting in most of the effort. I know thats not always easy though, but you really have to make sure you know when to call out BS.

**Comment by jefrecantuledesma** [comment]
> Let me know if you've tested the changes on your end and okay with me pushing it to the PR (you can do it too, just need to add me as a coauthor).

I invited you to be a collaborator on my fork. I tested out this change in the capacity of confirming that exporting still produces a sonically-identical (or similar enough lol) file. 

I fear that my technical expertise (or testing expertise, at the least) is nearly at capacity. Thank you so much for testing it more extensively, and if there is anything else I can directly do to help, let me know! Also, please let me know if I took the appropriate action(s) to grant you write access to my fork. 

Thank you, and happy holidays!

**Review by sakertooth — APPROVED** [review]
The previous output snippet I showed to compare 1.2.2 and the changes had a problem is looks like (the file wasn't supposed to be longer). I fixed that and the OGG export duration matches with 1.2.2. The changes look good to me.

Edit: Posting results
image
