### PR TITLE
Make factory samples relative

### LINKED ISSUE #3491: AFP Relative File Paths Broken
This is an LMMS 1.2.0-rc2 issue mainly. When you open .mmp or .mmpz files from https://lmms.io/lsp/ and they contain AudioFileProcessor files, it mostly does not autodetect any of these files in your LMMS directory. This needs to be fixed as many songs will use `<yourfilepath>/data/samples/drumsynth/` files, will nearly all of them will go missing through auto-detect and then viewing the error message with missing files that you have in your directory.

### PR DESCRIPTION
**Pull request by tresf**
Factory samples were broken in #1719.

This patch attempts to fix the problem by patching `tryToMakeRelative` by looping through all valid `data:/` search paths and making a sample relative if contained within `<path>/samples/`.

This DOES NOT have an upgrade routine to relativize existing samples (e.g. in broken RC2 projects).  Newly dragged samples should be fixed.  Clicking "browse" and reselecting samples will fix existing tracks.

Closes #3491

### CODE REVIEW

**Comment by tresf** [comment]
@Lukas-W do you want to review this one before merging?  I think by now there are enough projects out there in the wild we'll need an upgrade routine as either part of this PR or as a subsequent PR.

File: src/core/SampleBuffer.cpp [hunk 1]
```diff
@@ -1411,25 +1411,35 @@ void SampleBuffer::setReversed( bool _on )
...
-		usd.replace( QDir::separator(), '/' );
-		if( f.startsWith( fsd ) )
+		QString f = QString( file ).replace( QDir::separator(), '/' );
+
+		// First, look in factory samples
+		// Isolate "samples/" from "data:/samples/"
+		QString samplesSuffix = ConfigManager::inst()->factorySamplesDir().mid( ConfigManager::inst()->dataDir().length() );
+
+		// Iterate over all valid "data:/" searchPaths
+		foreach ( const QString& path, QDir::searchPaths( "data" ) )
```
Comment (Lukas-W) [inline src/core/SampleBuffer.cpp]: Minor, but `foreach` is a candidate for removal in Qt, [quote](http://doc.qt.io/qt-5.8/qtglobal.html#foreach):

> Since Qt 5.7, the use of this macro is discouraged. It will be removed in a future version of Qt. Please use C++11 range-for, possibly with qAsConst(), as needed.

So this would be the preferred way:

```c++
for ( const QString& path : QDir::searchPaths( "data" ) )
```

**Comment by tresf** [comment]
@Lukas-W thanks.  All points addressed.

Unfortunately my unit test fails.  Can you help me make it work?

**Comment by tresf** [comment]
> Can you help me make it work?

@Lukas-W I'll clarify... the [`SampleBuffer::tryToMakeRelative(...)`](https://github.com/LMMS/lmms/pull/3510/files#diff-ef9bc5377dfa2b05568e71876fee79afR37) needs some paths that can be detected as relative and then compare.  I've also written a small test case for `SampleBuffer::tryToMakeAbsolute(...)`.  Both are failing a unit test.

I'm not exactly sure how I should construct the path.  For example, if I use `/home/tresf/lmms/build/data/samples/drums/kick01.ogg` it does not work.  I believe running from the `~/lmms/build` directory, it would use the versions inside the source tree, but I'm unsure how to write a unit test for that.  Do I need to do some `CMakeCache.txt` trickery?  Any ideas?

**Comment by tresf** [comment]
@Lukas-W unit tests fixed.  Ready for review.

**Comment by Lukas-W** [comment]
@tresf Thanks. Somehow the `sourceDir` test fails for me when I run it from the `/tests` subdirectory. I'll see if I can find out why, or if I can come up with a test that doesn't need `sourceDir` to be exposed.

**Comment by Lukas-W** [comment]
@tresf I'd suggest the following changes:

```patch
diff --git a/include/ConfigManager.h b/include/ConfigManager.h
index 7d542d93c..c5ef45b34 100644
--- a/include/ConfigManager.h
+++ b/include/ConfigManager.h
@@ -74,11 +74,6 @@ public:
 		return m_workingDir;
 	}
 
-	const QString & sourceDir() const
-	{
-		return m_srcDir;
-	}
-
 	QString userProjectsDir() const
 	{
 		return workingDir() + PROJECTS_PATH;
@@ -258,7 +253,6 @@ private:
 
 	QString m_lmmsRcFile;
 	QString m_workingDir;
-	QString m_srcDir;
 	QString m_dataDir;
 	QString m_artworkDir;
 	QString m_vstDir;
diff --git a/src/core/ConfigManager.cpp b/src/core/ConfigManager.cpp
index 38ddbe892..7016acce8 100644
--- a/src/core/ConfigManager.cpp
+++ b/src/core/ConfigManager.cpp
@@ -63,12 +63,12 @@ ConfigManager::ConfigManager() :
 
 	// If we're in development (lmms is not installed) let's get the source and
 	// binary directories by reading the CMake Cache
-	QString appPath = qApp->applicationDirPath();
+	QDir appPath = qApp->applicationDirPath();
 	// If in tests, get parent directory
-	if(appPath.endsWith("/tests")) {
-		appPath = QFileInfo(appPath).dir().currentPath();
+	if(appPath.dirName() == "tests") {
+		appPath.cdUp();
 	}
-	QFile cmakeCache(appPath + "/CMakeCache.txt");
+	QFile cmakeCache(appPath.absoluteFilePath("CMakeCache.txt"));
 	if (cmakeCache.exists()) {
 		cmakeCache.open(QFile::ReadOnly);
 		QTextStream stream(&cmakeCache);
@@ -81,8 +81,8 @@ ConfigManager::ConfigManager() :
 			QString line = stream.readLine();
 
 			if (line.startsWith("lmms_SOURCE_DIR:")) {
-				m_srcDir = line.section('=', -1).trimmed();
-				QDir::addSearchPath("data", m_srcDir + "/data/");
+				QString srcDir = line.section('=', -1).trimmed();
+				QDir::addSearchPath("data", srcDir + "/data/");
 				done++;
 			}
 			if (line.startsWith("lmms_BINARY_DIR:")) {
diff --git a/tests/src/core/RelativePathsTest.cpp b/tests/src/core/RelativePathsTest.cpp
index 72e7ff967..9738f2127 100644
--- a/tests/src/core/RelativePathsTest.cpp
+++ b/tests/src/core/RelativePathsTest.cpp
@@ -36,9 +36,14 @@ private slots:
 	void RelativePathComparisonTests()
 	{
 		// Bail if we can't find the source directory
-		QVERIFY(ConfigManager::inst()->sourceDir() != nullptr);
-		QVERIFY(SampleBuffer::tryToMakeRelative(ConfigManager::inst()->sourceDir() + "/data/samples/drums/kick01.ogg") == "drums/kick01.ogg");
-		QVERIFY(SampleBuffer::tryToMakeAbsolute("drums/kick01.ogg") == ConfigManager::inst()->sourceDir() + "/data/samples/drums/kick01.ogg");
+		QFileInfo fi(ConfigManager::inst()->factorySamplesDir() + "/drums/kick01.ogg");
+		QVERIFY(fi.exists());
+
+		QString absPath = fi.absoluteFilePath();
+		QString relPath = "drums/kick01.ogg";
+
+		QCOMPARE(SampleBuffer::tryToMakeRelative(absPath), relPath);
+		QCOMPARE(SampleBuffer::tryToMakeAbsolute(relPath), absPath);
 	}
 } RelativePathTests;
```

This fixes the `tests` sub-dir problem I experienced, and implements the test in a way that removes the `sourceDir` dependency.

**Comment by tresf** [comment]
@Lukas-W thanks.  Done via 4ff86f8.

**Comment by Lukas-W** [comment]
:+1:
