### PR TITLE
Fix producing of NaN from Env/LFO parameter change while playing.

### LINKED ISSUE #3408: Envelope triggered NaN
Edit: Brief intro
 - We produce NaN.
 - NaN is triggered in instrument envelopes. Specifically by changing release time while playing.
 - This may only be during the first loop.
 - NaN introduced here. 9e1cdd0441bca0697f582be3b85d8e2d4c152c72
 - An uninitialized variable?

To reproduce.
 - Load test project:[envelopeNaN.mmp.zip](https://github.com/LMMS/lmms/files/825468/envelopeNaN.mmp.zip)

 - Play until loop. Sound disappears? If yes, proof. If no, reload project and try again.

---

Verbose intro

The sound went out, NaN style, when I tweaked the decay on an instrument while the song was playing. I set out to see if I could pinpoint the source and I eventually managed to find a way to reproduce it reliably enought to be able to bisect this and the bug seem to have been introduced in 9e1cdd0441bca0697f582be3b85d8e2d4c152c72

```
commit 9e1cdd0441bca0697f582be3b85d8e2d4c152c72
Author: Vesa <contact.diizy@nbl.fi>
Date:   Sun Aug 3 14:49:45 2014 +0300

    Start work on replacing/removing global locks
```

The test project is a simple melody with a bitinvader synt having the volume envelopes release knob controlled by an automation track. There is a reverb on the end for detection purposes as having a reverb seem to enormously aggravate the issue. The NaN is however introduced before the effect chain.
If you play this track the sound may go silent somewhere during the first loop but if it makes it to the second you're safe and need to reopen the project and repeat 'play' until it eventually crashes. For me it will go silent at least one time out of four. Since the issue seem to clear itself up after the first run, I suspect an uninitialised variable somewhere but so far I haven't managed to fix this. We divide with zero in the envelope which I set out to 'fix' in issue #3381 but fixing that doesn't affect this issue at all. I have only seen this with the release button and I think only on the first loop.
If you introduce an `assert( ! isnanf( some buffer ) ); ` in the input of the FX chain you will see that the NaN is detected on either:

 - The first loop cycle on a project launched from the command line (or automatically from last session).
 - Immediately on pressing play on a project launched from the gui.

This is related to https://github.com/LMMS/lmms/issues/1048 and https://github.com/LMMS/lmms/pull/3313 . I think this one should be fixed first as it's introduced first in the sound chain.

Test project: [envelopeNaN.mmp.zip](https://github.com/LMMS/lmms/files/825468/envelopeNaN.mmp.zip)

### PR DESCRIPTION
**Pull request by PhysSong**
Fixes #3408.

Guarantee thread safety to ensure `fillLevel()` not to read value from wrong buffer address, because of buffer reallocation in `updateSampleVars()`.

### CODE REVIEW

File: src/core/EnvelopeAndLfoParameters.cpp [hunk 1]
```diff
@@ -291,6 +291,8 @@ void EnvelopeAndLfoParameters::fillLevel( float * _buf, f_cnt_t _frame,
 						const f_cnt_t _release_begin,
 						const fpp_t _frames )
 {
+	m_paramMutex.lock();
```
Comment (michaelgregorius) [inline src/core/EnvelopeAndLfoParameters.cpp]: Please use a [QMutexLocker](https://doc.qt.io/qt-4.8/qmutexlocker.html) here to ensure safe unlocking in cases of exceptions, etc.

File: src/core/EnvelopeAndLfoParameters.cpp [hunk 2]
```diff
@@ -402,6 +406,8 @@ void EnvelopeAndLfoParameters::loadSettings( const QDomElement & _this )
 
 void EnvelopeAndLfoParameters::updateSampleVars()
 {
+	m_paramMutex.lock();
```
Comment (michaelgregorius) [inline src/core/EnvelopeAndLfoParameters.cpp]: Please use a [QMutexLocker](https://doc.qt.io/qt-4.8/qmutexlocker.html) here to ensure safe unlocking in cases of exceptions, etc.

**Comment by PhysSong** [comment]
@michaelgregorius Done via 667ee11.

**Comment by PhysSong** [comment]
I'll merge it after 12~24 hours if there's no objection.
