### PR TITLE
fixes #6759: Tempo Sync Knob - Context menu string don't update on custom tempo

### LINKED ISSUE #6759: Tempo Sync Knob - Context menu string don't update on custom tempo
### Bug Summary

When setting a custom tempo on a tempo sync knob, the string in the context menu doesn't update to the new value.

#### Steps to reproduce

Set a custom value and engage the context menu once more. The string showing current setting hasn't changed. Change custom setting a couple of times and observe that the string never changes. Now choose one of the fixed settings or **No Sync**. The string has now updated to the new setting. Now, once more, set a custom value. The string will now have updated to the last custom value used.

In order to set a custom value and have it show correctly you need to either:
* Set the custom value
* set a fixed value or no sync
* set the same custom value once more.
Or,
* Set the custom value, save the project and reload.

#### Screenshot

Setting a custom tempo
customtempo1

The string in the context menu should have updated to the new 5/4 value
customtempo2

After setting the tempo sync to one of the other options, including '**No Sync**', the custom value will show correctly if we once more select the same value.
customtempo3

#### Affected LMMS versions

1.2.2 and current master (5ccc8d952ac90ab5a4abfaf7b3a29701a5dec4ed)

### PR DESCRIPTION
**Pull request by consolegrl**
fixes #6759 
The TempoSyncKnobModel didn't emit any signal when a SyncMode::Custom was recalculated after it had been changed in the gui window.
Also it looks like someone broke the TempoSyncKnobModel because SyncMode had been renamed to TempoSyncMode and the build was screaming.

### CODE REVIEW

File: src/gui/widgets/TempoSyncKnob.cpp [hunk 1]
```diff
@@ -75,7 +75,7 @@ void TempoSyncKnob::modelChanged()
 	{
 		m_custom->setModel( &model()->m_custom );
 	}
-	connect( model(), SIGNAL(syncModeChanged(lmms::TempoSyncKnobModel::TempoSyncMode)),
+	connect( model(), SIGNAL(syncModeChanged(lmms::TempoSyncKnobModel::SyncMode)),
```
Comment (sakertooth) [inline src/gui/widgets/TempoSyncKnob.cpp:78]:
```suggestion
	connect(model(), SIGNAL(syncModeChanged(lmms::TempoSyncKnobModel::SyncMode)),
```

Comment (sakertooth) [inline src/gui/widgets/TempoSyncKnob.cpp:78]:
```suggestion
	connect(model(), SIGNAL(syncModeChanged(lmms::TempoSyncKnobModel::SyncMode)),
```

**Review by sakertooth — COMMENTED** [review]
> Also it looks like someone broke the TempoSyncKnobModel because SyncMode had been renamed to TempoSyncMode and the build was screaming.

This is probably due to f102777. The builds were not broken, but your branch probably needed to pull the changes first before you did any changes.

**Comment by consolegrl** [comment]
> This is probably due to [f102777](https://github.com/LMMS/lmms/commit/f10277715f6da1d3055a1ed75dc3b40a5cfac81d). The builds were not broken, but your branch probably needed to pull the changes first before you did any changes.

Weird, I pulled master before I branched only 20 min before the patch. How should I find out about branches that aren't master that I need to pull in?

File: src/gui/widgets/TempoSyncKnob.cpp (hunk 1 above)
Comment (sakertooth) [inline src/gui/widgets/TempoSyncKnob.cpp:78]: I find this odd. This code seems to pass in a ``SyncMode`` (an ``enum class``) as the signal argument and the builds pass? ``SIGNAL`` is a macro though, so I'm not sure how this is being parsed, but I think ``connect(model(), &TempoSyncKnobModel::syncModeChanged, this, &TempoSyncKnob::updateDescAndIcon);`` works better here. This also utilizes function pointers, [which have benefits over the ``SIGNAL``/``SLOT`` macros](https://doc.qt.io/qt-5/signalsandslots.html#signals-and-slots-with-default-arguments).

**Comment by sakertooth** [comment]
> How should I find out about branches that aren't master that I need to pull in?

I wouldn't worry about it unless the branch previously referenced ``enum``'s in anyway somehow. The problem occurs when those ``enum``'s were probably turned into ``enum class``'s, so theres an extra layer of scope to the ``enum``'s that you would have to add for new changes.

With this PR, it does not seem like you changed anything related to enums (disregarding that change to ``SyncMode`` within the signal, which I still think is incorrect syntax anyways?), so I'm not sure where your builds would ever start failing.

**Review by DomClark — APPROVED** [review]

**Review by sakertooth — APPROVED** [review]
