### PR TITLE
Lb302 cleanup

### LINKED ISSUE #8286: LB302 ignores note velocity
### System Information

Windows 10

### LMMS Version(s)

Version 1.3.0-alpha.1.956+f5688e9 (win32/x86_64, Qt 5.15.6, GCC 13-win32)

### Most Recent Working Version

_No response_

### Bug Summary

The LB302 instrument does not respond to note velocity; notes are played at the same volume regardless of velocity.

### Expected Behaviour

Notes should change in volume depending on their velocity.

### Steps To Reproduce

- Add a new LB302 track
- Add some notes to a clip on the track and change their velocities

### Logs

_No response_

### Screenshots / Minimum Reproducible Project

_No response_

### Please search the issue tracker for existing bug reports before submitting your own.

- [x] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by rubiefawn**
Makes the following changes to the Lb302 plugin for increased maintainability and readability:
- [x] Use [non-static data member initializers](https://en.cppreference.com/w/cpp/language/data_members.html#Member_initialization) where possible
- [x] Use `std::numbers::pi` instead of `M_PI`
- [x] Use `std::array` and `std::unique_ptr` instead of manual memory management
- [x] Change plain-old-data `class`es with only public members to `struct`s
- [x] Change some `int`s to `f_cnt_t`, ~~`fpp_t`~~, etc. to better communicate their purpose and avoid weird implicit casting nonsense
- [x] Change `float`s to `sample_t` where appropriate to better communicate their purpose
- [x] Find suitable homes for loose constants
- [x] Prefix standard library math function calls with `std::`
- [x] Ensure all floating-point literals intended to be `float`s end in `f` and are not `double`s to appease MSVC
- [x] Change uses of `SIGNAL` and `SLOT` macros to whatever they should be post-Qt6 upgrade
- [x] Remove cursed mutex in favor of a real-time safe queue (TODO: possible generalization for #6516?)
- [ ] Optimize `struct`/`class` member layout for better locality
- [x] Completely conform to current code conventions

The above list is not comprehensive and is destined to expand.

Also adds note velocity and note panning to Lb302, as well as floating point denormal flush-to-zero on ARM to audio worker threads because might as well

# Testing checklist

- [ ] General Lb302 torture test: slam it with notes, arpeggios, chords, rapid automation of the slide parameter, anything you can think of. It's monophonic so it should only play one note at a time. Mainly looking for any performance or stability issues.
- [ ] Velocity behavior, especially with slide enabled
- [ ] Note panning behavior, especially with slide enabled
- [x] Every Lb302 preset we ship still loads and plays, and sounds no different than they did before

### CODE REVIEW

**Comment by rubiefawn** [comment]
Figured I'd run some un-rigorous `perf stat` benchmarks of release builds as a sanity check to make sure I wasn't destroying performance by changing the mutex for a bunch of atomic operations and busy-wait loops.

Updated for commit 03cca1bdb1d0332f5a66186b53c8e78c58117a9c

Before, with mutex/dynamically allocated vector:

```
Performance counter stats for './lmms render /home/fawn/Documents/lmms/projects/torture.mmpz -a -f flac':

   103,084,983,781      task-clock                       #    2.979 CPUs utilized             
           695,800      context-switches                 #    6.750 K/sec                     
               388      cpu-migrations                   #    3.764 /sec                      
             6,173      page-faults                      #   59.883 /sec                      
   267,717,430,944      instructions                     #    1.17  insn per cycle            
   229,289,575,609      cycles                           #    2.224 GHz                       
    61,653,273,269      branches                         #  598.082 M/sec                     
       496,591,833      branch-misses                    #    0.81% of all branches           

      34.602878156 seconds time elapsed

      93.334079000 seconds user
       9.660192000 seconds sys
```

After, with atomic ringbuffer/statically allocated array:

```
Performance counter stats for './lmms render /home/fawn/Documents/lmms/projects/torture.mmpz -a -f flac':

   104,963,456,247      task-clock                       #    3.066 CPUs utilized             
           708,920      context-switches                 #    6.754 K/sec                     
                67      cpu-migrations                   #    0.638 /sec                      
             4,237      page-faults                      #   40.366 /sec                      
   267,503,252,259      instructions                     #    1.15  insn per cycle            
   233,160,958,544      cycles                           #    2.221 GHz                       
    61,493,266,240      branches                         #  585.854 M/sec                     
       511,104,882      branch-misses                    #    0.83% of all branches           

      34.239441489 seconds time elapsed

      95.604870000 seconds user
       9.199340000 seconds sys
```

Project file used for said benchmarks: [torture.mmp.xml](https://github.com/user-attachments/files/24028033/torture.mmp.xml)

**Edit:** Turns out the arpeggiator has significant overhead, so these results aren't really meaningful.

**Comment by rubiefawn** [comment]
`CACHELINE` and `busy_wait_hint` probably don't belong inside Lb302. Where is the best place for me to move these to?

File: plugins/Lb302/Lb302.cpp [hunk 1]
```diff
@@ -28,92 +28,98 @@
...
-// Envelope Recalculation period
-#define ENVINC 64
-
-//
-// New config
-//
 #define LB_24_IGNORE_ENVELOPE
-#define LB_FILTERED
-//#define LB_DECAY
 //#define LB_24_RES_TRICK
```
Comment (Rossmaxx) [inline plugins/Lb302/Lb302.cpp]: Since we cleaning up the codebase, it would make sense to remove this commented macro.

**Comment by messmerd** [comment]
> `CACHELINE` and `busy_wait_hint` probably don't belong inside Lb302. Where is the best place for me to move these to?

Maybe add them to a new `LmmsPolyfill.h` header. And rename `CACHELINE` to `lmms::hardware_destructive_interference_size` to match the name the standard library uses.

File: include/Hardware.h [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+ */
+
+#ifndef LMMS_HARDWARE_H
+#define LMMS_HARDWARE_H
+
+//! @brief Platform-dependent minimum amount of padding between objects to prevent false cache sharing.
+// TODO: Use std::hardware_destructive_interference_size directly once our compilers are updated enough (GCC 12.1+, Clang 19+, MSVC 2017 15.3)
+// TODO: Add other platforms as needed (LMMS currently only supports 64-bit x86 and ARM)
+#if __cpp_lib_hardware_interference_size >= 201703L
+#include <new>
```
Comment (messmerd) [inline include/Hardware.h]: The `__cpp_lib_hardware_interference_size` feature-test macro is defined in the `<new>` and `<version>` headers, so you'll need to include one of them first before testing the value of the macro.

File: include/Hardware.h [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+}
+#else // x86_64
+namespace lmms
+{
+inline constexpr std::size_t hardware_destructive_interference_size = 64;
+}
+#endif
+
+
+#if defined(__x86_64__) || defined(_M_AMD64) || defined(__i386__) || defined(_M_IX86)
```
Comment (messmerd) [inline include/Hardware.h]: I would use the host architecture macros from `lmmsconfig.h` instead

File: include/Hardware.h [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+	#include <immintrin.h>
+	#define busy_wait_hint() _mm_pause()
```
Comment (messmerd) [inline include/Hardware.h]:
```suggestion
	inline void busy_wait_hint() { _mm_pause() }
```
Better to avoid defining `busy_wait_hint()` as a macro I think. The compiler should inline it when optimizations are enabled.

File: plugins/Lb302/Lb302.cpp [hunk 5]
```diff
@@ -28,92 +28,75 @@
...
 
-#define LB_DIST_RATIO    4.0
-#define LB_24_VOL_ADJUST 3.0
-//#define LB_DECAY_NOTES
 
-#define LB_DEBUG
+namespace
+{
+// Helper to get the phase increment per sample, given a note's frequency and the current sample rate
+static inline float phaseInc(float freq) { return freq / lmms::Engine::audioEngine()->outputSampleRate(); }
```
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp]:
```suggestion
float phaseInc(float freq) { return freq / Engine::audioEngine()->outputSampleRate(); }
```
^ Can be written like this after nesting the anonymous namespace inside the `lmms` namespace

File: plugins/Lb302/Lb302.h [hunk 6]
```diff
@@ -71,109 +69,111 @@ class Lb302FilterKnobState
...
 
 	// Filter Decay
-	float vcf_c0;           // c0=e1 on retrigger; c0*=ed every sample; cutoff=e0+c0
-	float vcf_e0,           // e0 and e1 for interpolation
-	      vcf_e1;
-	float vcf_rescoeff;     // Resonance coefficient [0.30,9.54]
+	float vcf_c0 = 0.f; // c0=e1 on retrigger; c0*=ed every sample; cutoff=e0+c0
+	float vcf_e0 = 0.f; // e0 and e1 for interpolation
+	float vcf_e1 = 0.f;
+	float vcf_rescoeff; //!< Resonance coefficient [0.30, 9.54]
```
Comment (messmerd) [inline plugins/Lb302/Lb302.h]: These could be renamed to follow the naming conventions for data members

File: plugins/Lb302/Lb302.h [hunk 7]
```diff
@@ -71,109 +69,111 @@ class Lb302FilterKnobState
...
 {
-	public:
+public:
 	Lb302FilterIIR2(Lb302FilterKnobState* p_fs);
-	~Lb302FilterIIR2() override;
 
 	void recalc() override;
 	void envRecalc() override;
-	float process(const float& samp) override;
+	sample_t process(const sample_t& samp) override;
```
Comment (messmerd) [inline plugins/Lb302/Lb302.h]: I know it's not anything you changed, but passing a float by const reference rather than by value is a bit strange and may be slightly less efficient.

File: plugins/Lb302/Lb302.h [hunk 8]
```diff
@@ -71,109 +69,111 @@ class Lb302FilterKnobState
...
 
-	protected:
-	float vcf_d1,           //   d1 and d2 are added back into the sample with
-	      vcf_d2;           //   vcf_a and b as coefficients. IIR2 resonance
-	                        //   loop.
+protected:
```
Comment (messmerd) [inline plugins/Lb302/Lb302.h:100]: The data members of this class could also be renamed to follow the conventions

File: plugins/Lb302/Lb302.h [hunk 9]
```diff
@@ -71,109 +69,111 @@ class Lb302FilterKnobState
...
+	float kfcn;
+	float kp;
+	float kp1;
+	float kp1h;
+	float kres;
+	float ay1 = 0.f;
+	float ay2 = 0.f;
+	float aout = 0.f;
+	float lastin = 0.f;
+	float value;
```
Comment (messmerd) [inline plugins/Lb302/Lb302.h]: Same here

File: plugins/Lb302/Lb302.h [hunk 10]
```diff
@@ -71,109 +69,111 @@ class Lb302FilterKnobState
...
+	void recalcFilter();
+
+	enum class VcoShape { Sawtooth, Square, Triangle, Moog, RoundSquare, Sine, Exponential, WhiteNoise,
+		BLSawtooth, BLSquare, BLTriangle, BLMoog };
+	enum class VcaMode { Attack, Decay, Idle, NeverPlayed };
+
+	static constexpr float DIST_RATIO = 4.f;
+	static constexpr fpp_t ENVINC = 64; //!< Envelope Recalculation period
+	static constexpr float vca_attack = 1.f - 0.96406088f; //!< Amp attack
+	static constexpr float vca_a0 = 0.5f; //!< Initial amplifier coefficient
```
Comment (messmerd) [inline plugins/Lb302/Lb302.h]:
```suggestion
	static constexpr float s_distRatio = 4.f;
	static constexpr fpp_t s_envInc = 64; //!< Envelope Recalculation period
	static constexpr float s_vcaAttack = 1.f - 0.96406088f; //!< Amp attack
	static constexpr float s_vcaA0 = 0.5f; //!< Initial amplifier coefficient
```
Following the conventions for private static data members.

The other data members in this class could also be updated.

File: include/Hardware.h [hunk 11]
```diff
@@ -0,0 +1,72 @@
...
+#elif defined(_M_ARM64) // arm64 msvc
+	#include <intrin.h>
+	// See https://github.com/rust-lang/rust/commit/c064b6560b7ce0adeb9bbf5d7dcf12b1acb0c807
+	#define busy_wait_hint() __isb(15)
+#else
+	// TODO: Add other platforms as needed (LMMS currently only supports 64-bit x86 and ARM)
+	#error No busy-wait hint intrinsic available for this platform!
+#endif
+
+#endif
```
Comment (messmerd) [inline include/Hardware.h:158]:
```suggestion
#endif // LMMS_HARDWARE_H
```

Comment (rubiefawn) [reply include/Hardware.h:158]: Fixed as of [`6fccf95`](https://github.com/LMMS/lmms/pull/8132/commits/6fccf9562d3f9fa5b5b557c6ae0795476594ad5b)

File: include/Hardware.h (hunk 4 above)
Comment (rubiefawn) [reply include/Hardware.h]: Fixed as of [`6fccf95`](https://github.com/LMMS/lmms/pull/8132/commits/6fccf9562d3f9fa5b5b557c6ae0795476594ad5b)

File: include/Hardware.h (hunk 3 above)
Comment (rubiefawn) [reply include/Hardware.h]: Mostly resolved as of [`6fccf95`](https://github.com/LMMS/lmms/pull/8132/commits/6fccf9562d3f9fa5b5b557c6ae0795476594ad5b) (MSVC is a pain in the ass as usual)

File: include/Hardware.h (hunk 2 above)
Comment (rubiefawn) [reply include/Hardware.h]: Silly me! Fixed as of [`6fccf95`](https://github.com/LMMS/lmms/pull/8132/commits/6fccf9562d3f9fa5b5b557c6ae0795476594ad5b)

File: plugins/Lb302/Lb302.h (hunk 7 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.h]: Yeah, this is super weird. I had removed it at one point but I think it got reverted during a `git bisect` cause I put too much in one big commit. Thanks for reminding me this still exists.

Comment (rubiefawn) [reply plugins/Lb302/Lb302.h]: Resolved as of 7e031da34f6b496d66ec1ad33930ee08034c4608

File: plugins/Lb302/Lb302.h (hunk 10 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.h]: Fixed static members in ac820f4d767e1ab0ffa7342375b69e4bd60e6e8a, the rest still todo.

**Edit:** Fixed the rest of the member names in `Lb302Synth` as of 147c154dcccdc89a038275277299511463a5ccd2.

File: plugins/Lb302/Lb302.cpp (hunk 5 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: Resolved as of 84980155790c2618994ea85d3624c6ad858a9b35

**Comment by rubiefawn** [comment]
~~Ugh, I just noticed a bug I must have introduced in this PR with slide behavior. Notes continue to slide even after the toggle is disabled, but the slide-from note is whatever the last note was before the toggle was disabled.~~

**Edit:** Bug introduced in 1b563eda28f38aa914484bf29f3fb6f970ddc9d1, is fixed by 0fc7d88910de25987f13b9e6c4843b3cafb1893e. Hooray for `git bisect`

File: plugins/Lb302/Lb302.h (hunk 6 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.h]: For stuff like this where it's all `vcf_foo, vcf_bar`, with coefficient names that are supposed to be lowercase, I'm considering sticking them all in a POD struct like so:

```cpp
struct
{
    float c0 = 0.f; // c0 = e[1] on retrigger; c0 *='ed every sample; cutoff = e[0] + c0
    std::array<float, 2> e = { 0.f, 0.f }; // e[0] and e[1] for interpolation
    float resCoeff; //!< Resonance coefficient [0.30, 9.54]
} m_vcf;
```

File: include/Hardware.h [hunk 12]
```diff
@@ -0,0 +1,84 @@
...
+	256
+#elif defined(LMMS_HOST_X86_64) || defined(LMMS_HOST_X86)
+	64
+#else
+	#warning Defaulting to 64 for lmms::hardware_destructive_interference_size for this architecture. This may be incorrect.
+	64
+#endif
+	;
+
+// TODO: Add docs now that this isn't a macro
```
Comment (bratpeki) [inline include/Hardware.h]: Mind closing this TODO?

File: plugins/Lb302/CMakeLists.txt [hunk 13]
```diff
@@ -1,3 +1,7 @@
 INCLUDE(BuildPlugin)
 
+IF(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
+	ADD_COMPILE_OPTIONS(-Wno-interference-size)
```
Comment (bratpeki) [inline plugins/Lb302/CMakeLists.txt]: Why do this?

Comment (rubiefawn) [reply plugins/Lb302/CMakeLists.txt]: [GCC complains](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Winterference-size) and I need it to not do that

File: include/Hardware.h (hunk 12 above)
Comment (rubiefawn) [reply include/Hardware.h]: Resolved as of 90e6530f847e2ba8ec2aebd0e7f966cd15233ae4

File: plugins/Lb302/Lb302.h (hunk 6 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.h]: Resolved as of a4769edc782473c690631477b0310f0fc2f61ef2

File: plugins/Lb302/Lb302.h (hunk 8 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.h:100]: Resolved as of a4769edc782473c690631477b0310f0fc2f61ef2

**Comment by rubiefawn** [comment]
@sakertooth from [#8280](https://github.com/LMMS/lmms/pull/8280#issuecomment-3959826632):
> Since the actual processing only gets ran in `Lb302::play` (called by `InstrumentPlayHandle::play`), and `Lb302::playNote` does nothing but just track the notes, I wonder if you can remove `m_notes` and just pass the list of notes within `Lb302::play` as a parameter, and move the `release_frame` calculation into `Lb302Synth::play` as well (or maybe just leave it there if its needed earlier than when the `play` function will be called).
> 
> Its really odd to me. The per-note processing occurs in `processNote`, which only happens after the `InstrumentPlayHandle` processes all the notes.

Replying here since discussion of this PR belongs in this PR.

> Since the actual processing only gets ran in `Lb302::play` (called by `InstrumentPlayHandle::play`), and `Lb302::playNote` does nothing but just track the notes, I wonder if you can remove `m_notes` and just pass the list of notes within `Lb302::play` as a parameter,

`Lb302Synth::play()` and `Lb302Synth::playNote()` are overrides of `Instrument::play()` and `Instrument::playNote()`, respectively. Changing these would require a refactor of *everything* that inherits `Instrument`. I don't understand this suggestion.

```c++
// Instrument.h:76
	// if the plugin doesn't play each note, it can create an instrument-
	// play-handle and re-implement this method, so that it mixes its
	// output buffer only once per audio engine period
	virtual void play( SampleFrame* _working_buffer );

	// to be implemented by actual plugin
	virtual void playNote( NotePlayHandle * /* _note_to_play */,
					SampleFrame* /* _working_buf */ )
	{
	}
```

> and move the `release_frame` calculation into `Lb302Synth::play` as well (or maybe just leave it there if its needed earlier than when the `play` function will be called).

This is a good suggestion. As of 6aec9729c21160905743ac706fa0da43cd292968, I've moved the `release_frame` calculation into `Lb302Synth::processNote()`, which is a helper only ever called from inside `Lb302Synth::play()`. Now that it is only ever read or written to by one thread, I've made it a normal non-atomic `f_cnt_t`.

**Comment by sakertooth** [comment]
> `Lb302Synth::play()` and `Lb302Synth::playNote()` are overrides of `Instrument::play()` and `Instrument::playNote()`, respectively. Changing these would require a refactor of everything that inherits Instrument. I don't understand this suggestion.

Each call to `Lb302Synth::playNote` doesn't actually do any per note processing. It just adds it to a internal list of `NotePlayHandle` objects. But the `InstrumentPlayHandle` associated with the instrument already keeps track of all the notes that were supposed to run for the given track and then calls `Instrument::play`.

My idea was that maybe you can remove the `m_notes` list in `Lb302Synth`, and pass the list of notes that the `InstrumentPlayHandle` already manages into `Lb302Synth::play` as an extra parameter. The other instruments wont be impacted (though there function signatures might change) because you can just pass a empty list as a default parameter. The other instruments will just ignore that extra parameter while `Lb302Synth` is the start of where this migration will happen. The only difference is that the handle list managed by `InstrumentPlayHandle` may not respect the ordering requirements of the handles themselves (i.e., `NotePlayHandle` objects where `totalFramesPlayed() == 0` should be played last)

This is somewhat hard to explain (and also might not work), but this is just a idea I had that sprung into my mind to remove that seemingly redundant `m_notes` list in `Lb302Synth`. Consider this mostly as a thought experiment, not something you have to implement or anything.

---
```cpp
void InstrumentPlayHandle::play(SampleFrame* working_buffer)
{
	InstrumentTrack * instrumentTrack = m_instrument->instrumentTrack();

	// ensure that all our nph's have been processed first
	auto nphv = NotePlayHandle::nphsOfInstrumentTrack(instrumentTrack, true);

	bool nphsLeft;
	do
	{
		nphsLeft = false;
		for (const auto& handle : nphv)
		{
			if (handle->state() != ThreadableJob::ProcessingState::Done && !handle->isFinished())
			{
				nphsLeft = true;
				const_cast<NotePlayHandle*>(handle)->process();
			}
		}
	}
	while (nphsLeft);

	m_instrument->play(working_buffer);

	// Process the audio buffer that the instrument has just worked on...
	const fpp_t frames = Engine::audioEngine()->framesPerPeriod();
	instrumentTrack->processAudioBuffer(working_buffer, frames, nullptr);
}
```

`nphv` already keeps track of all the notes that were meant to be played by this instrument, so I was confused why in `Lb302Synth` there is a `m_notes` list with `Lb302Synth::playNote` doing the same thing but just putting the notes in a different order.

**Comment by sakertooth** [comment]
There's probably a better approach but would probably mean a larger refactor, but its rather plausible to think that the `m_notes` list in `Lb302Synth` (and probably the other instruments) is redundant tracking.

**Comment by rubiefawn** [comment]
> But the InstrumentPlayHandle associated with the instrument already keeps track of all the notes that were supposed to run for the given track and then calls Instrument::play.

I wasn't aware of this! That's good to know.

The queue (`m_notes`) is merely a safer replacement for the old behavior, which was a `QList` protected by a mutex (yuck!!). Getting rid of the mutex was one of the main motivators for making this PR. I assumed there wasn't an existing way to keep track of notes and that I should just make the current method safer, since if there were, Lb302 would already be using it, right? ... right? :scream:

If this can be done without `m_notes` that sounds like an even better upgrade. I'm still iffy on the idea of changing program-wide function signatures to accommodate one plugin, but there might be a way to avoid that too. I'll take a look at `InstrumentPlayHandle`.

**Edit:**

`nphsOfInstrumentTrack()` gets a list of *every single* `NotePlayHandle`, filters them by checking if they belong to the `instrumentTrack` parameter, and pushes them to a `QList`. It doesn't actually keep track of which `NotePlayHandle` belongs where, and use of `QList` is sketchy because of dynamic allocations in what is supposed to be a realtime audio callback function. That's pretty bad.

To fix this, I'd want to refactor `nphsOfInstrumentTrack()` or even `InstrumentPlayHandle`. That's beyond the scope of this PR.

**Comment by sakertooth** [comment]
>  I'm still iffy on the idea of changing program-wide function signatures to accommodate one plugin, but there might be a way to avoid that too.

Yeah I would recommend not doing anything like this here (might not work and also blurs the responsibilities of this PR), but its something to think about.

We might consider also removing `InstrumentPlayHandle` in the future (among some of the others since they don't do any actual processing on their own, like what is `PresetPreviewPlayHandle` even doing here?) after figuring out a more correct design, so the proposed idea may not be applicable.

File: plugins/Lb302/Lb302.h (hunk 9 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.h]: Should be mostly fixed as of ab50f380ea81bc622ffcc4fcc0a1642eac7f26e3.

File: plugins/Lb302/Lb302.cpp [hunk 14]
```diff
@@ -197,844 +155,622 @@ float Lb302FilterIIR2::process(const float& samp)
...
-	float ax1  = lastin;
-	float ay11 = ay1;
-	float ay31 = ay2;
-	lastin  = (samp) - tanh(kres*aout);
-	ay1     = kp1h * (lastin+ax1) - kp*ay1;
-	ay2     = kp1h * (ay1 + ay11) - kp*ay2;
-	aout    = kp1h * (ay2 + ay31) - kp*aout;
-
-	return tanh(aout*value)*LB_24_VOL_ADJUST/(1.0+fs->dist);
+	static constexpr float s_volAdjust = 3.f;
```
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp]:
```suggestion
	constexpr float volAdjust = 3.f;
```
I think the `s_` is just for private static member variables, like `m_` is for private non-static member variables. This is just a constexpr local variable, so it doesn't need the `s_` prefix or `static`.

File: plugins/Lb302/Lb302.cpp [hunk 15]
```diff
@@ -197,844 +155,622 @@ float Lb302FilterIIR2::process(const float& samp)
...
-	// Hold on to the current VCF, and use it throughout this period
-	Lb302Filter *filter = vcf.loadAcquire();
+	if (m_releaseFrame == 0 || !m_playingNote) { m_vcaMode = VcaMode::Decay; }
 
-	if( release_frame == 0 || ! m_playingNote ) 
+	if (m_playingNote)
 	{
-		vca_mode = VcaMode::Decay;
+		constexpr float s_volRatio = 1.f / DefaultVolume;
+		m_noteVolume = m_playingNote->getVolume() * s_volRatio;
```
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp]:
```suggestion
		constexpr float volRatio = 1.f / DefaultVolume;
		m_noteVolume = m_playingNote->getVolume() * volRatio;
```

File: plugins/Lb302/Lb302.cpp [hunk 16]
```diff
@@ -197,844 +155,622 @@ float Lb302FilterIIR2::process(const float& samp)
...
-	if( m_playingNote == _n )
-	{
-		m_playingNote = nullptr;
-	}
+	if (m_playingNote == nph) { m_playingNote = nullptr; }
 }
 
 
-gui::PluginView * Lb302Synth::instantiateView( QWidget * _parent )
+gui::PluginView * Lb302Synth::instantiateView(QWidget* parent)
```
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp]:
```suggestion
gui::PluginView* Lb302Synth::instantiateView(QWidget* parent)
```

File: include/Hardware.h [hunk 17]
```diff
@@ -0,0 +1,85 @@
...
+	64
+#else
+	#warning Defaulting to 64 for lmms::hardware_destructive_interference_size for this architecture. This may be incorrect.
+	64
+#endif
+	;
+
+//! @brief Platform-dependent hint to the processor that it is in a busy-wait loop.
+//! This helps optimize spinlocks by slowing down the processor a bit, which helps reduce contention on atomics.
+inline void busy_wait_hint()
```
Comment (messmerd) [inline include/Hardware.h]:
```suggestion
inline void busyWaitHint()
```
Style fix.

Also, I noticed that `AudioEngineWorkerThread::JobQueue::wait()` currently uses `_mm_pause()`. Maybe you could replace that with `busyWaitHint()`?

File: include/Hardware.h
Comment (messmerd) [inline include/Hardware.h:1]: We have a `denormals.h` header which could probably be merged into this header. And it currently lacks arm64 support, so that should probably be added in at some point.

Here's how JUCE does it:
https://github.com/juce-framework/JUCE/blob/46ea879739533ca0cdc689b967edfc5390c46ef7/modules/juce_audio_basics/buffers/juce_FloatVectorOperations.cpp#L1031-L1140

And a relevant Stack Overflow article: https://stackoverflow.com/questions/78251489/how-to-flush-denormal-numbers-to-zero-for-apple-silicon

This could also be done in a separate PR if you rather keep this PR focused on Lb302.

Comment (rubiefawn) [reply include/Hardware.h:1]: Might as well do it in this PR since this PR introduces `Hardware.h`. I'll look into it.

File: plugins/Lb302/Lb302.cpp (hunk 14 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: Fixed in 43c3b3855c4b976fc47ae3b024a155eadedd7040

File: plugins/Lb302/Lb302.cpp (hunk 15 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: Fixed in 43c3b3855c4b976fc47ae3b024a155eadedd7040

File: plugins/Lb302/Lb302.cpp (hunk 16 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: Fixed in 43c3b3855c4b976fc47ae3b024a155eadedd7040

File: include/Hardware.h (hunk 17 above)
Comment (rubiefawn) [reply include/Hardware.h]: Fixed in 022c50f7afef20d119cacb98fe4c33a4a10257b3

File: include/Hardware.h
Comment (rubiefawn) [reply include/Hardware.h:1]: Done, I think? I don't have an ARM machine to test it on, so I don't know if it works as intended yet.

Comment (messmerd) [reply include/Hardware.h:1]: I might be able to give it a shot on Apple Silicon this weekend

**Comment by messmerd** [comment]
I tested this a bit on Apple Silicon (a Mac Mini), and there didn't seem to be any issues caused by the `Hardware.h` changes.

Most of the Lb302 presets sound the same as before, except for "Oh Synth.xpf" which is noticeably different.
(Also, the "STrash.xpf" preset fails to load - something to do with a LADSPA effect failing to load - and will crash LMMS if you right click and try to send it to a new Instrument Track. Though this is not a regression from this PR.)

I played around with the Lb302 settings and they seemed to work fine, though I didn't compare it to the master branch Lb302 very much, so it's still possible there could be regressions. I played a lot of notes at a time to see if there were any issues, and I didn't see any. Toggling the slide on and off worked as expected.

The per-note volume and panning seemed to work fine as well.
(Side note: There's a weird issue where my bluetooth headphones only play out the right ear when LMMS is open - even audio from other applications - but only while LMMS is open and using the default SDL backend. The PortAudio/CoreAudio backend doesn't work. These do not appear to be regressions from this PR.)
(Side note 2: When I try to export audio, it hangs. Hopefully this will be fixed by saker's FIFO PR.)

Due to these issues, I had to verify per-note panning worked via the vectorscope.

**Comment by rubiefawn** [comment]
> Most of the Lb302 presets sound the same as before, except for "Oh Synth.xpf" which is noticeably different.

Found the offending commit through `git bisect`: 82d0b78883a724634e8933ef2468a9e80e7dc358

Turns out `Lb302Synth::VcoShape` was not in the same order as the giant `switch` block I removed in favor of a `static_cast`. The preset sounded weird because it was playing back with a triangle instead of the intended square.

**Comment by rubiefawn** [comment]
Last night I also encountered a segfault when previewing Lb302 presets from the sidebar. Accessing Lb302's `NotePlayHandle* m_playingNote` to get the per-note volume & panning was the cause according to `gdb`... but the value of `m_playingNote` was non-null, just invalid. What??

Notably I also cannot replicate this segfault on my windows partition, it only happens for me in linux. I'm going to look into it today.

**Edit:** I also cannot replicate the segfault when running the AppImage from 7c4d2c4db75f78ef3aaf2b1b43c3145cd1021c37 under WSL. I'll try recompiling from scratch on linux, maybe it was a problem on my local machine during compilation?

**Edit 2:** I cannot replicate it on linux using the AppImage from 7c4d2c4db75f78ef3aaf2b1b43c3145cd1021c37, nor can I replicate it after recompiling, nor does anything come up when recompiling with ASAN, MSAN, TSAN, and UBSAN. Looks like this was all a false alarm after all. Damn cosmic rays...

**Edit 3:** I am consistently getting a segfault on Windows only when attempting to load a project file with an instance of Lb302 in it, starting from commit a39b0555a4f56299843ed5502c7e40f2d998095d.

**Edit 4:** Found it. One of the places that assigned `m_playingNote` didn't assign its `m_pluginData`, which led to a use-after-free once that `NotePlayHandle` was freed, since `deleteNotePluginData()` was never called, which is supposed to unassign `m_playingNote`. This was never a problem before since it was never dereferenced.

**Comment by rubiefawn** [comment]
Did some more benchmarks using `perf stat`, this time with a project file that doesn't use the arpeggiator: [lb302-torture.mmp.xml](https://github.com/user-attachments/files/26336356/lb302-torture.mmp.xml)

# Current master (098f0ed4b99b09d2a1707b5b6002e486abb092f0)

**Edit:** I was previously using the AUR `lmms-git` package, but that wasn't compiled with the same CMake flags as the other test. I re-ran the test after compiling `master` locally with the same CMake flags for a more accurate comparison.

```
Performance counter stats for '~/src/lmms/build/lmms render lb302-torture.mmp -a -f flac' (10 runs):

430,971,240,352 instructions     ( +-  0.13% )
811,411,815,600 cycles           ( +-  0.40% )
     25,977,738 context-switches ( +-  0.28% )
         40,556 page-faults      ( +-  0.01% )
  4,969,657,842 branch-misses    ( +-  0.27% )
  7,690,457,618 cache-misses     ( +-  0.61% )

49.331 +- 0.148 seconds time elapsed  ( +-  0.30% )
```

# This branch (c86ef78434fb2e7360f5941fb67b36ded4e4f552)

```
Performance counter stats for '~/src/lmms-lb302/build/lmms render lb302-torture.mmp -a -f flac' (10 runs):

400,493,308,746 instructions     ( +-  0.07% )
758,790,284,354 cycles           ( +-  0.28% )
     24,368,422 context-switches ( +-  0.15% )
         40,361 page-faults      ( +-  0.21% )
  4,765,039,651 branch-misses    ( +-  0.17% )
  8,009,820,790 cache-misses     ( +-  0.67% )

44.6630 +- 0.0568 seconds time elapsed  ( +-  0.13% )
```

File: src/core/AudioEngineWorkerThread.cpp [hunk 18]
```diff
@@ -99,12 +96,7 @@ void AudioEngineWorkerThread::JobQueue::run()
 
 void AudioEngineWorkerThread::JobQueue::wait()
 {
-	while (m_itemsDone < m_writeIndex)
-	{
-#ifdef __SSE__
-		_mm_pause();
-#endif
-	}
+	while (m_itemsDone < m_writeIndex) { busyWaitHint(); }
```
Comment (rubiefawn) [inline src/core/AudioEngineWorkerThread.cpp:99]: I shouldn't worry about it in this PR, but these atomic member variables should probably use explicit memory ordering everywhere

**Comment by sakertooth** [comment]
> Did some more benchmarks using `perf stat`, this time with a project file that doesn't use the arpeggiator: [lb302-torture.mmp.xml](https://github.com/user-attachments/files/26336356/lb302-torture.mmp.xml)
> 
> 
> 
> # Current master (098f0ed4b99b09d2a1707b5b6002e486abb092f0)
> 
> 
> 
> **Edit:** I was previously using the AUR `lmms-git` package, but that wasn't compiled with the same CMake flags as the other test. I re-ran the test after compiling `master` locally with the same CMake flags for a more accurate comparison.
> 
> 
> 
> ```
> 
> Performance counter stats for '~/src/lmms/build/lmms render lb302-torture.mmp -a -f flac' (10 runs):
> 
> 
> 
> 430,971,240,352 instructions     ( +-  0.13% )
> 
> 811,411,815,600 cycles           ( +-  0.40% )
> 
>      25,977,738 context-switches ( +-  0.28% )
> 
>          40,556 page-faults      ( +-  0.01% )
> 
>   4,969,657,842 branch-misses    ( +-  0.27% )
> 
>   7,690,457,618 cache-misses     ( +-  0.61% )
> 
> 
> 
> 49.331 +- 0.148 seconds time elapsed  ( +-  0.30% )
> 
> ```
> 
> 
> 
> # This branch (c86ef78434fb2e7360f5941fb67b36ded4e4f552)
> 
> 
> 
> ```
> 
> Performance counter stats for '~/src/lmms-lb302/build/lmms render lb302-torture.mmp -a -f flac' (10 runs):
> 
> 
> 
> 400,493,308,746 instructions     ( +-  0.07% )
> 
> 758,790,284,354 cycles           ( +-  0.28% )
> 
>      24,368,422 context-switches ( +-  0.15% )
> 
>          40,361 page-faults      ( +-  0.21% )
> 
>   4,765,039,651 branch-misses    ( +-  0.17% )
> 
>   8,009,820,790 cache-misses     ( +-  0.67% )
> 
> 
> 
> 44.6630 +- 0.0568 seconds time elapsed  ( +-  0.13% )
> 
> ```

I would recommend scoping `perf` to only the audio threads to avoid skewing the results with the main thread and the like.

File: plugins/Lb302/Lb302.cpp [hunk 19]
```diff
@@ -28,165 +28,121 @@
...
+#include "Lb302.h"
+
 #include <cmath>
+#include <numbers>
+
+#include <QDebug>
 
-#include "Lb302.h"
 #include "AutomatableButton.h"
+#include "BandLimitedWave.h"
```
Comment (bratpeki) [inline plugins/Lb302/Lb302.cpp:39]: Why is this included now?

File: plugins/Lb302/Lb302.cpp [hunk 20]
```diff
@@ -28,165 +28,121 @@
...
-//
 
 namespace lmms
 {
 
-
-//#define engine::audioEngine()->outputSampleRate() 44100.0f
-const float sampleRateCutoff = 44100.0f;
+// Helper to get the phase increment per sample, given a note's frequency and the current sample rate
+static inline float phaseInc(float freq) { return freq / Engine::audioEngine()->outputSampleRate(); }
```
Comment (bratpeki) [inline plugins/Lb302/Lb302.cpp:60]: Note to self: Replaces `GET_INC`.

File: plugins/Lb302/Lb302.cpp [hunk 21]
```diff
@@ -197,844 +153,621 @@ float Lb302FilterIIR2::process(const float& samp)
...
 {
-	vcf = vcfs[db24Toggle.value()];
-	// These recalcFilter calls might suck
-	recalcFilter();
+	float d = (2.3f * m_vcfDecKnob.value() + 0.2f) * Engine::audioEngine()->outputSampleRate();
+	m_fs.envdecay = std::pow(0.1f, 1.0f / d * s_envInc);
 }
 
 
+void Lb302Synth::db24Toggled() { recalcFilter(); }
```
Comment (bratpeki) [inline plugins/Lb302/Lb302.cpp:305]: Why was `vcf = vcfs[db24Toggle.value()];` removed?

File: plugins/Lb302/Lb302.cpp (hunk 19 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp:39]: It was always included, I just organized the includes according to the code style guidelines. If you look a little further down you'll see it was removed from what used to be line 46.

File: plugins/Lb302/Lb302.h [hunk 22]
```diff
@@ -71,191 +66,246 @@ class Lb302FilterKnobState
...
-	FloatModel vcf_cut_knob;
-	FloatModel vcf_res_knob;
-	FloatModel vcf_mod_knob;
-	FloatModel vcf_dec_knob;
+	void processNote(NotePlayHandle* nph);
+	void process(SampleFrame* outbuf, const f_cnt_t size);
+	void recalcFilter();
 
-	FloatModel vco_fine_detune_knob;
+	enum class VcoShape { Sawtooth, Triangle, Square, RoundSquare, Moog, Sine, Exponential, WhiteNoise,
```
Comment (bratpeki) [inline plugins/Lb302/Lb302.h:166]: The old one was:
```cpp
enum class VcoShape { Sawtooth, Square, Triangle, Moog, RoundSquare, Sine, Exponential, WhiteNoise, BLSawtooth, BLSquare, BLTriangle, BLMoog };
```
Does the order matter for the models? Cause it's not being preserved.

File: plugins/Lb302/Lb302.cpp (hunk 21 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp:305]: Because I removed the `vcf` member entirely and replaced it with a getter function of the same name, no need to store redundant state. It's used on line 313 and 330.

File: plugins/Lb302/Lb302.h (hunk 22 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.h:166]: The order change is intended; see https://github.com/LMMS/lmms/pull/8132#issuecomment-4132370201

File: plugins/Lb302/Lb302.cpp [hunk 23]
```diff
@@ -197,844 +153,621 @@ float Lb302FilterIIR2::process(const float& samp)
...
+		const auto& nph = m_notes[i & s_notesBufMask];
+		if (nph->totalFramesPlayed() == 0) { continue; }
+		processNote(nph);
+	}
+	for (size_t i = readIdx; i < writeCommitted; ++i)
+	{
+		const auto& nph = m_notes[i & s_notesBufMask];
+		if (nph->totalFramesPlayed() != 0) { continue; }
+		processNote(nph);
+	}
```
Comment (bratpeki) [inline plugins/Lb302/Lb302.cpp:584]: Why does this happen twice?

Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp:584]: The first loop processes old notes, the second processes new notes. (Or rather, the first loop skips new notes, while the second loop skips old notes.)

Comment (bratpeki) [reply plugins/Lb302/Lb302.cpp:584]: How exactly does that work? They look identical.

Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp:584]: They are identical, except for the `continue` condition: `==` vs `!=`.

**Review by bratpeki — APPROVED** [review]

File: plugins/Lb302/CMakeLists.txt [hunk 24]
```diff
@@ -1,3 +1,8 @@
 INCLUDE(BuildPlugin)
 
+# GCC complains about std::hardware_destructive_interference_size used in Hardware.h
+IF(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
+	ADD_COMPILE_OPTIONS(-Wno-interference-size)
+ENDIF()
+
```
Comment (messmerd) [inline plugins/Lb302/CMakeLists.txt]: Maybe this could be moved to `BuildPlugin.cmake` so it applies to all plugins?

File: include/Hardware.h [hunk 25]
```diff
@@ -0,0 +1,144 @@
...
+//! context of audio signal processing, denormal values are typically
+//! near silence and contain no useful information anyways.
+inline void disableDenormals()
+{
+#if defined(LMMS_HOST_X86_64) || defined(LMMS_HOST_X86)
+	// https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html
+	// Intel® 64 and IA-32 Architectures Software Developer's Manual Volume 1: Basic Architecture
+	// 11.6.3 Checking for the DAZ Flag in the MXCSR Register
+	unsigned int flags = 0x8000; // FTZ
+	std::uint8_t buf[512] = {0};
```
Comment (messmerd) [inline include/Hardware.h]:
```suggestion
	alignas(16) std::uint8_t buf[512] = {0};
```
According to [this](https://www.felixcloutier.com/x86/fxsave), this has to be aligned to a 16-byte boundary.

File: plugins/Lb302/Lb302.h [hunk 26]
```diff
@@ -71,191 +66,246 @@ class Lb302FilterKnobState
...
 
-	f_cnt_t release_frame;
+	std::array<std::unique_ptr<Lb302Filter>, 2> m_vcfs; //!< Filters (just keep both loaded and switch)
 
-	// More States
-	int   vcf_envpos;       // Update counter. Updates when >= ENVINC
+	//! @brief Helper to get current vcf
+	//! @see m_vcfs
+	//! @see db24Toggle
+	inline Lb302Filter& vcf() { return *m_vcfs[m_db24Toggle.value()]; }
```
Comment (messmerd) [inline plugins/Lb302/Lb302.h]:
```suggestion
	Lb302Filter& vcf() { return *m_vcfs[m_db24Toggle.value()]; }
```
This method is already implicitly inline

File: plugins/Lb302/Lb302.cpp [hunk 27]
```diff
@@ -197,844 +153,621 @@ float Lb302FilterIIR2::process(const float& samp)
...
-		vcf_envpos = ENVINC;
+	if (nph->isMasterNote() || (nph->hasParent() && nph->isReleased())) { return; }
 
-		// Double Check
-		//vca_mode = 0;
-		//vca_a = 0.0;
+	auto tries = s_maxNoteEnqueueRetries;
+	auto write_claimed_expected = m_notesWriteClaimed.load(std::memory_order_relaxed);
+	size_t index, next_index;
+	do
```
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp]: I think you could remove the `goto` with a little reorganizing:

```cpp
for (;;)
{
	if (!tries--)
	{
		qDebug() << "Lb302: Note dropped due to catastrophically poor performance! This should never happen!";
		return;
	}

	const std::size_t occupied = writeClaimedExpected - m_notesReadSeq.load(std::memory_order_acquire);
	assert(occupied >= 0);

	// If full, wait for room
	if (occupied >= s_maxPendingNotes)
	{
		busyWaitHint();
		writeClaimedExpected = m_notesWriteClaimed.load(std::memory_order_relaxed);

		// Try to send note again
		continue;
	}

	index = writeClaimedExpected;
	nextIndex = writeClaimedExpected + 1;

	if (m_notesWriteClaimed.compare_exchange_strong(writeClaimedExpected, nextIndex, std::memory_order_acquire))
	{
		// Successfully sent note
		break;
	}
}
```

I wasn't sure why `occupied` was a `ptrdiff_t` - I made it a `std::size_t` instead.

File: plugins/Lb302/Lb302.cpp [hunk 28]
```diff
@@ -197,844 +153,621 @@ float Lb302FilterIIR2::process(const float& samp)
...
-		// Ensure envelope is recalculated
-		vcf_envpos = ENVINC;
+	if (nph->isMasterNote() || (nph->hasParent() && nph->isReleased())) { return; }
 
-		// Double Check
-		//vca_mode = 0;
-		//vca_a = 0.0;
+	auto tries = s_maxNoteEnqueueRetries;
+	auto write_claimed_expected = m_notesWriteClaimed.load(std::memory_order_relaxed);
+	size_t index, next_index;
```
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp]:
```suggestion
	auto writeClaimedExpected = m_notesWriteClaimed.load(std::memory_order_relaxed);
	std::size_t index;
	std::size_t nextIndex;
```
Fixed naming convention, used `std::`, and put declarations on their own lines

File: plugins/Lb302/Lb302.cpp [hunk 29]
```diff
@@ -197,844 +153,621 @@ float Lb302FilterIIR2::process(const float& samp)
...
-		vco_slide = vco_inc-vco_slideinc;	// Slide amount
-		vco_slidebase = vco_inc;			// The REAL frequency
-		vco_slideinc = 0;					// reset from-note
-	}
-	else {
-		vco_slide = 0;
+	size_t write_committed_expected = index;
+	while (!m_notesWriteCommitted.compare_exchange_strong(write_committed_expected, next_index, std::memory_order_release))
+	{
+		write_committed_expected = index; // Reset this as the CAS will have changed it
```
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp]:
```suggestion
	std::size_t writeCommittedExpected = index;
	while (!m_notesWriteCommitted.compare_exchange_strong(writeCommittedExpected, nextIndex, std::memory_order_release))
	{
		writeCommittedExpected = index; // Reset this as the CAS will have changed it
```
Naming convention and using `std::`

File: plugins/Lb302/Lb302.cpp [hunk 30]
```diff
@@ -197,844 +153,621 @@ float Lb302FilterIIR2::process(const float& samp)
...
 	}
-	else
+
+	// Check for slide
+	if (m_playingNote == nph)
 	{
-		m_notes.prepend( _n );
+		m_trueFreq = nph->frequency();
+		const auto true_inc = phaseInc(m_trueFreq);
+		if (m_slideToggle.value()) { m_slideBase = true_inc; } else { m_vcoInc = true_inc; }
```
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp]:
```suggestion
		const auto trueInc = phaseInc(m_trueFreq);
		if (m_slideToggle.value()) { m_slideBase = trueInc; } else { m_vcoInc = trueInc; }
```
Naming convention

File: plugins/Lb302/Lb302.h [hunk 31]
```diff
@@ -71,191 +66,246 @@ class Lb302FilterKnobState
...
+	sample_t process(sample_t samp) override;
+
+protected:
+	float m_kfcn;
+	float m_kp;
+	float m_kp1h; //!< Cached value of (@ref m_kp + 1) / 2
+	float m_kres;
+	std::array<sample_t, 3> m_ay = { 0.f, 0.f, 0.f };
+	float m_lastin = 0.f;
+	float m_value;
```
Comment (messmerd) [inline plugins/Lb302/Lb302.h:134]: I think I'd feel better if all data members were initialized

File: plugins/Lb302/Lb302.cpp [hunk 32]
```diff
@@ -197,844 +153,621 @@ float Lb302FilterIIR2::process(const float& samp)
...
+		if (m_slideToggle.value()) { m_slideInc = phaseInc(nph->frequency()); }
 	}
-	else
+
+	// Check for slide
+	if (m_playingNote == nph)
 	{
-		m_notes.prepend( _n );
+		m_trueFreq = nph->frequency();
+		const auto true_inc = phaseInc(m_trueFreq);
```
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp]:
```suggestion
		const auto trueInc = phaseInc(m_trueFreq);
```
It looks like `m_trueFreq` isn't initialized upon construction, and I'm not sure if it could be read before being initialized. Should probably set it to something.

File: plugins/Lb302/Lb302.h [hunk 33]
```diff
@@ -71,191 +66,246 @@ class Lb302FilterKnobState
...
+	//! @brief Helper to get current vcf
+	//! @see m_vcfs
+	//! @see db24Toggle
+	inline Lb302Filter& vcf() { return *m_vcfs[m_db24Toggle.value()]; }
 
-	float vca_attack,       // Amp attack
-	      vca_a0,           // Initial amplifier coefficient
-	      vca_a;            // Amplifier coefficient.
+	f_cnt_t m_vcfEnvPos = s_envInc; //!< Update counter. Updates when >= @ref s_envInc
+	f_cnt_t m_releaseFrame;
```
Comment (messmerd) [inline plugins/Lb302/Lb302.h]: Looks like this might be read before it is initialized.

File: plugins/Lb302/Lb302.h [hunk 34]
```diff
@@ -71,191 +66,246 @@ class Lb302FilterKnobState
...
+
+	//! @brief The maximum number of note events Lb302 can process per audio buffer.
+	//!
+	//! This value was arbitrarily chosen based off of stress tests with LMMS's
+	//! buffer size set to its maximum value (4096 samples) to maximize the
+	//! ratio of enqueue operations to dequeue operations per buffer. It may be
+	//! adjusted as needed, but it must always be a power of 2.
+	//!
+	//! @see m_notes
+	static constexpr size_t s_maxPendingNotes = 128;
```
Comment (messmerd) [inline plugins/Lb302/Lb302.h]: I'd prefer using `std::size_t` here and elsewhere, but it's not super important

File: include/Hardware.h (hunk 25 above)
Comment (rubiefawn) [reply include/Hardware.h]: Interesting. I didn't see anything about alignment on the *Intel Intrinsic Guide* for [`_fxsave(), _fxsave64()`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=fxsave&ig_expand=3523,3522) so I assumed it wasn't necessary. The *Intel® 64 and IA-32 Architectures Software Developer’s Manual* **does** specify that alignment requirement, but I didn't even think to check that since the *Intel Intrinsic Guide* usually includes alignment requirements.

I'll go ahead and add that back.

**Edit:** Resolved as of 19023f4e9583f6c0455db3c8bcb8d6ce6e065b25.

File: plugins/Lb302/Lb302.cpp (hunk 27 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: > I wasn't sure why occupied was a `ptrdiff_t` - I made it a `std::size_t` instead.

This is because I wanted to catch the case for `a - b` where `a < b`, hence the `assert()` on the next line. `ptrdiff_t` is signed, which allows me to distinguish between the case when `occupied < 0` (a fatal error) vs `occupied >= s_maxPendingNotes` (expected when the queue is full).

However, I just realized it wouldn't work as intended since it's currently just going to underflow to a really big number first (both operands are `size_t`), then put that really big number into the signed type lol. I need to cast the operands to a signed type *first* before subtracting.

File: plugins/Lb302/CMakeLists.txt (hunk 24 above)
Comment (rubiefawn) [reply plugins/Lb302/CMakeLists.txt]: I like this idea, but I get about ten thousand of the following error, mostly from LADSPA plugins with C sources:

```
warning: command-line option ‘-Wno-interference-size’ is valid for C++/ObjC++ but not for C
```

**Edit:** I wonder if I can put the solution inside `Hardware.h` itself by using `#pragma GCC diagnostic ignored`?

**Edit 2:** Resolved as of 19023f4e9583f6c0455db3c8bcb8d6ce6e065b25.

File: plugins/Lb302/Lb302.cpp (hunk 27 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: Resolved as of 19023f4e9583f6c0455db3c8bcb8d6ce6e065b25

File: plugins/Lb302/Lb302.cpp (hunk 28 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: Resolved as of 19023f4e9583f6c0455db3c8bcb8d6ce6e065b25

File: plugins/Lb302/Lb302.cpp (hunk 29 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: Resolved as of 19023f4e9583f6c0455db3c8bcb8d6ce6e065b25

File: plugins/Lb302/Lb302.cpp (hunk 30 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: Resolved as of 19023f4e9583f6c0455db3c8bcb8d6ce6e065b25

File: plugins/Lb302/Lb302.h (hunk 34 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.h]: Resolved as of 19023f4e9583f6c0455db3c8bcb8d6ce6e065b25

File: plugins/Lb302/Lb302.h (hunk 31 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.h:134]: - `m_kfcn` is always initialized in all code paths before it is used
- `m_kp` might be used before it is initialized? (I thought the constructor called `envRecalc()` but that doesn't seem to be the case anymore)
- `m_kp1h` has the same issues as `m_kp` as it is dependent on `m_kp`
- `m_kres` has the same issues
- `m_value` has the same issues

File: plugins/Lb302/Lb302.cpp (hunk 32 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: Resolved as of 73b92f4f532b016c81fecc6dd4f5731d201d0520

File: plugins/Lb302/Lb302.h (hunk 26 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.h]: Resolved as of 73b92f4f532b016c81fecc6dd4f5731d201d0520

File: plugins/Lb302/Lb302.h (hunk 33 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.h]: Resolved as of 73b92f4f532b016c81fecc6dd4f5731d201d0520

File: plugins/Lb302/Lb302.h (hunk 31 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.h:134]: Resolved as of bfc93077536cdd7296487c11376d19239bebf572

File: include/Hardware.h [hunk 35]
```diff
@@ -0,0 +1,151 @@
...
+#elif defined(LMMS_HOST_ARM64) || defined(LMMS_HOST_ARM32)
+	#if defined(__ARM_ACLE)
+		#include <arm_acle.h>
+	#elif defined(_MSC_VER)
+		#include <intrin.h>
+	#elif defined(__GNUG__) // HACK: Remove this once GCC properly provides __ARM_ACLE
+		#if defined(LMMS_HOST_ARM64)
+			// https://developer.arm.com/documentation/ddi0602/2026-03/Base-Instructions/ISB--Instruction-synchronization-barrier-
+			// 15 is the only allowed value for the parameter, so just ignore it and use 15 lol
+			inline void __isb(unsigned int) { asm volatile ("isb 15" ::: "memory"); }
```
Comment (messmerd) [inline include/Hardware.h:47]: Is ISB really what we want? It seems unrelated to spin locks.

Why not use the `yield` ASM instruction like you do for 32-bit ARM?

File: plugins/Lb302/Lb302.cpp [hunk 36]
```diff
@@ -197,844 +153,627 @@ float Lb302FilterIIR2::process(const float& samp)
...
+	if (nph->isMasterNote() || (nph->hasParent() && nph->isReleased())) { return; }
 
-		// Double Check
-		//vca_mode = 0;
-		//vca_a = 0.0;
+	// Enqueue new note in m_notes
+	auto tries = s_maxNoteEnqueueRetries;
+	auto writeClaimedExpected = m_notesWriteClaimed.load(std::memory_order_relaxed);
+	std::size_t index;
+	std::size_t next_index;
```
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp]:
```suggestion
	std::size_t nextIndex;
```
Missed this one

File: plugins/Lb302/Lb302.cpp
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp:1]: What are your thoughts on generalizing the new MPSC note processing you added in this PR to something that works for other instruments as well? Something that could let us hide most of the messy details in `Instrument.cpp` or somewhere else, and provide plugin developers with a nice, easy-to-use note queue which would be passed to `play()` for instruments to read from.

I'm not suggesting any of this should be done in this PR, of course, but it's something that would help with #8275, and note events are one of the few aspects of the new plugin API that I don't have a solid plan for.

File: plugins/Lb302/Lb302.cpp [hunk 37]
```diff
@@ -197,844 +153,627 @@ float Lb302FilterIIR2::process(const float& samp)
...
-	sawWaveBtn->setActiveGraphic( embed::getIconPixmap(
-						"saw_wave_active" ) );
-	sawWaveBtn->setInactiveGraphic( embed::getIconPixmap(
-						"saw_wave_inactive" ) );
-	sawWaveBtn->setToolTip(
-			tr( "Click here for a saw-wave." ) );
+	sawWaveBtn->move(waveBtnX, waveBtnY);
+	sawWaveBtn->setActiveGraphic(embed::getIconPixmap("saw_wave_active"));
+	sawWaveBtn->setInactiveGraphic(embed::getIconPixmap("saw_wave_inactive"));
+	sawWaveBtn->setToolTip(tr("Click here for a saw-wave."));
```
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp]:
```suggestion
	sawWaveBtn->setToolTip(tr("Click here for a saw wave."));
```
Maybe we should take the opportunity to remove the weird unnecessary hyphen from some of these tooltips?

File: plugins/Lb302/Lb302.cpp [hunk 38]
```diff
@@ -197,844 +153,627 @@ float Lb302FilterIIR2::process(const float& samp)
...
-	triangleWaveBtn->setActiveGraphic(
-		embed::getIconPixmap( "triangle_wave_active" ) );
-	triangleWaveBtn->setInactiveGraphic(
-		embed::getIconPixmap( "triangle_wave_inactive" ) );
-	triangleWaveBtn->setToolTip(
-			tr( "Click here for a triangle-wave." ) );
+	triangleWaveBtn->move(waveBtnX + (16 * 1), waveBtnY);
+	triangleWaveBtn->setActiveGraphic(embed::getIconPixmap("triangle_wave_active"));
+	triangleWaveBtn->setInactiveGraphic(embed::getIconPixmap("triangle_wave_inactive"));
+	triangleWaveBtn->setToolTip(tr("Click here for a triangle-wave."));
```
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp]:
```suggestion
	triangleWaveBtn->setToolTip(tr("Click here for a triangle wave."));
```

File: plugins/Lb302/Lb302.cpp [hunk 39]
```diff
@@ -197,844 +153,627 @@ float Lb302FilterIIR2::process(const float& samp)
...
-	sqrWaveBtn->setActiveGraphic( embed::getIconPixmap(
-					"square_wave_active" ) );
-	sqrWaveBtn->setInactiveGraphic( embed::getIconPixmap(
-					"square_wave_inactive" ) );
-	sqrWaveBtn->setToolTip(
-			tr( "Click here for a square-wave." ) );
+	sqrWaveBtn->move(waveBtnX + (16 * 2), waveBtnY);
+	sqrWaveBtn->setActiveGraphic(embed::getIconPixmap("square_wave_active"));
+	sqrWaveBtn->setInactiveGraphic(embed::getIconPixmap("square_wave_inactive"));
+	sqrWaveBtn->setToolTip(tr("Click here for a square-wave."));
```
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp]:
```suggestion
	sqrWaveBtn->setToolTip(tr("Click here for a square wave."));
```

File: plugins/Lb302/Lb302.cpp [hunk 40]
```diff
@@ -197,844 +153,627 @@ float Lb302FilterIIR2::process(const float& samp)
...
-	roundSqrWaveBtn->setActiveGraphic( embed::getIconPixmap(
-					"round_square_wave_active" ) );
-	roundSqrWaveBtn->setInactiveGraphic( embed::getIconPixmap(
-					"round_square_wave_inactive" ) );
-	roundSqrWaveBtn->setToolTip(
-			tr( "Click here for a square-wave with a rounded end." ) );
+	roundSqrWaveBtn->move(waveBtnX + (16 * 3), waveBtnY);
+	roundSqrWaveBtn->setActiveGraphic( embed::getIconPixmap("round_square_wave_active"));
+	roundSqrWaveBtn->setInactiveGraphic( embed::getIconPixmap("round_square_wave_inactive"));
+	roundSqrWaveBtn->setToolTip(tr("Click here for a square-wave with a rounded end."));
```
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp]:
```suggestion
	roundSqrWaveBtn->setToolTip(tr("Click here for a square wave with a rounded end."));
```

File: plugins/Lb302/Lb302.cpp [hunk 41]
```diff
@@ -197,844 +153,627 @@ float Lb302FilterIIR2::process(const float& samp)
...
-	sinWaveBtn->setActiveGraphic( embed::getIconPixmap(
-						"sin_wave_active" ) );
-	sinWaveBtn->setInactiveGraphic( embed::getIconPixmap(
-						"sin_wave_inactive" ) );
-	sinWaveBtn->setToolTip(
-			tr( "Click for a sine-wave." ) );
+	sinWaveBtn->move(waveBtnX + (16 * 5), waveBtnY);
+	sinWaveBtn->setActiveGraphic(embed::getIconPixmap("sin_wave_active"));
+	sinWaveBtn->setInactiveGraphic(embed::getIconPixmap("sin_wave_inactive"));
+	sinWaveBtn->setToolTip(tr("Click for a sine-wave."));
```
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp]:
```suggestion
	sinWaveBtn->setToolTip(tr("Click for a sine wave."));
```

File: plugins/Lb302/Lb302.cpp [hunk 42]
```diff
@@ -197,844 +153,627 @@ float Lb302FilterIIR2::process(const float& samp)
...
-	whiteNoiseWaveBtn->setActiveGraphic(
-		embed::getIconPixmap( "white_noise_wave_active" ) );
-	whiteNoiseWaveBtn->setInactiveGraphic(
-		embed::getIconPixmap( "white_noise_wave_inactive" ) );
-	whiteNoiseWaveBtn->setToolTip(
-			tr( "Click here for white-noise." ) );
+	whiteNoiseWaveBtn->move(waveBtnX + (16 * 7), waveBtnY);
+	whiteNoiseWaveBtn->setActiveGraphic(embed::getIconPixmap("white_noise_wave_active"));
+	whiteNoiseWaveBtn->setInactiveGraphic(embed::getIconPixmap("white_noise_wave_inactive"));
+	whiteNoiseWaveBtn->setToolTip(tr("Click here for white-noise."));
```
Comment (messmerd) [inline plugins/Lb302/Lb302.cpp]:
```suggestion
	whiteNoiseWaveBtn->setToolTip(tr("Click here for white noise."));
```

File: include/Hardware.h (hunk 35 above)
Comment (rubiefawn) [reply include/Hardware.h:47]: https://github.com/rust-lang/rust/commit/c064b6560b7ce0adeb9bbf5d7dcf12b1acb0c807

File: plugins/Lb302/Lb302.cpp
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp:1]: I think that's a good idea. The code for the MPSC note queue is taken from a project of mine: https://codeberg.org/rubiefawn/rtchan

I haven't meaningfully worked on it since I started this PR, but the other queue types can all be derived from MPMC, which is why that's the only one with any real code in it lol.

File: plugins/Lb302/Lb302.cpp (hunk 42 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: Resolved in 37de8f76aa977714117816092ca978838ea1f472

File: plugins/Lb302/Lb302.cpp (hunk 41 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: Resolved in 37de8f76aa977714117816092ca978838ea1f472

File: plugins/Lb302/Lb302.cpp (hunk 40 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: Resolved in 37de8f76aa977714117816092ca978838ea1f472

File: plugins/Lb302/Lb302.cpp (hunk 39 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: Resolved in 37de8f76aa977714117816092ca978838ea1f472

File: plugins/Lb302/Lb302.cpp (hunk 38 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: Resolved in 37de8f76aa977714117816092ca978838ea1f472

File: plugins/Lb302/Lb302.cpp (hunk 37 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: Resolved in 37de8f76aa977714117816092ca978838ea1f472

File: plugins/Lb302/Lb302.cpp (hunk 36 above)
Comment (rubiefawn) [reply plugins/Lb302/Lb302.cpp]: Resolved in 37de8f76aa977714117816092ca978838ea1f472

**Review by messmerd — APPROVED** [review]
LGTM

**Comment by rubiefawn** [comment]
Class member layout could probably be optimized for better locality, but feature freeze is in like two days lol. That can be tidied up after the freeze is over. Merging  immediately !!!🥝!!!
