### PR TITLE
Restore some whitespace to the mixer channel layout

### LINKED ISSUE #7505: Mixer looks cramped and has decreased usability
### LMMS Version(s)

4803bbb73ad3e7b9e36c39cabdec3aff6f1dafe4

### Bug Summary

With #7502 merged the mixer looks cramped and the usability has decreased because usable whitespace has been removed.

Here's how the mixer looks now:

7502-CrampedMixer

And here's how it looked before:

7502-MixerBefore

Before the changes the mixer had valuable white space which separated different elements.

### Expected Behaviour

The mixer should be usable while looking good and professional.

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by sakertooth**
Trying to reach a compromise with #7505 and #7502.

I think I initially believed that users were complaining about the spacing being too much horizontally. However, the vertical spacing in `QVBoxLayout` was 6 for me by default, which could be a bit large, and wasn't set to something smaller in #6591.

I changed the margin size and spacing to make the mixer channel a bit shorter, while also trying to not compromise useful whitespace.

I'm waiting for two approvals for this PR in particular before merge (I should probably require two approvals in general anyways).

Fixes #7505 (I think)

### CODE REVIEW

**Comment by michaelgregorius** [comment]
Look of the mixer with the changes in this PR as of now:

7502-CompromiseWith3

**Comment by sakertooth** [comment]
Thoughts @michaelgregorius?

File: src/gui/MixerChannelView.cpp [hunk 1]
```diff
@@ -128,8 +128,8 @@ namespace lmms::gui
         m_effectRackView->setFixedWidth(EffectRackView::DEFAULT_WIDTH);
 
         auto mainLayout = new QVBoxLayout{this};
-        mainLayout->setContentsMargins(0, 0, 0, 0);
-        mainLayout->setSpacing(0);
+        mainLayout->setContentsMargins(3, 3, 3, 3);
```
Comment (Rossmaxx) [inline src/gui/MixerChannelView.cpp:131]: I believe 4 would be a good value and for setSpacing, try 2.

Comment (sakertooth) [reply src/gui/MixerChannelView.cpp:131]: I am changing the horizontal margins to 4 and the vertical margins to match the spacing specified. A horizontal margin of 4 seems to work well in terms of keeping enough whitespace (3 arguably works too, but 4 might be a bit better). A vertical margin that matches how much we space the child widgets in the `QVBoxLayout` makes sense to me: if we are spacing the child widgets vertically by 2, it would make sense to use that same amount of space for our vertical margins at the edges of the layout.

**Comment by sakertooth** [comment]
Here's an updated image for how the mixer channel's look now:

image

I am very satisfied with this, but I'm waiting for other people's opinions before merge.

**Review by Rossmaxx — APPROVED** [review]
Looks good.

**Comment by michaelgregorius** [comment]
> I am very satisfied with this, but I'm waiting for other people's opinions before merge.

If this was mainly about the horizontal space then I'd appreciate if there was a bit more margin at the bottom where the fader ends.

Otherwise it looks okay to me.

File: src/gui/MixerChannelView.cpp (hunk 1 above)
Comment (sakertooth) [reply src/gui/MixerChannelView.cpp]: Nevermind, it seems like the margin space and the amount of spacing between widgets aren't exactly the same thing.

**Comment by sakertooth** [comment]
What do we think about moving the peak indiciator to the bottom? It adds some space for the fader at the bottom, and I think looks better?

image

**Comment by Rossmaxx** [comment]
Mixer at bottom doesn't look good according to me. It seems to increase the view angle, but that might be just me. It's something i cam get used to so it's not really a blocker.

**Comment by sakertooth** [comment]
How it looks as of the time of merge:
image
