### PR TITLE
Fix a few memory issues found with ASan

### LINKED ISSUE #6608: LMMS crashes when going left down piano in any instrument.
### Bug Summary
LMMS crashes when trying to reach the lowest note on the "piano" in the instrument tab.

#### Steps to reproduce
1. Open any instruments
2. Drag your mouse down the piano to the left, no scrolling.
3. 3. BOOM! Crash.

#### Expected behavior
Stays at the lowest note.

#### Actual behavior
Crashes

#### Affected LMMS versions

current master git

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
lilv_world_add_plugin(): warning: Duplicate plugin <https://github.com/werman/noise-suppression-for-voice>
lilv_world_add_plugin(): warning: ... found in file:///usr/lib/lv2/rnnoise_mono.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib/lv2/rnnoise_stereo.lv2/ (ignored)
Lv2 plugin SUMMARY: 179 of 367  loaded in 1889 msecs.
For details about not loaded plugins, please set
  environment variable "LMMS_LV2_DEBUG" to nonempty.
Lv2 Plugins blacklisted: 67 of 367
  If you want to ignore the blacklist (dangerous!), please set
  environment variable "LMMS_IGNORE_BLACKLIST" to nonempty.
/usr/include/c++/12.2.0/array:217: constexpr const std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) const [with _Tp = lmms::Piano::KeyTypes; long unsigned int _Nm = 12; const_reference = const lmms::Piano::KeyTypes&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
[1]    31786 IOT instruction  lmms
</pre>
</details>

### PR DESCRIPTION
**Pull request by messmerd**
I used an AddressSanitizer build to find and fix some memory issues:
- Memory leak in LADSPA effects
- Memory leak in SimpleTextFloat
- Invalid iterator in AutomationClip
    - Occurred when adding and removing nodes in the Automation Editor
    - Likely the cause of Automation Editor crashes that I've experienced before
- Buffer overflow in PianoView
    - I didn't understand the logic of the code I wanted to fix, so I rewrote it. It works in a more straightforward and understandable way now, and the buffer overflow problem is fixed.
    - Fixes #6608
    
I'm sure there are more memory-related errors I could find and fix with ASan, but this is enough for now.

### CODE REVIEW

**Review by DomClark — COMMENTED** [review]
Do you plan on contributing the CAPS changes upstream? I checked https://github.com/moddevices/caps-lv2 and it appears the destructor still isn't virtual there.

**Comment by messmerd** [comment]
@DomClark 
I just submitted a PR for the CAPS changes upstream: https://github.com/moddevices/caps-lv2/pull/32

I guess next I should revert those changes in this PR and then later update the CAPS submodule if/when it gets merged upstream?

**Comment by DomClark** [comment]
> I guess next I should revert those changes in this PR and then later update the CAPS submodule if/when it gets merged upstream?

I think it's fine to keep the changes here. It doesn't looks like we've updated CAPS in a long time, and doing so is probably a somewhat larger task that shouldn't be a prerequisite for this fix. We've made a number of changes to our vendored copy of CAPS anyway, so it's not as if there isn't precedent for fixing things here.

File: src/core/AutomationClip.cpp [hunk 1]
```diff
@@ -345,13 +345,17 @@ void AutomationClip::removeNode(const TimePos & time)
...
+	if (it != m_timeMap.end())
 	{
-		--it;
+		if (it != m_timeMap.begin())
+		{
+			--it;
+		}
+		generateTangents(it, 3);
 	}
-	generateTangents(it, 3);
```
[the remark this answers is not in the document]
Comment (messmerd) [reply src/core/AutomationClip.cpp]: I agree that's a better way to do it. It should be fixed now.

**Review by DomClark — APPROVED** [review]

File: src/core/AutomationClip.cpp [hunk 2]
```diff
@@ -1106,31 +1106,23 @@ void AutomationClip::generateTangents(timeMap::iterator it, int numToGenerate)
 {
 	QMutexLocker m(&m_clipMutex);
 
-	if( m_timeMap.size() < 2 && numToGenerate > 0 )
+	for (int i = 0; i < numToGenerate && it != m_timeMap.end(); ++i, ++it)
```
Comment (sakertooth) [inline src/core/AutomationClip.cpp:1109]: I personally prefer we don't use the comma operator, since it made a bug hard to find awhile back. But if there isn't a choice somehow, then I don't mind.

Comment (DomClark) [reply src/core/AutomationClip.cpp:1109]: It's fairly idiomatic in the iteration expression of a for-loop when there are multiple iteration variables, and its arguments here aren't problematic. I agree in general though, and would avoid it if a semicolon would do the same job (which obviously isn't an option here). I think the other main place it's useful is in a fold expression when each element of the pack needs to be evaluated unconditionally.

**Review by sakertooth — APPROVED** [review]

**Comment by tresf** [comment]
> > I guess next I should revert those changes in this PR and then later update the CAPS submodule if/when it gets merged upstream?
> 
> I think it's fine to keep the changes here. It doesn't looks like we've updated CAPS in a long time, and doing so is probably a somewhat larger task that shouldn't be a prerequisite for this fix. We've made a number of changes to our vendored copy of CAPS anyway, so it's not as if there isn't precedent for fixing things here.

We have an open PR with the upstream fork here: #4027.  I think it's worthwhile to send any patches there.  Technically, they should probably go to Tim Goetze.  I'm not sure how often moddevices sends their code to him.  He's pretty picky about patches, quoting:

> Contact
> If you think you have found a bug in CAPS, or if you want to make a related or unrelated remark or inquiry please write to tim@quitte.de. 
> 
> Patches
> Please do not send patches without asking first.  By submitting a patch, you claim sole authorship and agree that your submission becomes mine to use in any way I see fit, in exchange for no obligation on my part except attribution in the CAPS documentation. 

If we decide not to, the patches will get lost once we upgrade and we'll have to backtrack a little.

**Comment by messmerd** [comment]
@tresf I contacted Tim Goetze in early September and we agreed upon a solution to the memory leak, but he hasn't released a new version of CAPS yet. I don't know when/if he plans to.
