### PR TITLE
Fix hard-coding of knob and LCDWidget text color

### LINKED ISSUE #2695: Make text of both MainToolbar and Tracks editable
captura de pantalla_2016-03-20_20-08-09

It's hard to make clear themes with no way to change these.

### PR DESCRIPTION
**Pull request by Umcaruje**
Fixes #2695 

Example CSS:
```
Knob {
	qproperty-textColor: blue;
}

LcdWidget {
	qproperty-textColor: blue;
	qproperty-textShadowColor: red;
}
```

screenshot from 2016-04-02 01 36 46  screenshot from 2016-04-02 01 36 51

If there's no property defined in the CSS, it inits to default colors.

### CODE REVIEW

**Comment by Umcaruje** [comment]
Ok, this is ready for a code review. I removed underscores from some of the function parameters, since that is no longer a coding convention.

File: include/Knob.h [hunk 1]
```diff
@@ -65,6 +65,8 @@ class EXPORT Knob : public QWidget, public FloatModelView
 	mapPropertyFromModel(float,volumeRatio,setVolumeRatio,m_volumeRatio);
 
 	Q_PROPERTY(knobTypes knobNum READ knobNum WRITE setknobNum)
+	
+	Q_PROPERTY(QColor textColor READ textColor WRITE setTextColor)
```
Comment (grejppi) [inline include/Knob.h]: Why not `color`? Or is it reserved for something else?

Comment (Umcaruje) [inline include/Knob.h]: https://github.com/LMMS/lmms/blob/master/data/themes/default/style.css#L582

It seems to be reserved for the knob color. Also, it'd be inconsistent with the rest of the codebase.

**Comment by IvanMaldonado** [comment]
Tested and working! :+1: 

captura de pantalla_2016-04-08_09-27-32

**Comment by Umcaruje** [comment]
No objections in over a week, merging
