### PR TITLE
fixes #6736: Sample tracks lose FX Channel

### LINKED ISSUE #6736: Sample Tracks in projects from latest alpha version lose their assigned FX Channel when loaded in Nightly
### Bug Summary
After upgrading from the latest alpha version to Nightly, projects loaded have all their Sample Tracks lose their assigned FX Channel. I don't know if this is specific to upgrading from alpha to nightly, or a random nightly build broke it, as I can't check older builds.
#### Steps to reproduce
Make a project in 89fc6c9 (2021-04-26 Alpha release)(or maybe an older nightly?), create a Sample Track, create an FX Channel, and assign it to the Sample Track. Save and load in Nightly (I'm using g7c6ade573), the Sample Track is now assigned to 0.
#### Expected behavior
It keeps the FX Channel assignment
#### Actual behavior
It resets to master fx channel
#### Screenshot
This is supposed to be assigned to channel 1 (Which in this case I assigned for percussion)
image
#### Affected LMMS versions
1.3.0-alpha.1.302+g7c6ade573
maybe others, I can't check

### PR DESCRIPTION
**Pull request by consolegrl**
Fixes #6736 : **Sample Tracks in projects from latest alpha version lose their assigned FX Channel when loaded in Nightly**

It was just like @PhysSong said, just needed someone to do the work.

### CODE REVIEW

**Comment by consolegrl** [comment]
@Spekular I decompressed and opened the mmp of the Mariana Trench file that the op of the issue uploaded, the one suffixed " - Nightly" had already had its data destroyed, there was no recovering the mixer channel. This fix will fix the original file from the op's archive, but after saving it in that nightly the channel was destroyed.  All files from before the FX Mixer rename will be upgraded correctly though.

File: src/core/DataFile.cpp [hunk 1]
```diff
@@ -1725,6 +1725,16 @@ void DataFile::upgrade_mixerRename()
 			fxch.item(i).toElement().removeAttribute("fxch");
 		}
 	}
+	// Change the attribute fxch of element <sampletrack> to mixch
+	fxch = elementsByTagName("sampletrack");
+	for(int i = 0; !fxch.item(i).isNull(); ++i)
```
Comment (sakertooth) [inline src/core/DataFile.cpp:1730]:
```suggestion
	for (int i = 0; !fxch.item(i).isNull(); ++i)
```

**Review by sakertooth — COMMENTED** [review]
Using ``!fxch.item(i).isNull();`` seems a bit awkward. Say there were 3 items, where the first element is not null, the second is null, and the third is not null. That third element would be ignored (this might not happen in practice, but it's worth mentioning the possibility). Using ``fxch.length()`` and skipping null items with ``continue`` seems like a better choice.

You can also store ``fxch.item(i)`` in a variable like ``auto item`` and access the element through ``item.toElement()``, and then store that in another variable like ``auto element`` so there's less repetition going on.

File: src/core/DataFile.cpp [hunk 2]
```diff
@@ -1725,6 +1725,16 @@ void DataFile::upgrade_mixerRename()
...
+	{
+		if(fxch.item(i).toElement().hasAttribute("fxch"))
```
[the remark this answers is not in the document]
Comment (consolegrl) [reply src/core/DataFile.cpp:1732]: @sakertooth Should I also correct this in the one for instrumenttrack above?

**Comment by consolegrl** [comment]
> Using `!fxch.item(i).isNull();` seems a bit awkward. Say there were 3 items, where the first element is not null, the second is null, and the third is not null. That third element would be ignored (this might not happen in practice, but it's worth mentioning the possibility). Using `fxch.length()` and skipping null items with `continue` seems like a better choice.
> 
> You can also store `fxch.item(i)` in a variable like `auto item` and access the element through `item.toElement()`, and then store that in another variable like `auto element` so there's less repetition going on.

@sakertooth Should I also fix this in the block directly before this one that upgrades the intstrumenttrack?

**Comment by sakertooth** [comment]
> @sakertooth Should I also fix this in the block directly before this one that upgrades the intstrumenttrack?

Yes. For that upgrade section in your other PR, I would've said the same thing I said here :+1:.

File: src/core/DataFile.cpp [hunk 3]
```diff
@@ -1703,26 +1703,56 @@ void DataFile::upgrade_mixerRename()
 {
 	// Change nodename <fxmixer> to <mixer>
 	QDomNodeList fxmixer = elementsByTagName("fxmixer");
-	for (int i = 0; !fxmixer.item(i).isNull(); ++i)
+	for (int i = 0; fxmixer.length(); ++i)
```
Comment (PhysSong) [inline src/core/DataFile.cpp:1706]:
```suggestion
	for (int i = 0; i < fxmixer.length(); ++i)
```

File: src/core/DataFile.cpp [hunk 4]
```diff
@@ -1703,26 +1703,56 @@ void DataFile::upgrade_mixerRename()
...
+		}
+		if (item.hasAttribute("fxch"))
+		{
+			item.setAttribute("mixch", item.attribute("fxch"));
+			item.removeAttribute("fxch");
+		}
+	}
+	// Change the attribute fxch of element <sampletrack> to mixch
+	fxch = elementsByTagName("sampletrack");
+	for (int i = 0; fxch.length(); ++i)
```
Comment (PhysSong) [inline src/core/DataFile.cpp:1745]:
```suggestion
	for (int i = 0; i < fxmixer.length(); ++i)
```

Comment (consolegrl) [reply src/core/DataFile.cpp]: Yeah I done goofed, was super sleepy, fixed now.

**Comment by messmerd** [comment]
There are a couple other instances in DataFile.cpp where iteration is performed like this:
```c++
for (int i = 0; !elements.item(i).isNull(); ++i)
{
    // ...
}
```

Maybe we should take a look into those usages to see if there are any bugs we haven't discovered yet.

**Comment by messmerd** [comment]
I've confirmed that this PR fixes the issue.

**Comment by consolegrl** [comment]
@messmerd I've been going with the "skip null entries" policy instead of "break at null entries" policy as was recommended by @sakertooth. I assume it's possible to have null elements in the XML tree and still have valid ones after.

**Review by sakertooth — COMMENTED** [review]
I'm just noticing this, but it seems ``DataFile`` is doing a lot of repetiton. Could you maybe add reusable functions for this class? For example, when you want to change the name of the elements, you could have the functions (the indenting might need to be fixed and code wasn't tested):
```cpp
void DataFile::changeNameOfElements(const QDomNodeList& elements, const QString& newTagName)
{
	for (int i = 0; i < elements.length(); ++i)
	{
		auto item = elements.item(i).toElement();
		if (item.isNull()) { continue; }
		item.setTagName(newTagName);
	}
}
```
And:
```cpp
void DataFile::changeNameOfAttributes(const QDomNodeList& elements, const QString& oldName, const QString& newName)
{
          for (int i = 0; i < elements.length(); ++i)
          {
                auto item = elements.item(i).toElement();
                if (item.isNull() || !item.hasAttribute(oldName)) { continue; )
                item.setAttribute(newName, item.attribute(oldName));
		item.removeAttribute(oldName);
          }
}
```
Then you can replace the first two upgrades in ``upgrade_mixerRename`` using ``changeNameOfElements`` and the last one with ``changeNameOfAttributes``. Similar operations probably exist elsewhere within this class, which is why it's nice having these since we can clean up these upgrade functions in the future easily if we ever wanted to. Dont feel the need to use these functions outside of ``upgrade_mixerRename`` for this PR obviously.

~~PS: I removed ``removeAttribute`` because [Qt replaces the attribute if it already exists, rather than adds it](https://doc.qt.io/qt-6/qdomelement.html#setAttribute).~~

Edit: Didn't see it was referring to the value, not the name. I applied the correction to the code.

**Comment by consolegrl** [comment]
> Then you can replace the first two upgrades in `upgrade_mixerRename` using `changeNameOfElements` and the last one with `changeNameOfAttributes`. Similar operations probably exist elsewhere within this class, which is why it's nice having these since we can clean up these upgrade functions in the future easily if we ever wanted to. Dont feel the need to use these functions outside of `upgrade_mixerRename` for this PR obviously.

Sure, we could even refactor it to take a lambda callback that it would run on each element, the question is just how crazy we wanna go/how much scope creep we want with this PR, maybe I create another issue "Refactor DataFile Upgrade Procedures" and work on it next week when I have time?

**Review by sakertooth — APPROVED** [review]

**Comment by messmerd** [comment]
> @messmerd I've been going with the "skip null entries" policy instead of "break at null entries" policy as was recommended by @sakertooth. I assume it's possible to have null elements in the XML tree and still have valid ones after.

I meant elsewhere in the file there are instances where the "break at null entries" policy is used, and maybe they could be the source of unreported bugs.

I searched for `.item(i).isNull();` and found 6 instances of it currently in DataFile.cpp.

However, it's probably beyond the scope of this PR to change them, and we don't even know for sure that it's actually causing any issues. It's just something worth noting.

**Review by messmerd — APPROVED** [review]
