### PR TITLE
Fix cloning of B/B tracks

### LINKED ISSUE #6062: Crash when trying to clone B/B pattern when there is not any
Steps to reproduce:
- Open an empty project with no B/B tracks
- Open the B+B editor
- Click on Clone Pattern button

Expected behavior:
Nothing happens

Actual behavior:
Instant crash.

### PR DESCRIPTION
**Pull request by dj-pixus**
Fixes #6062.
Also the editor changes to the new track correctly now.

### CODE REVIEW

File: src/gui/editors/BBEditor.cpp [hunk 1]
```diff
@@ -326,11 +326,15 @@ void BBTrackContainerView::clonePattern()
...
-	Track *newTrack = bbt->clone();
-
-	// Track still have the TCOs which is undesirable in this case, clear the track
-	newTrack->lock();
-	newTrack->deleteTCOs();
-	newTrack->unlock();
+	if( bbt )
+	{
+		// Clone the track
+		Track *newTrack = bbt->clone();
```
Comment (Spekular) [inline src/gui/editors/BBEditor.cpp:332]:
```suggestion
		BBTrack *newTrack = bbt->clone();
```
I don't have my dev machine running right now, do you mind checking if this works? It probably won't, but if it does you can remove the cast on the next line.

File: src/gui/editors/BBEditor.cpp [hunk 2]
```diff
@@ -326,11 +326,15 @@ void BBTrackContainerView::clonePattern()
...
+		bbtc->setCurrentBB( dynamic_cast<BBTrack *>( newTrack )->index() );
```
Comment (Spekular) [inline src/gui/editors/BBEditor.cpp:333]:
```suggestion
		bbtc->setCurrentBB( static_cast<BBTrack *>( newTrack )->index() );
```
I think you can use a static cast in this case. We know that `bbt` is a BBTrack, and since `newTrack` is cloned from `bbt` it should have the same type.

**Review by Spekular — COMMENTED** [review]
Good fix, I left a few minor suggestions.

File: src/gui/editors/BBEditor.cpp (hunk 1 above)
Comment (dj-pixus) [reply src/gui/editors/BBEditor.cpp:332]: Checked. Doesn't work because `clone()` always returns a `Track*`.
The static cast is fine though.

Comment (Spekular) [reply src/gui/editors/BBEditor.cpp:332]: Figures. Thanks for double checking.

**Review by Spekular — APPROVED** [review]
LGTM.
