### PR TITLE
Fix lost control links in copied automation patterns

### LINKED ISSUE #3359: Copies of  shapes in automation are wrong
OS  : winXP sp3
LMMS 1.1.90-RC2.8

**Issue description:**
Graphs/  shapes in automation are wrong, after they have been copied.

**Example          :**
copyautomarionerror
**Recreate         :**
New project
* drag a panning-dial into automation-track
* Open track
* insert automation like in the picture' top part
* Close editor
* ctrl+drag-copy block to other pos.
The result is like the second part of the picture
A similar issue exists for all 3 shapes, but in linear the bug will only apear if a *declining* pattern is drawn.

Bug is logical (no dial control), not just graphical

### LINKED ISSUE #3781: Control links are lost when duplicating automation clips
When using Copy/Paste or Ctrl+Drag to duplicate  an automation clip, the link to a control is lost.

This makes it very tedious to duplicate automation clips, as one needs to restore the links manually for each clip.

LMMS 1.2 RC3 Linux.

### PR DESCRIPTION
**Pull request by PhysSong**
As I said in #3781, I decided to work around the bug temporarily, at least in `stable-1.2`. I believe we can fix underlying issues as well, but the required change is too large for stable releases.
I think the ultimate solution is to decouple journaling and automation(see https://github.com/LMMS/lmms/issues/3781#issuecomment-407301931). I'll create a new issue to keep track on it once this PR gets merged.

Fixes #3781, fixes #3359.

### CODE REVIEW

File: src/core/AutomationPattern.cpp [hunk 1]
```diff
@@ -787,6 +787,16 @@ void AutomationPattern::resolveAllIDs()
 						{
 							a->addObject( dynamic_cast<AutomatableModel *>( o ), false );
 						}
+						else
+						{
+							// FIXME: Remove this block once the automation system gets fixed
+							// This is a temporary fix for https://github.com/LMMS/lmms/issues/3781
+							o = Engine::projectJournal()->journallingObject( *k + ( 1 << 23 ) );
```
Comment (jasp00) [inline src/core/AutomationPattern.cpp]: It is dangerous to mess with ProjectJournal internals like this. You should request new ids and copy data if necessary.

Comment (PhysSong) [reply src/core/AutomationPattern.cpp]: I also think this is a bad design, but this is the minimal fix for the bug which doesn't involve possibly dangerous structure changes for stable releases.
I want to remove this one in `master` as soon as I get my work completed.

Comment (jasp00) [reply src/core/AutomationPattern.cpp]: Please make it less minimal. Do not expose `EO_ID_MSB`.

**Comment by qnebra** [comment]
Possible regression with projects which single kind of parametr from multiple tracks connected to one automation track. For further checking.

File: src/core/AutomationPattern.cpp (hunk 1 above)
Comment (PhysSong) [reply src/core/AutomationPattern.cpp]: I didn't want to do so. However, changing `ProjectJournal` may affect other stuff than automation. I can address this, but it will make the *temporary* fix much complicated.

Comment (jasp00) [reply src/core/AutomationPattern.cpp]: Please address this.

Comment (jasp00) [reply src/core/AutomationPattern.cpp]: Do you want to become a coder or not?

Comment (PhysSong) [reply src/core/AutomationPattern.cpp]: What do you mean?

Comment (jasp00) [reply src/core/AutomationPattern.cpp]: Let us assume you want to be a better coder. Minimizing structural changes does not mean to make the smallest patch. Minimizing changes certainly does not mean breaking code organization.

I have asked you an easy task: do not expose `EO_ID_MSB`. It will not make your fix that much complicated. Could you give it a try? Do you need a hint?

Comment (PhysSong) [reply src/core/AutomationPattern.cpp]: I agree that the code organization is important, but we're on a branch targetting an upcoming release. Code organization is important in the long term, but bug fixes are more important for now. We consider design changes are out of the scope of `stable-1.2`, though they are important in `master`.
I will remove the exposure of `EO_ID_MSB` in `master`, with new changes in the design.

Comment (jasp00) [reply src/core/AutomationPattern.cpp]: Fine, I will fix your fix.

Comment (PhysSong) [reply src/core/AutomationPattern.cpp]: On which branch, and how?

Comment (zonkmachine) [reply src/core/AutomationPattern.cpp]: @PhysSong I think he intends fixing this in stable-1.2.
Merge this PR and we'll know for sure.

Comment (PhysSong) [reply src/core/AutomationPattern.cpp]: Okay. BTW, @jasp00, please note that you will probably make double work. I already have a fix with new designs and what I need to do is just cleaning them up.

Comment (DomClark) [reply src/core/AutomationPattern.cpp]: I think it makes more sense to argue using comments, rather than to argue using commits. We can merge or close once we've reached a consensus on what the code should look like.
Is the desired change something as simple as, e.g.
```cpp
jo_id_t ProjectJournal::idFromSave( jo_id_t id )
{
	return id | EO_ID_MSB;
}
```
?

Comment (PhysSong) [reply src/core/AutomationPattern.cpp]: I'm not sure if we need that, but that could be a solution.

Comment (PhysSong) [reply src/core/AutomationPattern.cpp]: @jasp00 If you're comfortable with the @DomClark's suggestion, I will use that for now.

Comment (jasp00) [reply src/core/AutomationPattern.cpp]: OK.
