### PR TITLE
Fix track name not updating

### LINKED ISSUE #7713: "Assign to new Mixer Channel" Does not update mixer channel name
### System Information

Arch Linux, GNOME 47

### LMMS Version(s)

1.3.0-alpha.1.771+gcd9af2478 (or any recent master)

### Most Recent Working Version

1.2.2

### Bug Summary

When you rightclick on a mixer channel LCD and select "Assign to" and "New Mixer Channel", it creates a new mixer channel, but the name of the mixer channel is not updated, it just stays at "Channel 13" or something. However, if you double-click on the mixer channel to rename it, the correct name appears. Or if you hover over it, the tooltip shows the correct name.

This bug does not occur in stable.

### Expected Behaviour

The name shown on the new mixer channel should be updated immediately after the mixer channel is created.

### Steps To Reproduce

- Make a new project
- Add an instrument
- Rightclick on the instrument's mixer channel LCD, select "Assign to"->"New Mixer Channel"
- The new mixer channel is created, but without the instrument's name.

### Screenshots / Minimum Reproducible Project

Image

Image

Image

### Please search the issue tracker for existing bug reports before submitting your own.

- [x] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by rubiefawn**
Fixes a regression from 07baf9e27a4990b2e1cc88b9cbe1347c70366d9d, in which a channel that was created through a tracks "Assign track to new mixer channel" context menu would display an incorrect name until it was renamed by a user.

It looks like the channel name was previously updated whenever there was a paint event, but that got optimized out. Since the channel name is set *after* the channel is created, but no "rename" had occurred, that meant it would display its default name until a user renamed it. This PR solves this by restoring that removed paint event code.

Resolves #7713.

### CODE REVIEW

**Review by regulus79 — COMMENTED** [review]
I briefly tested it and it appears to fix the issue, thanks a lot for making this PR!

File: src/gui/MixerChannelView.cpp [hunk 1]
```diff
@@ -197,6 +197,14 @@ void MixerChannelView::paintEvent(QPaintEvent*)
...
 	auto painter = QPainter{this};
 
+	// If name was updated without rename, such as when a channel is
+	// created for a track, forcefully update the name
+	const auto elidedName = elideName(channel->m_name);
+	if (!m_inRename && m_renameLineEdit->text() != elidedName)
+	{
+		m_renameLineEdit->setText(elidedName);
+	}
+
```
Comment (regulus79) [inline src/gui/MixerChannelView.cpp:207]: I'm curious whether it is best to put it in `paintEvent` or whether we should be relying on signals or something similar to trigger updates? My original idea was to somehow trigger an update of the name when it was set in `InstrumentTrackView::createMixerLine()`, but maybe this is more flexible?

Comment (rubiefawn) [reply src/gui/MixerChannelView.cpp:207]: I did think about signals, and it might be worth trying, but the current solution makes no changes to the class interfaces, and it's also what we were doing prior to the regression.

Comment (regulus79) [reply src/gui/MixerChannelView.cpp:207]: I assume it was removed for a reason, but I guess it is important that we fix this regression so maybe it's fine. Maybe https://github.com/LMMS/lmms/commit/07baf9e27a4990b2e1cc88b9cbe1347c70366d9d did not realize that the name could be set outside of the mixer channel view class, and so only added the `m_renameLineEdit->setText(elideName(mixerChannel->m_name));` to `MixerChannelView::setChannelIndex(int index)`.

@sakertooth, you did the refactoring in that commit, do you have any opinions in this?

Comment (sakertooth) [reply src/gui/MixerChannelView.cpp:207]: Hi @regulus79, IMO, I have no idea why this code is in the paint event. IIRC, this code was already here before I did my refactoring. I think we should definitely move this out the paint event and into a Qt signal.

Comment (sakertooth) [reply src/gui/MixerChannelView.cpp:207]: Ideally, the name of the `MixerChannelView` would be passed into the constructor to initialize it, and there should also be Qt signals in place so that it is updated when necessary.

Comment (rubiefawn) [reply src/gui/MixerChannelView.cpp:207]: > IIRC, this code was already here before I did my refactoring.

Yes, you *removed* that code in the refactor, presumably for the same reason you are suggesting it be removed now. It's weird for the name stuff to be in the paint event. You weren't/aren't wrong about that.

> Ideally, the name of the `MixerChannelView` would be passed into the constructor to initialize it, and there should also be Qt signals in place so that it is updated when necessary.

This is possible, but the existing code for creating a mixer channel through for a track is kind of convoluted. There's a reason I did not choose this approach at first, even if it is a more correct approach. Here's how a mixer channel is created in this context:

1. Either the `InstrumentTrackView::createMixerLine()` or `SampleTrackView::createMixerLine()` slot receives a signal;
2. `createMixerLine()` requests the `MixerView` to `addNewChannel()` by calling it directly (even though it is a slot?)
3. `MixerView::addNewChannel()` asks the `Mixer` to `createChannel()`
4. The `Mixer` pushes a new instance of `MixerChannel` onto its internal vector of `MixerChannels` (it is unnamed at this point)
5. The `Mixer` then sets the channel name to the default name using `Mixer::clearChannel()`
6. `Mixer::createChannel()` returns the channel index to `MixerView:addNewChannel()`, which returns the channel index to `createMixerLine()`
7. `createMixerLine()` sets the channel name to the track's name (but the channel has already been painted with the default name!)

So yes, I could solve this by passing the name through that entire call stack. It's ugly.

Comment (regulus79) [reply src/gui/MixerChannelView.cpp:207]: Should we just merge this quick fix now, and leave refactoring the mixer channel/view system for a future PR?

Comment (rubiefawn) [reply src/gui/MixerChannelView.cpp:207]: I think I have the correct but ugly version working, I'm compiling to double-check that it works as intended. I'll push that, and you guys can choose which version you hate less.

Comment (rubiefawn) [reply src/gui/MixerChannelView.cpp]: @sakertooth I've made those changes. It's no longer in the paint event

Comment (tresf) [reply src/gui/MixerChannelView.cpp]: > `createMixerLine()` sets the channel name to the track's name (but the channel has already been painted with the default name!)

Hmm... This is odd because `createMixerLine` calls `assignMixerLine` which calls `setCurrentMixerChannel(int)` which calls `setCurrentMixerChannel(MixerChannelView)` which calls `updateMixerChannel` which calls `update()`, which will schedule a repaint on the main event loop.

Comment (rubiefawn) [reply src/gui/MixerChannelView.cpp]: I'll take a closer look at that tomorrow, you're right about `assignMixerLine()`. Earlier I had set up a `qDebug()` in the paint event to show me what the mixer's actual name was, and it did not indicate that it was secretly repainting it with the correct name. Spooky.

Comment (sakertooth) [reply src/gui/MixerChannelView.cpp]: @rubiefawn, seeing the most recent changes, I can understand why you were concerned. This feels very wrong (e.g., passing in a name parameter to `Mixer::clearChannel`). `Mixer` needs a refactoring, but we shouldn't succumb to bad solutions if we can help it.

For this problem, I see the overall flow like this:
1. User clicks on "Assign to mixer channel"
2. The GUI code (`createMixerLine`) involved in that will go to `MixerView` and tell it to make a new channel
3. `MixerView` will then go to `Mixer` and will create the channel and return the added `MixerChannelView` as a pointer
4. `createMixerLine` will then call some `MixerChannelView::setName` member function to set its name to its own
5. `MixerChannelView::setName` will update its own name stored in `m_renameLineEdit`, while also calling `MixerChannel::setName` on the channel it has been assigned to. Alternatively, `MixerView::addNewChannel` can take as a parameter a name instead and call a new `MixerChannelView` constructor that initializes the new channel with the specified name.

The problem seems to be that while `createMixerLine` was setting the name already, but the update wasn't received by other parts of the GUI, only the Core got it.

`createMixerLine` could go to the Core directly, but then you would need Qt signals, and `MixerChannel` is not a `QObject`, so it would have to go in `Mixer`. This is a more convoluted flow. I'm not sure if I'm the first to have this opinion, but if at all possible, we should not be adding Qt signals to the Core directly. Qt signals were meant to signal other parts of the GUI of updates. If the Core did this, not only is separating Qt from the Core harder (i.e., you have to inherit from `QObject` somewhere), but since the Core cannot always send a Qt signal, it would have to delegate it to some other object that is one, which is more complex and sometimes not possible.

Comment (tresf) [reply src/gui/MixerChannelView.cpp]: > (I know I just said that Qt signals could be used here, but I thought about the problem more, and any Qt signals should still reside only in the GUI, so for example `createMixerLine` could talk to `MixerView` using Qt signals instead of through the `getGUI` function if it wanted, but that's a separate topic)

Reminds me a bit of this discussion.... https://github.com/LMMS/lmms/issues/1600#issuecomment-69869253 👀

Comment (tresf) [reply src/gui/MixerChannelView.cpp]: (starts getting relevant to this discussion right around here: https://github.com/LMMS/lmms/issues/1600#issuecomment-69933813)

**Comment by bratpeki** [comment]
Tested with long and unusual names, that's it! :rocket:

**Review by bratpeki — APPROVED** [review]

File: src/gui/MixerChannelView.cpp (hunk 1 above)
Comment (rubiefawn) [reply src/gui/MixerChannelView.cpp]: Does anybody still feel strongly about keeping the code out of the paint event?

Comment (sakertooth) [reply src/gui/MixerChannelView.cpp]: @rubiefawn did you see my most recent message?

Comment (rubiefawn) [reply src/gui/MixerChannelView.cpp]: I did, but it seemed more exploratory than prescriptive. Restoring the paint event code doesn't make it any worse than it was before the regression, is known to work, and is a 3 line diff, so I thought I'd ask.

Comment (sakertooth) [reply src/gui/MixerChannelView.cpp]: It was meant to be a practical explanation, not a theoretical one, but I suppose we can do the easy solution for now that is a 3 line diff and fix it up later.

Comment (sakertooth) [reply src/gui/MixerChannelView.cpp]: Maybe just add a TODO comment in that case.

Comment (rubiefawn) [reply src/gui/MixerChannelView.cpp]: Also, I don't really see how the suggested method is better:

> `MixerChannelView::setName` will update its own name stored in `m_renameLineEdit`, while also calling `MixerChannel::setName` on the channel it has been assigned to. 

This suggestion is just the current state of `master`: the name is updated after the `MixerChannel` has already been created. Wouldn't this have the exact same regression?

> Alternatively, `MixerView::addNewChannel` can take as a parameter a name instead and calls a new `MixerChannelView` constructor that initializes the new channel with the specified name.

I'm not sure I understand this one. It's either the same thing as my second solution, or it has other problems:

The `MixerChannel` owns the channel name. Exposing a way for the `MixerChannelView` to be initialized with a name by anything other than its corresponding `MixerChannel` seems like a mistake, and even more of a hack than forcing the `MixerChannelView` to double-check itself in the paint event. The only time the `MixerChannelView`'s visible name should be different than its `MixerChannel` is length elision (and if it weren't for name length elision it would be wrong for `MixerChannelView` to even store a copy of the name in the first place).

Comment (sakertooth) [reply src/gui/MixerChannelView.cpp]: My suggestion would update both the Core and the GUI, while `master` only updates from the Core, which is the problem. `MixerChannelView::setName` should update itself and the Core.  No need to talk about this though, it can be done later.

Comment (tresf) [reply src/gui/MixerChannelView.cpp]: Would you consider this less hacky?

```diff
diff --git a/src/gui/MixerView.cpp b/src/gui/MixerView.cpp
index d05ff097d..0fc390b53 100644
--- a/src/gui/MixerView.cpp
+++ b/src/gui/MixerView.cpp
@@ -376,6 +376,9 @@ void MixerView::updateMixerChannel(int index)
        }
 
        thisLine->m_sendButton->updateLightStatus();
+       // TODO: Find out why update() doesn't do this
+       thisLine->renameChannel();
+       thisLine->renameFinished();
        thisLine->update();
 }
```

Comment (rubiefawn) [reply src/gui/MixerChannelView.cpp]: Actually yeah, that way it doesn't happen ever paint event.

I also realized I hadn't even looked at the [Qt docs](https://doc.qt.io/qt-5/qwidget.html#update) yet:

> Calling `update()` several times normally results in just one [`paintEvent()`](https://doc.qt.io/qt-5/qwidget.html#paintEvent) call.

Is it possible that `update()` is just not repainting it since it happens so quickly after the first repaint?

**Review by tresf — APPROVED** [review]

**Comment by bratpeki** [comment]
> Tested with long and unusual names, that's it! 🚀

Retested, all good!

File: src/gui/MixerChannelView.cpp (hunk 1 above)
Comment (sakertooth) [reply src/gui/MixerChannelView.cpp]: Oh wow, interesting stuff.

**Review by sakertooth — APPROVED** [review]
This change makes sense: `TrackView::createMixerLine` from derived classes call `MixerView::addNewChannel`, which then calls `MixerView::updateMixerChannel` as expected, but we forgot to update the name as well. I wonder if we can catch this within a test.. probably, but no need to worry about that here.

Peki already tested this, so LGTM

**Comment by tresf** [comment]
Slightly off-topic, but this PR made me very happy.  Nice teamwork!
