### PR TITLE
Fix #4201: BB editor: adjust cursor position

### LINKED ISSUE #4201: Beat editor: clicking on a beat toggles the previous beat on/off
I'm using a fairly large amount of beats on a small window (48 beat/12 bars) and the actual click area of each beat does not correspond to the beat itself as-draw. Instead, it often will toggle the beat to the left of it, even when I'm clicking it *very obviously* on the right beat.

OK just as I'm writing this I think I notice what's wrong. When I move the cursor on to the beat, if goes from the normal system cursor to a "pointing hand" and the actual cursor click does not register on the position of the pointing finger but on the thumb instead, which is a few pixels to the left.

Here's what I mean: even though the index finger is clearly on the right beat, the click registers on the thumb instead (left beat):

screenshot_20180228_152152

I'm not sure if that's my system's cursor too or something that comes with LMMS. Either way, it gets pretty confusing, especially when working with more beats in less screen space so an alternative would be great.

### PR DESCRIPTION
**Pull request by JohannesLorenz**
This fixes an offset for cursors whose pointer position varies between
different themes.

~~TODO: Offset is not 100% accurate yet. (16, 16) is wrong, but it's
good for testing.~~ -> Fixed. Un-drafting PR.

### CODE REVIEW

**Comment by JohannesLorenz** [comment]
I recommend Veratil should check the code, as he designed a proposal for it and is involved in the issue.

File: src/core/Track.cpp [hunk 1]
```diff
@@ -572,7 +580,7 @@ void TrackContentObjectView::leaveEvent( QEvent * e )
 {
 	if( cursor().shape() != Qt::BitmapCursor )
 	{
-		setCursor( QCursor( embed::getIconPixmap( "hand" ), 3, 3 ) );
+		setCursor( QCursor( embed::getIconPixmap( "hand" ), m_mouseHotspotX, m_mouseHotspotY ) );
```
Comment (JohannesLorenz) [inline src/core/Track.cpp:583]: Looking at this now, I think we need to add `3` and `3` in the "classic" theme CSS?

File: src/core/Track.cpp [hunk 2]
```diff
@@ -317,6 +319,12 @@ TrackContentObjectView::~TrackContentObjectView()
  */
 void TrackContentObjectView::update()
 {
+	if( !m_cursorSetYet )
```
Comment (JohannesLorenz) [inline src/core/Track.cpp:322]: I only set this once to avoid setting the cursor all the time. I hope this is enough, but the mouse hotspot should actually never change during runtime, right?

Comment (Spekular) [reply src/core/Track.cpp:322]: It can be set when a cursor is constructed, isn't that enough?

Comment (Spekular) [reply src/core/Track.cpp:322]: Nevermind, I missed your comment in the issue post.

Comment (JohannesLorenz) [reply src/core/Track.cpp:322]: What do you mean? The cursor has already been constructed in `TrackContentObjectView`'s CTOR, and at that time, the hotspot is not yet read from the CSS.

File: src/core/Track.cpp (hunk 1 above)
Comment (zonkmachine) [reply src/core/Track.cpp:583]: Correct, and I believe the new cursor was using something like 3, 7 last I tried it.

Comment (JohannesLorenz) [reply src/core/Track.cpp:583]: How do you find out the right coordinates? Opening both images in gimp/etc and just use where the finger points? If yes, I think it's (2,7) for the default, and (3,3) for the classic.

Comment (zonkmachine) [reply src/core/Track.cpp:583]: Right, 2,7. I've added the settings for classic too and this works fine.

Comment (JohannesLorenz) [reply src/core/Track.cpp:583]: Thanks, added this in a new commit.

**Comment by JohannesLorenz** [comment]
I tested it and now the mouse selects exactly the correct patterns (though it might be subjective where exactly the finger points). IMO there's no testing required, only the code review.

**Comment by JohannesLorenz** [comment]
CI (Windows) just complained:
```
/home/travis/build/LMMS/lmms/include/Track.h:314:24: error: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [-Werror]

  bool m_cursorSetYet = false;
```
Can't we set -std=c++11? Otherwise, I'll change this code ofc.

**Comment by PhysSong** [comment]
We disabled C++11 for some plugins on `stable-1.2`, so I think you need to change the code.

File: data/themes/classic/style.css [hunk 3]
```diff
@@ -618,6 +618,9 @@ TrackContentObjectView   {
 	qproperty-textColor: rgb( 255, 255, 255 );
 	qproperty-textShadowColor: rgb( 0, 0, 0 );
 	qproperty-gradient: true; /* boolean property, set true to have a gradient */
+	/* finger tip offset of cursor */
+	qproperty-mouseHotspotX: 3;
```
Comment (Spekular) [inline data/themes/classic/style.css:622]: Can we name this something more specific, since we have several different cursors? `cursorHotspotX-hand`?

For example, when the Knife tool is merged that will have it's own cursor which should ideally be themeable as well. If this is merged as-is and then renamed, we'd end up breaking themes between 1.2 and 1.3 unnecessarily.

File: include/Track.h [hunk 4]
```diff
@@ -226,13 +228,18 @@ class TrackContentObjectView : public selectableObject, public ModelView
 	QColor textShadowColor() const;
 	QColor BBPatternBackground() const;
 	bool gradient() const;
+	int getMouseHotspotX() const { return m_mouseHotspotX; }
+	int getMouseHotspotY() const { return m_mouseHotspotY; }
```
Comment (Spekular) [inline include/Track.h:232]: Are these functions necessary? I removed all references to `getMouseHotspot_`, and the PR still compiled and worked as expected. Once again, I'm concerned about adding more cursors, so it'd be ideal if each one took as few lines as possible.

**Comment by Spekular** [comment]
> IMO there's no testing required, only the code review.

I tested anyway, works as expected! I left a review, but technically the comments aren't relevant for 1.2. Looks good otherwise.

File: data/themes/classic/style.css (hunk 3 above)
Comment (JohannesLorenz) [reply data/themes/classic/style.css:622]: Wouldn't that knife symbol need to be treated the same way in order to hit the right B&B blocks? With your proposition, we'd then name it `cursorHotspotX-knife`?

Comment (Spekular) [reply data/themes/classic/style.css:622]: Yes, that's what I'm thinking.

File: include/Track.h (hunk 4 above)
Comment (JohannesLorenz) [reply include/Track.h:232]: Indeed, I removed those here and after the `READ` in the properties. Works fine.

File: data/themes/classic/style.css (hunk 3 above)
Comment (Spekular) [reply data/themes/classic/style.css:622]: The exact naming scheme is up to you of course, the essence of the suggestion is just to add the specific cursor type somewhere in the property name.

Comment (JohannesLorenz) [reply data/themes/classic/style.css:622]: Oh I think I get what you mean. We now have only one cursor (per theme), so one "qproperty" is always enough to describe the offset. But if we have two cursors (per theme), we need to qproperties, because the offsets can differ (between knife and hand). Do you mean that?

Comment (Spekular) [reply data/themes/classic/style.css:622]: Yes!

Comment (Veratil) [reply data/themes/classic/style.css:622]: What if we make a new class which contains all the cursor data?

Also, I'm looking at how to make `QPoint` properties which will allow us to do something like `qproperty-hotspot-hand: 3 3;`

Comment (JohannesLorenz) [reply data/themes/classic/style.css:622]: @Veratil I like the `QPoint` idea. About the new class, sounds good, but how would our `TrackContentObjectView` access that class? Do you plan that each class that needs these cursor data should inherit that special class? If such a class must inherit `QObject`, we must be careful with diamond inheritance.

Comment (zonkmachine) [reply data/themes/classic/style.css:622]: This PR looks good to merge to me. Do you intend the proposed new class to be implemented here? (_this PR, stable-1.2_)

Comment (JohannesLorenz) [reply data/themes/classic/style.css:622]: @zonkmachine That was the idea.

**Comment by JohannesLorenz** [comment]
I just pushed rework which now uses `QSize` instead of 2 integers. I agreed with Veratil that this solves his comment.

Can someone please code-review this small commit ( 943062a ) ? Maybe @Spekular (you did the initial review) or @Veratil ? Then we can merge.

**Review by Spekular — APPROVED** [review]
LGTM! 🎉
