### PR TITLE
fix #6807: Marked notes bleed into note velocity

### LINKED ISSUE #6807: Marked notes bleed into note velocity
### Bug Summary
One row of marked notes in the piano roll bleed into the velocity editor for notes

#### Steps to reproduce
Mark notes either manually or using the Scale setting feature, and scroll so that a marked note is at the top of where the velocity section is
#### Expected behavior
it doesn't, like it did before
#### Screenshot
image

#### Affected LMMS versions
ge87d44b42

### PR DESCRIPTION
**Pull request by consolegrl**
Issue was caused by an obiwan (off-by-one)
The 'if (y > limit)' test was broken by an incorrect inequality,
 should be >=, and a graphical adjustment made previously in the
 'y = ...' statement. I perserved the graphical adjustment and
 fixed the test to be 'if (y >= limit - 1) { break; }'
 
 Fixes #6807

### CODE REVIEW

**Comment by Veratil** [comment]
Looks good! I'm glad my thought was correct that it seemed to be an off by one. :)

**Comment by Veratil** [comment]
Hm, link to the issue isn't updating in the title, so linking here: #6807

File: src/gui/editors/PianoRoll.cpp [hunk 1]
```diff
@@ -3357,7 +3357,7 @@ void PianoRoll::paintEvent(QPaintEvent * pe )
 			const int key_num = m_markedSemiTones.at(x);
 			const int y = keyAreaBottom() - 1 - m_keyLineHeight *
 				(key_num - m_startKey + 1);
-			if(y > keyAreaBottom()) { break; }
+			if(y >= keyAreaBottom() - 1) { break; }
```
Comment (Veratil) [inline src/gui/editors/PianoRoll.cpp:3360]: Not sure when the space got deleted here, but it should be there.
```suggestion
			if (y >= keyAreaBottom() - 1) { break; }
```

**Review by Veratil — APPROVED** [review]
Style not needed for merge, but would be appreciated. 👍

**Comment by sakertooth** [comment]
> Hm, link to the issue isn't updating in the title, so linking here: #6807

Odd, still doesn't appear for me. Maybe try adding it to the PR description (if you are able to do so)? I also think it could've linked if the commit stated ``fix #6807`` instead of ``fix: Issue 6807``

**Comment by consolegrl** [comment]
Sorry about the style issue, will review thoroughly for next time :)

**Comment by consolegrl** [comment]
Woops, didn't mean to close it yet, sorry; am new.

File: src/gui/editors/PianoRoll.cpp (hunk 1 above)
Comment (consolegrl) [reply src/gui/editors/PianoRoll.cpp:3360]: Yep seems so.

**Comment by consolegrl** [comment]
Hey @Veratil do I need to do some more for merge or are we just waiting on a maintainer approval?

**Comment by IanCaio** [comment]
> Hey @Veratil do I need to do some more for merge or are we just waiting on a maintainer approval?

Usually it takes 2 approvals for a merge (or more if some of the active devs show interest in reviewing)

**Review by IanCaio — APPROVED** [review]
LGTM by the way :smile:
