### PR TITLE
Fix regressions on loading broken projects

### LINKED ISSUE #781: Attempting to open non-readable project clears project
This is mostly a cosmetic problem, as the user probably doesn't mind the project disappearing. But it is a bit surprising IMO. At least checks for existence and readability of the project file should go before clearing out the old one.

(Master branch)

### PR DESCRIPTION
**Pull request by zonkmachine**
The original issue #781 concerned active projects being overwritten by a default project on failing to load another project.
This was closed in #1258 which worked indeed but broke handing a default project on failing to load from the command line. Also, failing to open a project, be it from the command line or gui, still sets the project title.
Enter #1838 which breaks testing of if the project could be opened. It replaces this with a suffix test. I simply revert that line.

This should fix #781 without breaking anything.

### CODE REVIEW

File: include/Song.h [hunk 1]
```diff
@@ -340,6 +340,7 @@ private slots:
 	QString m_fileName;
 	QString m_oldFileName;
 	bool m_modified;
+	bool m_loadOnLaunch;
```
Comment (zonkmachine) [inline include/Song.h]: Yes,`song::loadProject( ... )` needs to know if the project is loaded on launch or from the gui. If there is a way to do this already we can drop this bool or if you have a better name for `m_loadOnLaunch` no one is happier than me.

File: src/core/Song.cpp [hunk 2]
```diff
@@ -947,17 +949,24 @@ void Song::loadProject( const QString & fileName )
...
 	Engine::projectJournal()->setJournalling( false );
 
+	m_oldFileName = m_fileName;
 	m_fileName = fileName;
-	m_oldFileName = fileName;
 
 	DataFile dataFile( m_fileName );
 	// if file could not be opened, head-node is null and we create
 	// new project
-	if( dataFile.validate( fileName.right( fileName.lastIndexOf(".") ) ) )
```
Comment (zonkmachine) [inline src/core/Song.cpp]: If dataFile.validate() is needed here we could keep it in with `an &&` but right now it seem to be kind of broken. The only other place that calls it is in [/src/gui/FileBrowser.cpp](https://github.com/zonkmachine/lmms/blob/9ea7f2eb3419a581651ef71ad11ed7ce366cde04/src/gui/FileBrowser.cpp#L421) but it doesn't seem to execute properly. Try dragging or double clicking on some random non-valid file in the "My Projects" or samples. The message box should appear but it doesn't. It does however if I invert the logic (removes the ! in the linked line above) but that's prone to crashing. For now, here, `dataFile.head().isNull()` should be enough.

**Comment by zonkmachine** [comment]
Tested, works... Mergez!
