### PR TITLE
Fix VST parameter automation performance

### LINKED ISSUE #8066: High CPU usage when controlling VST plugin/instrument from LMMS host
### System Information

GNU/Linux OS, Manjaro distribution

### LMMS Version(s)

1.3.0-alpha.1.880+2eea79b

### Most Recent Working Version

Stable perhaps

### Bug Summary

LMMS starts lagging when VST plugins or instruments are being controlled from the window that can be opened by pressing wrench icon. It lags less when window of VST plugin (not instrument) is closed

### Expected Behaviour

No lag should occur (or at least it should lag much less)

### Steps To Reproduce (VST plugin)

1. Put TripleOscillator to the Song Editor
2. Create an LFO
3. Put VST plugin on TripleOscillator (I used FreeClip)
4. Open plugin window by clicking `Controls` button and click on the wrench button which should say `Control VST plugin from LMMS host`
5. Hook up the LFO to any knob (I used `Ceiling`)
6. Play the instrument, CPU usage should increase

</pre>
</details>

### Screenshots / Minimum Reproducible Project

https://github.com/user-attachments/assets/3e0b9acb-4eda-4286-aebe-7a2533071287

### Please search the issue tracker for existing bug reports before submitting your own.

- [ ] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by messmerd**
Fixes #8066

<details>
<summary>Before</summary>

https://github.com/user-attachments/assets/d9aa0f04-0cb7-4e08-b8b5-364bf7b29544

</details>

<details>
<summary>After</summary>

https://github.com/user-attachments/assets/e90050fc-cb89-464a-826d-1688e49388c9 

</details>

## The cause
Every time any VST parameter was modified, Vestige and VST effects would update the parameter labels and display text for *all* of their parameters.

This is bad because the parameter labels/display are only used by the text floats for parameter knobs, and exactly 0 or 1 text floats for knobs are visible at any given time globally. So it was making expensive calls into RemotePlugin to update the text for *all* parameters, even though this is only needed for at most 1 parameter and most of the time is not needed at all.

This performance regression was introduced by #5321, as @sakertooth explained [here](https://github.com/LMMS/lmms/issues/8066#issuecomment-3865899522).

## A solution
- I added RemoteVstPlugin op codes for updating a single parameter label or display text rather than all of them
- Removed some unnecessary string copies in `RemotePlugin`
- Refactored `FloatModelEditorBase`, replacing the `displayValue()` method with two methods for setting/updating the value of the SimpleTextFloat:
  ```cpp
  virtual QString getCustomFloatingText();
  virtual std::optional<QString> getCustomFloatingTextUpdate();
  ```
  What these do is explained in the comments.
- Added `VstPluginKnob` class which implements `Knob` for Vestige/VST Effects.
  - This knob implementation limits the rate of updates to the floating text. Without rate limiting, the CPU spikes when the text float is visible and the parameter's value is changing rapidly, so I had to add this in. (Note: This solves a performance issue specific to `RemotePlugin`, not something that affects other knobs, so putting it in a `Knob` implementation for VSTs is appropriate.)
  - Uses the new RemoteVstPlugin op codes to only update a specific parameter's text rather than all of them
- Removed `CustomTextKnob`  since a superset of its functionality is now supported by `Knob` as well as every other class that inherits from `FloatModelEditorBase`.

Bonus:
- I moved the weird volume knob hacks from `FloatModelEditorBase` into a new class called `VolumeKnob` which inherits from `Knob`. This isn't strictly necessary for this PR, but it makes `FloatModelEditorBase` significantly smaller in size (and therefore `Knob` as well). These changes are self-contained in this commit: https://github.com/LMMS/lmms/commit/1e5ca51bee215099903112652dad33dc611b3daa

### CODE REVIEW

File: include/FloatModelEditorBase.h [hunk 1]
```diff
@@ -62,21 +61,47 @@ class LMMS_EXPORT FloatModelEditorBase : public QWidget, public FloatModelView
...
+
+		/**
+		 * Floating text is updated by an external component calling `pushFloatingText` when needed.
+		 *
+		 * This mode may optionally function in a hybrid fashion where this widget periodically emits
+		 * the `floatingTextUpdateRequested` signal for an external component to respond to by pushing
+		 * an update to `pushFloatingText`.
+		 */
+		Push
+	};
```
Comment (sakertooth) [inline include/FloatModelEditorBase.h]: I'm guessing the difference is that `Pull` still sends a message and blocks the audio thread (although far more deterministically since only one text float is being updated, not N text floats), and ‘Push‘ bypasses that entirely via a separate Qt signal?

I feel like with plugins like VST, the common approach is the host pulling the data you need from the plugin. What's the purpose of `Push`? Is it just more optimal given the current faulty IPC system?

**Comment by sakertooth** [comment]
Why the complication with the timers, `Push`/`Pull` mode and all? Isn't it just "when this knob's value changes, update its tooltip by sending a message and then using the updated string as the tooltip for the knob that was returned"? Though this does make stuff like automation less efficient since its rapidly changing (instead of the polling approach you used), though I wonder if that could suffice if only one tooltip is being updated, not for all the knobs. I feel like with a better IPC system the solution would be straightforward (if needed at all), but we're not there yet.

And I don't get why we have a separate `SimpleTextFloat` class (which I am guessing is the tooltip for the knob)?

**Comment by messmerd** [comment]
@sakertooth I agree the design was pretty ugly and convoluted. I just finished refactoring the PR, and now it's much cleaner and more straightforward. I no longer have any unease about the design.

> Why the complication with the timers

> Isn't it just "when this knob's value changes, update its tooltip by sending a message and then using the updated string as the tooltip for the knob that was returned"? 

When I tested it without a timer to limit the rate of updates, it caused the CPU to spike whenever I rapidly adjusted the value of a parameter while the text float was visible. This is even after all the other optimizations. But with some simple rate limiting using a timer, there's no such problem.

Before I reworked the PR, the timer stuff was cluttering up the `FloatModelEditorBase` base class used by all knobs, but now it has been moved to a new class `VstPluginKnob` used only by VSTs, which is a much better place for it.

**Comment by sakertooth** [comment]
@messmerd, nice, I'll try to review again when I have time.

> When I tested it without a timer to limit the rate of updates, it caused the CPU to spike whenever I rapidly adjusted the value of a parameter while the text float was visible. This is even after all the other optimizations. But with some simple rate limiting using a timer, there's no such problem.

Isn't this a bandage fix (and if so, should we make note of that)? Rate limiting wouldn't be necessary if the messages to update the parameters were sent on another queue for communication between the UI and the plugin, such that the audio thread wouldn't be blocked on messages it doesn't care about, right? Perhaps this is a more suitable approach to solving this problem, but if its too much to ask for here, we shouldn't need to worry much about the ideal.

**Comment by messmerd** [comment]
@sakertooth 
There should definitely be separate channels for main/GUI thread messages and audio thread messages. For the audio thread, there should be a message queue since time-stamped events need to be pushed onto a queue during each processing period then sent to the plugin to read all at once during the process method.

For main/GUI thread messages, such as the messages for updating parameter text that this PR uses, maybe there shouldn't be a queue and the messages should just be sent synchronously as soon as possible. Of course, main/GUI thread messages and audio thread messages would be sent concurrently and not interfere with each other.

For the parameter text updates, it's different from other more important messages because it happens regularly and there is no significant penalty if it fails, so it makes sense to me to place a limit on how often it can be called. Even after an IPC rewrite, I think rate limiting could still be good for performance. Whether the rate limiting should be implemented in a generic fashion in `RemotePlugin` or `AutomatableModel` in future, I'm not sure, but if that happens, it will require some more thought and would have to happen during/after the IPC rewrite. And who knows, maybe after the IPC rewrite, performance would be so good that rate limiting won't be worth having due to the extra complexity. I don't know.

But for now, rate limiting for VST parameter text updates makes a noticeable improvement to performance, and the implementation is confined to `VstPluginKnob`, so nothing else depends on it and it's not difficult to remove if we ever decide to do so.

File: src/gui/widgets/Knob.cpp [hunk 2]
```diff
@@ -530,6 +531,46 @@ void Knob::changeEvent(QEvent * ev)
 	}
 }
 
+QString VolumeKnob::getCustomFloatingText()
+{
+	auto const valueToVolumeRatio = model()->getRoundedValue() / volumeRatio();
```
Comment (sakertooth) [inline src/gui/widgets/Knob.cpp]: Doesn't really matter, but do we have a convention in place for `auto const` vs `const auto`?

File: plugins/VstBase/VstPlugin.h [hunk 3]
```diff
@@ -173,7 +176,30 @@ public slots:
...
+class VSTBASE_EXPORT VstPluginKnob : public gui::Knob
+{
+public:
+	VstPluginKnob(VstPlugin* plugin, int paramIndex, const QString& name, QWidget* parent);
+	~VstPluginKnob() override = default;
+
+private:
+	void timerEvent(QTimerEvent* event) override;
+
+	auto getCustomFloatingText() -> QString;
```
Comment (sakertooth) [inline plugins/VstBase/VstPlugin.h]: `clangd` was flagging a warning for this.

```suggestion
	auto getCustomFloatingText() -> QString override;
```

File: src/gui/widgets/SimpleTextFloat.cpp [hunk 4]
```diff
@@ -76,8 +76,15 @@ void SimpleTextFloat::showWithDelay(int msecBeforeDisplay, int msecDisplayTime)
 	}
 }
 
+void SimpleTextFloat::show()
+{
+	m_hideTimer->start();
```
Comment (sakertooth) [inline src/gui/widgets/SimpleTextFloat.cpp:81]: I was thinking all the rate limiting/timer logic would be in `VstPluginKnob`.

File: include/FloatModelEditorBase.h [hunk 5]
```diff
@@ -98,23 +86,54 @@ class LMMS_EXPORT FloatModelEditorBase : public QWidget, public FloatModelView
...
+	 * This method controls only the "custom text" portion.
+	 * To modify the other portions, call setDescription() or setUnit().
+	 *
+	 * @returns the up-to-date value for the floating text, or std::nullopt to indicate
+	 *          nothing changed and the previous floating text value should continue being used
+	 */
+	virtual std::optional<QString> getCustomFloatingTextUpdate()
+	{
+		return getCustomFloatingText();
+	}
```
Comment (sakertooth) [inline include/FloatModelEditorBase.h:121]: AFICT, the `[description] [custom text][unit]` is specifically a quirk of the VST2 API. We don't have to force its awkardness onto the rest of the `Knob` code.

Comment (messmerd) [reply include/FloatModelEditorBase.h:121]: I didn't change the way `Knob` formats its floating text - I just documented behavior that was previously undocumented. A lot of the rest of the codebase makes use of the "description" and "unit" fields - often by calling `setHintText` - so it's not just VST2.

File: src/gui/widgets/Knob.cpp (hunk 2 above)
Comment (messmerd) [reply src/gui/widgets/Knob.cpp]: I was just copying the old code, but I could change it for consistency's sake.

File: src/gui/widgets/SimpleTextFloat.cpp (hunk 4 above)
Comment (messmerd) [reply src/gui/widgets/SimpleTextFloat.cpp:81]: This isn't related to rate limiting - it just makes the floating text visible and starts the timer to hide it if it hasn't already been started. I added this method while refactoring how `FloatModelEditorBase` uses `SimpleTextFloat`, but it may not be necessary anymore. I'll have to check.

Comment (sakertooth) [reply src/gui/widgets/SimpleTextFloat.cpp:81]: On a separate note, a part of me questions why the code isn't just a simple call to `setTooltip` (i.e., why the `SimpleTextFloat` classes and such). I don't spend too much time in this part of the codebase, but it feels different than from what I was expecting.

Comment (messmerd) [reply src/gui/widgets/SimpleTextFloat.cpp:81]: Our `SimpleTextFloat` allows specifying both a delay before the tooltip is shown and a display duration, while `setToolTip`/`QToolTip` only supports a display duration. And looking at `QToolTip`'s documentation, it looks like it would be more difficult to adapt to our use cases than `SimpleTextFloat`.

One thing I don't like about `SimpleTextFloat` though, is how it's not a static class. We should probably look into changing that in a separate PR. And maybe rename it to `ToolTip`.

**Comment by messmerd** [comment]
I just realized this PR also fixes a bug where the tooltip text displayed by a knob when you hover over it without clicking it remains static and unchanging even when the knob is being automated or controlled.

File: plugins/Vestige/Vestige.h [hunk 6]
```diff
@@ -46,8 +46,8 @@ class VstPlugin;
 
 namespace gui
 {
+class VstPluginKnob;
```
Comment (messmerd) [inline plugins/Vestige/Vestige.h]: note to self: fix ordering

File: include/RemotePluginBase.h [hunk 7]
```diff
@@ -370,9 +368,10 @@ class LMMS_EXPORT RemotePluginBase
 		{
 		}
 
-		inline message & addString( const std::string & _s )
+		template<class... Args>
+		message& addString(Args&&... args)
```
Comment (sakertooth) [inline include/RemotePluginBase.h:372]: I vividly remember asking about this but after checking the messages in this PR I guess not? I was wondering why you changed this function to accept multiple parameters?

Comment (messmerd) [reply include/RemotePluginBase.h:372]: It functions like emplace - you can use any constructor that `std::string` has.

Comment (sakertooth) [reply include/RemotePluginBase.h:372]: Why not just create a `std::string` object like it was doing before? Is this for performance?

Comment (sakertooth) [reply include/RemotePluginBase.h:372]: > It functions like emplace - you can use any constructor that std::string has.

To clarify, I understand what it does, just not why you did it.

Comment (messmerd) [reply include/RemotePluginBase.h:372]: Yes, to minimize copies.

**Comment by rubiefawn** [comment]
# Before

https://github.com/user-attachments/assets/b287e87b-b32a-4f2f-8708-c13ea92ddd4c


# After

https://github.com/user-attachments/assets/4dc1ee3a-6e4a-4617-82ca-8564cbfac551

Excellent work!

**Comment by messmerd** [comment]
@rubiefawn Thanks for testing! :heart:
