### PR TITLE
Really remove all controllers while removing all controllers

### LINKED ISSUE #2979: Controllers don't get removed when switching projects
`master` branch, elementary OS Freya x64.
Steps to reproduce:
1. Add a bunch of controllers to the controller rack(6 or 7 are enough)
2. Press the new project button and discard changes so you start fresh
3. Look at the controller rack again
4. Every second controller is still there, yet they don't appear under the controller list if you try to connect the control to them

Here's a GIF: 
gifrecord_2016-08-18_233651

This also happens when you open already exisiting projects, and the controller order also gets mixed up, and all kinds of weirdness happens.

Marking this for 1.2, as this does not exist in 1.1. Tagging @michaelgregorius since he is the author of the new controllers.

### PR DESCRIPTION
**Pull request by grejppi**
This should fix #2979

### CODE REVIEW

**Comment by Umcaruje** [comment]
I can confirm this fixes #2979 :+1:

File: src/core/Song.cpp [hunk 1]
```diff
@@ -1217,9 +1217,9 @@ void Song::restoreControllerStates( const QDomElement & element )
...
 void Song::removeAllControllers()
 {
-	for (int i = 0; i < m_controllers.size(); ++i)
+	while (m_controllers.size() != 0)
 	{
-		removeController(m_controllers.at(i));
+		removeController(m_controllers.at(0));
 	}
 
 	m_controllers.clear();
```
Comment (jasp00) [inline src/core/Song.cpp]: This line should be removed.
