### PR TITLE
Avoid adding journal checkpoints when initially creating volume knobs

### LINKED ISSUE #8211: Volume knobs on tracks show as a percentage after undoing
### System Information

Windows 10

### LMMS Version(s)

1.3.0-alpha.1.930+248acbf

### Most Recent Working Version

_No response_

### Bug Summary

After creating a new instrument or sample track, the volume knob is supposed to show volume in units of dbFS. However, if you click undo after creating the new track, then use that track's volume knob, it will show as a percentage instead of dbFS.

### Expected Behaviour

Track volume knobs should keep displaying volume in dbFS.

### Steps To Reproduce

- Add a new instrument or sample track in the song editor
- Click undo or press Ctrl+Z
- The new track's volume knob will now show a percentage instead of dbFS

### Logs

_No response_

### Screenshots / Minimum Reproducible Project

https://github.com/user-attachments/assets/0407074e-1ab3-4fbf-955a-f586d09d4389

### Please search the issue tracker for existing bug reports before submitting your own.

- [x] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by Itreza2**
fixes #8211

The cause of this "bug" is that the method setValue of the class AutomatableModel is creating a journal checkpoint.

```
void AutomatableModel::setValue(const float value, const bool isAutomated)
{
	if (fittedValue(value) == m_value)
	{
		// TODO check why we need this signal, is there a better solution?
		if (!isAutomated) { emit dataUnchanged(); }
		return;
	}

	if (!isAutomated) { addJournalCheckPoint(); }

	// set value for this and the other linked models
	setValueInternal(value);
	for (auto model = m_nextLink; model != this; model = model->m_nextLink)
	{
		model->setValueInternal(value);
	}
}
```

When a new instrument / sample track is created, the setter "SetVolumeKnob( true )" of the member m_volumeKnob FloatModelEditorBase is called. Currently, this create a journal checkpoint that, when undone, is falsely setting back m_volumeKnob to false (hence why % is showing instead of dBFS on the label).

My proposal to avoid this behavior is to rewrite SetVolumeKnob so it set the parameter "isAutomated" of setValue to true, as automated Models are not creating journal checkpoint.
It's a rudimentary workaround, but it avoids rewriting a larger portion of the code.

### CODE REVIEW

**Comment by regulus79** [comment]
Now that I look at the code, it feels odd why we are using a `BoolModel` to store whether a knob is a volume knob or not. Would it make sense to change it to be a simple `bool`?

**Comment by Itreza2** [comment]
Indeed, maybe was it made this way just to lazily take advantage of the mapPropertyFromModel macro ?
I don't think changing it to bool would break anything, and it would be both clearer and more efficient. That being said I don't know the code base and may miss something...

File: include/FloatModelEditorBase.h [hunk 1]
```diff
@@ -112,6 +121,7 @@ class LMMS_EXPORT FloatModelEditorBase : public QWidget, public FloatModelView
 
 	DirectionOfManipulation m_directionOfManipulation;
 
+
```
Comment (regulus79) [inline include/FloatModelEditorBase.h]: Maybe removing the extra/removed blank lines would clean up the diff

File: src/gui/widgets/FloatModelEditorBase.cpp [hunk 2]
```diff
@@ -59,6 +59,7 @@ FloatModelEditorBase::FloatModelEditorBase(DirectionOfManipulation directionOfMa
 }
 
 
+
```
Comment (regulus79) [inline src/gui/widgets/FloatModelEditorBase.cpp]: .

File: src/gui/widgets/FloatModelEditorBase.cpp [hunk 3]
```diff
@@ -374,7 +375,6 @@ void FloatModelEditorBase::setPosition(const QPoint & p)
 	}
 }
 
-
```
Comment (regulus79) [inline src/gui/widgets/FloatModelEditorBase.cpp:377]: .

File: include/FloatModelEditorBase.h [hunk 4]
```diff
@@ -63,11 +62,21 @@ class LMMS_EXPORT FloatModelEditorBase : public QWidget, public FloatModelView
...
+	{
+		return m_volumeKnob;
+	}	
+
 signals:
 	void sliderPressed();
 	void sliderReleased();
 	void sliderMoved(float value);
 
+public slots:
```
Comment (regulus79) [inline include/FloatModelEditorBase.h]: Does this have to be a slot? I can't find any occurrences in the codebase where it's used as a slot.

**Comment by sakertooth** [comment]
`AutomatableModel` should not be setting checkpoints in `setValue` because it mixes up the intent of setting a model to the given value with a common use-case (setting the journal checkpoint after setting the value, like when dragging the knob) but does not work in all cases (like this one, i.e., setting the journal checkpoint on initialization of the knob).

Wanted to make this point but you don't necessarily have to act on it. Just something to keep in mind.

File: include/FloatModelEditorBase.h [hunk 5]
```diff
@@ -63,6 +62,16 @@ class LMMS_EXPORT FloatModelEditorBase : public QWidget, public FloatModelView
...
 
+	inline bool isVolumeKnob() const
+	{
+		return m_volumeKnob;
+	}	
+
+	inline void setVolumeKnob( const bool val )
+	{
+		m_volumeKnob = val;
+	}
```
Comment (sakertooth) [inline include/FloatModelEditorBase.h]:
```suggestion
	bool isVolumeKnob() const
	{
		return m_volumeKnob;
	}	

	void setVolumeKnob(const bool val)
	{
		m_volumeKnob = val;
	}
```

You can avoid using `inline` here (compilers inline better than we can and any function defined inside class declarations is `inline` by default to uphold the one definition rule).

I would also fix the formatting.
