### PR TITLE
Use `std::optional` for colour interfaces and storage

### LINKED ISSUE #6987: Changing a track's color instantly crashes program
### Bug Summary
When changing the color of a track (instrument, automation, sample) (FX Channels seem to be fine), the program nearly instantaneously crashes before it even pulls up the color window.
#### Steps to reproduce
Add a track in the song editor and go to change its track color.
#### Expected behavior
It pulls up the window for picking a color, and then works.
#### Actual behavior
Bye-bye program
#### Affected LMMS versions
g609c008a7

### PR DESCRIPTION
**Pull request by DomClark**
Fixes #6987.

Colours of mixer channels, clips, and tracks are now all stored as `std::optional<QColor>`, and the getters and setters use this type too. This simplifies the interface for colours to a single getter and setter, rather than four functions such as `hasColor`, `getColor`, `setColor`, and `resetColor`. This also makes the interface easier to use correctly - the bug occurred because `getColor` was previously safe to use unconditionally, but since #6421 should not be called without first checking whether a colour was set. Now `getColor` is always safe to call again, and the caller has to handle the returned optional appropriately.

### CODE REVIEW

File: src/core/Clip.cpp [hunk 1]
```diff
@@ -48,9 +48,7 @@ Clip::Clip( Track * track ) :
 	m_startPosition(),
 	m_length(),
 	m_mutedModel( false, this, tr( "Mute" ) ),
-	m_selectViewOnCreate( false ),
-	m_color( 128, 128, 128 ),
-	m_useCustomClipColor( false )
+	m_selectViewOnCreate( false )
```
Comment (sakertooth) [inline src/core/Clip.cpp:51]:
```suggestion
	m_selectViewOnCreate(false)
```

**Review by sakertooth — APPROVED** [review]

File: src/gui/MixerLine.cpp [hunk 2]
```diff
@@ -430,36 +430,34 @@ void MixerLine::setStrokeInnerInactive( const QColor & c )
...
 {
 	auto channel = Engine::mixer()->mixerChannel( m_channelIndex );
-	auto new_color = ColorChooser(this).withPalette(ColorChooser::Palette::Mixer)->getColor(channel->m_color.value_or(backgroundActive().color()));
-	if(!new_color.isValid()) { return; }
-	channel->setColor (new_color);
+	auto new_color = ColorChooser(this)
+		.withPalette(ColorChooser::Palette::Mixer)
+		->getColor(channel->color().value_or(backgroundActive().color()));
+	if (!new_color.isValid()) { return; }
+	channel->setColor(new_color);
```
Comment (messmerd) [inline src/gui/MixerLine.cpp:441]:
```suggestion
	auto newColor = ColorChooser(this)
		.withPalette(ColorChooser::Palette::Mixer)
		->getColor(channel->color().value_or(backgroundActive().color()));
	if (!newColor.isValid()) { return; }
	channel->setColor(newColor);
```
style

File: src/gui/MixerLine.cpp [hunk 3]
```diff
@@ -430,36 +430,34 @@ void MixerLine::setStrokeInnerInactive( const QColor & c )
...
 	update();
 }
 
-
 // Pick a random color from the mixer palette and set it as our color
 void MixerLine::randomizeColor()
 {
 	auto channel = Engine::mixer()->mixerChannel( m_channelIndex );
-	channel->setColor (ColorChooser::getPalette(ColorChooser::Palette::Mixer)[rand() % 48]);
+	channel->setColor(ColorChooser::getPalette(ColorChooser::Palette::Mixer)[rand() % 48]);
```
Comment (messmerd) [inline src/gui/MixerLine.cpp:458]:
```suggestion
	channel->setColor(ColorChooser::getPalette(ColorChooser::Palette::Mixer)[std::rand() % 48]);
```
Use `std::` namespace prefix

File: src/gui/clips/ClipView.cpp [hunk 4]
```diff
@@ -340,45 +340,35 @@ void ClipView::updatePosition()
...
-
 void ClipView::selectColor()
 {
 	// Get a color from the user
-	QColor new_color = ColorChooser( this ).withPalette( ColorChooser::Palette::Track )->getColor( m_clip->color() );
-	if (new_color.isValid()) { setColor(&new_color); }
+	QColor new_color = ColorChooser{this}
+		.withPalette(ColorChooser::Palette::Track)
+		->getColor(m_clip->color().value_or(palette().background().color()));
+	if (new_color.isValid()) { setColor(new_color); }
```
Comment (messmerd) [inline src/gui/clips/ClipView.cpp:349]:
```suggestion
	QColor newColor = ColorChooser{this}
		.withPalette(ColorChooser::Palette::Track)
		->getColor(m_clip->color().value_or(palette().background().color()));
	if (newColor.isValid()) { setColor(newColor); }
```
style

File: src/gui/clips/ClipView.cpp [hunk 5]
```diff
@@ -340,45 +340,35 @@ void ClipView::updatePosition()
...
 }
 
-
-
-
 void ClipView::randomizeColor()
 {
-	setColor(&ColorChooser::getPalette(ColorChooser::Palette::Mixer)[rand() % 48]);
+	setColor(ColorChooser::getPalette(ColorChooser::Palette::Mixer)[rand() % 48]);
```
Comment (messmerd) [inline src/gui/clips/ClipView.cpp:354]:
```suggestion
	setColor(ColorChooser::getPalette(ColorChooser::Palette::Mixer)[std::rand() % 48]);
```
Use `std::` namespace prefix

File: src/gui/tracks/TrackOperationsWidget.cpp [hunk 6]
```diff
@@ -265,8 +265,9 @@ void TrackOperationsWidget::removeTrack()
 
 void TrackOperationsWidget::selectTrackColor()
 {
-	QColor new_color = ColorChooser( this ).withPalette( ColorChooser::Palette::Track )-> \
-		getColor( m_trackView->getTrack()->color() );
+	QColor new_color = ColorChooser{this}
```
Comment (messmerd) [inline src/gui/tracks/TrackOperationsWidget.cpp:268]: Since you're modifying this line, this could be renamed to `newColor`.

**Review by messmerd — APPROVED** [review]
A few minor suggestions, but otherwise it looks good.
