### PR TITLE
Fix OpulenZ level scaling knob

### LINKED ISSUE #8306: OpulenZ's Scale knob seems to not do anything
### System Information

Arch Linux

### LMMS Version(s)

1.3.0-alpha.1.960+83313e7

### Most Recent Working Version

_No response_

### Bug Summary

The SCALE knob in OpulenZ doesn't do what it's supposed to do. All notes always output with the same amplitude regardless of this value.

### Expected Behaviour

In my understanding it should set the amount by which the volume is scaled based on the frequency right(?)

### Steps To Reproduce

Load OpulenZ and set the Scale knobs to any >0 value.

### Logs

_No response_

### Screenshots / Minimum Reproducible Project

_No response_

### Please search the issue tracker for existing bug reports before submitting your own.

- [x] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by zynskeywolf**
Fixes #8306. Parameter now works, value is set to 0 for old savefiles.

### CODE REVIEW

File: src/core/DataFile.cpp [hunk 1]
```diff
@@ -2084,6 +2085,25 @@ void DataFile::upgrade_fixBassLoopsTypo()
 	mapSrcAttributeInElementsWithResources(replacementMap);
 }
 
+void DataFile::upgrade_fixOpulenzScaling()
```
Comment (messmerd) [inline src/core/DataFile.cpp]: Could you perform the upgrade routine in `OpulenzInstrument::loadSettings` instead? Better to keep it local to Opulenz itself if possible.

You could also add a "version" attribute if you need a way to distinguish between projects that have been upgraded and those that haven't.

Comment (zynskeywolf) [reply src/core/DataFile.cpp]: Done.

File: plugins/OpulenZ/OpulenZ.cpp [hunk 2]
```diff
@@ -250,14 +251,14 @@ void OpulenzInstrument::setVoiceVelocity(int voice, int vel) {
 	// Velocity calculation, some kind of approximation
 	// Only calculate for operator 1 if in adding mode, don't want to change timbre
 	theEmulator->write(0x40+adlib_opadd[voice],
-			   ( (int)op1_scale_mdl.value() & 0x03 << 6) +
+			   (((int)op1_scale_mdl.value() & 0x03) << 6) +
```
Comment (messmerd) [inline plugins/OpulenZ/OpulenZ.cpp]:
```suggestion
			   ((op1_scale_mdl.value<int>() & 0x03) << 6) +
```
I think this should be possible

File: plugins/OpulenZ/OpulenZ.cpp [hunk 3]
```diff
@@ -250,14 +251,14 @@ void OpulenzInstrument::setVoiceVelocity(int voice, int vel) {
...
 			   ( vel_adjusted & 0x3f ) );
 
 
 	vel_adjusted = 63 - ( op2_lvl_mdl.value() * vel/127.0 );
 	// vel_adjusted = 63 - op2_lvl_mdl.value();
 	theEmulator->write(0x43+adlib_opadd[voice],
-			   ( (int)op2_scale_mdl.value() & 0x03 << 6) +
+			   (((int)op2_scale_mdl.value() & 0x03) << 6) +
```
Comment (messmerd) [inline plugins/OpulenZ/OpulenZ.cpp]:
```suggestion
			   ((op2_scale_mdl.value<int>() & 0x03) << 6) +
```

File: plugins/OpulenZ/OpulenZ.cpp [hunk 4]
```diff
@@ -438,16 +439,28 @@ void OpulenzInstrument::saveSettings( QDomDocument & _doc, QDomElement & _this )
 	fm_mdl.saveSettings( _doc, _this, "fm" );
 	vib_depth_mdl.saveSettings( _doc, _this, "vib_depth" );
 	trem_depth_mdl.saveSettings( _doc, _this, "trem_depth" );
+
+	_this.setAttribute("version", 1);
 }
 
 void OpulenzInstrument::loadSettings( const QDomElement & _this )
 {
+	if(_this.attribute("version").toInt() < 1)
```
Comment (messmerd) [inline plugins/OpulenZ/OpulenZ.cpp]:
```suggestion
	if (_this.attribute("version", "0").toInt() < 1)
```
Style + making the default value explicit

File: plugins/OpulenZ/OpulenZ.cpp (hunk 2 above)
Comment (zynskeywolf) [reply plugins/OpulenZ/OpulenZ.cpp]: Tried it, doesn't compile. Apparently because it's a FloatModel where value() is just float and not a template.

Comment (rubiefawn) [reply plugins/OpulenZ/OpulenZ.cpp]: C++-style casts are preferred:

```suggestion
			   ((static_cast<int>(op1_scale_mdl.value()) & 0x03) << 6) +
```

File: plugins/OpulenZ/OpulenZ.cpp (hunk 3 above)
Comment (rubiefawn) [reply plugins/OpulenZ/OpulenZ.cpp]:
```suggestion
			   ((static_cast<int>(op2_scale_mdl.value()) & 0x03) << 6) +
```

**Review by rubiefawn — APPROVED** [review]

**Comment by yohannd1** [comment]
Just tested it, works fine here! Scale now works as expected and the upgrade worked both while using an old project I have here and by importing the factory patch `Bells.xpf`, which had non-zero scales.
