### PR TITLE
Fix mixer channel updates on solo/mute

### LINKED ISSUE #7054: Mixer channels do not get repainted during solo
### Bug Summary
The mixer channels do not get repainted when a channel is soloed.

#### Steps to reproduce
1. Load the demo song "Greippi - Krem Kaakkuja (Second Flight Remix).mmpz".
2. Solo the channel "8-bit pluck". Some of the neighboring channels will partially change colors.
3. Move the Mixer view. All channels get painted correctly.
4. Unsolo the channel. Update is missing.
5. Move the Mixer view. All channels get painted correctly.

It seems that an update is missing somewhere.

#### Expected behavior
This video shows the behavior at commit 4e63f606523 (before 6b21dc7896e):

https://github.com/LMMS/lmms/assets/9293269/8749679c-d538-42f7-af7d-22eb4fbda0e1

#### Actual behavior
This video shows the current behavior in master (at commit 1eff322c2a3):

https://github.com/LMMS/lmms/assets/9293269/75be4410-9a2f-4ddd-ab90-5d9f5e08c000

#### Affected LMMS versions
master at commit 1eff322c2a3.

### PR DESCRIPTION
**Pull request by michaelgregorius**
Fix the update of the mixer channels whenever a channel is soloed or muted.

The solution is rather "brutal" as it updates all mixer channel views when one of the models changes.

Introduce private helper method `MixerView::updateAllMixerChannels`. It calls the `update` method on each `MixerChannelView` so that they can get repainted.

Call `updateAllMixerChannels` at the end of the existing method `toggledSolo`.

Introduce a new method `MixerView::toggledMute` which is called whenever the mute model of a channel changes. It also updates all mixer channels.

Fixes #7054.

### CODE REVIEW

**Comment by sakertooth** [comment]
Can we consider the simpler solution I discovered in #7054?

**Comment by michaelgregorius** [comment]
Hi @sakertooth! With commit ede65963ea1 I have improved the implementation a bit by going more into the right direction. There's now a direct connection from the mute model to the `MixerChannelView` and the `MixerView` is not involved anymore in any updates in this case.

Please refer to the commit message for some more details.

**Comment by sakertooth** [comment]
> Hi @sakertooth! With commit ede65963ea1 I have improved the implementation a bit by going more into the right direction. There's now a direct connection from the mute model to the `MixerChannelView` and the `MixerView` is not involved anymore in any updates in this case.
> 
> 
> 
> Please refer to the commit message for some more details.

Nice! 👍

I am working on a more permanent solution for this issue, but I don't mind this one for now. I'll take a look soon.

**Comment by sakertooth** [comment]
I took a look. If we are going to keep the original solution for solo, I think it would just be simpler doing the same for mute as well, and add a TODO comment explaning that the solution can be improved. I was thinking maybe we could go with the signal and slot one-liner solution the whole way, but you are right that the codebase currently makes this somewhat difficult.

From my perspective and anyone looking at the code, its more clear if the solution was consisent and cohesive. What I mean is that there are two separate functions in different places, `MixerView::toggledSolo` and `MixerChannelView::toggledMute`, and both do different things to achieve the same goal of updating the widget when the model changes. Surely this is not the ideal design?

And then theres the function of `MixerChannelView::setChannelIndex`. The code was already improperly modifying models while seemingly doing something as simple as changing the channel index, but the disconnecting added drove complexity further up.

I would advise for the simplest solution to the problem for now with a TODO comment. When a solo/mute model changes, we update the `MixerView` and all its channels. Now that I think of it, I dont necessarily see this as a brutal solution. If anything, its more straightforward and consistent for both soloing and muting. Calling `update` multiple times for mute is also probably not a dealbreaker performance wise, so we should really going for the most simplest solution when we can.

**Comment by michaelgregorius** [comment]
Hi @sakertooth, I have reverted commit ede65963ea1 and have added a comment to the slots.

**Comment by michaelgregorius** [comment]
@sakertooth , I have added some more improvement, consolidation and cleanup commits.

Commit b0355ee116b makes the `MixerView` connect directly to the solo and mute models instead of indirectly via the constructor of `MixerChannelView`.

Other than that I have started applying the "Dependency Inversion Principle" to `MixerView`. It now receives the `Mixer` it is operating upon from the outside instead of having to ask for it.

File: src/gui/MixerView.cpp [hunk 1]
```diff
@@ -211,14 +214,18 @@ void MixerView::refreshDisplay()
...
 	}
 	m_channelAreaWidget->adjustSize();
 
 	// re-add the views
-	m_mixerChannelViews.resize(Engine::mixer()->numChannels());
+	m_mixerChannelViews.resize(getMixer()->numChannels());
 	for (int i = 1; i < m_mixerChannelViews.size(); ++i)
 	{
 		m_mixerChannelViews[i] = new MixerChannelView(m_channelAreaWidget, this, i);
+		// We are readding the views for existing channels so we do not have to connect to solo/mute here
```
Comment (sakertooth) [inline src/gui/MixerView.cpp:228]: I believe `refreshDisplay` is also called when we load the project, so maybe the connections are missing here.

**Review by sakertooth — COMMENTED** [review]
Code wise, it looks good, but I just ran a test on the Greppi demo and the bug still seems to be there. Not exactly sure why though, but maybe a connection is missing somewhere. Could you confirm (or disconfirm) this?

File: src/gui/MixerView.cpp (hunk 1 above)
Comment (michaelgregorius) [reply src/gui/MixerView.cpp]: Argh, you're right. Of all the cases I did not check the one this issue is actually about. :sweat_smile:

Fixed with commit f01cf366338.

**Review by sakertooth — APPROVED** [review]
Tested it again and it seems to be working. Just one suggestion/question on the code.

File: include/MixerView.h [hunk 2]
```diff
@@ -97,7 +102,17 @@ public slots:
...
 private slots:
 	void updateFaders();
+	// TODO This should be improved. Currently the solo and mute models are connected via
+	// the MixerChannelView's constructor with the MixerView. It would already be an improvement
+	// if the MixerView connected itself to each new MixerChannel that it creates/handles.
 	void toggledSolo();
+	void toggledMute();
+
+private:
+	Mixer* getMixer() const;
```
[the remark this answers is not in the document]
Comment (michaelgregorius) [reply include/MixerView.h:112]: The rationale for the naming is explained in the message of commit 37f97344d07: "It's called `getMixer` and not just `mixer` because it allows for locale variables to be called `mixer` without confusing it with the method."

I think it makes the code more readable. Otherwise you have code like:
```
auto * m = mixer();
m->doThis();
```
Or:
```
auto * mix = mixer();
mix->doThat();
```

I think the code is more comprehensible if the local variable can be called `mixer`:
```
auto * mixer = getMixer();
mixer->doFoo();
```
