### PR TITLE
Fixes #6401: Reinit Lv2ControlBase on SR change

### LINKED ISSUE #6401: Sound of exported LV2 instrument plugins is shifted down one half tone
### Bug Summary

When exporting sounds from a LV2 instrument plugin the resulting mp3 or wav file plays this sounds one half tone lower.

#### Steps to reproduce

- Add a LV2 instrument plugin - e.g. Calf Organ or MDA ePiano 
- Create a melody
- Export it as mp3 or wav format (between loop markers)
- Resulting melody plays one half tone lower

#### Expected behavior

Exported sound from LV2 instrument plugins should match the sound played directly in LMMS

#### Actual behavior

Exported sound from LV2 instrument plugins are shifted one half tone lower

#### Affected LMMS versions

Version 1.3.0-alpha.1.149

### PR DESCRIPTION
**Pull request by JohannesLorenz**
This implements the previous stub `Lv2ControlBase::reloadPlugin`, which
is required if the LMMS sample rate changes.

Additionally, this removes two unused pure virtual functions of
`Lv2ControlBase`, making the class non-abstract, so we can call its CTOR
after deleting it.

### CODE REVIEW

**Comment by JohannesLorenz** [comment]
Drafting this, since it segfaults when you export the project.

**Comment by spechtstatt** [comment]
@JohannesLorenz: thank you very much - I will try it.

**Comment by spechtstatt** [comment]
@JohannesLorenz: I am a little bit confused because I have taken the current master state and it worked there - but the fix is not merged yet isn't it?

**Comment by JohannesLorenz** [comment]
> but the fix is not merged yet isn't it?

Correct. Maybe you had this PR, then switched to master but did not recompile? Or accidentally used VST instead of LV2?

**Comment by zonkmachine** [comment]
I'm testing this and it's working fine so far apart. It seem like of the mda plugins, the piano and epiano modules do answer to the change in export frequency where the dx10 and jx10 don't. I assume this is a shortage of the mda plugins and not of this PR. Right?

Example project: [lv2export2.mmp.zip](https://github.com/LMMS/lmms/files/9035416/lv2export2.mmp.zip)

**Comment by JohannesLorenz** [comment]
> I'm testing this and it's working fine so far apart from one issue. It seem like of the mda plugins, the piano and epiano modules do answer to the change in export frequency where the dx10 and jx10 don't. I assume this is a shortage of the mda plugins and not of this PR. Right?

From looking at the code of the mda plugins, while the dx10 uses a function `getSampleRate()`, the pianos do not. The following use the `getSampleRate()`:

```
mdaBandisto
mdaBeatBox
mdaCombo
mdaDegrade
mdaDelay
mdaDetune
mdaDubDelay
mdaDynamics
mdaLeslie
mdaLimiter
mdaLoudness
mdaMultiBand
mdaRePsycho
mdaRezFilter
mdaRingMod
mdaRoundPan
mdaShepard
mdaSplitter
mdaStereo
mdaSubSynth
mdaTalkBox
mdaTestTone
mdaThruZero
mdaTracker
mdaVocInput
mdaVocoder
```

Can you please check if any of those work?

Aside, can you check whether it works in other hosts than LMMS? Then we know if it's our fault...

**Comment by zonkmachine** [comment]
> Can you please check if any of those work?

I'm on the case. A first quick test tells me that there are issues here and that it may take a while to test it. 

> Aside, can you check whether it works in other hosts than LMMS? Then we know if it's our fault...

Ardour maybe. I don't have any greater experience with other hosts.

**Comment by zonkmachine** [comment]
I also get occasional crashes.

```gdb

(gdb) bt full
#0  0x00005555557ad4c2 in lmms::AutomatableModel::maxValue<float>() const (this=0x0) at /home/zonkmachine/builds/lmms/include/AutomatableModel.h:200
#1  0x0000555555862712 in lmms::TypedAutomatableModel<float>::maxValue() const (this=0x0) at /home/zonkmachine/builds/lmms/include/AutomatableModel.h:451
#2  0x00005555559c1da8 in lmms::gui::Knob::drawKnob(QPainter*) (this=0x55555793cfb0, _p=0x7fffffff9618) at /home/zonkmachine/builds/lmms/src/gui/widgets/Knob.cpp:440
        enabled = true

                      currentArcColor = {cspec = QColor::Rgb, ct = {argb = {alpha = 17990, red = 7453, green = 58082, blue = 30326, pad = 0}, ahsv = {alpha = 17990, hue = 7453, saturation = 58082, value = 30326, pad = 0}, acmyk = {alpha = 17990, cyan = 7453, magenta = 58082, yellow = 30326, black = 0}, ahsl = {alpha = 17990, hue = 7453, saturation = 58082, lightness = 30326, pad = 0}, argbExtended = {alphaF16 = 17990, redF16 = 7453, greenF16 = 58082, blueF16 = 30326, pad = 0}, array = {17990, 7453, 58082, 30326, 0}}}

                      currentLineColor = {cspec = QColor::Rgb, ct = {argb = {alpha = 65535, red = 7453, green = 58082, blue = 30326, pad = 0}, ahsv = {alpha = 65535, hue = 7453, saturation = 58082, value = 30326, pad = 0}, acmyk = {alpha = 65535, cyan = 7453, magenta = 58082, yellow = 30326, black = 0}, ahsl = {alpha = 65535, hue = 7453, saturation = 58082, lightness = 30326, pad = 0}, argbExtended = {alphaF16 = 65535, redF16 = 7453, greenF16 = 58082, blueF16 = 30326, pad = 0}, array = {65535, 7453, 58082, 30326, 0}}}
        p = {d_ptr = {d = 0x5555583cf1a0}}
        mid = {xp = 17, yp = 13}
        radius = 12.5
        centerAngle = 0
        arcLineWidth = 0
        arcRectSize = 0
#3  0x00005555559c3280 in lmms::gui::Knob::paintEvent(QPaintEvent*) (this=0x55555793cfb0, _me=0x7fffffff97f0) at /home/zonkmachine/builds/lmms/src/gui/widgets/Knob.cpp:668
        p = {d_ptr = {d = 0x55555814c030}}
```

**Comment by JohannesLorenz** [comment]
> lv2 units now resets to default values on export. Tested with mda-lv2 and dpf-plugins-lv2.

Sorry, what did you mean by "units"? (I'm really dumb, asking 3 months later... :smiling_face_with_tear:)

**Comment by JohannesLorenz** [comment]
> I also get occasional crashes.

Any idea how I can reproduce those?

**Comment by zonkmachine** [comment]
> > lv2 units now resets to default values on export. Tested with mda-lv2 and dpf-plugins-lv2.
> 
> Sorry, what did you mean by "units"? (I'm really dumb, asking 3 months later... smiling_face_with_tear)



> > I also get occasional crashes.
> 
> Any idea how I can reproduce those?

np. I'll try and test this one again and see if I can answer those questions. :wink:

**Comment by JohannesLorenz** [comment]
@zonkmachine It would be cool if we can advance with this PR, as it's a requirement for #6484 .

**Comment by zonkmachine** [comment]
> > lv2 units now resets to default values on export. Tested with mda-lv2 and dpf-plugins-lv2.
> 
> Sorry, what did you mean by "units"? (I'm really dumb, asking 3 months later... smiling_face_with_tear)

By units I meant plugins. If I change a parameter from the default, the plugin will revert to it's default sound on export and then crash, at least sometimes, if the plugin is tweaked after the erroneous export.

Example. This should export as two notes with long decay but comes out as short and staccato.
[exportkars.mmp.zip](https://github.com/LMMS/lmms/files/9845281/exportkars.mmp.zip)

**Comment by JohannesLorenz** [comment]
> By units I meant plugins. If I change a parameter from the default, the plugin will revert to it's default sound on export and then crash, at least sometimes, if the plugin is tweaked after the erroneous export.
> 
> Example. This should export as two notes with long decay but comes out as short and staccato. [exportkars.mmp.zip](https://github.com/LMMS/lmms/files/9845281/exportkars.mmp.zip)

Ah I get it. Good point! I accidentally reset the whole plugin, including all its knob values ("so called models"). I will fix this.

**Comment by zonkmachine** [comment]
> Ah I get it. Good point! I accidentally reset the whole plugin, including all its knob values ("so called models"). I will fix this.

This also explains the crash above. https://github.com/LMMS/lmms/pull/6419#issuecomment-1181959192
Export with plugin gui open and tweak the gui after export. Crash.

That would be all observations for this PR. The failing mda plugins is in all likelihood upstream.

**Comment by JohannesLorenz** [comment]
I pushed a rewrite of code that should also keep the model values and not reset them.

Sadly, for the plugin Sawtooth (from the "blop" plugins), I get a crash when exporting to WAV. The problem is that the code from `lilv_plugin_instantiate` returns a "NULL" instance. In wavedata_load (inside the blop plugin), something goes wrong, but sadly, I am unable to debug it because I can't see enough debug symbols.

Help here, or general testing, would be appreciated.

**Comment by zonkmachine** [comment]
> Sadly, for the plugin Sawtooth (from the "blop" plugins), I get a crash when exporting to WAV. T

Which one of the blop pugins works for you? I have tried sawtooth, triangle, random, lp4pole and a simple amp. All crash on export.

**Comment by JohannesLorenz** [comment]
> Which ones of the blop pugins works for you?

They all fail. I need to investigate further...

**Comment by JohannesLorenz** [comment]
I have the impression that it's not reloading those plugins that causes the issue, but the sample rate of 44100. Can anyone please test simply loading "Sawtooth" with 44100 Hz?

File: plugins/Lv2Effect/Lv2FxControls.h [hunk 1]
```diff
@@ -60,8 +60,8 @@ private slots:
 	void changeControl();
 
 private:
-	DataFile::Types settingsType() override;
-	void setNameFromFile(const QString &name) override;
+	void onSampleRateChanged();
+	void reload();
```
Comment (PhysSong) [inline plugins/Lv2Effect/Lv2FxControls.h:64]: There's no definition for `Lv2FxControls::reload`, making macOS builds fail.

Comment (JohannesLorenz) [reply plugins/Lv2Effect/Lv2FxControls.h]: Thanks, I did not see that. Fixed it now.

**Comment by JohannesLorenz** [comment]
> I have the impression that it's not reloading those plugins that causes the issue, but the sample rate of 44100. Can anyone please test simply loading "Sawtooth" with 44100 Hz?

After a lot of debugging, I found out that this plugin [is not able to be instantiated a second time with different SR](https://gitlab.com/drobilla/blop-lv2/-/blob/8c565a9fa7b74c642a95371cadd1e563282966eb/src/wdatutil.c#L410-421). Now, I'll ask the Lv2 guys if it's an error in the plugin or if our behavior of switching SR and then re-instantiating is an error. I will report the results soon.

**Comment by JohannesLorenz** [comment]
> > Sadly, for the plugin Sawtooth (from the "blop" plugins), I get a crash when exporting to WAV. T
> 
> Which ones of the blop pugins works for you? I have tried sawtooth, triangle, random, lp4pole and a simple amp. All crash on export.

The problem I describe above is only valid for the basic shapes (saw, pulse, power, sine wave). For "amp", I can't reproduce crashes. For lp4pole, I get crashes, but unrelated to my previous post - must be investigated.

This raises 2 further issues:

(1) investigate lp4pole issue (knob lost its connected model)
(2) in the situation with saw, do not crash - print a proper warning

**Comment by JohannesLorenz** [comment]
@zonkmachine I think I fixed all issues and banned all plugins :grin: Can you please test this PR again?

**Comment by zonkmachine** [comment]
Yes, I'm building it right now.

**Comment by zonkmachine** [comment]
> Export with plugin gui open and tweak the gui after export. Crash.

I get this crash still.

```cpp
Thread 1 "lmms" received signal SIGSEGV, Segmentation fault.
0x00005555557b5a3f in lmms::AutomatableModel::value<float> (this=0x0, frameOffset=0) at /home/zonkmachine/builds/lmms/include/AutomatableModel.h:154
154			if (m_controllerConnection)
(gdb) bt full
#0  0x00005555557b5a3f in lmms::AutomatableModel::value<float>(int) const (this=0x0, frameOffset=0) at /home/zonkmachine/builds/lmms/include/AutomatableModel.h:154
#1  0x00005555557b5eb0 in lmms::TypedAutomatableModel<float>::value(int) const (this=0x0, frameOffset=0) at /home/zonkmachine/builds/lmms/include/AutomatableModel.h:435
#2  0x00005555557b4acc in lmms::FloatModel::getRoundedValue() const (this=0x0) at /home/zonkmachine/builds/lmms/src/core/AutomatableModel.cpp:795
#3  0x00005555559d1931 in lmms::gui::Knob::displayValue() const (this=0x55555d60ca50) at /home/zonkmachine/builds/lmms/src/gui/widgets/Knob.cpp:820
#4  0x00005555559d0299 in lmms::gui::Knob::mousePressEvent(QMouseEvent*) (this=0x55555d60ca50, _me=0x7fffffffd540)
    at /home/zonkmachine/builds/lmms/src/gui/widgets/Knob.cpp:583
        thisModel = 0x0
        p = @0x7fffffffd028: {xp = 13, yp = 23}
```

**Comment by zonkmachine** [comment]
From [above](https://github.com/LMMS/lmms/pull/6419#issuecomment-1287923947): [exportkars.mmp.zip](https://github.com/LMMS/lmms/files/9845281/exportkars.mmp.zip)
* Open the project
* Open the Kars plugin gui
* Export the project
* Change a setting in the plugin gui (crash)

**Comment by JohannesLorenz** [comment]
@zonkmachine Thankss a lot for the error report. Should be fixed now.

**Comment by zonkmachine** [comment]
> @zonkmachine Thankss a lot for the error report. Should be fixed now.

Yes indeed, fix confirmed!

File: src/core/lv2/Lv2Proc.cpp [hunk 2]
```diff
@@ -175,6 +176,26 @@ Lv2Proc::~Lv2Proc() { shutdownPlugin(); }
...
+	QDomDocument doc;
+	QDomElement controls = doc.createElement("controls");
+	saveValues(doc, controls);
+	// backup construction variables
+	const LilvPlugin* plugin = m_plugin;
+	Model* parent = Model::parentModel();
+	// destroy everything using RAII ...
+	this->~Lv2Proc();
+	// ... and reuse it ("placement new")
+	new (this) Lv2Proc(plugin, parent);
```
Comment (DomClark) [inline src/core/lv2/Lv2Proc.cpp:191]: This isn't exception-safe: if `Lv2Proc`'s constructor throws an exception for some reason, then the object will be left in a destructed state, probably leading to a double-destruction later (which is undefined behaviour). The typical approach would be to construct a new `Lv2Proc`, then assign it to `*this`. Unfortunately, `QObject` is not assignable, but when we get Qt out of the core, we should revisit this.

**Review by DomClark — APPROVED** [review]

File: src/core/lv2/Lv2Proc.cpp (hunk 2 above)
Comment (JohannesLorenz) [reply src/core/lv2/Lv2Proc.cpp:191]: @DomClark Since the only one who calls `Lv2Proc::reload()` is `Lv2ControlBase`, which has an array of `Lv2Proc*`, couldn't we let `Lv2ControlBase` do the following?

1. save the contols + backup the construction variables
2. try to create the new Lv2Proc
3. try to load the values into the new Lv2Proc
4. only if 2+3 worked: do a pointer swap and delete the old Lv2Proc

Comment (JohannesLorenz) [reply src/core/lv2/Lv2Proc.cpp:191]: (Though this is worse than the current solution in that an additional heap allocation is required - but that's probably the negligible price of safety)

**Comment by JohannesLorenz** [comment]
Will merge in 2 days. Only left comment is from @DomClark and it's non-functional, so can still be improved later.
