### PR TITLE
Fix loading of CMT delays with locale-dependent names

### LINKED ISSUE #5167: Unknown LADSPA plugin fbdelay_0.1s
OS: xubuntu 19.04
lmms-1.2.0-linux-x86_64.AppImage

The following happens after opening "Thalendric - Armageddon" demo:
```
The following errors occured while loading: 
Unknown LADSPA plugin fbdelay_0.1s requested.
Unknown LADSPA plugin fbdelay_0.1s requested.
```

Even though the effect is visible and should be provided by CMT:
Screenshot_2019-09-03_22-24-13

### PR DESCRIPTION
**Pull request by michaelgregorius**
Add an upgrade routine for CMT delays. This fix will only work in conjunction with a fix in the CMT delay itself.

The CMT delay uses `sprintf` calls to generate the technical names and display names of the delays. These calls are locale dependent. As a consequence for example the feedback delay might have been saved either as "fbdelay_0.1s" (point) or "fbdelay_0,1s" (comma) in a save file.

The CMT fix makes sure that all delays use points in their names. Therefore we must upgrade all names that contain commas to ones that contain points.

This pull request must only be merged once https://github.com/LMMS/cmt/pull/6 is merged so that the the LMMS CMT submodule can be bumped to the corresponding commit.

### CODE REVIEW

File: src/core/DataFile.cpp [hunk 1]
```diff
@@ -1684,6 +1685,50 @@ void DataFile::upgrade_noteTypes()
...
+		auto attributes = effect.elementsByTagName("attribute");
+		for (int j = 0; j < attributes.size(); ++j)
+		{
+			auto attribute = attributes.item(j).toElement();
+
+			if (attribute.attribute("name") == "plugin")
+			{
+				const auto attributeValue = attribute.attribute("value");
+
+				QMap<QString, QString>::const_iterator it = nameMap.find(attributeValue);
```
Comment (Veratil) [inline src/core/DataFile.cpp:1716]: A `const auto` should correctly call the const version of `QMap.find`.
```suggestion
				const auto it = nameMap.find(attributeValue);
```

File: src/core/DataFile.cpp [hunk 2]
```diff
@@ -1684,6 +1685,50 @@ void DataFile::upgrade_noteTypes()
...
+
+	const auto effects = elementsByTagName("effect");
+	bool generalInfoPrinted = false;
+
+	for (int i = 0; i < effects.size(); ++i)
+	{
+		auto effect = effects.item(i).toElement();
+
+		// We are only interested in LADSPA plugins
+		if (effect.attribute("name") != "ladspaeffect") continue;
```
Comment (Veratil) [inline src/core/DataFile.cpp:1704]:
```suggestion
		if (effect.attribute("name") != "ladspaeffect") { continue; }
```

File: src/core/DataFile.cpp [hunk 3]
```diff
@@ -1684,6 +1685,50 @@ void DataFile::upgrade_noteTypes()
...
+
+				QMap<QString, QString>::const_iterator it = nameMap.find(attributeValue);
+				if (it != nameMap.end())
+				{
+					if (!generalInfoPrinted)
+					{
+						qInfo() << "Performing data upgrade for CMT delay(s). See LMMS issue #5167 for more details.";
+						generalInfoPrinted = true;
+					}
+					qInfo() << "Replacing" << attributeValue << "with" << *it;
```
Comment (Veratil) [inline src/core/DataFile.cpp:1724]: No other upgrade routine outputs anything. I'd prefer we remove this.

File: src/core/DataFile.cpp [hunk 4]
```diff
@@ -1684,6 +1685,50 @@ void DataFile::upgrade_noteTypes()
 	}
 }
 
+void DataFile::upgrade_fixCMTDelays()
+{
+	QMap<QString, QString> nameMap;
+	nameMap["delay_0,01s"] = "delay_0.01s";
+	nameMap["delay_0,1s"] = "delay_0.1s";
+	nameMap["fbdelay_0,01s"] = "fbdelay_0.01s";
+	nameMap["fbdelay_0,1s"] = "fbdelay_0.1s";
```
Comment (Veratil) [inline src/core/DataFile.cpp:1694]: This can probably be a static map?
```suggestion
	static const QMap<QString, QString> nameMap{
		{"delay_0,01s", "delay_0.01s"},
		{"delay_0,1s", "delay_0.1s"},
		{"fbdelay_0,01s", "fbdelay_0.01s"},
		{"fbdelay_0,1s", "fbdelay_0.1s"}
	};
```

**Comment by PhysSong** [comment]
@michaelgregorius I merged the CMT PR. You can update the submodule in this PR as well.

File: src/core/DataFile.cpp (hunk 2 above)
Comment (michaelgregorius) [reply src/core/DataFile.cpp]: Adjusted with commit e1899d82755.

File: src/core/DataFile.cpp (hunk 3 above)
Comment (michaelgregorius) [reply src/core/DataFile.cpp]: Adjusted with commit e1899d82755. I thought the output might have been interesting in case of bug reports.

File: src/core/DataFile.cpp (hunk 4 above)
Comment (michaelgregorius) [reply src/core/DataFile.cpp]: Adjusted with commit e1899d82755.

File: src/core/DataFile.cpp (hunk 1 above)
Comment (michaelgregorius) [reply src/core/DataFile.cpp]: When I replaced it as proposed and hovered over the variable it still showed that an `iterator` was returned instead of a `const_iterator`. The iterator itself was `const` but my understanding is that I cannot move the iterator in that case but that I can still mutate what the iterator points at.

With commit e1899d82755 I have added some more "constness" for the iterator itself.

**Comment by michaelgregorius** [comment]
> @michaelgregorius I merged the CMT PR. You can update the submodule in this PR as well.

Thanks @PhysSong! I have bumped the version of the CMT submodule with commit 0e3ee2fd312.

So this PR should be ready to go now.

File: src/core/DataFile.cpp [hunk 5]
```diff
@@ -1684,6 +1685,43 @@ void DataFile::upgrade_noteTypes()
 	}
 }
 
+void DataFile::upgrade_fixCMTDelays()
+{
+	static QMap<QString, QString> nameMap;
+	nameMap["delay_0,01s"] = "delay_0.01s";
+	nameMap["delay_0,1s"] = "delay_0.1s";
+	nameMap["fbdelay_0,01s"] = "fbdelay_0.01s";
+	nameMap["fbdelay_0,1s"] = "fbdelay_0.1s";
```
Comment (Veratil) [inline src/core/DataFile.cpp:1694]: This should be initialized in place like my previous comment mentioned.

File: src/core/DataFile.cpp [hunk 6]
```diff
@@ -1684,6 +1685,43 @@ void DataFile::upgrade_noteTypes()
...
+		for (int j = 0; j < attributes.size(); ++j)
+		{
+			auto attribute = attributes.item(j).toElement();
+
+			if (attribute.attribute("name") == "plugin")
+			{
+				const auto attributeValue = attribute.attribute("value");
+
+				const QMap<QString, QString>::const_iterator it = nameMap.find(attributeValue);
+				if (it != nameMap.end())
```
Comment (Veratil) [inline src/core/DataFile.cpp:1716]: This should work
```suggestion
				auto it = nameMap.constFind(attributeValue);
				if (it != nameMap.constEnd())
```

File: src/core/DataFile.cpp (hunk 5 above)
Comment (michaelgregorius) [reply src/core/DataFile.cpp]: Ah, sorry I have missed that. Done with commit 564f50f2e37.

File: src/core/DataFile.cpp (hunk 6 above)
Comment (michaelgregorius) [reply src/core/DataFile.cpp]: Adjusted with commit 564f50f2e37. I have used `const auto` because with only `auto` it was still possible to increment the iterator. Now the thing is as `const` as it gets. :sweat_smile:

Comment (Veratil) [reply src/core/DataFile.cpp]: Good point! If only... `const auto const it const = const nameMap.constFind(const attributeValue) const;` 😂

**Review by Veratil — APPROVED** [review]

**Comment by Veratil** [comment]
Be sure to update the PR title to upgrading CMT submodule too
