### PR TITLE
Fix `AutomatableSlider` Creating Too Many Journal Entries

### LINKED ISSUE #8222: Master volume and pitch sliders only undo partially
### System Information

Windows 10

### LMMS Version(s)

1.3.0-alpha.1.935+a4d2521

### Most Recent Working Version

_No response_

### Bug Summary

Moving the master volume or master pitch sliders creates multiple journal entries, causing them to only undo partially. Moving the slider slowly creates more journal entries than if it is moved quickly. This is related to #3973 (which was fixed by #4147), but affects the `AutomatableSlider` class instead of `Fader`.

### Expected Behaviour

Changes to the value of a slider should be undone fully in one undo, like how knobs and faders currently work.

### Steps To Reproduce

- Move the master volume or master pitch slider to a new value
- Click undo or press Ctrl+Z

### Logs

_No response_

### Screenshots / Minimum Reproducible Project

https://github.com/user-attachments/assets/15c241e8-9196-4d22-a7e9-8c03c00ef6bd

### Please search the issue tracker for existing bug reports before submitting your own.

- [x] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by extern-stat**
This fixes #8222 by only creating one journal entry when a slider is first pressed, similar to how the `Fader` and `Knob` classes currently work.

### CODE REVIEW

File: src/gui/widgets/AutomatableSlider.cpp [hunk 1]
```diff
@@ -83,6 +90,12 @@ void AutomatableSlider::mousePressEvent( QMouseEvent * _me )
 
 void AutomatableSlider::mouseReleaseEvent( QMouseEvent * _me )
 {
+	AutomatableModel *thisModel = model();
```
Comment (messmerd) [inline src/gui/widgets/AutomatableSlider.cpp]:
```suggestion
	AutomatableModel* thisModel = model();
```
style

**Comment by bratpeki** [comment]
> Haven't tested it, but the code changes look fine

And that's where I come in!

File: src/gui/widgets/AutomatableSlider.cpp [hunk 2]
```diff
@@ -83,6 +90,12 @@ void AutomatableSlider::mousePressEvent( QMouseEvent * _me )
 
 void AutomatableSlider::mouseReleaseEvent( QMouseEvent * _me )
 {
+	AutomatableModel* thisModel = model();
+	if (thisModel)
+	{
+		thisModel->restoreJournallingState();
+	}
+
```
Comment (bratpeki) [inline src/gui/widgets/AutomatableSlider.cpp]: Extra whitespace. 😝

**Comment by bratpeki** [comment]
```
$ grep "AutomatableSlider" -r src/gui/editors
src/gui/editors/SongEditor.cpp:#include "AutomatableSlider.h"
src/gui/editors/SongEditor.cpp: m_masterVolumeSlider = new AutomatableSlider( tb,
src/gui/editors/SongEditor.cpp: m_masterPitchSlider = new AutomatableSlider( tb, tr( "Global transposition" ) );
src/gui/editors/SongEditor.cpp: m_zoomingSlider = new AutomatableSlider(m_toolBar, tr("Zoom"));
```

Tested the "Global transposition" and "Master volume" at the top of the GUI, works great!

**Comment by bratpeki** [comment]
I don't fully get out journaling system, but I trust @messmerd regarding the code.
That being said, purely informatively, does the release event need to call `thisModel->saveJournallingState(true);` to undo the `false`? How does that work?

---

LGTM. Works great, too. Please merge!

**Comment by extern-stat** [comment]
> That being said, purely informatively, does the release event need to call `thisModel->saveJournallingState(true);` to undo the `false`? How does that work?

`saveJournalingState` and `restoreJournallingState` push and pop to a stack, respectively, so when the mouse gets pressed we can create one journal entry, and push `false` to stop more journal entries from being created by the model's `setValue` function. Then once the mouse is released, we can pop that `false` from the stack to allow journal entries to be created again. This makes the journal checkpoint added in `mousePressEvent` the only one created each time you move the slider. That being said, the code I added is just copied from what already exists in the `Fader` class.
