### PR TITLE
Fix playback within `Sample`

### LINKED ISSUE #7094: Distorted audio at loop points in AudioFileProcessor (nightly)
### Bug Summary
Audio becomes distorted when AFP reaches the loop region of sample 

#### Steps to reproduce
1. Download the latest nightly build of LMMS (gc2052151a as of writing this bug report)
2. Open AFP and import a sample/waveform sample
3. Set loop points to the sample's waveform cycle or to the whole sample
4. Play the sample (especially at high notes)

#### Expected behavior
Sample is played normally 

#### Actual behavior
Sample is played incorrectly at the loop points, resulting in distorted audio

#### Screenshots and audio files
image

#### Audio in old LMMS

https://github.com/LMMS/lmms/assets/81458575/4e36de52-a6ba-475b-94bd-d51c57fd9abb

#### Audio in latest LMMS

https://github.com/LMMS/lmms/assets/81458575/d5b9f8d6-77cb-4d51-8001-f318dcaf92fc

##### LMMS build
image

### PR DESCRIPTION
**Pull request by sakertooth**
This PR is meant to fix incorrect playback within `Sample`, particularly distorted audio occurring when looping. Other changes have been made as well to tidy up `Sample` and simplify both its interface and implementation.

Fixes #7094.

### CODE REVIEW

File: src/core/Sample.cpp [hunk 1]
```diff
@@ -117,58 +114,40 @@ auto Sample::operator=(Sample&& other) -> Sample&
 	return *this;
 }
 
-bool Sample::play(sampleFrame* dst, PlaybackState* state, int numFrames, float desiredFrequency, Loop loopMode)
+bool Sample::play(sampleFrame* dst, PlaybackState* state, size_t numFrames, float desiredFrequency, Loop loopMode) const
 {
-	if (numFrames <= 0 || desiredFrequency <= 0) { return false; }
+	if (loopMode == Loop::Off && (state->m_frameIndex >= m_endFrame || (state->m_frameIndex < 0 && state->m_backwards)))
```
Comment (Veratil) [inline src/core/Sample.cpp:119]: This is quite a guard with nested conditions. Maybe we can split it up into variables? If not it's okay though.

File: src/core/Sample.cpp [hunk 2]
```diff
@@ -117,58 +114,40 @@ auto Sample::operator=(Sample&& other) -> Sample&
...
 
-	auto resampleRatio = static_cast<float>(Engine::audioEngine()->processingSampleRate()) / m_buffer->sampleRate();
-	resampleRatio *= frequency() / desiredFrequency;
+	auto playBuffer = std::vector<sampleFrame>(numFrames / resampleRatio + marginSize);
+	playRaw(playBuffer.data(), playBuffer.size(), state, loopMode);
 
-	auto playBuffer = std::vector<sampleFrame>(numFrames / resampleRatio);
-	if (!typeInfo<float>::isEqual(resampleRatio, 1.0f))
+	const auto resampleResult
+		= state->resampler().resample(&playBuffer[0][0], playBuffer.size(), &dst[0][0], numFrames, resampleRatio);
```
Comment (Veratil) [inline src/core/Sample.cpp:133]: What do we think looks better? I'm usually split at a `(` kind of style.
```suggestion
	const auto resampleResult = state->resampler().resample(
		&playBuffer[0][0], playBuffer.size(), &dst[0][0], numFrames, resampleRatio);
```

File: src/core/Sample.cpp [hunk 3]
```diff
@@ -117,58 +114,40 @@ auto Sample::operator=(Sample&& other) -> Sample&
...
+	advance(state, resampleResult.inputFramesUsed, loopMode);
+
+	if (resampleResult.outputFramesGenerated < numFrames)
 	{
-		playBuffer.resize(playBuffer.size() + s_interpolationMargins[state->resampler().interpolationMode()]);
+		std::fill(dst + resampleResult.outputFramesGenerated, dst + resampleResult.outputFramesGenerated + numFrames,
+			sampleFrame{0, 0});
```
Comment (Veratil) [inline src/core/Sample.cpp:139]: I feel like this is more readable.
```suggestion
		std::fill(dst + resampleResult.outputFramesGenerated,
			dst + resampleResult.outputFramesGenerated + numFrames,
			sampleFrame{0, 0});
```

File: src/core/Sample.cpp (hunk 2 above)
Comment (sakertooth) [reply src/core/Sample.cpp:133]: I just format the whole document based on clang-tidy and go off of that. I don't mind either one really.

Comment (Veratil) [reply src/core/Sample.cpp:133]: Gotcha, okay no worries then.

File: src/core/Sample.cpp (hunk 3 above)
Comment (messmerd) [reply src/core/Sample.cpp]: Or better yet, use `std::fill_n`

File: src/core/Sample.cpp [hunk 4]
```diff
@@ -117,58 +114,35 @@ auto Sample::operator=(Sample&& other) -> Sample&
 	return *this;
 }
 
-bool Sample::play(sampleFrame* dst, PlaybackState* state, int numFrames, float desiredFrequency, Loop loopMode)
+bool Sample::play(sampleFrame* dst, PlaybackState* state, size_t numFrames, float desiredFrequency, Loop loopMode) const
 {
-	if (numFrames <= 0 || desiredFrequency <= 0) { return false; }
+	const auto pastBounds = state->m_frameIndex >= m_endFrame || (state->m_frameIndex < 0 && state->m_backwards);
+	if (loopMode == Loop::Off && pastBounds) { return false; }
```
Comment (Veratil) [inline src/core/Sample.cpp:120]: Do we still want to check for `desiredFrequency <= 0` or is this handled elsewhere now?

Comment (sakertooth) [reply src/core/Sample.cpp:120]: I feel like the code is simpler if we make the assumption that the caller gives us resonable parameters. If the caller gave us a `desiredFrequency` of `-440.0f` for example, that's on them, and the bug should be fixed at the call site. Otherwise, if we add this guard, the bug may never be found.

**Review by Veratil — APPROVED** [review]
